APM:Plane: ArduPlane/altitude.pde File Reference
altitude.pde File Reference
Functions
static void adjust_altitude_target ()
static void setup_glide_slope (void)
static int32_t get_RTL_altitude ()
static float relative_altitude (void)
static int32_t relative_altitude_abs_cm (void)
static void set_target_altitude_current (void)
static void set_target_altitude_current_adjusted (void)
static void set_target_altitude_location (const Location &loc)
static int32_t relative_target_altitude_cm (void)
static void change_target_altitude (int32_t change_cm)
static void set_target_altitude_proportion (const Location &loc, float proportion)
static void constrain_target_altitude_location (const Location &loc1, const Location &loc2)
static int32_t calc_altitude_error_cm (void)
static void check_minimum_altitude (void)
static void reset_offset_altitude (void)
static void set_offset_altitude_location (const Location &loc)
static bool above_location_current (const Location &loc)
static void setup_terrain_target_alt (Location &loc)
static int32_t adjusted_altitude_cm (void)
static int32_t adjusted_relative_altitude_cm (void)
static float height_above_target (void)
static float lookahead_adjustment (void)
static float rangefinder_correction (void)
static void rangefinder_height_update (void)
Function Documentation
static bool above_location_current (const Location & loc) static
Definition at line 384 of file altitude.pde.
Referenced by setup_glide_slope().
static void adjust_altitude_target () static
Definition at line 25 of file altitude.pde.
static int32_t adjusted_altitude_cm (void) static
Definition at line 423 of file altitude.pde.
Referenced by adjusted_relative_altitude_cm(), calc_altitude_error_cm(), do_change_alt(), geofence_check_maxalt(), geofence_check_minalt(), height_above_target(), set_target_altitude_current_adjusted(), verify_change_alt(), and verify_continue_and_change_alt().
static int32_t adjusted_relative_altitude_cm (void) static
Definition at line 433 of file altitude.pde.
Referenced by setup_glide_slope(), and verify_takeoff().
static int32_t calc_altitude_error_cm (void) static
Definition at line 288 of file altitude.pde.
Referenced by adjust_altitude_target(), set_target_altitude_proportion(), and update_fbwb_speed_height().
static void change_target_altitude (int32_t change_cm) static
Definition at line 233 of file altitude.pde.
Referenced by do_change_alt(), set_target_altitude_proportion(), update_fbwb_speed_height(), and verify_change_alt().
static void check_minimum_altitude (void) static
Definition at line 303 of file altitude.pde.
Referenced by update_fbwb_speed_height().
static void constrain_target_altitude_location (const Location & loc1, const Location & loc2) static
Definition at line 276 of file altitude.pde.
Referenced by adjust_altitude_target(), and setup_landing_glide_slope().
static int32_t get_RTL_altitude () static
Definition at line 105 of file altitude.pde.
Referenced by do_RTL(), exit_mission_callback(), and geofence_check().
static float height_above_target (void) static
Definition at line 441 of file altitude.pde.
Referenced by tecs_hgt_afe(), and verify_land().
static float lookahead_adjustment (void) static
Definition at line 463 of file altitude.pde.
Referenced by relative_target_altitude_cm().
static float rangefinder_correction (void) static
Definition at line 524 of file altitude.pde.
Referenced by relative_target_altitude_cm(), tecs_hgt_afe(), and verify_land().
static void rangefinder_height_update (void) static
Definition at line 547 of file altitude.pde.
Referenced by read_rangefinder().
static float relative_altitude (void) static
Definition at line 117 of file altitude.pde.
Referenced by rangefinder_height_update(), send_location(), stabilize_yaw(), and tecs_hgt_afe().
static int32_t relative_altitude_abs_cm (void) static
Definition at line 125 of file altitude.pde.
Referenced by stabilize(), and suppress_throttle().
static int32_t relative_target_altitude_cm (void) static
Definition at line 204 of file altitude.pde.
Referenced by update_flight_stage().
static void reset_offset_altitude (void) static
Definition at line 327 of file altitude.pde.
Referenced by do_change_alt(), do_continue_and_change_alt(), set_target_altitude_current(), and setup_glide_slope().
static void set_offset_altitude_location (const Location & loc) static
Definition at line 339 of file altitude.pde.
Referenced by set_target_altitude_proportion(), and setup_glide_slope().
static void set_target_altitude_current (void) static
Definition at line 136 of file altitude.pde.
Referenced by set_guided_WP(), set_mode(), set_target_altitude_current_adjusted(), and update_fbwb_speed_height().
static void set_target_altitude_current_adjusted (void) static
Definition at line 163 of file altitude.pde.
Referenced by do_change_alt().
static void set_target_altitude_location (const Location & loc) static
Definition at line 174 of file altitude.pde.
Referenced by adjust_altitude_target(), do_RTL(), set_next_WP(), and set_target_altitude_proportion().
static void set_target_altitude_proportion (const Location & loc, float proportion) static
Definition at line 254 of file altitude.pde.
Referenced by adjust_altitude_target(), and setup_landing_glide_slope().
static void setup_glide_slope (void) static
Definition at line 58 of file altitude.pde.
Referenced by do_change_alt(), do_RTL(), exit_mission_callback(), set_guided_WP(), and set_next_WP().
static void setup_terrain_target_alt (Location & loc) static
Definition at line 409 of file altitude.pde.
Referenced by do_RTL(), exit_mission_callback(), and geofence_check().