APM:Plane: ArduPlane/Attitude.pde File Reference
Attitude.pde File Reference
Functions
static float get_speed_scaler (void)
static bool stick_mixing_enabled (void)
static void stabilize_roll (float speed_scaler)
static void stabilize_pitch (float speed_scaler)
static void stick_mix_channel (RC_Channel *channel, int16_t &servo_out)
static void stabilize_stick_mixing_direct ()
static void stabilize_stick_mixing_fbw ()
static void stabilize_yaw (float speed_scaler)
static void stabilize_training (float speed_scaler)
static void stabilize_acro (float speed_scaler)
static void stabilize ()
static void calc_throttle ()
static void calc_nav_yaw_coordinated (float speed_scaler)
static void calc_nav_yaw_course (void)
static void calc_nav_yaw_ground (void)
static void calc_nav_pitch ()
static void calc_nav_roll ()
static void throttle_slew_limit (int16_t last_throttle)
static void flap_slew_limit (int8_t &last_value, int8_t &new_value)
static bool suppress_throttle (void)
static void channel_output_mixer (uint8_t mixing_type, int16_t &chan1_out, int16_t &chan2_out)
static void flaperon_update (int8_t flap_percent)
static void set_servos (void)
static void demo_servos (uint8_t i)
static void adjust_nav_pitch_throttle (void)
static void update_load_factor (void)
Variables
static bool demoing_servos
Function Documentation
static void adjust_nav_pitch_throttle (void) static
Definition at line 1007 of file Attitude.pde.
Referenced by update_flight_mode().
static void calc_nav_pitch () static
Definition at line 487 of file Attitude.pde.
Referenced by handle_auto_mode(), takeoff_calc_pitch(), update_fbwb_speed_height(), and update_flight_mode().
static void calc_nav_roll () static
Definition at line 499 of file Attitude.pde.
Referenced by handle_auto_mode(), takeoff_calc_roll(), and update_flight_mode().
static void calc_nav_yaw_coordinated (float speed_scaler) static
Definition at line 414 of file Attitude.pde.
Referenced by stabilize_yaw().
static void calc_nav_yaw_course (void) static
Definition at line 431 of file Attitude.pde.
Referenced by stabilize_yaw().
static void calc_nav_yaw_ground (void) static
Definition at line 446 of file Attitude.pde.
Referenced by stabilize_yaw().
static void calc_throttle () static
Definition at line 394 of file Attitude.pde.
Referenced by handle_auto_mode(), update_fbwb_speed_height(), and update_flight_mode().
static void channel_output_mixer (uint8_t mixing_type, int16_t & chan1_out, int16_t & chan2_out) static
Definition at line 617 of file Attitude.pde.
Referenced by failsafe_check(), flaperon_update(), and set_servos().
static void demo_servos (uint8_t i) static
Definition at line 985 of file Attitude.pde.
Referenced by startup_ground().
static void flap_slew_limit (int8_t & last_value, int8_t & new_value) static
Definition at line 531 of file Attitude.pde.
Referenced by set_servos().
static void flaperon_update (int8_t flap_percent) static
Definition at line 662 of file Attitude.pde.
Referenced by failsafe_check(), and set_servos().
static float get_speed_scaler (void) static
Definition at line 13 of file Attitude.pde.
Referenced by stabilize().
static void set_servos (void) static
Definition at line 691 of file Attitude.pde.
Referenced by test_radio().
static void stabilize () static
Definition at line 348 of file Attitude.pde.
static void stabilize_acro (float speed_scaler) static
Definition at line 281 of file Attitude.pde.
Referenced by stabilize().
static void stabilize_pitch (float speed_scaler) static
Definition at line 98 of file Attitude.pde.
Referenced by stabilize(), and stabilize_training().
static void stabilize_roll (float speed_scaler) static
Definition at line 72 of file Attitude.pde.
Referenced by stabilize(), and stabilize_training().
static void stabilize_stick_mixing_direct () static
Definition at line 138 of file Attitude.pde.
Referenced by stabilize().
static void stabilize_stick_mixing_fbw () static
Definition at line 157 of file Attitude.pde.
Referenced by stabilize().
static void stabilize_training (float speed_scaler) static
Definition at line 248 of file Attitude.pde.
Referenced by stabilize().
static void stabilize_yaw (float speed_scaler) static
Definition at line 207 of file Attitude.pde.
Referenced by stabilize(), and stabilize_training().
static void stick_mix_channel (RC_Channel * channel, int16_t & servo_out) static
Definition at line 123 of file Attitude.pde.
Referenced by calc_nav_yaw_course(), and stabilize_stick_mixing_direct().
static bool stick_mixing_enabled (void) static
Definition at line 42 of file Attitude.pde.
Referenced by calc_nav_yaw_course(), stabilize_stick_mixing_direct(), and stabilize_stick_mixing_fbw().
static bool suppress_throttle (void) static
Definition at line 559 of file Attitude.pde.
Referenced by set_servos().
static void throttle_slew_limit (int16_t last_throttle) static
Definition at line 510 of file Attitude.pde.
Referenced by set_servos().
static void update_load_factor (void) static
Definition at line 1022 of file Attitude.pde.
Referenced by calc_nav_roll(), and update_flight_mode().
Variable Documentation
bool demoing_servos static
Definition at line 983 of file Attitude.pde.
Referenced by demo_servos(), and failsafe_check().