APM:Plane: ArduPlane/commands_logic.pde File Reference
commands_logic.pde File Reference
Functions
static void do_takeoff (const AP_Mission::Mission_Command &cmd)
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
static void do_nav_wp (const AP_Mission::Mission_Command &cmd)
static void do_land (const AP_Mission::Mission_Command &cmd)
static void do_loiter_unlimited (const AP_Mission::Mission_Command &cmd)
static void do_loiter_turns (const AP_Mission::Mission_Command &cmd)
static void do_loiter_time (const AP_Mission::Mission_Command &cmd)
static void do_wait_delay (const AP_Mission::Mission_Command &cmd)
static void do_within_distance (const AP_Mission::Mission_Command &cmd)
static void do_change_alt (const AP_Mission::Mission_Command &cmd)
static void do_change_speed (const AP_Mission::Mission_Command &cmd)
static void do_set_home (const AP_Mission::Mission_Command &cmd)
static void do_continue_and_change_alt (const AP_Mission::Mission_Command &cmd)
static void do_loiter_to_alt (const AP_Mission::Mission_Command &cmd)
static bool verify_nav_wp (const AP_Mission::Mission_Command &cmd)
static void do_digicam_configure (const AP_Mission::Mission_Command &cmd)
static void do_digicam_control (const AP_Mission::Mission_Command &cmd)
static void do_align_path (const AP_Mission::Mission_Command &cmd)
static bool start_command (const AP_Mission::Mission_Command &cmd)
static bool verify_command (const AP_Mission::Mission_Command &cmd)
static void do_RTL (void)
static void loiter_set_direction_wp (const AP_Mission::Mission_Command &cmd)
static bool verify_takeoff ()
static bool verify_loiter_unlim ()
static bool verify_loiter_time ()
static bool verify_loiter_turns ()
static bool verify_loiter_to_alt ()
static bool verify_RTL ()
static bool verify_continue_and_change_alt ()
static bool verify_align_path ()
static bool verify_wait_delay ()
static bool verify_change_alt ()
static bool verify_within_distance ()
static void do_loiter_at_location ()
static void do_take_picture ()
static void log_picture ()
static bool start_command_callback (const AP_Mission::Mission_Command &cmd)
static bool verify_command_callback (const AP_Mission::Mission_Command &cmd)
static void exit_mission_callback ()
Function Documentation
static void do_align_path (const AP_Mission::Mission_Command & cmd) static
Definition at line 394 of file commands_logic.pde.
Referenced by start_command().
static void do_change_alt (const AP_Mission::Mission_Command & cmd) static
Definition at line 686 of file commands_logic.pde.
Referenced by start_command().
static void do_change_speed (const AP_Mission::Mission_Command & cmd) static
Definition at line 754 of file commands_logic.pde.
Referenced by start_command().
static void do_continue_and_change_alt (const AP_Mission::Mission_Command & cmd) static
Definition at line 388 of file commands_logic.pde.
Referenced by start_command().
static void do_digicam_configure (const AP_Mission::Mission_Command & cmd) static
Definition at line 787 of file commands_logic.pde.
Referenced by start_command().
static void do_digicam_control (const AP_Mission::Mission_Command & cmd) static
Definition at line 795 of file commands_logic.pde.
Referenced by start_command().
static void do_land (const AP_Mission::Mission_Command & cmd) static
Definition at line 351 of file commands_logic.pde.
Referenced by start_command().
static void do_loiter_at_location () static
Definition at line 744 of file commands_logic.pde.
Referenced by set_mode().
static void do_loiter_time (const AP_Mission::Mission_Command & cmd) static
Definition at line 379 of file commands_logic.pde.
Referenced by start_command().
static void do_loiter_to_alt (const AP_Mission::Mission_Command & cmd) static
Definition at line 399 of file commands_logic.pde.
Referenced by start_command().
static void do_loiter_turns (const AP_Mission::Mission_Command & cmd) static
Definition at line 372 of file commands_logic.pde.
Referenced by start_command().
static void do_loiter_unlimited (const AP_Mission::Mission_Command & cmd) static
Definition at line 366 of file commands_logic.pde.
Referenced by start_command().
static void do_nav_wp (const AP_Mission::Mission_Command & cmd) static
Definition at line 346 of file commands_logic.pde.
Referenced by start_command().
static void do_RTL (void) static
Definition at line 305 of file commands_logic.pde.
Referenced by set_mode().
static void do_set_home (const AP_Mission::Mission_Command & cmd) static
Definition at line 776 of file commands_logic.pde.
Referenced by start_command().
static void do_take_picture () static
Definition at line 804 of file commands_logic.pde.
Referenced by update_GPS_10Hz().
static void do_takeoff (const AP_Mission::Mission_Command & cmd) static
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 328 of file commands_logic.pde.
Referenced by start_command().
static void do_wait_delay (const AP_Mission::Mission_Command & cmd) static
Definition at line 677 of file commands_logic.pde.
Referenced by start_command().
static void do_within_distance (const AP_Mission::Mission_Command & cmd) static
Definition at line 700 of file commands_logic.pde.
Referenced by start_command().
static void exit_mission_callback () static
Definition at line 843 of file commands_logic.pde.
static void log_picture () static
Definition at line 813 of file commands_logic.pde.
Referenced by do_digicam_control(), and do_take_picture().
static void loiter_set_direction_wp (const AP_Mission::Mission_Command & cmd) static
Definition at line 357 of file commands_logic.pde.
Referenced by do_loiter_time(), do_loiter_to_alt(), do_loiter_turns(), and do_loiter_unlimited().
static bool start_command (const AP_Mission::Mission_Command & cmd) static
Definition at line 34 of file commands_logic.pde.
Referenced by exit_mission_callback(), and start_command_callback().
static bool start_command_callback (const AP_Mission::Mission_Command & cmd) static
Definition at line 823 of file commands_logic.pde.
static bool verify_align_path () static
Definition at line 666 of file commands_logic.pde.
Referenced by verify_command().
static bool verify_change_alt () static
Definition at line 718 of file commands_logic.pde.
Referenced by verify_command().
static bool verify_command (const AP_Mission::Mission_Command & cmd) static
Definition at line 222 of file commands_logic.pde.
Referenced by verify_command_callback().
static bool verify_command_callback (const AP_Mission::Mission_Command & cmd) static
Definition at line 833 of file commands_logic.pde.
static bool verify_continue_and_change_alt () static
Definition at line 647 of file commands_logic.pde.
Referenced by verify_command().
static bool verify_loiter_time () static
Definition at line 544 of file commands_logic.pde.
Referenced by verify_command().
static bool verify_loiter_to_alt () static
Definition at line 576 of file commands_logic.pde.
Referenced by verify_command().
static bool verify_loiter_turns () static
Definition at line 559 of file commands_logic.pde.
Referenced by verify_command().
static bool verify_loiter_unlim () static
Definition at line 538 of file commands_logic.pde.
Referenced by verify_command().
static bool verify_nav_wp (const AP_Mission::Mission_Command & cmd) static
Definition at line 494 of file commands_logic.pde.
Referenced by verify_command().
static bool verify_RTL () static
Definition at line 635 of file commands_logic.pde.
Referenced by verify_command().
static bool verify_takeoff () static
Definition at line 428 of file commands_logic.pde.
Referenced by verify_command().
static bool verify_wait_delay () static
Definition at line 709 of file commands_logic.pde.
Referenced by verify_command().
static bool verify_within_distance () static
Definition at line 731 of file commands_logic.pde.
Referenced by verify_command().