APM:Plane: ArduPlane/control_modes.pde File Reference
control_modes.pde File Reference
Functions
static void read_control_switch ()
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
static uint8_t readSwitch (void)
static void reset_control_switch ()
static void autotune_start (void)
static void autotune_restore (void)
static bool fly_inverted (void)
Function Documentation
static void autotune_restore (void) static
Definition at line 134 of file control_modes.pde.
Referenced by set_mode().
static void autotune_start (void) static
Definition at line 125 of file control_modes.pde.
Referenced by set_mode().
static bool fly_inverted (void) static
Definition at line 143 of file control_modes.pde.
Referenced by stabilize_roll(), stabilize_stick_mixing_fbw(), update_flight_mode(), and update_load_factor().
static void read_control_switch () static
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 4 of file control_modes.pde.
Referenced by reset_control_switch().
static uint8_t readSwitch (void) static
Definition at line 104 of file control_modes.pde.
Referenced by read_control_switch(), test_failsafe(), and test_modeswitch().
static void reset_control_switch () static
Definition at line 116 of file control_modes.pde.
Referenced by init_ardupilot().