APM:Plane: ArduPlane/events.pde File Reference
events.pde File Reference
Functions
static void failsafe_short_on_event (enum failsafe_state fstype)
static void failsafe_long_on_event (enum failsafe_state fstype)
static void failsafe_short_off_event ()
void low_battery_event (void)
static void update_events (void)
Function Documentation
static void failsafe_long_on_event (enum failsafe_state fstype) static
Definition at line 51 of file events.pde.
Referenced by check_long_failsafe().
static void failsafe_short_off_event () static
Definition at line 96 of file events.pde.
Referenced by check_short_failsafe().
static void failsafe_short_on_event (enum failsafe_state fstype) static
Definition at line 4 of file events.pde.
Referenced by check_short_failsafe().
void low_battery_event (void)
Definition at line 110 of file events.pde.
Referenced by read_battery().
static void update_events (void) static
Definition at line 123 of file events.pde.