APM:Plane: ArduPlane/GCS_Mavlink.pde File Reference
GCS_Mavlink.pde File Reference
Macros
#define MAVLINK_SENSOR_PRESENT_DEFAULT (MAV_SYS_STATUS_SENSOR_3D_GYRO | MAV_SYS_STATUS_SENSOR_3D_ACCEL | MAV_SYS_STATUS_SENSOR_ABSOLUTE_PRESSURE | MAV_SYS_STATUS_SENSOR_ANGULAR_RATE_CONTROL | MAV_SYS_STATUS_SENSOR_ATTITUDE_STABILIZATION | MAV_SYS_STATUS_SENSOR_YAW_POSITION | MAV_SYS_STATUS_SENSOR_Z_ALTITUDE_CONTROL | MAV_SYS_STATUS_SENSOR_XY_POSITION_CONTROL | MAV_SYS_STATUS_SENSOR_MOTOR_OUTPUTS | MAV_SYS_STATUS_AHRS)
#define CHECK_PAYLOAD_SIZE(id) if (txspace < MAVLINK_NUM_NON_PAYLOAD_BYTES+MAVLINK_MSG_ID_ ## id ## _LEN) return false
Functions
static NOINLINE void send_heartbeat (mavlink_channel_t chan)
static NOINLINE void send_attitude (mavlink_channel_t chan)
static NOINLINE void send_fence_status (mavlink_channel_t chan)
static NOINLINE void send_extended_status1 (mavlink_channel_t chan)
static void NOINLINE send_location (mavlink_channel_t chan)
static void NOINLINE send_nav_controller_output (mavlink_channel_t chan)
void NOINLINE send_servo_out (mavlink_channel_t chan)
static void NOINLINE send_radio_out (mavlink_channel_t chan)
static void NOINLINE send_vfr_hud (mavlink_channel_t chan)
static void NOINLINE send_simstate (mavlink_channel_t chan)
static void NOINLINE send_hwstatus (mavlink_channel_t chan)
static void NOINLINE send_wind (mavlink_channel_t chan)
static void NOINLINE send_rangefinder (mavlink_channel_t chan)
static void NOINLINE send_current_waypoint (mavlink_channel_t chan)
static void NOINLINE send_statustext (mavlink_channel_t chan)
static bool telemetry_delayed (mavlink_channel_t chan)
static void mavlink_delay_cb ()
static void gcs_send_message (enum ap_message id)
static void gcs_data_stream_send (void)
static void gcs_update (void)
static void gcs_send_text_P (gcs_severity severity, const prog_char_t *str)
void gcs_send_text_fmt (const prog_char_t *fmt,...)
static void gcs_send_airspeed_calibration (const Vector3f &vg)
static void gcs_retry_deferred (void)
Variables
static bool in_mavlink_delay
static bool gcs_out_of_time
static mavlink_hil_state_t last_hil_state
const AP_Param::GroupInfo
GCS_MAVLINK::var_info[] PROGMEM
Macro Definition Documentation
#define CHECK_PAYLOAD_SIZE (id) if (txspace < MAVLINK_NUM_NON_PAYLOAD_BYTES+MAVLINK_MSG_ID_ ## id ## _LEN) return false
Definition at line 514 of file GCS_Mavlink.pde.
#define MAVLINK_SENSOR_PRESENT_DEFAULT (MAV_SYS_STATUS_SENSOR_3D_GYRO | MAV_SYS_STATUS_SENSOR_3D_ACCEL | MAV_SYS_STATUS_SENSOR_ABSOLUTE_PRESSURE | MAV_SYS_STATUS_SENSOR_ANGULAR_RATE_CONTROL | MAV_SYS_STATUS_SENSOR_ATTITUDE_STABILIZATION | MAV_SYS_STATUS_SENSOR_YAW_POSITION | MAV_SYS_STATUS_SENSOR_Z_ALTITUDE_CONTROL | MAV_SYS_STATUS_SENSOR_XY_POSITION_CONTROL | MAV_SYS_STATUS_SENSOR_MOTOR_OUTPUTS | MAV_SYS_STATUS_AHRS)
Definition at line 4 of file GCS_Mavlink.pde.
Referenced by send_extended_status1().
Function Documentation
static void gcs_data_stream_send (void) static
Definition at line 1685 of file GCS_Mavlink.pde.
Referenced by mavlink_delay_cb().
static void gcs_retry_deferred (void) static
retry any deferred messages
Definition at line 1765 of file GCS_Mavlink.pde.
static void gcs_send_airspeed_calibration (const Vector3f & vg) static
Definition at line 1750 of file GCS_Mavlink.pde.
Referenced by airspeed_ratio_update().
static void gcs_send_message (enum ap_message id) static
Definition at line 1673 of file GCS_Mavlink.pde.
Referenced by gcs_retry_deferred(), geofence_check(), geofence_load(), log_picture(), mavlink_delay_cb(), and one_second_loop().
void gcs_send_text_fmt (const prog_char_t * fmt, ...)
Definition at line 1727 of file GCS_Mavlink.pde.
Referenced by auto_takeoff_check(), control_failsafe(), do_change_speed(), exit_mission_callback(), failsafe_long_on_event(), failsafe_short_on_event(), init_home(), log_perf_info(), low_battery_event(), start_command(), suppress_throttle(), verify_land(), verify_nav_wp(), and verify_takeoff().
static void gcs_send_text_P (gcs_severity severity, const prog_char_t * str) static
Definition at line 1710 of file GCS_Mavlink.pde.
Referenced by demo_servos(), disarm_if_autoland_complete(), do_erase_logs(), failsafe_long_on_event(), failsafe_short_off_event(), failsafe_short_on_event(), geofence_check(), geofence_load(), init_ardupilot(), init_barometer(), init_home(), jump_to_landing_sequence(), mavlink_delay_cb(), read_control_switch(), set_flight_stage(), set_next_WP(), startup_ground(), startup_INS_ground(), takeoff_tail_hold(), update_flight_mode(), verify_command(), verify_loiter_time(), verify_loiter_turns(), verify_RTL(), verify_takeoff(), and zero_airspeed().
static void gcs_update (void) static
Definition at line 1697 of file GCS_Mavlink.pde.
Referenced by ahrs_update(), and mavlink_delay_cb().
static void mavlink_delay_cb () static
Definition at line 1642 of file GCS_Mavlink.pde.
Referenced by init_ardupilot().
static NOINLINE void send_attitude (mavlink_channel_t chan) static
Definition at line 105 of file GCS_Mavlink.pde.
static void NOINLINE send_current_waypoint (mavlink_channel_t chan) static
Definition at line 483 of file GCS_Mavlink.pde.
static NOINLINE void send_extended_status1 (mavlink_channel_t chan) static
Definition at line 127 of file GCS_Mavlink.pde.
static NOINLINE void send_fence_status (mavlink_channel_t chan) static
Definition at line 120 of file GCS_Mavlink.pde.
static NOINLINE void send_heartbeat (mavlink_channel_t chan) static
Definition at line 22 of file GCS_Mavlink.pde.
static void NOINLINE send_hwstatus (mavlink_channel_t chan) static
Definition at line 452 of file GCS_Mavlink.pde.
static void NOINLINE send_location (mavlink_channel_t chan) static
Definition at line 313 of file GCS_Mavlink.pde.
static void NOINLINE send_nav_controller_output (mavlink_channel_t chan) static
Definition at line 340 of file GCS_Mavlink.pde.
static void NOINLINE send_radio_out (mavlink_channel_t chan) static
Definition at line 375 of file GCS_Mavlink.pde.
static void NOINLINE send_rangefinder (mavlink_channel_t chan) static
Definition at line 471 of file GCS_Mavlink.pde.
void NOINLINE send_servo_out (mavlink_channel_t chan)
Definition at line 355 of file GCS_Mavlink.pde.
Referenced by set_servos().
static void NOINLINE send_simstate (mavlink_channel_t chan) static
Definition at line 430 of file GCS_Mavlink.pde.
static void NOINLINE send_statustext (mavlink_channel_t chan) static
Definition at line 488 of file GCS_Mavlink.pde.
static void NOINLINE send_vfr_hud (mavlink_channel_t chan) static
Definition at line 406 of file GCS_Mavlink.pde.
static void NOINLINE send_wind (mavlink_channel_t chan) static
Definition at line 460 of file GCS_Mavlink.pde.
static bool telemetry_delayed (mavlink_channel_t chan) static
Definition at line 498 of file GCS_Mavlink.pde.
Variable Documentation
bool gcs_out_of_time static
Definition at line 10 of file GCS_Mavlink.pde.
bool in_mavlink_delay static
Definition at line 7 of file GCS_Mavlink.pde.
Referenced by erase_logs(), mavlink_delay_cb(), and should_log().
mavlink_hil_state_t last_hil_state static
Definition at line 427 of file GCS_Mavlink.pde.
const AP_Param::GroupInfo GCS_MAVLINK::var_info [] PROGMEM
Definition at line 731 of file GCS_Mavlink.pde.