APM:Plane: ArduPlane/geofence.pde File Reference
geofence.pde File Reference
Classes
struct GeofenceState
Macros
#define MIN_GEOFENCE_POINTS 5
Functions
static uint8_t max_fencepoints (void)
static Vector2l get_fence_point_with_index (unsigned i)
static void set_fence_point_with_index (Vector2l &point, unsigned i)
static void geofence_load (void)
static bool geofence_present (void)
static void geofence_update_pwm_enabled_state ()
static bool geofence_set_enabled (bool enable, GeofenceEnableReason r)
static bool geofence_enabled (void)
static bool geofence_set_floor_enabled (bool floor_enable)
static bool geofence_check_minalt (void)
static bool geofence_check_maxalt (void)
static void geofence_check (bool altitude_check_only)
static bool geofence_stickmixing (void)
static void geofence_send_status (mavlink_channel_t chan)
static bool geofence_breached (void)
Variables
static struct GeofenceState * geofence_state
static const StorageAccess fence_storage (StorageManager::StorageFence)
Macro Definition Documentation
#define MIN_GEOFENCE_POINTS 5
Definition at line 9 of file geofence.pde.
Referenced by geofence_present().
Function Documentation
static bool geofence_breached (void) static
Definition at line 452 of file geofence.pde.
Referenced by obc_fs_check(), and send_extended_status1().
static void geofence_check (bool altitude_check_only) static
Definition at line 278 of file geofence.pde.
Referenced by update_alt(), and update_GPS_10Hz().
static bool geofence_check_maxalt (void) static
Definition at line 263 of file geofence.pde.
Referenced by geofence_check().
static bool geofence_check_minalt (void) static
Definition at line 249 of file geofence.pde.
Referenced by geofence_check().
static bool geofence_enabled (void) static
Definition at line 213 of file geofence.pde.
Referenced by geofence_check(), geofence_send_status(), geofence_stickmixing(), and send_extended_status1().
static void geofence_load (void) static
Definition at line 90 of file geofence.pde.
Referenced by geofence_check(), geofence_set_enabled(), and geofence_update_pwm_enabled_state().
static bool geofence_present (void) static
Definition at line 150 of file geofence.pde.
Referenced by geofence_check(), geofence_enabled(), and send_extended_status1().
static void geofence_send_status (mavlink_channel_t chan) static
Definition at line 438 of file geofence.pde.
Referenced by send_fence_status().
static bool geofence_set_enabled (bool enable, GeofenceEnableReason r) static
Definition at line 191 of file geofence.pde.
Referenced by geofence_update_pwm_enabled_state(), set_flight_stage(), start_command(), and verify_takeoff().
static bool geofence_set_floor_enabled (bool floor_enable) static
Definition at line 237 of file geofence.pde.
Referenced by geofence_set_enabled(), set_flight_stage(), and start_command().
static bool geofence_stickmixing (void) static
Definition at line 423 of file geofence.pde.
Referenced by stick_mixing_enabled().
static void geofence_update_pwm_enabled_state () static
Definition at line 163 of file geofence.pde.
Referenced by geofence_enabled().
static Vector2l get_fence_point_with_index (unsigned i) static
Definition at line 56 of file geofence.pde.
Referenced by geofence_load().
static uint8_t max_fencepoints (void) static
Definition at line 48 of file geofence.pde.
Referenced by geofence_load(), get_fence_point_with_index(), and set_fence_point_with_index().
static void set_fence_point_with_index (Vector2l & point, unsigned i) static
Definition at line 72 of file geofence.pde.
Variable Documentation
const StorageAccess fence_storage(StorageManager::StorageFence) static
Referenced by get_fence_point_with_index(), max_fencepoints(), and set_fence_point_with_index().
struct GeofenceState * geofence_state static
Referenced by geofence_breached(), geofence_check(), geofence_enabled(), geofence_load(), geofence_send_status(), geofence_set_enabled(), geofence_set_floor_enabled(), geofence_stickmixing(), geofence_update_pwm_enabled_state(), and set_fence_point_with_index().