APM:Plane: ArduPlane/landing.pde File Reference
landing.pde File Reference
Functions
static bool verify_land ()
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
static void disarm_if_autoland_complete ()
static void setup_landing_glide_slope (void)
static bool jump_to_landing_sequence (void)
static float tecs_hgt_afe (void)
Function Documentation
static void disarm_if_autoland_complete () static
Definition at line 105 of file landing.pde.
Referenced by verify_land().
static bool jump_to_landing_sequence (void) static
Definition at line 212 of file landing.pde.
Referenced by update_navigation().
static void setup_landing_glide_slope (void) static
Definition at line 131 of file landing.pde.
Referenced by adjust_altitude_target().
static float tecs_hgt_afe (void) static
Definition at line 236 of file landing.pde.
Referenced by update_flight_stage(), and update_speed_height().
static bool verify_land () static
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 11 of file landing.pde.
Referenced by verify_command().