APM:Plane: ArduPlane/Log.pde File Reference
Log.pde File Reference
Classes
struct log_Performance
struct log_Startup
struct log_Control_Tuning
struct log_Nav_Tuning
struct log_Status
struct log_Sonar
struct log_Optflow
struct log_Arm_Disarm
Macros
#define PLOG(_s) if (g.log_bitmask & MASK_LOG_ ## _s) cliSerial->printf_P(PSTR(" %S"), PSTR(# _s))
#define TARG(_s) if (!strcasecmp_P(argv[1].str, PSTR(# _s))) bits |= MASK_LOG_ ## _s
Functions
static int8_t dump_log (uint8_t argc, const Menu::arg *argv)
static int8_t erase_logs (uint8_t argc, const Menu::arg *argv)
static int8_t select_logs (uint8_t argc, const Menu::arg *argv)
MENU2 (log_menu,"Log", log_menu_commands, print_log_menu)
static bool print_log_menu (void)
static int8_t process_logs (uint8_t argc, const Menu::arg *argv)
static void do_erase_logs (void)
static void Log_Write_Attitude (void)
static void Log_Write_Performance ()
static void Log_Write_Cmd (const AP_Mission::Mission_Command &cmd)
static void Log_Write_Startup (uint8_t type)
static void Log_Write_EntireMission ()
static void Log_Write_Control_Tuning ()
static void Log_Write_TECS_Tuning (void)
static void Log_Write_Nav_Tuning ()
static void Log_Write_Status ()
static void Log_Write_Sonar ()
static void Log_Write_Optflow ()
static void Log_Write_Current ()
static void Log_Arm_Disarm ()
static void Log_Write_GPS (uint8_t instance)
static void Log_Write_IMU ()
static void Log_Write_RC (void)
static void Log_Write_Baro (void)
static void Log_Write_Airspeed (void)
static void Log_Read (uint16_t log_num, int16_t start_page, int16_t end_page)
static void start_logging ()
Variables
static const struct
Menu::command
log_menu_commands[] PROGMEM
Macro Definition Documentation
#define PLOG (_s) if (g.log_bitmask & MASK_LOG_ ## _s) cliSerial->printf_P(PSTR(" %S"), PSTR(# _s))
Referenced by print_log_menu().
#define TARG (_s) if (!strcasecmp_P(argv[1].str, PSTR(# _s))) bits |= MASK_LOG_ ## _s
Referenced by select_logs().
Function Documentation
static void do_erase_logs (void) static
Definition at line 163 of file Log.pde.
Referenced by erase_logs(), and init_ardupilot().
static int8_t dump_log (uint8_t argc, const Menu::arg * argv) static
Definition at line 67 of file Log.pde.
static int8_t erase_logs (uint8_t argc, const Menu::arg * argv) static
Definition at line 98 of file Log.pde.
static void Log_Arm_Disarm () static
Definition at line 431 of file Log.pde.
Referenced by change_arm_state().
static void Log_Read (uint16_t log_num, int16_t start_page, int16_t end_page) static
Definition at line 495 of file Log.pde.
Referenced by dump_log().
static void Log_Write_Airspeed (void) static
Definition at line 463 of file Log.pde.
Referenced by read_airspeed().
static void Log_Write_Attitude (void) static
Definition at line 172 of file Log.pde.
Referenced by ahrs_update(), and update_logging1().
static void Log_Write_Baro (void) static
Definition at line 457 of file Log.pde.
Referenced by update_alt().
static void Log_Write_Cmd (const AP_Mission::Mission_Command & cmd) static
Definition at line 226 of file Log.pde.
Referenced by Log_Write_EntireMission(), and start_command().
static void Log_Write_Control_Tuning () static
Definition at line 277 of file Log.pde.
Referenced by update_logging2().
static void Log_Write_Current () static
Definition at line 423 of file Log.pde.
Referenced by one_second_loop().
static void Log_Write_EntireMission () static
Definition at line 252 of file Log.pde.
Referenced by Log_Write_Startup().
static void Log_Write_GPS (uint8_t instance) static
Definition at line 441 of file Log.pde.
Referenced by update_GPS_50Hz().
static void Log_Write_IMU () static
Definition at line 446 of file Log.pde.
Referenced by ahrs_update(), and update_logging1().
static void Log_Write_Nav_Tuning () static
Definition at line 314 of file Log.pde.
Referenced by update_logging2().
static void Log_Write_Optflow () static
Definition at line 395 of file Log.pde.
static void Log_Write_Performance () static
Definition at line 209 of file Log.pde.
Referenced by log_perf_info().
static void Log_Write_RC (void) static
Definition at line 451 of file Log.pde.
Referenced by update_logging2().
static void Log_Write_Sonar () static
Definition at line 367 of file Log.pde.
Referenced by read_rangefinder().
static void Log_Write_Startup (uint8_t type) static
Definition at line 239 of file Log.pde.
Referenced by init_ardupilot().
static void Log_Write_Status () static
Definition at line 340 of file Log.pde.
Referenced by one_second_loop().
static void Log_Write_TECS_Tuning (void) static
Definition at line 295 of file Log.pde.
Referenced by update_flight_stage().
MENU2 (log_menu , "Log" , log_menu_commands , print_log_menu)
static bool print_log_menu (void) static
Definition at line 30 of file Log.pde.
static int8_t process_logs (uint8_t argc, const Menu::arg * argv) static
Definition at line 155 of file Log.pde.
static int8_t select_logs (uint8_t argc, const Menu::arg * argv) static
Definition at line 107 of file Log.pde.
static void start_logging () static
Definition at line 510 of file Log.pde.
Referenced by should_log().
Variable Documentation
const struct LogStructure log_structure [] PROGMEM static
Initial value:
= {
    {"dump",        dump_log},
    {"erase",       erase_logs},
    {"enable",      select_logs},
    {"disable",     select_logs}
}
Definition at line 19 of file Log.pde.