APM:Plane: ArduPlane/navigation.pde File Reference
navigation.pde File Reference
Functions
static void set_nav_controller (void)
static void loiter_angle_reset (void)
static void loiter_angle_update (void)
static void navigate ()
static void calc_airspeed_errors ()
static void calc_gndspeed_undershoot ()
static void update_loiter ()
static void update_cruise ()
static void update_fbwb_speed_height (void)
static void setup_turn_angle (void)
Function Documentation
static void calc_airspeed_errors () static
Definition at line 75 of file navigation.pde.
Referenced by read_airspeed().
static void calc_gndspeed_undershoot () static
Definition at line 114 of file navigation.pde.
Referenced by update_GPS_10Hz().
static void loiter_angle_reset (void) static
Definition at line 17 of file navigation.pde.
Referenced by set_guided_WP(), and set_next_WP().
static void loiter_angle_update (void) static
Definition at line 27 of file navigation.pde.
Referenced by navigate().
static void navigate () static
Definition at line 46 of file navigation.pde.
static void set_nav_controller (void) static
Definition at line 5 of file navigation.pde.
Referenced by init_ardupilot(), and navigate().
static void setup_turn_angle (void) static
Definition at line 205 of file navigation.pde.
Referenced by do_RTL(), exit_mission_callback(), set_guided_WP(), and set_next_WP().
static void update_cruise () static
Definition at line 137 of file navigation.pde.
Referenced by update_navigation().
static void update_fbwb_speed_height (void) static
Definition at line 173 of file navigation.pde.
Referenced by update_flight_mode().
static void update_loiter () static
Definition at line 128 of file navigation.pde.
Referenced by update_navigation(), verify_loiter_time(), verify_loiter_to_alt(), verify_loiter_turns(), verify_loiter_unlim(), and verify_RTL().