APM:Plane: ArduPlane/radio.pde File Reference
radio.pde File Reference
Functions
static void set_control_channels (void)
static void init_rc_in ()
static void init_rc_out ()
static void rudder_arm_check ()
static void read_radio ()
static void control_failsafe (uint16_t pwm)
static void trim_control_surfaces ()
static void trim_radio ()
static bool rc_failsafe_active (void)
Function Documentation
static void control_failsafe (uint16_t pwm) static
Definition at line 189 of file radio.pde.
Referenced by read_radio().
static void init_rc_in () static
Definition at line 40 of file radio.pde.
Referenced by init_ardupilot().
static void init_rc_out () static
Definition at line 54 of file radio.pde.
Referenced by init_ardupilot().
static bool rc_failsafe_active (void) static
Definition at line 308 of file radio.pde.
Referenced by control_failsafe(), and stick_mixing_enabled().
static void read_radio () static
Definition at line 127 of file radio.pde.
Referenced by setup_radio(), test_failsafe(), test_radio(), test_radio_pwm(), trim_control_surfaces(), and trim_radio().
static void rudder_arm_check () static
Definition at line 78 of file radio.pde.
Referenced by read_radio().
static void set_control_channels (void) static
Definition at line 9 of file radio.pde.
Referenced by init_ardupilot(), and one_second_loop().
static void trim_control_surfaces () static
Definition at line 241 of file radio.pde.
Referenced by set_mode(), and trim_radio().
static void trim_radio () static
Definition at line 295 of file radio.pde.
Referenced by setup_radio(), startup_ground(), test_failsafe(), and test_radio().