APM:Plane: ArduPlane/sensors.pde File Reference
sensors.pde File Reference
Functions
static void init_barometer (void)
static void init_rangefinder (void)
static void read_rangefinder (void)
static void read_airspeed (void)
static void zero_airspeed (bool in_startup)
static void read_battery (void)
void read_receiver_rssi (void)
Function Documentation
static void init_barometer (void) static
Definition at line 3 of file sensors.pde.
Referenced by startup_INS_ground(), and test_pressure().
static void init_rangefinder (void) static
Definition at line 11 of file sensors.pde.
Referenced by init_ardupilot().
static void read_airspeed (void) static
Definition at line 32 of file sensors.pde.
Referenced by test_airspeed(), and zero_airspeed().
static void read_battery (void) static
Definition at line 67 of file sensors.pde.
static void read_rangefinder (void) static
Definition at line 19 of file sensors.pde.
void read_receiver_rssi (void)
Definition at line 80 of file sensors.pde.
static void zero_airspeed (bool in_startup) static
Definition at line 56 of file sensors.pde.
Referenced by startup_INS_ground(), and test_airspeed().