APM:Plane: ArduPlane/setup.pde File Reference
setup.pde File Reference
Functions
static int8_t setup_radio (uint8_t argc, const Menu::arg *argv)
static int8_t setup_show (uint8_t argc, const Menu::arg *argv)
static int8_t setup_factory (uint8_t argc, const Menu::arg *argv)
static int8_t setup_accel_scale (uint8_t argc, const Menu::arg *argv)
static int8_t setup_set (uint8_t argc, const Menu::arg *argv)
static int8_t setup_erase (uint8_t argc, const Menu::arg *argv)
static int8_t setup_compass (uint8_t argc, const Menu::arg *argv)
MENU (setup_menu,"setup", setup_menu_commands)
static int8_t setup_mode (uint8_t argc, const Menu::arg *argv)
static void report_radio ()
static void report_ins ()
static void report_compass ()
static void print_radio_values ()
static void print_done ()
static void print_blanks (int16_t num)
static void print_divider (void)
static void zero_eeprom (void)
static void print_enabled (bool b)
static void print_accel_offsets_and_scaling (void)
static void print_gyro_offsets (void)
Variables
static const struct
Menu::command
setup_menu_commands[] PROGMEM
Function Documentation
MENU (setup_menu , "setup" , setup_menu_commands)
static void print_accel_offsets_and_scaling (void) static
Definition at line 417 of file setup.pde.
Referenced by report_ins().
static void print_blanks (int16_t num) static
Definition at line 383 of file setup.pde.
Referenced by report_compass(), report_ins(), and report_radio().
static void print_divider (void) static
Definition at line 392 of file setup.pde.
Referenced by report_ins(), and report_radio().
static void print_done () static
Definition at line 377 of file setup.pde.
Referenced by setup_radio().
static void print_enabled (bool b) static
Definition at line 407 of file setup.pde.
Referenced by report_compass(), test_airspeed(), and test_mag().
static void print_gyro_offsets (void) static
Definition at line 431 of file setup.pde.
Referenced by report_ins().
static void print_radio_values () static
Definition at line 363 of file setup.pde.
Referenced by report_radio().
static void report_compass () static
Definition at line 343 of file setup.pde.
Referenced by setup_compass(), and test_mag().
static void report_ins () static
Definition at line 332 of file setup.pde.
Referenced by setup_accel_scale().
static void report_radio () static
Definition at line 322 of file setup.pde.
Referenced by setup_radio().
static int8_t setup_accel_scale (uint8_t argc, const Menu::arg * argv) static
Definition at line 271 of file setup.pde.
static int8_t setup_compass (uint8_t argc, const Menu::arg * argv) static
Definition at line 292 of file setup.pde.
static int8_t setup_erase (uint8_t argc, const Menu::arg * argv) static
Definition at line 250 of file setup.pde.
static int8_t setup_factory (uint8_t argc, const Menu::arg * argv) static
Definition at line 138 of file setup.pde.
static int8_t setup_mode (uint8_t argc, const Menu::arg * argv) static
Definition at line 33 of file setup.pde.
static int8_t setup_radio (uint8_t argc, const Menu::arg * argv) static
Definition at line 165 of file setup.pde.
static int8_t setup_set (uint8_t argc, const Menu::arg * argv) static
Definition at line 78 of file setup.pde.
static int8_t setup_show (uint8_t argc, const Menu::arg * argv) static
Definition at line 51 of file setup.pde.
static void zero_eeprom (void) static
Definition at line 400 of file setup.pde.
Referenced by setup_erase().
Variable Documentation
const struct Menu::command setup_menu_commands [] PROGMEM static
Initial value:
= {
    {"reset",                       setup_factory},
    {"radio",                       setup_radio},
    {"accel",                       setup_accel_scale},
    {"compass",                     setup_compass},
    {"show",                        setup_show},
    {"set",                         setup_set},
    {"erase",                       setup_erase},
}
Definition at line 16 of file setup.pde.