APM:Plane: ArduPlane/system.pde File Reference
system.pde File Reference
Functions
static int8_t process_logs (uint8_t argc, const Menu::arg *argv)
static int8_t setup_mode (uint8_t argc, const Menu::arg *argv)
static int8_t test_mode (uint8_t argc, const Menu::arg *argv)
static int8_t reboot_board (uint8_t argc, const Menu::arg *argv)
static int8_t main_menu_help (uint8_t argc, const Menu::arg *argv)
MENU (main_menu, THISFIRMWARE, main_menu_commands)
static void run_cli (AP_HAL::UARTDriver *port)
static void init_ardupilot ()
static void startup_ground (void)
static enum FlightMode get_previous_mode ()
static void set_mode (enum FlightMode mode)
static bool mavlink_set_mode (uint8_t mode)
static void exit_mode (enum FlightMode mode)
static void check_long_failsafe ()
static void check_short_failsafe ()
static void startup_INS_ground (void)
static void update_notify ()
static void resetPerfData (void)
static void check_usb_mux (void)
static void print_flight_mode (AP_HAL::BetterStream *port, uint8_t mode)
static void print_comma (void)
static void servo_write (uint8_t ch, uint16_t pwm)
static bool should_log (uint32_t mask)
static void frsky_telemetry_send (void)
static uint8_t throttle_percentage (void)
static void change_arm_state (void)
static bool arm_motors (AP_Arming::ArmingMethod method)
static bool disarm_motors (void)
Variables
static const struct
Menu::command
main_menu_commands[] PROGMEM
Function Documentation
static bool arm_motors (AP_Arming::ArmingMethod method) static
Definition at line 740 of file system.pde.
static void change_arm_state (void) static
Definition at line 725 of file system.pde.
Referenced by arm_motors(), and disarm_motors().
static void check_long_failsafe () static
Definition at line 476 of file system.pde.
static void check_short_failsafe () static
Definition at line 506 of file system.pde.
static void check_usb_mux (void) static
Definition at line 585 of file system.pde.
Referenced by init_ardupilot(), and mavlink_delay_cb().
static bool disarm_motors (void) static
Definition at line 755 of file system.pde.
Referenced by disarm_if_autoland_complete().
static void exit_mode (enum FlightMode mode) static
Definition at line 466 of file system.pde.
Referenced by set_mode().
static void frsky_telemetry_send (void) static
Definition at line 705 of file system.pde.
static enum FlightMode get_previous_mode () static
Definition at line 308 of file system.pde.
Referenced by geofence_check().
static void init_ardupilot () static
Definition at line 71 of file system.pde.
Referenced by setup().
static int8_t main_menu_help (uint8_t argc, const Menu::arg * argv) static
Definition at line 20 of file system.pde.
static bool mavlink_set_mode (uint8_t mode) static
Definition at line 443 of file system.pde.
MENU (main_menu , THISFIRMWARE , main_menu_commands)
static void print_comma (void) static
Definition at line 659 of file system.pde.
Referenced by test_passthru().
static void print_flight_mode (AP_HAL::BetterStream * port, uint8_t mode) static
Definition at line 610 of file system.pde.
static int8_t process_logs (uint8_t argc, const Menu::arg * argv) static
static int8_t reboot_board (uint8_t argc, const Menu::arg * argv) static
Definition at line 45 of file system.pde.
static void resetPerfData (void) static
Definition at line 576 of file system.pde.
Referenced by log_perf_info().
static void run_cli (AP_HAL::UARTDriver * port) static
Definition at line 52 of file system.pde.
static void servo_write (uint8_t ch, uint16_t pwm) static
Definition at line 668 of file system.pde.
Referenced by demo_servos(), and test_passthru().
static void set_mode (enum FlightMode mode) static
Definition at line 312 of file system.pde.
Referenced by failsafe_long_on_event(), failsafe_short_off_event(), failsafe_short_on_event(), geofence_check(), init_ardupilot(), jump_to_landing_sequence(), low_battery_event(), mavlink_set_mode(), read_control_switch(), start_command(), and startup_ground().
static int8_t setup_mode (uint8_t argc, const Menu::arg * argv) static
static bool should_log (uint32_t mask) static
Definition at line 683 of file system.pde.
Referenced by ahrs_update(), change_arm_state(), do_RTL(), init_ardupilot(), log_perf_info(), log_picture(), one_second_loop(), read_airspeed(), read_rangefinder(), set_mode(), start_command(), startup_ground(), update_alt(), update_compass(), update_flight_stage(), update_GPS_50Hz(), update_logging1(), and update_logging2().
static void startup_ground (void) static
Definition at line 251 of file system.pde.
Referenced by init_ardupilot().
static void startup_INS_ground (void) static
Definition at line 524 of file system.pde.
Referenced by startup_ground().
static int8_t test_mode (uint8_t argc, const Menu::arg * argv) static
static uint8_t throttle_percentage (void) static
Definition at line 715 of file system.pde.
Referenced by adjust_nav_pitch_throttle(), and send_vfr_hud().
static void update_notify () static
Definition at line 571 of file system.pde.
Variable Documentation
const struct Menu::command main_menu_commands [] PROGMEM static
Initial value:
= {
    {"logs",                process_logs},
    {"setup",               setup_mode},
    {"test",                test_mode},
    {"reboot",              reboot_board},
    {"help",                main_menu_help},
}
Definition at line 32 of file system.pde.