APM:Plane: ArduPlane/takeoff.pde File Reference
takeoff.pde File Reference
Functions
static bool auto_takeoff_check (void)
static void takeoff_calc_roll (void)
static void takeoff_calc_pitch (void)
static int8_t takeoff_tail_hold (void)
Function Documentation
static bool auto_takeoff_check (void) static
Definition at line 12 of file takeoff.pde.
Referenced by suppress_throttle().
static void takeoff_calc_pitch (void) static
Definition at line 108 of file takeoff.pde.
Referenced by handle_auto_mode().
static void takeoff_calc_roll (void) static
Definition at line 88 of file takeoff.pde.
Referenced by handle_auto_mode().
static int8_t takeoff_tail_hold (void) static
Definition at line 137 of file takeoff.pde.
Referenced by stabilize_pitch().