APM:Plane: ArduPlane/test.pde File Reference
test.pde File Reference
Functions
static int8_t test_radio_pwm (uint8_t argc, const Menu::arg *argv)
static int8_t test_radio (uint8_t argc, const Menu::arg *argv)
static int8_t test_passthru (uint8_t argc, const Menu::arg *argv)
static int8_t test_failsafe (uint8_t argc, const Menu::arg *argv)
static int8_t test_gps (uint8_t argc, const Menu::arg *argv)
static int8_t test_adc (uint8_t argc, const Menu::arg *argv)
static int8_t test_ins (uint8_t argc, const Menu::arg *argv)
static int8_t test_relay (uint8_t argc, const Menu::arg *argv)
static int8_t test_wp (uint8_t argc, const Menu::arg *argv)
static int8_t test_airspeed (uint8_t argc, const Menu::arg *argv)
static int8_t test_pressure (uint8_t argc, const Menu::arg *argv)
static int8_t test_mag (uint8_t argc, const Menu::arg *argv)
static int8_t test_xbee (uint8_t argc, const Menu::arg *argv)
static int8_t test_modeswitch (uint8_t argc, const Menu::arg *argv)
static int8_t test_logging (uint8_t argc, const Menu::arg *argv)
static int8_t test_shell (uint8_t argc, const Menu::arg *argv)
static void test_wp_print (const AP_Mission::Mission_Command &cmd)
MENU (test_menu,"test", test_menu_commands)
static int8_t test_mode (uint8_t argc, const Menu::arg *argv)
static void print_hit_enter ()
Variables
static const struct
Menu::command
test_menu_commands[] PROGMEM
Function Documentation
MENU (test_menu , "test" , test_menu_commands)
static void print_hit_enter () static
Definition at line 73 of file test.pde.
Referenced by test_adc(), test_airspeed(), test_failsafe(), test_gps(), test_ins(), test_mag(), test_modeswitch(), test_passthru(), test_pressure(), test_radio(), test_radio_pwm(), test_relay(), and test_xbee().
static int8_t test_adc (uint8_t argc, const Menu::arg * argv) static
Definition at line 359 of file test.pde.
static int8_t test_airspeed (uint8_t argc, const Menu::arg * argv) static
Definition at line 537 of file test.pde.
static int8_t test_failsafe (uint8_t argc, const Menu::arg * argv) static
Definition at line 174 of file test.pde.
static int8_t test_gps (uint8_t argc, const Menu::arg * argv) static
Definition at line 379 of file test.pde.
static int8_t test_ins (uint8_t argc, const Menu::arg * argv) static
Definition at line 408 of file test.pde.
static int8_t test_logging (uint8_t argc, const Menu::arg * argv) static
Definition at line 336 of file test.pde.
static int8_t test_mag (uint8_t argc, const Menu::arg * argv) static
Definition at line 460 of file test.pde.
static int8_t test_mode (uint8_t argc, const Menu::arg * argv) static
Definition at line 66 of file test.pde.
static int8_t test_modeswitch (uint8_t argc, const Menu::arg * argv) static
Definition at line 310 of file test.pde.
static int8_t test_passthru (uint8_t argc, const Menu::arg * argv) static
Definition at line 109 of file test.pde.
static int8_t test_pressure (uint8_t argc, const Menu::arg * argv) static
Definition at line 563 of file test.pde.
static int8_t test_radio (uint8_t argc, const Menu::arg * argv) static
Definition at line 135 of file test.pde.
static int8_t test_radio_pwm (uint8_t argc, const Menu::arg * argv) static
Definition at line 79 of file test.pde.
static int8_t test_relay (uint8_t argc, const Menu::arg * argv) static
Definition at line 229 of file test.pde.
static int8_t test_shell (uint8_t argc, const Menu::arg * argv) static
Definition at line 347 of file test.pde.
static int8_t test_wp (uint8_t argc, const Menu::arg * argv) static
Definition at line 252 of file test.pde.
static void test_wp_print (const AP_Mission::Mission_Command & cmd) static
Definition at line 278 of file test.pde.
Referenced by test_wp().
static int8_t test_xbee (uint8_t argc, const Menu::arg * argv) static
Definition at line 291 of file test.pde.
Variable Documentation
const struct Menu::command test_menu_commands [] PROGMEM static
Initial value:
= {
    {"pwm",                         test_radio_pwm},
    {"radio",                       test_radio},
    {"passthru",            test_passthru},
    {"failsafe",            test_failsafe},
    {"relay",                       test_relay},
    {"waypoints",           test_wp},
    {"xbee",                        test_xbee},
    {"modeswitch",          test_modeswitch},
    {"adc",                 test_adc},
    {"gps",                 test_gps},
    {"ins",                 test_ins},
    {"airspeed",    test_airspeed},
    {"airpressure", test_pressure},
    {"compass",             test_mag},
    {"logging",             test_logging},
    {"shell",               test_shell},
}
Definition at line 35 of file test.pde.