APM:Libraries: libraries/AP_Airspeed/examples/Airspeed/Airspeed.pde File Reference
Airspeed.pde File Reference
#include <AP_Common.h>
#include <AP_Progmem.h>
#include <AP_Param.h>
#include <AP_Math.h>
#include <AP_HAL.h>
#include <AP_HAL_AVR.h>
#include <AP_HAL_Linux.h>
#include <AP_HAL_Empty.h>
#include <AP_ADC.h>
#include <AP_ADC_AnalogSource.h>
#include <Filter.h>
#include <AP_Buffer.h>
#include <AP_Airspeed.h>
#include <AP_Vehicle.h>
#include <AP_Notify.h>
#include <AP_Compass.h>
#include <AP_Declination.h>
#include <AP_AHRS.h>
#include <AP_NavEKF.h>
#include <AP_Terrain.h>
#include <DataFlash.h>
#include <AP_Baro.h>
#include <GCS_MAVLink.h>
#include <AP_Mission.h>
#include <StorageManager.h>
#include <AP_GPS.h>
#include <AP_InertialSensor.h>
#include <AP_BattMonitor.h>
#include <AP_Rally.h>
#include <AP_RangeFinder.h>
Functions
void setup ()
void loop (void)
AP_HAL_MAIN ()
Variables
AP_ADC_ADS7844 apm1_adc
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
const AP_HAL::HAL & hal = AP_HAL_BOARD_DRIVER
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
static AP_Vehicle::FixedWing aparm
AP_Airspeed airspeed (aparm)
Function Documentation
AP_HAL_MAIN ()
void loop (void)
Definition at line 74 of file Airspeed.pde.
void setup (void)
Definition at line 64 of file Airspeed.pde.
Variable Documentation
AP_Airspeed airspeed(aparm)
Referenced by HALSITL::SITL_State::_airspeed_sensor(), AP_Arming::airspeed_checks(), AP_AHRS_DCM::drift_correction(), AP_AHRS_DCM::estimate_wind(), AP_AHRS::groundspeed_vector(), loop(), mavlink_msg_vfr_hud_pack(), mavlink_msg_vfr_hud_pack_chan(), AP_AHRS::set_airspeed(), AP_Airspeed::set_HIL(), NavEKF::SetFlightAndFusionModes(), AP_Airspeed::setHIL(), setup(), and Airspeed_Calibration::update().
AP_Vehicle::FixedWing aparm static
Definition at line 60 of file Airspeed.pde.
AP_ADC_ADS7844 apm1_adc
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 55 of file Airspeed.pde.
const AP_HAL::HAL& hal = AP_HAL_BOARD_DRIVER
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 58 of file Airspeed.pde.