APM:Libraries: libraries/AP_Mission/examples/AP_Mission_test/AP_Mission_test.pde File Reference
AP_Mission_test.pde File Reference
#include <AP_Common.h>
#include <AP_Progmem.h>
#include <AP_Math.h>
#include <AP_Curve.h>
#include <AP_Param.h>
#include <AP_HAL.h>
#include <AP_HAL_AVR.h>
#include <AP_HAL_SITL.h>
#include <AP_HAL_PX4.h>
#include <AP_HAL_Empty.h>
#include <SITL.h>
#include <AP_Rally.h>
#include <GCS_MAVLink.h>
#include <AP_Notify.h>
#include <AP_Vehicle.h>
#include <DataFlash.h>
#include <AP_Mission.h>
#include <AP_NavEKF.h>
#include <StorageManager.h>
#include <AP_Terrain.h>
#include <AP_GPS.h>
#include <AP_ADC.h>
#include <AP_ADC_AnalogSource.h>
#include <AP_Baro.h>
#include <Filter.h>
#include <AP_Compass.h>
#include <AP_Declination.h>
#include <AP_InertialSensor.h>
#include <AP_AHRS.h>
#include <AP_Airspeed.h>
#include <AP_Buffer.h>
#include <AP_BattMonitor.h>
#include <AP_RangeFinder.h>
Functions
bool start_cmd (const AP_Mission::Mission_Command &cmd)
bool verify_cmd (const AP_Mission::Mission_Command &cmd)
void mission_complete (void)
AP_Mission mission (ahrs,&start_cmd,&verify_cmd,&mission_complete)
void setup (void)
void loop (void)
void run_mission_test ()
void init_mission ()
void init_mission_no_nav_commands ()
void init_mission_endless_loop ()
void init_mission_jump_to_nonnav ()
void init_mission_starts_with_do_commands ()
void init_mission_ends_with_do_commands ()
void init_mission_ends_with_jump_command ()
void print_mission ()
void run_resume_test ()
void run_set_current_cmd_test ()
void run_set_current_cmd_while_stopped_test ()
void run_replace_cmd_test ()
void run_max_cmd_test ()
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL_BOARD_DRIVER
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
AP_InertialSensor ins
AP_Baro baro
static AP_GPS gps
Compass compass
AP_AHRS_DCM ahrs (ins, baro, gps)
static uint8_t verify_nav_cmd_iterations_to_complete = 3
static uint8_t verify_do_cmd_iterations_to_complete = 1
static uint8_t num_nav_cmd_runs = 0
static uint8_t num_do_cmd_runs = 0
Function Documentation
AP_HAL_MAIN ()
void init_mission ()
Definition at line 193 of file AP_Mission_test.pde.
Referenced by run_mission_test().
void init_mission_endless_loop ()
Definition at line 321 of file AP_Mission_test.pde.
void init_mission_ends_with_do_commands ()
Definition at line 514 of file AP_Mission_test.pde.
void init_mission_ends_with_jump_command ()
Definition at line 590 of file AP_Mission_test.pde.
void init_mission_jump_to_nonnav ()
Definition at line 373 of file AP_Mission_test.pde.
void init_mission_no_nav_commands ()
Definition at line 264 of file AP_Mission_test.pde.
void init_mission_starts_with_do_commands ()
Definition at line 437 of file AP_Mission_test.pde.
void loop (void)
Definition at line 119 of file AP_Mission_test.pde.
AP_Mission mission (ahrs , & start_cmd, & verify_cmd, & mission_complete)
Referenced by init_mission(), init_mission_endless_loop(), init_mission_ends_with_do_commands(), init_mission_ends_with_jump_command(), init_mission_jump_to_nonnav(), init_mission_no_nav_commands(), init_mission_starts_with_do_commands(), print_mission(), run_max_cmd_test(), run_mission_test(), run_replace_cmd_test(), run_resume_test(), run_set_current_cmd_test(), run_set_current_cmd_while_stopped_test(), and setup().
void mission_complete (void)
Definition at line 100 of file AP_Mission_test.pde.
Referenced by ToneAlarm_PX4::update().
void print_mission ()
Definition at line 673 of file AP_Mission_test.pde.
Referenced by run_mission_test(), run_replace_cmd_test(), run_resume_test(), run_set_current_cmd_test(), and run_set_current_cmd_while_stopped_test().
void run_max_cmd_test ()
Definition at line 1165 of file AP_Mission_test.pde.
void run_mission_test ()
Definition at line 134 of file AP_Mission_test.pde.
Referenced by loop().
void run_replace_cmd_test ()
Definition at line 1060 of file AP_Mission_test.pde.
void run_resume_test ()
Definition at line 712 of file AP_Mission_test.pde.
void run_set_current_cmd_test ()
Definition at line 818 of file AP_Mission_test.pde.
void run_set_current_cmd_while_stopped_test ()
Definition at line 923 of file AP_Mission_test.pde.
void setup (void)
Definition at line 109 of file AP_Mission_test.pde.
bool start_cmd (const AP_Mission::Mission_Command & cmd)
Definition at line 60 of file AP_Mission_test.pde.
bool verify_cmd (const AP_Mission::Mission_Command & cmd)
Definition at line 76 of file AP_Mission_test.pde.
Variable Documentation
AP_AHRS_DCM ahrs(ins, baro, gps)
AP_Baro baro
Definition at line 44 of file AP_Mission_test.pde.
Compass compass
Definition at line 49 of file AP_Mission_test.pde.
AP_GPS gps static
Definition at line 47 of file AP_Mission_test.pde.
const AP_HAL::HAL& hal = AP_HAL_BOARD_DRIVER
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 41 of file AP_Mission_test.pde.
AP_InertialSensor ins
Definition at line 43 of file AP_Mission_test.pde.
uint8_t num_do_cmd_runs = 0 static
Definition at line 56 of file AP_Mission_test.pde.
Referenced by start_cmd(), and verify_cmd().
uint8_t num_nav_cmd_runs = 0 static
Definition at line 55 of file AP_Mission_test.pde.
Referenced by start_cmd(), and verify_cmd().
uint8_t verify_do_cmd_iterations_to_complete = 1 static
Definition at line 54 of file AP_Mission_test.pde.
Referenced by verify_cmd().
uint8_t verify_nav_cmd_iterations_to_complete = 3 static
Definition at line 53 of file AP_Mission_test.pde.
Referenced by verify_cmd().