APM:Libraries: libraries/AP_Math/AP_Math.cpp File Reference
AP_Math.cpp File Reference
#include "AP_Math.h"
#include <float.h>
Functions
float safe_asin (float v)
float safe_sqrt (float v)
float constrain_float (float amt, float low, float high)
int16_t constrain_int16 (int16_t amt, int16_t low, int16_t high)
int32_t constrain_int32 (int32_t amt, int32_t low, int32_t high)
float radians (float deg)
float degrees (float rad)
float sq (float v)
float pythagorous2 (float a, float b)
float pythagorous3 (float a, float b, float c)
Function Documentation
float constrain_float (float amt, float low, float high)
Definition at line 74 of file AP_Math.cpp.
Referenced by AP_PitchController::_get_coordination_rate_offset(), AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), HALSITL::SITL_State::_ground_sonar(), AP_TECS::_update_pitch(), AP_TECS::_update_speed_demand(), AP_TECS::_update_throttle(), AP_TECS::_update_throttle_option(), AC_PosControl::accel_to_lean_angles(), AP_AHRS::add_trim(), AC_WPNav::advance_wp_target_along_track(), AP_AHRS_DCM::airspeed_estimate(), AP_AHRS::airspeed_estimate(), AC_AttitudeControl::angle_ef_roll_pitch_rate_ef_yaw(), AC_AttitudeControl::angle_ef_roll_pitch_rate_ef_yaw_smooth(), AC_AttitudeControl::angle_ef_roll_pitch_yaw(), DigitalLPF::apply(), AP_Motors::apply_thrust_curve_and_volt_scaling(), AC_Circle::calc_velocities(), Compass::calculate_heading(), NavEKF::ConstrainStates(), NavEKF::ConstrainVariances(), NavEKF::CovariancePrediction(), AP_Motors::current_limit_max_throttle(), NavEKF::decayGpsOffset(), AP_AHRS_DCM::drift_correction(), NavEKF::FuseAirspeed(), NavEKF::FuseMagnetometer(), NavEKF::FuseOptFlow(), NavEKF::FuseVelPosNED(), AC_AttitudeControl::get_boosted_throttle(), AP_Motors::get_compensation_gain(), AP_Declination::get_declination(), get_declination(), PID::get_pid_4500(), AP_YawController::get_servo_out(), AP_SteerController::get_steering_out_rate(), AC_PosControl::get_stopping_point_xy(), AC_PosControl::get_stopping_point_z(), AC_AttitudeControl::integrate_bf_rate_error_to_angle_errors(), Compass::learn_offsets(), longitude_scale(), AP_MotorsHeli::move_swash(), AP_L1_Control::nav_roll_cd(), RC_Channel::norm_input(), RC_Channel::norm_input_dz(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), AC_AttitudeControl::rate_bf_roll_pitch_yaw(), AC_AttitudeControl::rate_bf_to_motor_pitch(), AC_AttitudeControl::rate_bf_to_motor_roll(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_AttitudeControl_Heli::rate_bf_to_motor_yaw(), AC_AttitudeControl::rate_bf_to_motor_yaw(), AC_AttitudeControl::rate_ef_roll_pitch_yaw(), NavEKF::readGpsData(), NavEKF::readHgtData(), CRRCSim::send_servos_fixed_wing(), CRRCSim::send_servos_heli(), AC_PosControl::set_alt_target_from_climb_rate(), AC_PosControl::set_alt_target_with_slew(), AP_Param::set_param_by_name(), AP_AHRS::set_trim(), AC_WPNav::set_wp_origin_and_destination(), AP_AutoTune::start(), Airspeed_Calibration::update(), AC_Circle::update(), AP_Airspeed::update_calibration(), AC_AttitudeControl::update_ef_pitch_angle_and_error(), AC_AttitudeControl::update_ef_roll_angle_and_error(), AC_AttitudeControl::update_ef_yaw_angle_and_error(), AP_L1_Control::update_heading_hold(), AP_Motors::update_lift_max_from_batt_voltage(), AP_L1_Control::update_loiter(), AC_AttitudeControl::update_rate_bf_targets(), AP_Mount_Backend::update_targets_from_rc(), AP_Motors::update_throttle_filter(), AP_Motors::update_throttle_thr_mix(), AP_AHRS::update_trig(), AP_L1_Control::update_waypoint(), NavEKF::UpdateStrapdownEquationsNED(), and NavEKF::writeOptFlowMeas().
int16_t constrain_int16 (int16_t amt, int16_t low, int16_t high)
Definition at line 87 of file AP_Math.cpp.
Referenced by RC_Channel::calc_pwm(), AP_MotorsHeli::init_swash(), AP_MotorsMatrix::output_armed_stabilizing(), RC_Channel::pwm_to_range_dz(), NavEKF::readGpsData(), AP_Camera::relay_pic(), AP_MotorsHeli::rotor_ramp(), AP_Camera::servo_pic(), AP_MotorsHeli::set_delta_phase_angle(), RC_Channel_aux::set_radio(), RC_Channel_aux::set_radio_trimmed(), AP_Motors::slow_start(), and AP_MotorsHeli::tail_ramp().
int32_t constrain_int32 (int32_t amt, int32_t low, int32_t high)
Definition at line 92 of file AP_Math.cpp.
float degrees (float rad)
Definition at line 102 of file AP_Math.cpp.
Referenced by AP_InertialSensor::_calculate_trim(), AP_TECS::_update_pitch(), JSBSim::create_templates(), Aircraft::fill_fdm(), DataFlash_Class::Log_Write_AHRS2(), AP_L1_Control::nav_roll_cd(), JSBSim::recv_fdm(), AP_GPS::setHIL(), AP_Mount_Servo::stabilize(), AP_AHRS::update_cd_values(), and Aircraft::update_position().
float pythagorous2 (float a, float b)
Definition at line 112 of file AP_Math.cpp.
Referenced by AP_InertialSensor::_calculate_trim(), HALSITL::SITL_State::_update_gps_mtk(), HALSITL::SITL_State::_update_gps_mtk16(), HALSITL::SITL_State::_update_gps_mtk19(), HALSITL::SITL_State::_update_gps_nmea(), HALSITL::SITL_State::_update_gps_ubx(), AP_AHRS_DCM::_yaw_gain(), AC_WPNav::advance_wp_target_along_track(), NavEKF::alignMagStateDeclination(), AP_Mount_Backend::calc_angle_to_location(), AC_WPNav::calc_loiter_desired_velocity(), AC_WPNav::calculate_wp_leash_length(), NavEKF::decayGpsOffset(), AP_AHRS_DCM::drift_correction(), AC_Circle::get_closest_point_on_circle(), get_distance(), AC_PosControl::get_stopping_point_xy(), AC_WPNav::get_wp_distance_to_destination(), Vector2< T >::length(), AC_PosControl::pos_to_rate_xy(), AC_PosControl::rate_to_accel_xy(), AP_GPS::setHIL(), NavEKF::setWindVelStates(), AC_Sprayer::update(), and NavEKF::UpdateStrapdownEquationsNED().
float pythagorous3 (float a, float b, float c)
Definition at line 117 of file AP_Math.cpp.
Referenced by HALSITL::SITL_State::_update_gps_ubx(), NavEKF::FuseAirspeed(), Vector3< T >::length(), and Airspeed_Calibration::update().
float radians (float deg)
Definition at line 97 of file AP_Math.cpp.
Referenced by AP_InertialSensor::_calculate_trim(), AP_PitchController::_get_coordination_rate_offset(), HALSITL::SITL_State::_ground_sonar(), HALSITL::SITL_State::_update_compass(), HALSITL::SITL_State::_update_flow(), OpticalFlow_backend::_yawAngleRad(), AP_MotorsMatrix::add_motor(), Aircraft::Aircraft(), NavEKF::alignYawGPS(), AP_Mount_Backend::angle_input_rad(), Rover::calc_lat_accel(), NavEKF::calcEarthRateNED(), AP_MotorsHeli::calculate_roll_pitch_collective_factors(), NavEKF::CovarianceInit(), AP_AHRS::groundspeed_vector(), Helicopter::Helicopter(), AP_Arming::ins_checks(), location_update(), NavEKF::resetGyroBias(), AP_Mount_Backend::set_angle_targets(), Compass::set_initial_location(), Aircraft::set_yaw_degrees(), test_euler(), Rover::turn_circle(), Rover::update(), Helicopter::update(), MultiCopter::update(), AP_L1_Control::update_heading_hold(), AP_TECS::update_pitch_throttle(), and AP_Mount_Backend::update_targets_from_rc().
float safe_asin (float v)
Definition at line 7 of file AP_Math.cpp.
Referenced by Quaternion::get_euler_pitch(), Matrix3< T >::to_euler(), and Quaternion::to_vector312().
float safe_sqrt (float v)
Definition at line 26 of file AP_Math.cpp.
Referenced by AP_GPS_SBP::_attempt_state_update(), AC_WPNav::advance_spline_target_along_track(), AP_Motors::apply_thrust_curve_and_volt_scaling(), AC_Circle::calc_velocities(), AP_Baro::get_EAS2TAS(), AC_WPNav::get_slow_down_speed(), AC_PosControl::pos_to_rate_xy(), AC_PosControl::set_alt_target_from_climb_rate(), AC_AttitudeControl::sqrt_controller(), and AP_AHRS::update_trig().
float sq (float v)
Definition at line 107 of file AP_Math.cpp.
Referenced by NavEKF::alignYawGPS(), AC_WPNav::calc_loiter_desired_velocity(), NavEKF::ConstrainVariances(), NavEKF::CovarianceInit(), NavEKF::CovariancePrediction(), NavEKF::EstimateTerrainOffset(), Quaternion::from_axis_angle_fast(), NavEKF::FuseAirspeed(), SmallEKF::fuseCompass(), NavEKF::FuseMagnetometer(), NavEKF::FuseOptFlow(), NavEKF::FuseSideslip(), SmallEKF::fuseVelocity(), NavEKF::FuseVelPosNED(), AP_Baro::get_air_density_ratio(), NavEKF::healthy(), Quaternion::length(), location_path_proportion(), SmallEKF::predictCovariance(), pythagorous2(), pythagorous3(), NavEKF::resetGyroBias(), Quaternion::rotate_fast(), SmallEKF::RunEKF(), NavEKF::SelectFlowFusion(), NavEKF::SetFlightAndFusionModes(), AC_AttitudeControl::sqrt_controller(), Quaternion::to_axis_angle(), AP_L1_Control::turn_distance(), Airspeed_Calibration::update(), AP_Airspeed::update_calibration(), AP_L1_Control::update_loiter(), and Aircraft::update_position().