APM:Libraries: libraries/AP_Progmem/AP_Progmem_Identity.h File Reference
AP_Progmem_Identity.h File Reference
#include <string.h>
#include <stdint.h>
Macros
#define PSTR(s) s
#define PROGMEM __attribute__(())
Typedefs
typedef char prog_char_t
typedef char prog_char
Functions
static int strcasecmp_P (const char *str1, const prog_char_t *pstr)
static int strcmp_P (const char *str1, const prog_char_t *pstr)
static size_t strlen_P (const prog_char_t *pstr)
static void * memcpy_P (void *dest, const prog_char_t *src, size_t n)
static char * strncpy_P (char *buffer, const prog_char_t *pstr, size_t buffer_size)
static size_t strnlen_P (const prog_char_t *str, size_t size)
static int strncmp_P (const char *str1, const prog_char_t *str2, size_t n)
static uint8_t pgm_read_byte (const void *s)
static uint8_t pgm_read_byte_far (const void *s)
static uint16_t pgm_read_word (const void *s)
static uint32_t pgm_read_dword (const void *s)
static float pgm_read_float (const void *s)
static uintptr_t pgm_read_pointer (const void *s)
Macro Definition Documentation
#define PROGMEM __attribute__(())
Definition at line 13 of file AP_Progmem_Identity.h.
#define PSTR (s) s
Definition at line 11 of file AP_Progmem_Identity.h.
Typedef Documentation
typedef char prog_char
Definition at line 9 of file AP_Progmem_Identity.h.
typedef char prog_char_t
Definition at line 8 of file AP_Progmem_Identity.h.
Function Documentation
static void* memcpy_P (void * dest, const prog_char_t * src, size_t n) inline static
Definition at line 30 of file AP_Progmem_Identity.h.
static uint8_t pgm_read_byte (const void * s) inline static
Definition at line 53 of file AP_Progmem_Identity.h.
Referenced by AP_Param::AP_Param(), AP_MotorsTri::enable(), AP_MotorsMatrix::enable(), AP_MotorsCoax::enable(), AP_MotorsSingle::enable(), AP_MotorsHeli::enable(), AP_MotorsTri::get_motor_mask(), mavlink_get_message_crc(), AP_MotorsHeli::move_swash(), AP_MotorsTri::output_armed_not_stabilizing(), AP_MotorsCoax::output_armed_not_stabilizing(), AP_MotorsSingle::output_armed_not_stabilizing(), AP_MotorsMatrix::output_armed_not_stabilizing(), AP_MotorsTri::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_MotorsTri::output_min(), AP_MotorsMatrix::output_min(), AP_MotorsCoax::output_min(), AP_MotorsSingle::output_min(), AP_MotorsTri::output_test(), AP_MotorsMatrix::output_test(), AP_MotorsCoax::output_test(), AP_MotorsSingle::output_test(), AP_MotorsHeli::output_test(), pgm_read_pointer(), AP_HAL::UARTDriver::print_P(), print_vprintf(), StorageAccess::read_block(), AP_GPS::send_blob_update(), GCS_MAVLINK::send_text_P(), AP_MotorsMatrix::set_update_rate(), AP_MotorsTri::set_update_rate(), AP_MotorsCoax::set_update_rate(), AP_MotorsSingle::set_update_rate(), AP_MotorsHeli::set_update_rate(), StorageAccess::StorageAccess(), AP_Motors::throttle_pass_through(), and StorageAccess::write_block().
static uint8_t pgm_read_byte_far (const void * s) inline static
Definition at line 58 of file AP_Progmem_Identity.h.
static uint32_t pgm_read_dword (const void * s) inline static
Definition at line 68 of file AP_Progmem_Identity.h.
Referenced by AP_GPS::detect_instance().
static float pgm_read_float (const void * s) inline static
Definition at line 73 of file AP_Progmem_Identity.h.
Referenced by AP_AutoTune::check_state_exit(), and AP_AutoTune::start().
static uintptr_t pgm_read_pointer (const void * s) inline static
Definition at line 79 of file AP_Progmem_Identity.h.
static uint16_t pgm_read_word (const void * s) inline static
Definition at line 63 of file AP_Progmem_Identity.h.
Referenced by crc16_ccitt(), StorageManager::erase(), pgm_read_pointer(), StorageAccess::read_block(), AP_Scheduler::run(), StorageAccess::StorageAccess(), and StorageAccess::write_block().
static int strcasecmp_P (const char * str1, const prog_char_t * pstr) inline static
Definition at line 15 of file AP_Progmem_Identity.h.
static int strcmp_P (const char * str1, const prog_char_t * pstr) inline static
Definition at line 20 of file AP_Progmem_Identity.h.
static size_t strlen_P (const prog_char_t * pstr) inline static
Definition at line 25 of file AP_Progmem_Identity.h.
static int strncmp_P (const char * str1, const prog_char_t * str2, size_t n) inline static
Definition at line 46 of file AP_Progmem_Identity.h.
Referenced by AP_Param::find(), and AP_Param::find_group().
static char* strncpy_P (char * buffer, const prog_char_t * pstr, size_t buffer_size) inline static
Definition at line 36 of file AP_Progmem_Identity.h.
static size_t strnlen_P (const prog_char_t * str, size_t size) inline static
Definition at line 41 of file AP_Progmem_Identity.h.
Referenced by AP_Param::find(), AP_Param::find_group(), and print_vprintf().