APM:Libraries: libraries/AP_Math/AP_Math.h File Reference
AP_Math.h File Reference
#include <AP_Common.h>
#include <AP_Param.h>
#include <math.h>
#include <stdint.h>
#include "rotations.h"
#include "vector2.h"
#include "vector3.h"
#include "matrix3.h"
#include "quaternion.h"
#include "polygon.h"
#include "edc.h"
#include "float.h"
Macros
#define M_PI_F 3.141592653589793f
#define M_2PI_F (2*M_PI_F)
#define PI M_PI_F
#define M_PI_2 1.570796326794897f
#define DEG_TO_RAD 0.017453292519943295769236907684886f
#define RAD_TO_DEG 57.295779513082320876798154814105f
#define DEG_TO_RAD_DOUBLE 0.0174532925199432954743716805978692718781530857086181640625
#define RAD_TO_DEG_DOUBLE 57.29577951308232286464772187173366546630859375
#define RadiansToCentiDegrees(x) ((x) * 5729.5779513082320876798154814105f)
#define GRAVITY_MSS 9.80665f
#define RADIUS_OF_EARTH 6378100
#define ROTATION_COMBINATION_SUPPORT 0
#define LATLON_TO_M 0.01113195f
#define LATLON_TO_CM 1.113195f
#define WGS84_A 6378137.0
#define WGS84_IF 298.257223563
#define WGS84_F (1/WGS84_IF)
#define WGS84_B (WGS84_A*(1-WGS84_F))
#define WGS84_E (sqrt(2*WGS84_F - WGS84_F*WGS84_F))
#define max(a, b) ((a)>(b)?(a):(b))
#define min(a, b) ((a)<(b)?(a):(b))
Functions
AP_PARAMDEFV (Matrix3f, Matrix3f, AP_PARAM_MATRIX3F)
AP_PARAMDEFV (Vector3f, Vector3f, AP_PARAM_VECTOR3F)
static bool is_equal (const float fVal1, const float fVal2)
static bool is_zero (const float fVal1)
float safe_asin (float v)
float safe_sqrt (float v)
float longitude_scale (const struct Location &loc)
float get_distance (const struct Location &loc1, const struct Location &loc2)
uint32_t get_distance_cm (const struct Location &loc1, const struct Location &loc2)
int32_t get_bearing_cd (const struct Location &loc1, const struct Location &loc2)
bool location_passed_point (const struct Location &location, const struct Location &point1, const struct Location &point2)
float location_path_proportion (const struct Location &location, const struct Location &point1, const struct Location &point2)
void location_update (struct Location &loc, float bearing, float distance)
void location_offset (struct Location &loc, float ofs_north, float ofs_east)
Vector2f location_diff (const struct Location &loc1, const struct Location &loc2)
int32_t wrap_360_cd (int32_t error)
int32_t wrap_180_cd (int32_t error)
float wrap_360_cd_float (float angle)
float wrap_180_cd_float (float angle)
float wrap_PI (float angle_in_radians)
void print_latlon (AP_HAL::BetterStream *s, int32_t lat_or_lon)
void wgsllh2ecef (const Vector3d &llh, Vector3d &ecef)
void wgsecef2llh (const Vector3d &ecef, Vector3d &llh)
float constrain_float (float amt, float low, float high)
int16_t constrain_int16 (int16_t amt, int16_t low, int16_t high)
int32_t constrain_int32 (int32_t amt, int32_t low, int32_t high)
float radians (float deg)
float degrees (float rad)
float sq (float v)
float pythagorous2 (float a, float b)
float pythagorous3 (float a, float b, float c)
Macro Definition Documentation
#define DEG_TO_RAD 0.017453292519943295769236907684886f
Definition at line 38 of file AP_Math.h.
Referenced by longitude_scale(), and radians().
#define DEG_TO_RAD_DOUBLE 0.0174532925199432954743716805978692718781530857086181640625
Definition at line 45 of file AP_Math.h.
#define GRAVITY_MSS 9.80665f
Definition at line 52 of file AP_Math.h.
Referenced by AP_InertialSensor::_calibrate_accel(), AP_PitchController::_get_coordination_rate_offset(), AP_TECS::_update_energies(), AP_TECS::_update_pitch(), AP_TECS::_update_STE_rate_lim(), AC_PosControl::accel_to_lean_angles(), AC_PosControl::accel_to_throttle(), AP_AHRS_DCM::drift_correction(), AP_YawController::get_servo_out(), NavEKF::getAccelNED(), Helicopter::Helicopter(), AC_PosControl::lean_angles_to_accel(), MultiCopter::MultiCopter(), SmallEKF::predictStates(), AC_PosControl::relax_alt_hold_controllers(), GCS_MAVLINK::send_raw_imu(), Rover::update(), Helicopter::update(), MultiCopter::update(), AP_TECS::update_50hz(), and NavEKF::UpdateStrapdownEquationsNED().
#define LATLON_TO_CM 1.113195f
Definition at line 62 of file AP_Math.h.
#define LATLON_TO_M 0.01113195f
Definition at line 61 of file AP_Math.h.
#define M_2PI_F (2*M_PI_F)
Definition at line 29 of file AP_Math.h.
Referenced by DigitalLPF::apply(), AC_PI_2D::calc_filt_alpha(), and AC_PID::get_filt_alpha().
#define M_PI_2 1.570796326794897f
Definition at line 35 of file AP_Math.h.
Referenced by AP_L1_Control::update_heading_hold(), AP_L1_Control::update_loiter(), and wgsecef2llh().
#define M_PI_F 3.141592653589793f
Definition at line 26 of file AP_Math.h.
Referenced by AP_L1_Control::_prevent_indecision(), AC_PosControl::accel_to_lean_angles(), Rover::calc_yaw_rate(), and AP_Mount_Servo::stabilize().
#define max (a, b) ((a)>(b)?(a):(b))
Definition at line 193 of file AP_Math.h.
Referenced by AP_PitchController::_get_coordination_rate_offset(), AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), AP_InertialSensor_PX4::_get_sample(), AP_InertialSensor_PX4::_new_accel_sample(), AP_InertialSensor_PX4::_new_gyro_sample(), AP_TECS::_update_pitch(), AP_TECS::_update_speed(), AC_WPNav::calc_loiter_desired_velocity(), NavEKF::ConstrainStates(), NavEKF::EstimateTerrainOffset(), AC_PI_2D::filt_hz(), AC_PID::filt_hz(), NavEKF::FuseOptFlow(), AC_Fence::get_breach_distance(), AP_YawController::get_servo_out(), AP_SteerController::get_steering_out_rate(), NavEKF::getEkfControlLimits(), NavEKF::getFlowDebug(), NavEKF::getHeightControlLimit(), AC_PosControl::lean_angles_to_accel(), AP_GPS_SBP::logging_log_raw_sbp(), loop(), AP_MotorsTri::output_armed_stabilizing(), AP_MotorsCoax::output_armed_stabilizing(), AP_MotorsSingle::output_armed_stabilizing(), AP_MotorsMatrix::output_armed_stabilizing(), AP_Airspeed::read(), NavEKF::readGpsData(), NavEKF::readHgtData(), NavEKF::readIMUData(), NavEKF::readRangeFinder(), NavEKF::SelectFlowFusion(), show_data(), Airspeed_Calibration::update(), AC_Sprayer::update(), AP_TECS::update_50hz(), AP_Motors::update_lift_max_from_batt_voltage(), AP_L1_Control::update_loiter(), RC_Channel::update_min_max(), AP_TECS::update_pitch_throttle(), RangeFinder::update_pre_arm_check(), and AP_L1_Control::update_waypoint().
#define min (a, b) ((a)<(b)?(a):(b))
Definition at line 194 of file AP_Math.h.
Referenced by AP_HAL_AVR::AVRUARTDriver::_allocBuffer(), AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), AP_InertialSensor::_init_gyro(), AP_InertialSensor_PX4::_new_gyro_sample(), AP_GPS_NMEA::_parse_degrees(), AP_TECS::_update_pitch(), AC_PosControl::accel_to_lean_angles(), AC_WPNav::advance_wp_target_along_track(), AC_WPNav::calc_loiter_desired_velocity(), AC_Circle::calc_velocities(), AC_WPNav::calculate_wp_leash_length(), AP_InertialSensor::calibrate_accel(), NavEKF::EstimateTerrainOffset(), AC_PI_2D::get_i_shrink(), AP_YawController::get_servo_out(), AP_SteerController::get_steering_out_rate(), loop(), AP_GPS_Backend::make_gps_time(), AP_MotorsMatrix::output_armed_stabilizing(), AC_PosControl::set_alt_target_from_climb_rate(), show_data(), AP_L1_Control::turn_distance(), AC_Sprayer::update(), RC_Channel::update_min_max(), AP_TECS::update_pitch_throttle(), RangeFinder::update_pre_arm_check(), and AP_Motors::update_throttle_thr_mix().
#define PI M_PI_F
Definition at line 32 of file AP_Math.h.
Referenced by AC_Circle::calc_velocities(), Compass::calculate_heading(), check_result(), DigitalBiquadFilter::compute_params(), PID::get_pid(), AC_Circle::init_start_angle(), loop(), rad_diff(), safe_asin(), setup(), test_quaternion_eulers(), AC_Circle::update(), and wrap_PI().
#define RAD_TO_DEG 57.295779513082320876798154814105f
Definition at line 39 of file AP_Math.h.
Referenced by AP_Mount_Alexmos::control_axis(), and degrees().
#define RAD_TO_DEG_DOUBLE 57.29577951308232286464772187173366546630859375
Definition at line 46 of file AP_Math.h.
#define RadiansToCentiDegrees (x) ((x) * 5729.5779513082320876798154814105f)
Definition at line 49 of file AP_Math.h.
Referenced by AC_WPNav::advance_spline_target_along_track(), AP_L1_Control::bearing_error_cd(), and AP_L1_Control::nav_bearing_cd().
#define RADIUS_OF_EARTH 6378100
Definition at line 55 of file AP_Math.h.
Referenced by AP_Mission::mavlink_to_mission_cmd().
#define ROTATION_COMBINATION_SUPPORT 0
Definition at line 57 of file AP_Math.h.
#define WGS84_A 6378137.0
Definition at line 65 of file AP_Math.h.
Referenced by wgsecef2llh(), and wgsllh2ecef().
#define WGS84_B (WGS84_A*(1-WGS84_F))
Definition at line 71 of file AP_Math.h.
Referenced by wgsecef2llh().
#define WGS84_E (sqrt(2*WGS84_F - WGS84_F*WGS84_F))
Definition at line 73 of file AP_Math.h.
Referenced by wgsecef2llh(), and wgsllh2ecef().
#define WGS84_F (1/WGS84_IF)
Definition at line 69 of file AP_Math.h.
#define WGS84_IF 298.257223563
Definition at line 67 of file AP_Math.h.
Function Documentation
AP_PARAMDEFV (Matrix3f , Matrix3f , AP_PARAM_MATRIX3F)
AP_PARAMDEFV (Vector3f , Vector3f , AP_PARAM_VECTOR3F)
float constrain_float (float amt, float low, float high)
Definition at line 74 of file AP_Math.cpp.
Referenced by AP_PitchController::_get_coordination_rate_offset(), AP_RollController::_get_rate_out(), AP_PitchController::_get_rate_out(), HALSITL::SITL_State::_ground_sonar(), AP_TECS::_update_pitch(), AP_TECS::_update_speed_demand(), AP_TECS::_update_throttle(), AP_TECS::_update_throttle_option(), AC_PosControl::accel_to_lean_angles(), AP_AHRS::add_trim(), AC_WPNav::advance_wp_target_along_track(), AP_AHRS_DCM::airspeed_estimate(), AP_AHRS::airspeed_estimate(), AC_AttitudeControl::angle_ef_roll_pitch_rate_ef_yaw(), AC_AttitudeControl::angle_ef_roll_pitch_rate_ef_yaw_smooth(), AC_AttitudeControl::angle_ef_roll_pitch_yaw(), DigitalLPF::apply(), AP_Motors::apply_thrust_curve_and_volt_scaling(), AC_Circle::calc_velocities(), Compass::calculate_heading(), NavEKF::ConstrainStates(), NavEKF::ConstrainVariances(), NavEKF::CovariancePrediction(), AP_Motors::current_limit_max_throttle(), NavEKF::decayGpsOffset(), AP_AHRS_DCM::drift_correction(), NavEKF::FuseAirspeed(), NavEKF::FuseMagnetometer(), NavEKF::FuseOptFlow(), NavEKF::FuseVelPosNED(), AC_AttitudeControl::get_boosted_throttle(), AP_Motors::get_compensation_gain(), AP_Declination::get_declination(), get_declination(), PID::get_pid_4500(), AP_YawController::get_servo_out(), AP_SteerController::get_steering_out_rate(), AC_PosControl::get_stopping_point_xy(), AC_PosControl::get_stopping_point_z(), AC_AttitudeControl::integrate_bf_rate_error_to_angle_errors(), Compass::learn_offsets(), longitude_scale(), AP_MotorsHeli::move_swash(), AP_L1_Control::nav_roll_cd(), RC_Channel::norm_input(), RC_Channel::norm_input_dz(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), AC_AttitudeControl::rate_bf_roll_pitch_yaw(), AC_AttitudeControl::rate_bf_to_motor_pitch(), AC_AttitudeControl::rate_bf_to_motor_roll(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_AttitudeControl_Heli::rate_bf_to_motor_yaw(), AC_AttitudeControl::rate_bf_to_motor_yaw(), AC_AttitudeControl::rate_ef_roll_pitch_yaw(), NavEKF::readGpsData(), NavEKF::readHgtData(), CRRCSim::send_servos_fixed_wing(), CRRCSim::send_servos_heli(), AC_PosControl::set_alt_target_from_climb_rate(), AC_PosControl::set_alt_target_with_slew(), AP_Param::set_param_by_name(), AP_AHRS::set_trim(), AC_WPNav::set_wp_origin_and_destination(), AP_AutoTune::start(), Airspeed_Calibration::update(), AC_Circle::update(), AP_Airspeed::update_calibration(), AC_AttitudeControl::update_ef_pitch_angle_and_error(), AC_AttitudeControl::update_ef_roll_angle_and_error(), AC_AttitudeControl::update_ef_yaw_angle_and_error(), AP_L1_Control::update_heading_hold(), AP_Motors::update_lift_max_from_batt_voltage(), AP_L1_Control::update_loiter(), AC_AttitudeControl::update_rate_bf_targets(), AP_Mount_Backend::update_targets_from_rc(), AP_Motors::update_throttle_filter(), AP_Motors::update_throttle_thr_mix(), AP_AHRS::update_trig(), AP_L1_Control::update_waypoint(), NavEKF::UpdateStrapdownEquationsNED(), and NavEKF::writeOptFlowMeas().
int16_t constrain_int16 (int16_t amt, int16_t low, int16_t high)
Definition at line 87 of file AP_Math.cpp.
Referenced by RC_Channel::calc_pwm(), AP_MotorsHeli::init_swash(), AP_MotorsMatrix::output_armed_stabilizing(), RC_Channel::pwm_to_range_dz(), NavEKF::readGpsData(), AP_Camera::relay_pic(), AP_MotorsHeli::rotor_ramp(), AP_Camera::servo_pic(), AP_MotorsHeli::set_delta_phase_angle(), RC_Channel_aux::set_radio(), RC_Channel_aux::set_radio_trimmed(), AP_Motors::slow_start(), and AP_MotorsHeli::tail_ramp().
int32_t constrain_int32 (int32_t amt, int32_t low, int32_t high)
Definition at line 92 of file AP_Math.cpp.
float degrees (float rad)
Definition at line 102 of file AP_Math.cpp.
Referenced by AP_InertialSensor::_calculate_trim(), AP_TECS::_update_pitch(), JSBSim::create_templates(), Aircraft::fill_fdm(), DataFlash_Class::Log_Write_AHRS2(), AP_L1_Control::nav_roll_cd(), JSBSim::recv_fdm(), AP_GPS::setHIL(), AP_Mount_Servo::stabilize(), AP_AHRS::update_cd_values(), and Aircraft::update_position().
int32_t get_bearing_cd (const struct Location & loc1, const struct Location & loc2)
Definition at line 69 of file location.cpp.
Referenced by AP_Mission::get_next_ground_course_cd(), test_one_offset(), AP_L1_Control::update_loiter(), and AP_L1_Control::update_waypoint().
float get_distance (const struct Location & loc1, const struct Location & loc2)
Definition at line 55 of file location.cpp.
Referenced by AP_Rally::find_nearest_rally_point(), get_distance_cm(), AP_Mission::get_landing_sequence_start(), test_accuracy(), test_one_offset(), AP_Limit_Geofence::triggered(), and AP_Camera::update_location().
uint32_t get_distance_cm (const struct Location & loc1, const struct Location & loc2)
Definition at line 63 of file location.cpp.
static bool is_equal (const float fVal1, const float fVal2) inline static
Definition at line 80 of file AP_Math.h.
Referenced by AP_InertialSensor::accel_calibrated_ok_all(), AP_Param::convert_old_parameter(), AP_AHRS_DCM::drift_correction(), AC_Circle::init_start_angle(), Vector2< T >::operator!=(), Vector3< T >::operator!=(), Vector2< T >::operator==(), Vector3< T >::operator==(), NavEKF::readMagData(), AP_Param::save(), Compass::setHIL(), and AP_AHRS_DCM::yaw_error_compass().
static bool is_zero (const float fVal1) inline static
Definition at line 83 of file AP_Math.h.
Referenced by AP_InertialSensor::_calibrate_find_delta(), AP_InertialSensor::accel_calibrated_ok_all(), AC_AttitudeControl::accel_limiting(), AC_WPNav::advance_spline_target_along_track(), DigitalBiquadFilter::apply(), AP_Compass_Backend::apply_corrections(), AC_PI_2D::calc_filt_alpha(), AC_WPNav::calc_loiter_desired_velocity(), AC_WPNav::calculate_wp_leash_length(), AC_Fence::check_fence(), Compass::configured(), AP_AHRS_DCM::drift_correction(), AC_AttitudeControl::frame_conversion_bf_to_ef(), AC_Circle::get_closest_point_on_circle(), AP_Baro::get_EAS2TAS(), AC_PID::get_filt_alpha(), AC_PI_2D::get_i(), AC_PID::get_i(), AC_PI_2D::get_i_shrink(), AC_HELI_PID::get_leaky_i(), AC_PosControl::get_stopping_point_xy(), location_offset(), AP_Compass_AK8963_MPU9250::read_raw(), AC_WPNav::set_wp_origin_and_destination(), AC_AttitudeControl::sqrt_controller(), AP_Mount_Servo::stabilize(), AP_Baro::update(), AC_Circle::update(), AP_Camera::update_location(), and wgsecef2llh().
Vector2f location_diff (const struct Location & loc1, const struct Location & loc2)
Definition at line 143 of file location.cpp.
Referenced by NavEKF::getPosNED(), location_path_proportion(), NavEKF::readGpsData(), CRRCSim::recv_fdm(), AP_L1_Control::update_loiter(), and AP_L1_Control::update_waypoint().
void location_offset (struct Location & loc, float ofs_north, float ofs_east)
Definition at line 129 of file location.cpp.
Referenced by AP_AHRS_DCM::get_position(), NavEKF::getLLH(), location_update(), and test_one_offset().
bool location_passed_point (const struct Location & location, const struct Location & point1, const struct Location & point2)
Definition at line 83 of file location.cpp.
Referenced by test_passed_waypoint().
float location_path_proportion (const struct Location & location, const struct Location & point1, const struct Location & point2)
Definition at line 97 of file location.cpp.
Referenced by location_passed_point().
void location_update (struct Location & loc, float bearing, float distance)
Definition at line 118 of file location.cpp.
Referenced by AP_AHRS_DCM::get_position(), and Aircraft::update_position().
float longitude_scale (const struct Location & loc)
Definition at line 36 of file location.cpp.
Referenced by get_bearing_cd(), get_distance(), location_diff(), and location_offset().
void print_latlon (AP_HAL::BetterStream * s, int32_t lat_or_lon)
Definition at line 222 of file location.cpp.
Referenced by DataFlash_Class::_print_log_entry(), and loop().
float pythagorous2 (float a, float b)
Definition at line 112 of file AP_Math.cpp.
Referenced by AP_InertialSensor::_calculate_trim(), HALSITL::SITL_State::_update_gps_mtk(), HALSITL::SITL_State::_update_gps_mtk16(), HALSITL::SITL_State::_update_gps_mtk19(), HALSITL::SITL_State::_update_gps_nmea(), HALSITL::SITL_State::_update_gps_ubx(), AP_AHRS_DCM::_yaw_gain(), AC_WPNav::advance_wp_target_along_track(), NavEKF::alignMagStateDeclination(), AP_Mount_Backend::calc_angle_to_location(), AC_WPNav::calc_loiter_desired_velocity(), AC_WPNav::calculate_wp_leash_length(), NavEKF::decayGpsOffset(), AP_AHRS_DCM::drift_correction(), AC_Circle::get_closest_point_on_circle(), get_distance(), AC_PosControl::get_stopping_point_xy(), AC_WPNav::get_wp_distance_to_destination(), Vector2< T >::length(), AC_PosControl::pos_to_rate_xy(), AC_PosControl::rate_to_accel_xy(), AP_GPS::setHIL(), NavEKF::setWindVelStates(), AC_Sprayer::update(), and NavEKF::UpdateStrapdownEquationsNED().
float pythagorous3 (float a, float b, float c)
Definition at line 117 of file AP_Math.cpp.
Referenced by HALSITL::SITL_State::_update_gps_ubx(), NavEKF::FuseAirspeed(), Vector3< T >::length(), and Airspeed_Calibration::update().
float radians (float deg)
Definition at line 97 of file AP_Math.cpp.
Referenced by AP_InertialSensor::_calculate_trim(), AP_PitchController::_get_coordination_rate_offset(), HALSITL::SITL_State::_ground_sonar(), HALSITL::SITL_State::_update_compass(), HALSITL::SITL_State::_update_flow(), OpticalFlow_backend::_yawAngleRad(), AP_MotorsMatrix::add_motor(), Aircraft::Aircraft(), NavEKF::alignYawGPS(), AP_Mount_Backend::angle_input_rad(), Rover::calc_lat_accel(), NavEKF::calcEarthRateNED(), AP_MotorsHeli::calculate_roll_pitch_collective_factors(), NavEKF::CovarianceInit(), AP_AHRS::groundspeed_vector(), Helicopter::Helicopter(), AP_Arming::ins_checks(), location_update(), NavEKF::resetGyroBias(), AP_Mount_Backend::set_angle_targets(), Compass::set_initial_location(), Aircraft::set_yaw_degrees(), test_euler(), Rover::turn_circle(), Rover::update(), Helicopter::update(), MultiCopter::update(), AP_L1_Control::update_heading_hold(), AP_TECS::update_pitch_throttle(), and AP_Mount_Backend::update_targets_from_rc().
float safe_asin (float v)
Definition at line 7 of file AP_Math.cpp.
Referenced by Quaternion::get_euler_pitch(), Matrix3< T >::to_euler(), and Quaternion::to_vector312().
float safe_sqrt (float v)
Definition at line 26 of file AP_Math.cpp.
Referenced by AP_GPS_SBP::_attempt_state_update(), AC_WPNav::advance_spline_target_along_track(), AP_Motors::apply_thrust_curve_and_volt_scaling(), AC_Circle::calc_velocities(), AP_Baro::get_EAS2TAS(), AC_WPNav::get_slow_down_speed(), AC_PosControl::pos_to_rate_xy(), AC_PosControl::set_alt_target_from_climb_rate(), AC_AttitudeControl::sqrt_controller(), and AP_AHRS::update_trig().
float sq (float v)
Definition at line 107 of file AP_Math.cpp.
Referenced by NavEKF::alignYawGPS(), AC_WPNav::calc_loiter_desired_velocity(), NavEKF::ConstrainVariances(), NavEKF::CovarianceInit(), NavEKF::CovariancePrediction(), NavEKF::EstimateTerrainOffset(), Quaternion::from_axis_angle_fast(), NavEKF::FuseAirspeed(), SmallEKF::fuseCompass(), NavEKF::FuseMagnetometer(), NavEKF::FuseOptFlow(), NavEKF::FuseSideslip(), SmallEKF::fuseVelocity(), NavEKF::FuseVelPosNED(), AP_Baro::get_air_density_ratio(), NavEKF::healthy(), Quaternion::length(), location_path_proportion(), SmallEKF::predictCovariance(), pythagorous2(), pythagorous3(), NavEKF::resetGyroBias(), Quaternion::rotate_fast(), SmallEKF::RunEKF(), NavEKF::SelectFlowFusion(), NavEKF::SetFlightAndFusionModes(), AC_AttitudeControl::sqrt_controller(), Quaternion::to_axis_angle(), AP_L1_Control::turn_distance(), Airspeed_Calibration::update(), AP_Airspeed::update_calibration(), AP_L1_Control::update_loiter(), and Aircraft::update_position().
void wgsecef2llh (const Vector3d & ecef, Vector3d & llh)
Definition at line 252 of file location.cpp.
Referenced by test_wgs_conversion_functions().
void wgsllh2ecef (const Vector3d & llh, Vector3d & ecef)
Definition at line 242 of file location.cpp.
Referenced by test_wgs_conversion_functions().
int32_t wrap_180_cd (int32_t error)
Definition at line 166 of file location.cpp.
Referenced by AP_L1_Control::_prevent_indecision(), AP_L1_Control::nav_bearing_cd(), AP_L1_Control::target_bearing_cd(), test_wrap_cd(), AC_AttitudeControl::update_ef_pitch_angle_and_error(), AC_AttitudeControl::update_ef_roll_angle_and_error(), AC_AttitudeControl::update_ef_yaw_angle_and_error(), AP_L1_Control::update_heading_hold(), and AP_AHRS_DCM::use_compass().
float wrap_180_cd_float (float angle)
Definition at line 194 of file location.cpp.
Referenced by AC_AttitudeControl::angle_ef_roll_pitch_rate_ef_yaw(), AC_AttitudeControl::angle_ef_roll_pitch_rate_ef_yaw_smooth(), AC_AttitudeControl::angle_ef_roll_pitch_yaw(), AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), and AC_AttitudeControl::rate_bf_roll_pitch_yaw().
int32_t wrap_360_cd (int32_t error)
Definition at line 152 of file location.cpp.
Referenced by DataFlash_Class::Log_Write_AHRS2(), SITL::Log_Write_SIMSTATE(), test_wrap_cd(), and AC_AttitudeControl::update_ef_yaw_angle_and_error().
float wrap_360_cd_float (float angle)
Definition at line 180 of file location.cpp.
Referenced by AC_AttitudeControl_Heli::passthrough_bf_roll_pitch_rate_yaw(), and AC_AttitudeControl::rate_bf_roll_pitch_yaw().
float wrap_PI (float angle_in_radians)
Definition at line 208 of file location.cpp.
Referenced by NavEKF::alignYawGPS(), AP_Mount_Backend::calc_angle_to_location(), AC_Circle::calc_velocities(), AP_AHRS_DCM::drift_correction_yaw(), AC_Circle::init_start_angle(), test_wrap_cd(), Quaternion::to_axis_angle(), and AC_Circle::update().