APM:Libraries: AP_HAL::AnalogIn Class Reference
AP_HAL::AnalogIn Class Reference abstract
#include <AnalogIn.h>
Public Member Functions
virtual void init (void *implspecific)=0
virtual AP_HAL::AnalogSource * channel (int16_t n)=0
virtual float board_voltage (void)=0
virtual float servorail_voltage (void)
virtual uint16_t power_status_flags (void)
Detailed Description
Definition at line 40 of file AnalogIn.h.
Member Function Documentation
virtual float AP_HAL::AnalogIn::board_voltage (void) pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogIn, AP_HAL_AVR::AVRAnalogIn, VRBRAIN::VRBRAINAnalogIn, PX4::PX4AnalogIn, HALSITL::SITLAnalogIn, NavioAnalogIn, Linux::LinuxAnalogIn, and Empty::EmptyAnalogIn.
Referenced by DataFlash_Class::Log_Write_Current(), DataFlash_Class::Log_Write_Power(), and GCS_MAVLINK::send_power_status().
virtual AP_HAL::AnalogSource* AP_HAL::AnalogIn::channel (int16_t n) pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogIn, AP_HAL_AVR::AVRAnalogIn, VRBRAIN::VRBRAINAnalogIn, PX4::PX4AnalogIn, HALSITL::SITLAnalogIn, NavioAnalogIn, Empty::EmptyAnalogIn, and Linux::LinuxAnalogIn.
Referenced by AP_BattMonitor_Analog::AP_BattMonitor_Analog(), AP_RangeFinder_analog::AP_RangeFinder_analog(), AP_Airspeed_Analog::init(), setup(), AP_HAL_AVR::ADCSource::voltage_average(), and AP_HAL_AVR::ADCSource::voltage_latest().
virtual void AP_HAL::AnalogIn::init (void * implspecific) pure virtual
Implemented in AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogIn, AP_HAL_AVR::AVRAnalogIn, VRBRAIN::VRBRAINAnalogIn, PX4::PX4AnalogIn, HALSITL::SITLAnalogIn, NavioAnalogIn, Empty::EmptyAnalogIn, and Linux::LinuxAnalogIn.
Referenced by HAL_Linux::init(), HAL_SITL::init(), HAL_AVR_APM1::init(), HAL_AVR_APM2::init(), HAL_FLYMAPLE::init(), and main_loop().
virtual uint16_t AP_HAL::AnalogIn::power_status_flags (void) inline virtual
Reimplemented in VRBRAIN::VRBRAINAnalogIn, and PX4::PX4AnalogIn.
Definition at line 52 of file AnalogIn.h.
Referenced by DataFlash_Class::Log_Write_Power(), and GCS_MAVLINK::send_power_status().
virtual float AP_HAL::AnalogIn::servorail_voltage (void) inline virtual
Reimplemented in VRBRAIN::VRBRAINAnalogIn, and PX4::PX4AnalogIn.
Definition at line 49 of file AnalogIn.h.
Referenced by DataFlash_Class::Log_Write_Power(), and GCS_MAVLINK::send_power_status().
The documentation for this class was generated from the following file:
libraries/AP_HAL/AnalogIn.h