APM:Libraries: AP_InertialSensor_Backend Class Reference
AP_InertialSensor_Backend Class Reference abstract
#include <AP_InertialSensor_Backend.h>
Public Member Functions
AP_InertialSensor_Backend (AP_InertialSensor &imu)
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
virtual ~AP_InertialSensor_Backend (void)
virtual bool update ()=0
virtual bool accel_sample_available ()=0
virtual bool gyro_sample_available ()=0
int16_t product_id (void) const
Protected Member Functions
void _rotate_and_correct_accel (uint8_t instance, Vector3f &accel)
void _rotate_and_correct_gyro (uint8_t instance, Vector3f &gyro)
void _publish_delta_velocity (uint8_t instance, const Vector3f &delta_velocity, float dt)
void _publish_delta_angle (uint8_t instance, const Vector3f &delta_angle)
void _publish_gyro (uint8_t instance, const Vector3f &gyro, bool rotate_and_correct=true)
void _publish_accel (uint8_t instance, const Vector3f &accel, bool rotate_and_correct=true)
void _publish_temperature (uint8_t instance, float temperature)
void _set_accel_error_count (uint8_t instance, uint32_t error_count)
void _set_gyro_error_count (uint8_t instance, uint32_t error_count)
uint8_t _accel_filter_cutoff (void) const
uint8_t _gyro_filter_cutoff (void) const
uint16_t get_sample_rate_hz (void) const
DataFlash_Class * get_dataflash (void) const
Protected Attributes
AP_InertialSensor & _imu
int16_t _product_id
Detailed Description
Definition at line 27 of file AP_InertialSensor_Backend.h.
Constructor & Destructor Documentation
AP_InertialSensor_Backend::AP_InertialSensor_Backend (AP_InertialSensor & imu)
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 7 of file AP_InertialSensor_Backend.cpp.
virtual AP_InertialSensor_Backend::~AP_InertialSensor_Backend (void) inline virtual
Definition at line 34 of file AP_InertialSensor_Backend.h.
Member Function Documentation
uint8_t AP_InertialSensor_Backend::_accel_filter_cutoff (void) const inline protected
Definition at line 89 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_MPU6000::_hardware_init(), AP_InertialSensor_Flymaple::_init_sensor(), AP_InertialSensor_MPU9150::_init_sensor(), AP_InertialSensor_PX4::_init_sensor(), AP_InertialSensor_L3G4200D::_init_sensor(), AP_InertialSensor_Flymaple::update(), AP_InertialSensor_MPU9150::update(), AP_InertialSensor_L3G4200D::update(), AP_InertialSensor_MPU9250::update(), AP_InertialSensor_PX4::update(), and AP_InertialSensor_MPU6000::update().
uint8_t AP_InertialSensor_Backend::_gyro_filter_cutoff (void) const inline protected
Definition at line 92 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_MPU9150::_init_sensor(), AP_InertialSensor_PX4::_init_sensor(), AP_InertialSensor_MPU9150::update(), AP_InertialSensor_MPU9250::update(), AP_InertialSensor_PX4::update(), and AP_InertialSensor_MPU6000::update().
void AP_InertialSensor_Backend::_publish_accel (uint8_t instance, const Vector3f & accel, bool rotate_and_correct = true) protected
Definition at line 71 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_Oilpan::update(), AP_InertialSensor_Flymaple::update(), AP_InertialSensor_MPU9150::update(), AP_InertialSensor_L3G4200D::update(), AP_InertialSensor_MPU9250::update(), AP_InertialSensor_PX4::update(), and AP_InertialSensor_MPU6000::update().
void AP_InertialSensor_Backend::_publish_delta_angle (uint8_t instance, const Vector3f & delta_angle) protected
Definition at line 40 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_PX4::update().
void AP_InertialSensor_Backend::_publish_delta_velocity (uint8_t instance, const Vector3f & delta_velocity, float dt) protected
Definition at line 60 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_PX4::update().
void AP_InertialSensor_Backend::_publish_gyro (uint8_t instance, const Vector3f & gyro, bool rotate_and_correct = true) protected
Definition at line 50 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_Oilpan::update(), AP_InertialSensor_Flymaple::update(), AP_InertialSensor_MPU9150::update(), AP_InertialSensor_L3G4200D::update(), AP_InertialSensor_MPU9250::update(), AP_InertialSensor_PX4::update(), and AP_InertialSensor_MPU6000::update().
void AP_InertialSensor_Backend::_publish_temperature (uint8_t instance, float temperature) protected
Definition at line 103 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_PX4::_new_accel_sample().
void AP_InertialSensor_Backend::_rotate_and_correct_accel (uint8_t instance, Vector3f & accel) protected
Definition at line 12 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_PX4::_new_accel_sample(), and _publish_accel().
void AP_InertialSensor_Backend::_rotate_and_correct_gyro (uint8_t instance, Vector3f & gyro) protected
Definition at line 33 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_PX4::_new_gyro_sample(), and _publish_gyro().
void AP_InertialSensor_Backend::_set_accel_error_count (uint8_t instance, uint32_t error_count) protected
Definition at line 82 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_PX4::_new_accel_sample().
void AP_InertialSensor_Backend::_set_gyro_error_count (uint8_t instance, uint32_t error_count) protected
Definition at line 88 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_PX4::_new_gyro_sample().
virtual bool AP_InertialSensor_Backend::accel_sample_available () pure virtual
Implemented in AP_InertialSensor_MPU6000, AP_InertialSensor_PX4, AP_InertialSensor_MPU9250, AP_InertialSensor_L3G4200D, AP_InertialSensor_MPU9150, AP_InertialSensor_Flymaple, AP_InertialSensor_Oilpan, and AP_InertialSensor_HIL.
Referenced by AP_InertialSensor::wait_for_sample().
DataFlash_Class* AP_InertialSensor_Backend::get_dataflash (void) const inline protected
Definition at line 98 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_PX4::_get_accel_sample(), and AP_InertialSensor_PX4::_get_gyro_sample().
uint16_t AP_InertialSensor_Backend::get_sample_rate_hz (void) const protected
Definition at line 94 of file AP_InertialSensor_Backend.cpp.
Referenced by AP_InertialSensor_PX4::_queue_depth().
virtual bool AP_InertialSensor_Backend::gyro_sample_available () pure virtual
Implemented in AP_InertialSensor_MPU6000, AP_InertialSensor_PX4, AP_InertialSensor_MPU9250, AP_InertialSensor_L3G4200D, AP_InertialSensor_MPU9150, AP_InertialSensor_Flymaple, AP_InertialSensor_Oilpan, and AP_InertialSensor_HIL.
Referenced by AP_InertialSensor::wait_for_sample().
int16_t AP_InertialSensor_Backend::product_id (void) const inline
Definition at line 58 of file AP_InertialSensor_Backend.h.
virtual bool AP_InertialSensor_Backend::update () pure virtual
Implemented in AP_InertialSensor_MPU6000, AP_InertialSensor_PX4, AP_InertialSensor_MPU9250, AP_InertialSensor_L3G4200D, AP_InertialSensor_MPU9150, AP_InertialSensor_Flymaple, AP_InertialSensor_Oilpan, and AP_InertialSensor_HIL.
Referenced by AP_InertialSensor::update().
Member Data Documentation
AP_InertialSensor& AP_InertialSensor_Backend::_imu protected
Definition at line 62 of file AP_InertialSensor_Backend.h.
Referenced by _accel_filter_cutoff(), _gyro_filter_cutoff(), AP_InertialSensor_MPU6000::_hardware_init(), AP_InertialSensor_HIL::_init_sensor(), AP_InertialSensor_Oilpan::_init_sensor(), AP_InertialSensor_Flymaple::_init_sensor(), AP_InertialSensor_MPU9150::_init_sensor(), AP_InertialSensor_MPU9250::_init_sensor(), AP_InertialSensor_L3G4200D::_init_sensor(), AP_InertialSensor_PX4::_init_sensor(), AP_InertialSensor_MPU6000::_init_sensor(), _publish_accel(), _publish_delta_angle(), _publish_delta_velocity(), _publish_gyro(), _publish_temperature(), _rotate_and_correct_accel(), _rotate_and_correct_gyro(), _set_accel_error_count(), _set_gyro_error_count(), get_dataflash(), and get_sample_rate_hz().
int16_t AP_InertialSensor_Backend::_product_id protected
Definition at line 86 of file AP_InertialSensor_Backend.h.
Referenced by AP_InertialSensor_MPU6000::_hardware_init(), AP_InertialSensor_HIL::_init_sensor(), AP_InertialSensor_Oilpan::_init_sensor(), AP_InertialSensor_Flymaple::_init_sensor(), AP_InertialSensor_MPU9250::_init_sensor(), AP_InertialSensor_PX4::_init_sensor(), AP_InertialSensor_L3G4200D::_init_sensor(), and product_id().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp