APM:Libraries: AP_HAL_AVR::APM2RCOutput Class Reference
AP_HAL_AVR::APM2RCOutput Class Reference
#include <RCOutput.h>
Public Member Functions
void init (void *machtnichts)
void set_freq (uint32_t chmask, uint16_t freq_hz)
uint16_t get_freq (uint8_t ch)
void enable_ch (uint8_t ch)
void disable_ch (uint8_t ch)
void write (uint8_t ch, uint16_t period_us)
void write (uint8_t ch, uint16_t *period_us, uint8_t len)
uint16_t read (uint8_t ch)
void read (uint16_t *period_us, uint8_t len)
Public Member Functions inherited from AP_HAL::RCOutput
virtual void set_safety_pwm (uint32_t chmask, uint16_t period_us)
virtual void set_failsafe_pwm (uint32_t chmask, uint16_t period_us)
virtual bool force_safety_on (void)
virtual void force_safety_off (void)
virtual void set_esc_scaling (uint16_t min_pwm, uint16_t max_pwm)
Private Member Functions
uint16_t _timer_period (uint16_t speed_hz)
Detailed Description
Definition at line 35 of file RCOutput.h.
Member Function Documentation
uint16_t APM2RCOutput::_timer_period (uint16_t speed_hz) private
Definition at line 202 of file RCOutput_APM2.cpp.
Referenced by set_freq().
void APM2RCOutput::disable_ch (uint8_t ch) virtual
Implements AP_HAL::RCOutput.
Definition at line 126 of file RCOutput_APM2.cpp.
void APM2RCOutput::enable_ch (uint8_t ch) virtual
Implements AP_HAL::RCOutput.
Definition at line 111 of file RCOutput_APM2.cpp.
uint16_t APM2RCOutput::get_freq (uint8_t ch) virtual
Implements AP_HAL::RCOutput.
Definition at line 79 of file RCOutput_APM2.cpp.
void APM2RCOutput::init (void * machtnichts) virtual
Implements AP_HAL::RCOutput.
Definition at line 14 of file RCOutput_APM2.cpp.
uint16_t APM2RCOutput::read (uint8_t ch) virtual
Implements AP_HAL::RCOutput.
Definition at line 177 of file RCOutput_APM2.cpp.
Referenced by read().
void APM2RCOutput::read (uint16_t * period_us, uint8_t len) virtual
Implements AP_HAL::RCOutput.
Definition at line 196 of file RCOutput_APM2.cpp.
void APM2RCOutput::set_freq (uint32_t chmask, uint16_t freq_hz) virtual
Implements AP_HAL::RCOutput.
Definition at line 63 of file RCOutput_APM2.cpp.
void APM2RCOutput::write (uint8_t ch, uint16_t period_us) virtual
Implements AP_HAL::RCOutput.
Definition at line 149 of file RCOutput_APM2.cpp.
Referenced by write().
void APM2RCOutput::write (uint8_t ch, uint16_t * period_us, uint8_t len) virtual
Implements AP_HAL::RCOutput.
Definition at line 168 of file RCOutput_APM2.cpp.
The documentation for this class was generated from the following files:
libraries/AP_HAL_AVR/RCOutput.h
libraries/AP_HAL_AVR/RCOutput_APM2.cpp