APM:Libraries: AP_HAL::SPIDeviceManager Class Reference
AP_HAL::SPIDeviceManager Class Reference abstract
#include <SPIDriver.h>
Public Member Functions
virtual void init (void *)=0
virtual AP_HAL::SPIDeviceDriver * device (enum AP_HAL::SPIDevice)=0
Detailed Description
Definition at line 8 of file SPIDriver.h.
Member Function Documentation
virtual AP_HAL::SPIDeviceDriver* AP_HAL::SPIDeviceManager::device (enum AP_HAL::SPIDevice) pure virtual
Implemented in Linux::LinuxSPIDeviceManager, AP_HAL_FLYMAPLE_NS::FLYMAPLESPIDeviceManager, Empty::EmptySPIDeviceManager, AP_HAL_AVR::APM2SPIDeviceManager, and AP_HAL_AVR::APM1SPIDeviceManager.
Referenced by AP_InertialSensor_MPU9250::_init_sensor(), AP_InertialSensor_MPU6000::_init_sensor(), AP_InertialSensor_LSM9DS0::_init_sensor(), Linux::LinuxSPIUARTDriver::begin(), AP_ADC_ADS7844::Init(), AP_SerialBus_SPI::init(), DataFlash_APM1::Init(), AK8963_MPU9250_SPI_Backend::init(), loop(), Linux::LinuxStorage_FRAM::open(), and setup().
virtual void AP_HAL::SPIDeviceManager::init (void *) pure virtual
Implemented in Linux::LinuxSPIDeviceManager, AP_HAL_FLYMAPLE_NS::FLYMAPLESPIDeviceManager, Empty::EmptySPIDeviceManager, AP_HAL_AVR::APM2SPIDeviceManager, and AP_HAL_AVR::APM1SPIDeviceManager.
Referenced by HAL_Linux::init(), HAL_AVR_APM2::init(), HAL_AVR_APM1::init(), and HAL_FLYMAPLE::init().
The documentation for this class was generated from the following file:
libraries/AP_HAL/SPIDriver.h