APM:Libraries: AP_HAL_AVR::AVRDigitalSource Class Reference
AP_HAL_AVR::AVRDigitalSource Class Reference
#include <GPIO.h>
Public Member Functions
AVRDigitalSource (uint8_t bit, uint8_t port)
void mode (uint8_t output)
uint8_t read ()
void write (uint8_t value)
void toggle ()
Private Attributes
const uint8_t _bit
const uint8_t _port
Detailed Description
Definition at line 24 of file GPIO.h.
Constructor & Destructor Documentation
AP_HAL_AVR::AVRDigitalSource::AVRDigitalSource (uint8_t bit, uint8_t port) inline
Definition at line 26 of file GPIO.h.
Member Function Documentation
void AVRDigitalSource::mode (uint8_t output) virtual
Implements AP_HAL::DigitalSource.
Definition at line 149 of file GPIO.cpp.
Referenced by AP_HAL_AVR::AVRSPI0DeviceDriver::init(), AP_HAL_AVR::AVRSPI2DeviceDriver::init(), and AP_HAL_AVR::AVRSPI3DeviceDriver::init().
uint8_t AVRDigitalSource::read (void) virtual
Implements AP_HAL::DigitalSource.
Definition at line 169 of file GPIO.cpp.
void AVRDigitalSource::toggle () virtual
Implements AP_HAL::DigitalSource.
Definition at line 194 of file GPIO.cpp.
void AVRDigitalSource::write (uint8_t value) virtual
Implements AP_HAL::DigitalSource.
Definition at line 176 of file GPIO.cpp.
Referenced by AP_HAL_AVR::AVRSPI0DeviceDriver::_cs_assert(), AP_HAL_AVR::AVRSPI2DeviceDriver::_cs_assert(), AP_HAL_AVR::AVRSPI3DeviceDriver::_cs_assert(), AP_HAL_AVR::AVRSPI0DeviceDriver::_cs_release(), AP_HAL_AVR::AVRSPI2DeviceDriver::_cs_release(), AP_HAL_AVR::AVRSPI3DeviceDriver::_cs_release(), AP_HAL_AVR::AVRSPI0DeviceDriver::init(), AP_HAL_AVR::AVRSPI2DeviceDriver::init(), and AP_HAL_AVR::AVRSPI3DeviceDriver::init().
Member Data Documentation
const uint8_t AP_HAL_AVR::AVRDigitalSource::_bit private
Definition at line 33 of file GPIO.h.
Referenced by mode(), read(), toggle(), and write().
const uint8_t AP_HAL_AVR::AVRDigitalSource::_port private
Definition at line 34 of file GPIO.h.
Referenced by mode(), read(), toggle(), and write().
The documentation for this class was generated from the following files:
libraries/AP_HAL_AVR/GPIO.h
libraries/AP_HAL_AVR/GPIO.cpp