APM:Libraries: AP_HAL_AVR::AVRSPI0DeviceDriver Class Reference
AP_HAL_AVR::AVRSPI0DeviceDriver Class Reference
#include <SPIDevices.h>
Public Member Functions
AVRSPI0DeviceDriver (AP_HAL_AVR::AVRDigitalSource *cs_pin, uint8_t spcr_lowspeed, uint8_t spcr_highspeed, uint8_t spsr)
void init ()
AP_HAL::Semaphore * get_semaphore ()
void transaction (const uint8_t *tx, uint8_t *rx, uint16_t len)
void cs_assert ()
void cs_release ()
uint8_t transfer (uint8_t data)
void transfer (const uint8_t *data, uint16_t len)
void set_bus_speed (enum bus_speed speed)
Private Member Functions
void _cs_assert ()
void _cs_release ()
uint8_t _transfer (uint8_t data)
void _transfer16 (const uint8_t *tx, uint8_t *rx)
Private Attributes
AP_HAL_AVR::AVRDigitalSource * _cs_pin
const uint8_t _spcr_lowspeed
const uint8_t _spcr_highspeed
uint8_t _spcr
const uint8_t _spsr
Static Private Attributes
static AP_HAL_AVR::AVRSemaphore _semaphore
static bool _force_low_speed
Additional Inherited Members
Public Types inherited from AP_HAL::SPIDeviceDriver
enum bus_speed { SPI_SPEED_LOW, SPI_SPEED_HIGH }
Detailed Description
Definition at line 8 of file SPIDevices.h.
Constructor & Destructor Documentation
AP_HAL_AVR::AVRSPI0DeviceDriver::AVRSPI0DeviceDriver (AP_HAL_AVR::AVRDigitalSource * cs_pin, uint8_t spcr_lowspeed, uint8_t spcr_highspeed, uint8_t spsr) inline
Definition at line 10 of file SPIDevices.h.
Member Function Documentation
void AVRSPI0DeviceDriver::_cs_assert () private
Definition at line 40 of file SPIDevice_SPI0.cpp.
Referenced by cs_assert(), and transaction().
void AVRSPI0DeviceDriver::_cs_release () private
Definition at line 57 of file SPIDevice_SPI0.cpp.
Referenced by cs_release(), and transaction().
uint8_t AVRSPI0DeviceDriver::_transfer (uint8_t data) private
Definition at line 62 of file SPIDevice_SPI0.cpp.
Referenced by transaction(), and transfer().
void AVRSPI0DeviceDriver::_transfer16 (const uint8_t * tx, uint8_t * rx) private
a specialised transfer function for the MPU6k. This saves 2 usec per byte
Definition at line 83 of file SPIDevice_SPI0.cpp.
Referenced by transaction().
void AVRSPI0DeviceDriver::cs_assert () virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 133 of file SPIDevice_SPI0.cpp.
void AVRSPI0DeviceDriver::cs_release () virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 137 of file SPIDevice_SPI0.cpp.
AP_HAL::Semaphore * AVRSPI0DeviceDriver::get_semaphore () virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 36 of file SPIDevice_SPI0.cpp.
void AVRSPI0DeviceDriver::init (void) virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 24 of file SPIDevice_SPI0.cpp.
Referenced by AP_HAL_AVR::APM1SPIDeviceManager::init(), and AP_HAL_AVR::APM2SPIDeviceManager::init().
void AVRSPI0DeviceDriver::set_bus_speed (enum bus_speed speed) virtual
allow on the fly bus speed changes for MPU6000
Reimplemented from AP_HAL::SPIDeviceDriver.
Definition at line 148 of file SPIDevice_SPI0.cpp.
void AVRSPI0DeviceDriver::transaction (const uint8_t * tx, uint8_t * rx, uint16_t len) virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 112 of file SPIDevice_SPI0.cpp.
uint8_t AVRSPI0DeviceDriver::transfer (uint8_t data) virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 141 of file SPIDevice_SPI0.cpp.
void AVRSPI0DeviceDriver::transfer (const uint8_t * data, uint16_t len) virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 106 of file SPIDevice_SPI0.cpp.
Member Data Documentation
AP_HAL_AVR::AVRDigitalSource* AP_HAL_AVR::AVRSPI0DeviceDriver::_cs_pin private
Definition at line 44 of file SPIDevices.h.
Referenced by _cs_assert(), _cs_release(), and init().
bool AVRSPI0DeviceDriver::_force_low_speed static private
Definition at line 42 of file SPIDevices.h.
Referenced by _cs_assert(), and set_bus_speed().
AVRSemaphore AVRSPI0DeviceDriver::_semaphore static private
Definition at line 41 of file SPIDevices.h.
Referenced by get_semaphore().
uint8_t AP_HAL_AVR::AVRSPI0DeviceDriver::_spcr private
Definition at line 47 of file SPIDevices.h.
Referenced by _cs_assert(), and set_bus_speed().
const uint8_t AP_HAL_AVR::AVRSPI0DeviceDriver::_spcr_highspeed private
Definition at line 46 of file SPIDevices.h.
Referenced by set_bus_speed().
const uint8_t AP_HAL_AVR::AVRSPI0DeviceDriver::_spcr_lowspeed private
Definition at line 45 of file SPIDevices.h.
Referenced by _cs_assert(), and set_bus_speed().
const uint8_t AP_HAL_AVR::AVRSPI0DeviceDriver::_spsr private
Definition at line 48 of file SPIDevices.h.
Referenced by _cs_assert().
The documentation for this class was generated from the following files:
libraries/AP_HAL_AVR/SPIDevices.h
libraries/AP_HAL_AVR/SPIDevice_SPI0.cpp