APM:Libraries: AP_HAL::SPIDeviceDriver Class Reference
AP_HAL::SPIDeviceDriver Class Reference abstract
#include <SPIDriver.h>
Public Types
enum bus_speed { SPI_SPEED_LOW, SPI_SPEED_HIGH }
Public Member Functions
virtual void init ()=0
virtual AP_HAL::Semaphore * get_semaphore ()=0
virtual void transaction (const uint8_t *tx, uint8_t *rx, uint16_t len)=0
virtual void cs_assert ()=0
virtual void cs_release ()=0
virtual uint8_t transfer (uint8_t data)=0
virtual void transfer (const uint8_t *data, uint16_t len)=0
virtual void set_bus_speed (enum bus_speed speed)
Detailed Description
We still need an abstraction for performing bulk transfers to be portable to other platforms.
Definition at line 19 of file SPIDriver.h.
Member Enumeration Documentation
enum AP_HAL::SPIDeviceDriver::bus_speed
optional set_bus_speed() interface. This can be used by drivers to request higher speed for sensor registers once the sensor is initialised. This is used by the MPU6000 driver which can handle 20MHz for sensor register reads, but only 1MHz for other registers.
Enumerator
SPI_SPEED_LOW
SPI_SPEED_HIGH
Definition at line 37 of file SPIDriver.h.
Member Function Documentation
virtual void AP_HAL::SPIDeviceDriver::cs_assert () pure virtual
Implemented in AP_HAL_AVR::AVRSPI3DeviceDriver, AP_HAL_AVR::AVRSPI2DeviceDriver, Linux::LinuxSPIDeviceDriver, AP_HAL_FLYMAPLE_NS::FLYMAPLESPIDeviceDriver, AP_HAL_AVR::AVRSPI0DeviceDriver, and Empty::EmptySPIDeviceDriver.
Referenced by DataFlash_APM1::BlockErase(), DataFlash_APM1::BlockRead(), DataFlash_APM1::BlockWrite(), DataFlash_APM1::BufferToPage(), DataFlash_APM1::ChipErase(), AP_ADC_ADS7844::Init(), mpu6k_read(), DataFlash_APM1::PageErase(), DataFlash_APM1::PageToBuffer(), DataFlash_APM1::ReadManufacturerID(), DataFlash_APM1::ReadStatusReg(), register_read(), and register_write().
virtual void AP_HAL::SPIDeviceDriver::cs_release () pure virtual
Implemented in AP_HAL_AVR::AVRSPI3DeviceDriver, AP_HAL_AVR::AVRSPI2DeviceDriver, Linux::LinuxSPIDeviceDriver, AP_HAL_FLYMAPLE_NS::FLYMAPLESPIDeviceDriver, AP_HAL_AVR::AVRSPI0DeviceDriver, and Empty::EmptySPIDeviceDriver.
Referenced by DataFlash_APM1::BlockErase(), DataFlash_APM1::BlockRead(), DataFlash_APM1::BlockWrite(), DataFlash_APM1::BufferToPage(), DataFlash_APM1::ChipErase(), AP_ADC_ADS7844::Init(), mpu6k_read(), DataFlash_APM1::PageErase(), DataFlash_APM1::PageToBuffer(), DataFlash_APM1::ReadManufacturerID(), DataFlash_APM1::ReadStatusReg(), register_read(), and register_write().
virtual AP_HAL::Semaphore* AP_HAL::SPIDeviceDriver::get_semaphore () pure virtual
Implemented in AP_HAL_AVR::AVRSPI3DeviceDriver, AP_HAL_AVR::AVRSPI2DeviceDriver, Linux::LinuxSPIDeviceDriver, AP_HAL_FLYMAPLE_NS::FLYMAPLESPIDeviceDriver, AP_HAL_AVR::AVRSPI0DeviceDriver, and Empty::EmptySPIDeviceDriver.
Referenced by AP_InertialSensor_MPU9250::_init_sensor(), AP_InertialSensor_MPU6000::_init_sensor(), AP_InertialSensor_LSM9DS0::_init_sensor(), Linux::LinuxSPIUARTDriver::begin(), AP_ADC_ADS7844::Init(), AP_SerialBus_SPI::init(), DataFlash_APM1::Init(), AK8963_MPU9250_SPI_Backend::init(), loop(), setup(), and Linux::LinuxStorage_FRAM::transaction().
virtual void AP_HAL::SPIDeviceDriver::init () pure virtual
Implemented in AP_HAL_AVR::AVRSPI3DeviceDriver, AP_HAL_AVR::AVRSPI2DeviceDriver, Linux::LinuxSPIDeviceDriver, AP_HAL_FLYMAPLE_NS::FLYMAPLESPIDeviceDriver, AP_HAL_AVR::AVRSPI0DeviceDriver, and Empty::EmptySPIDeviceDriver.
virtual void AP_HAL::SPIDeviceDriver::set_bus_speed (enum bus_speed speed) inline virtual
Reimplemented in Linux::LinuxSPIDeviceDriver, and AP_HAL_AVR::AVRSPI0DeviceDriver.
Definition at line 41 of file SPIDriver.h.
Referenced by AP_InertialSensor_MPU9250::_hardware_init(), AP_InertialSensor_MPU6000::_hardware_init(), AP_InertialSensor_LSM9DS0::_hardware_init(), AP_InertialSensor_MPU6000::_read_data_transaction(), Linux::LinuxSPIUARTDriver::begin(), AP_SerialBus_SPI::init(), and AP_InertialSensor_MPU6000::update().
virtual void AP_HAL::SPIDeviceDriver::transaction (const uint8_t * tx, uint8_t * rx, uint16_t len) pure virtual
Implemented in AP_HAL_AVR::AVRSPI3DeviceDriver, AP_HAL_AVR::AVRSPI2DeviceDriver, Linux::LinuxSPIDeviceDriver, AP_HAL_FLYMAPLE_NS::FLYMAPLESPIDeviceDriver, AP_HAL_AVR::AVRSPI0DeviceDriver, and Empty::EmptySPIDeviceDriver.
Referenced by AP_InertialSensor_MPU9250::_read_data_transaction(), AP_InertialSensor_MPU6000::_read_data_transaction(), Linux::LinuxSPIUARTDriver::_read_fd(), AP_InertialSensor_MPU9250::_register_read(), AP_InertialSensor_MPU6000::_register_read(), AP_InertialSensor_LSM9DS0::_register_read_g(), AP_InertialSensor_LSM9DS0::_register_read_xm(), AP_InertialSensor_MPU9250::_register_write(), AP_InertialSensor_MPU6000::_register_write(), AP_InertialSensor_LSM9DS0::_register_write_g(), AP_InertialSensor_LSM9DS0::_register_write_xm(), Linux::LinuxSPIUARTDriver::_write_fd(), loop(), AP_ADC_ADS7844::read(), AK8963_MPU9250_SPI_Backend::read(), AP_SerialBus_SPI::read_16bits(), AP_SerialBus_SPI::read_24bits(), Linux::LinuxStorage_FRAM::transaction(), AP_SerialBus_SPI::write(), and AK8963_MPU9250_SPI_Backend::write().
virtual uint8_t AP_HAL::SPIDeviceDriver::transfer (uint8_t data) pure virtual
Implemented in AP_HAL_AVR::AVRSPI3DeviceDriver, AP_HAL_AVR::AVRSPI2DeviceDriver, Linux::LinuxSPIDeviceDriver, AP_HAL_FLYMAPLE_NS::FLYMAPLESPIDeviceDriver, AP_HAL_AVR::AVRSPI0DeviceDriver, and Empty::EmptySPIDeviceDriver.
Referenced by DataFlash_APM1::BlockErase(), DataFlash_APM1::BlockRead(), DataFlash_APM1::BlockWrite(), DataFlash_APM1::BufferToPage(), DataFlash_APM1::ChipErase(), AP_ADC_ADS7844::Init(), mpu6k_read(), DataFlash_APM1::PageErase(), DataFlash_APM1::PageToBuffer(), DataFlash_APM1::ReadManufacturerID(), DataFlash_APM1::ReadStatusReg(), register_read(), register_write(), and spi_read_16().
virtual void AP_HAL::SPIDeviceDriver::transfer (const uint8_t * data, uint16_t len) pure virtual
Implemented in AP_HAL_AVR::AVRSPI3DeviceDriver, AP_HAL_AVR::AVRSPI2DeviceDriver, Linux::LinuxSPIDeviceDriver, AP_HAL_FLYMAPLE_NS::FLYMAPLESPIDeviceDriver, AP_HAL_AVR::AVRSPI0DeviceDriver, and Empty::EmptySPIDeviceDriver.
The documentation for this class was generated from the following file:
libraries/AP_HAL/SPIDriver.h