APM:Libraries: DigitalLPF Class Reference
DigitalLPF Class Reference
#include <LowPassFilter.h>
Classes
struct lpf_params
Public Member Functions
DigitalLPF ()
float apply (float sample, float cutoff_freq, float dt)
float get () const
void reset (float value)
Private Attributes
float _output
Detailed Description
Definition at line 30 of file LowPassFilter.h.
Constructor & Destructor Documentation
DigitalLPF::DigitalLPF () inline
Definition at line 34 of file LowPassFilter.h.
Member Function Documentation
float DigitalLPF::apply (float sample, float cutoff_freq, float dt) inline
Definition at line 44 of file LowPassFilter.h.
Referenced by LowPassFilterFloat::apply(), LowPassFilterVector2f::apply(), and LowPassFilterVector3f::apply().
float DigitalLPF::get () const inline
Definition at line 57 of file LowPassFilter.h.
Referenced by LowPassFilterFloat::get().
void DigitalLPF::reset (float value) inline
Definition at line 61 of file LowPassFilter.h.
Referenced by LowPassFilterFloat::reset(), LowPassFilterVector2f::reset(), and LowPassFilterVector3f::reset().
Member Data Documentation
float DigitalLPF::_output private
Definition at line 64 of file LowPassFilter.h.
Referenced by apply(), get(), and reset().
The documentation for this class was generated from the following file:
libraries/Filter/LowPassFilter.h