APM:Libraries: LowPassFilter2pVector3f Class Reference
LowPassFilter2pVector3f Class Reference
#include <LowPassFilter2p.h>
Public Member Functions
LowPassFilter2pVector3f ()
LowPassFilter2pVector3f (float sample_freq, float cutoff_freq)
Vector3f apply (const Vector3f &sample)
Public Member Functions inherited from LowPassFilter2p
LowPassFilter2p ()
LowPassFilter2p (float sample_freq, float cutoff_freq)
void set_cutoff_frequency (float sample_freq, float cutoff_freq)
float get_cutoff_freq (void) const
float get_sample_freq (void) const
Private Attributes
DigitalBiquadFilter _filter_x
DigitalBiquadFilter _filter_y
DigitalBiquadFilter _filter_z
Additional Inherited Members
Protected Attributes inherited from LowPassFilter2p
struct
DigitalBiquadFilter::biquad_params _params
Detailed Description
Definition at line 97 of file LowPassFilter2p.h.
Constructor & Destructor Documentation
LowPassFilter2pVector3f::LowPassFilter2pVector3f () inline
Definition at line 100 of file LowPassFilter2p.h.
LowPassFilter2pVector3f::LowPassFilter2pVector3f (float sample_freq, float cutoff_freq) inline
Definition at line 103 of file LowPassFilter2p.h.
Member Function Documentation
Vector3f LowPassFilter2pVector3f::apply (const Vector3f & sample) inline
Definition at line 106 of file LowPassFilter2p.h.
Referenced by AP_InertialSensor_Flymaple::_accumulate(), AP_InertialSensor_MPU9150::_accumulate(), AP_InertialSensor_L3G4200D::_accumulate(), AP_InertialSensor_PX4::_new_accel_sample(), AP_InertialSensor_PX4::_new_gyro_sample(), AP_InertialSensor_MPU9250::_read_data_transaction(), and AP_InertialSensor_MPU6000::_read_data_transaction().
Member Data Documentation
DigitalBiquadFilter LowPassFilter2pVector3f::_filter_x private
Definition at line 115 of file LowPassFilter2p.h.
Referenced by apply().
DigitalBiquadFilter LowPassFilter2pVector3f::_filter_y private
Definition at line 116 of file LowPassFilter2p.h.
Referenced by apply().
DigitalBiquadFilter LowPassFilter2pVector3f::_filter_z private
Definition at line 117 of file LowPassFilter2p.h.
Referenced by apply().
The documentation for this class was generated from the following file:
libraries/Filter/LowPassFilter2p.h