APM:Libraries: CRRCSim Class Reference
CRRCSim Class Reference
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
#include <SIM_CRRCSim.h>
Classes
struct fdm_packet
struct servo_packet
Public Member Functions
CRRCSim (const char *home_str, const char *frame_str)
void update (const struct sitl_input &input)
Public Member Functions inherited from Aircraft
Aircraft (const char *home_str, const char *frame_str)
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
void set_speedup (float speedup)
void set_instance (uint8_t _instance)
void fill_fdm (struct sitl_fdm &fdm) const
Static Public Member Functions
static Aircraft * create (const char *home_str, const char *frame_str)
Private Member Functions
void send_servos_heli (const struct sitl_input &input)
void send_servos_fixed_wing (const struct sitl_input &input)
void recv_fdm (const struct sitl_input &input)
void send_servos (const struct sitl_input &input)
Private Attributes
bool heli_servos
double last_timestamp
SocketAPM sock
Additional Inherited Members
Protected Member Functions inherited from Aircraft
bool on_ground (const Vector3f &pos) const
void update_position (void)
void set_yaw_degrees (float yaw_degrees)
void time_advance (float deltat)
void setup_frame_time (float rate, float speedup)
void adjust_frame_time (float rate)
void sync_frame_time (void)
void add_noise (float throttle)
uint64_t get_wall_time_us (void) const
double rand_normal (double mean, double stddev)
Protected Attributes inherited from Aircraft
Location home
Location location
float ground_level
float frame_height
Matrix3f dcm
Vector3f gyro
Vector3f velocity_ef
Vector3f position
float mass
Vector3f accel_body
uint64_t time_now_us
const float gyro_noise
const float accel_noise
float rate_hz
float achieved_rate_hz
float target_speedup
uint64_t frame_time_us
float scaled_frame_time_us
uint64_t last_wall_time_us
uint8_t instance
Detailed Description
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 29 of file SIM_CRRCSim.h.
Constructor & Destructor Documentation
CRRCSim::CRRCSim (const char * home_str, const char * frame_str)
Definition at line 30 of file SIM_CRRCSim.cpp.
Referenced by create().
Member Function Documentation
static Aircraft* CRRCSim::create (const char * home_str, const char * frame_str) inline static
Definition at line 38 of file SIM_CRRCSim.h.
void CRRCSim::recv_fdm (const struct sitl_input & input) private
Definition at line 111 of file SIM_CRRCSim.cpp.
Referenced by update().
void CRRCSim::send_servos (const struct sitl_input & input) private
Definition at line 98 of file SIM_CRRCSim.cpp.
Referenced by recv_fdm(), and update().
void CRRCSim::send_servos_fixed_wing (const struct sitl_input & input) private
Definition at line 78 of file SIM_CRRCSim.cpp.
Referenced by send_servos().
void CRRCSim::send_servos_heli (const struct sitl_input & input) private
Definition at line 52 of file SIM_CRRCSim.cpp.
Referenced by send_servos().
void CRRCSim::update (const struct sitl_input & input) virtual
Implements Aircraft.
Definition at line 151 of file SIM_CRRCSim.cpp.
Member Data Documentation
bool CRRCSim::heli_servos private
Definition at line 74 of file SIM_CRRCSim.h.
Referenced by CRRCSim(), and send_servos().
double CRRCSim::last_timestamp private
Definition at line 75 of file SIM_CRRCSim.h.
Referenced by recv_fdm().
SocketAPM CRRCSim::sock private
Definition at line 76 of file SIM_CRRCSim.h.
Referenced by CRRCSim(), recv_fdm(), send_servos_fixed_wing(), and send_servos_heli().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_CRRCSim.h
libraries/SITL/SIM_CRRCSim.cpp