APM:Libraries: LowPassFilter2p Class Reference
LowPassFilter2p Class Reference
#include <LowPassFilter2p.h>
Public Member Functions
LowPassFilter2p ()
LowPassFilter2p (float sample_freq, float cutoff_freq)
void set_cutoff_frequency (float sample_freq, float cutoff_freq)
float get_cutoff_freq (void) const
float get_sample_freq (void) const
Protected Attributes
struct
DigitalBiquadFilter::biquad_params _params
Detailed Description
Definition at line 53 of file LowPassFilter2p.h.
Constructor & Destructor Documentation
LowPassFilter2p::LowPassFilter2p () inline
Definition at line 56 of file LowPassFilter2p.h.
LowPassFilter2p::LowPassFilter2p (float sample_freq, float cutoff_freq) inline
Definition at line 58 of file LowPassFilter2p.h.
Member Function Documentation
float LowPassFilter2p::get_cutoff_freq (void) const inline
Definition at line 69 of file LowPassFilter2p.h.
float LowPassFilter2p::get_sample_freq (void) const inline
Definition at line 73 of file LowPassFilter2p.h.
void LowPassFilter2p::set_cutoff_frequency (float sample_freq, float cutoff_freq) inline
Definition at line 64 of file LowPassFilter2p.h.
Referenced by AP_InertialSensor_MPU9250::_set_accel_filter(), AP_InertialSensor_MPU9150::_set_accel_filter_frequency(), AP_InertialSensor_PX4::_set_accel_filter_frequency(), AP_InertialSensor_Flymaple::_set_filter_frequency(), AP_InertialSensor_L3G4200D::_set_filter_frequency(), AP_InertialSensor_MPU9250::_set_gyro_filter(), AP_InertialSensor_MPU9150::_set_gyro_filter_frequency(), AP_InertialSensor_PX4::_set_gyro_filter_frequency(), LowPassFilter2p(), and AP_InertialSensor_MPU6000::update().
Member Data Documentation
struct DigitalBiquadFilter::biquad_params LowPassFilter2p::_params protected
Definition at line 78 of file LowPassFilter2p.h.
Referenced by LowPassFilter2pfloat::apply(), LowPassFilter2pVector3f::apply(), get_cutoff_freq(), get_sample_freq(), LowPassFilter2p(), and set_cutoff_frequency().
The documentation for this class was generated from the following file:
libraries/Filter/LowPassFilter2p.h