APM:Libraries: AP_HAL_AVR::AVRSPI3DeviceDriver Class Reference
AP_HAL_AVR::AVRSPI3DeviceDriver Class Reference
#include <SPIDevices.h>
Public Member Functions
AVRSPI3DeviceDriver (AP_HAL_AVR::AVRDigitalSource *cs_pin, uint8_t ucsr3c, uint16_t ubrr3)
void init ()
AP_HAL::Semaphore * get_semaphore ()
void transaction (const uint8_t *tx, uint8_t *rx, uint16_t len)
void cs_assert ()
void cs_release ()
uint8_t transfer (uint8_t data)
void transfer (const uint8_t *data, uint16_t len)
Public Member Functions inherited from AP_HAL::SPIDeviceDriver
virtual void set_bus_speed (enum bus_speed speed)
Private Member Functions
void _cs_assert ()
void _cs_release ()
uint8_t _transfer (uint8_t data)
void _transfer (const uint8_t *data, uint16_t size)
Private Attributes
AP_HAL_AVR::AVRDigitalSource * _cs_pin
uint8_t _ucsr3c
uint16_t _ubrr3
Static Private Attributes
static AP_HAL_AVR::AVRSemaphore _semaphore
Additional Inherited Members
Public Types inherited from AP_HAL::SPIDeviceDriver
enum bus_speed { SPI_SPEED_LOW, SPI_SPEED_HIGH }
Detailed Description
Definition at line 88 of file SPIDevices.h.
Constructor & Destructor Documentation
AP_HAL_AVR::AVRSPI3DeviceDriver::AVRSPI3DeviceDriver (AP_HAL_AVR::AVRDigitalSource * cs_pin, uint8_t ucsr3c, uint16_t ubrr3) inline
Definition at line 90 of file SPIDevices.h.
Member Function Documentation
void AVRSPI3DeviceDriver::_cs_assert () private
Definition at line 47 of file SPIDevice_SPI3.cpp.
Referenced by cs_assert(), and transaction().
void AVRSPI3DeviceDriver::_cs_release () private
Definition at line 60 of file SPIDevice_SPI3.cpp.
Referenced by cs_release(), and transaction().
uint8_t AVRSPI3DeviceDriver::_transfer (uint8_t data) private
Definition at line 64 of file SPIDevice_SPI3.cpp.
Referenced by transaction(), and transfer().
void AVRSPI3DeviceDriver::_transfer (const uint8_t * data, uint16_t size) private
Definition at line 78 of file SPIDevice_SPI3.cpp.
void AVRSPI3DeviceDriver::cs_assert () virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 107 of file SPIDevice_SPI3.cpp.
void AVRSPI3DeviceDriver::cs_release () virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 111 of file SPIDevice_SPI3.cpp.
AP_HAL::Semaphore * AVRSPI3DeviceDriver::get_semaphore () virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 43 of file SPIDevice_SPI3.cpp.
void AVRSPI3DeviceDriver::init (void) virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 24 of file SPIDevice_SPI3.cpp.
Referenced by AP_HAL_AVR::APM2SPIDeviceManager::init().
void AVRSPI3DeviceDriver::transaction (const uint8_t * tx, uint8_t * rx, uint16_t len) virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 94 of file SPIDevice_SPI3.cpp.
uint8_t AVRSPI3DeviceDriver::transfer (uint8_t data) virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 115 of file SPIDevice_SPI3.cpp.
void AVRSPI3DeviceDriver::transfer (const uint8_t * data, uint16_t len) virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 119 of file SPIDevice_SPI3.cpp.
Member Data Documentation
AP_HAL_AVR::AVRDigitalSource* AP_HAL_AVR::AVRSPI3DeviceDriver::_cs_pin private
Definition at line 117 of file SPIDevices.h.
Referenced by _cs_assert(), _cs_release(), and init().
AVRSemaphore AVRSPI3DeviceDriver::_semaphore static private
Definition at line 115 of file SPIDevices.h.
Referenced by get_semaphore().
uint16_t AP_HAL_AVR::AVRSPI3DeviceDriver::_ubrr3 private
Definition at line 119 of file SPIDevices.h.
Referenced by _cs_assert().
uint8_t AP_HAL_AVR::AVRSPI3DeviceDriver::_ucsr3c private
Definition at line 118 of file SPIDevices.h.
Referenced by _cs_assert().
The documentation for this class was generated from the following files:
libraries/AP_HAL_AVR/SPIDevices.h
libraries/AP_HAL_AVR/SPIDevice_SPI3.cpp