APM:Libraries: AP_HAL::GPIO Class Reference
AP_HAL::GPIO Class Reference abstract
#include <GPIO.h>
Public Member Functions
GPIO ()
virtual void init ()=0
virtual void pinMode (uint8_t pin, uint8_t output)=0
virtual uint8_t read (uint8_t pin)=0
virtual void write (uint8_t pin, uint8_t value)=0
virtual void toggle (uint8_t pin)=0
virtual int8_t analogPinToDigitalPin (uint8_t pin)=0
virtual AP_HAL::DigitalSource * channel (uint16_t n)=0
virtual bool attach_interrupt (uint8_t interrupt_num, AP_HAL::Proc p, uint8_t mode)=0
virtual bool usb_connected (void)=0
Detailed Description
Definition at line 24 of file GPIO.h.
Constructor & Destructor Documentation
AP_HAL::GPIO::GPIO () inline
Definition at line 26 of file GPIO.h.
Member Function Documentation
virtual int8_t AP_HAL::GPIO::analogPinToDigitalPin (uint8_t pin) pure virtual
Implemented in Linux::LinuxGPIO_BBB, Linux::LinuxGPIO_RPI, AP_HAL_AVR::AVRGPIO, PX4::PX4GPIO, AP_HAL_FLYMAPLE_NS::FLYMAPLEGPIO, VRBRAIN::VRBRAINGPIO, and Empty::EmptyGPIO.
Referenced by AP_HAL_AVR::ADCSource::set_pin(), AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogSource::set_pin(), AP_HAL_AVR::ADCSource::setup_read(), AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogSource::setup_read(), AP_HAL_AVR::ADCSource::stop_read(), and AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogSource::stop_read().
virtual bool AP_HAL::GPIO::attach_interrupt (uint8_t interrupt_num, AP_HAL::Proc p, uint8_t mode) pure virtual
Implemented in Linux::LinuxGPIO_BBB, Linux::LinuxGPIO_RPI, AP_HAL_AVR::AVRGPIO, PX4::PX4GPIO, AP_HAL_FLYMAPLE_NS::FLYMAPLEGPIO, VRBRAIN::VRBRAINGPIO, and Empty::EmptyGPIO.
virtual AP_HAL::DigitalSource* AP_HAL::GPIO::channel (uint16_t n) pure virtual
Implemented in Linux::LinuxGPIO_BBB, Linux::LinuxGPIO_RPI, AP_HAL_AVR::AVRGPIO, PX4::PX4GPIO, AP_HAL_FLYMAPLE_NS::FLYMAPLEGPIO, VRBRAIN::VRBRAINGPIO, and Empty::EmptyGPIO.
Referenced by AP_InertialSensor_MPU6000::_init_sensor(), AP_InertialSensor_LSM9DS0::_init_sensor(), Linux::LinuxRCOutput_Navio::init(), Linux::LinuxSPIDeviceDriver::init(), and setup().
virtual void AP_HAL::GPIO::init () pure virtual
Implemented in Linux::LinuxGPIO_BBB, Linux::LinuxGPIO_RPI, AP_HAL_AVR::AVRGPIO, PX4::PX4GPIO, AP_HAL_FLYMAPLE_NS::FLYMAPLEGPIO, VRBRAIN::VRBRAINGPIO, and Empty::EmptyGPIO.
Referenced by HAL_Linux::init(), and main_loop().
virtual void AP_HAL::GPIO::pinMode (uint8_t pin, uint8_t output) pure virtual
Implemented in Linux::LinuxGPIO_BBB, Linux::LinuxGPIO_RPI, AP_HAL_AVR::AVRGPIO, PX4::PX4GPIO, AP_HAL_FLYMAPLE_NS::FLYMAPLEGPIO, VRBRAIN::VRBRAINGPIO, and Empty::EmptyGPIO.
Referenced by AP_Baro_BMP085::AP_Baro_BMP085(), APM_OBC::check(), APM_OBC::heartbeat(), VRBoard_LED::hw_init(), AP_HAL_AVR::APM1RCOutput::init(), Linux::LinuxRCInput_PRU::init(), AP_HAL_AVR::AVRSPI0DeviceDriver::init(), AP_HAL_AVR::APM1RCInput::init(), AP_HAL_AVR::APM2RCOutput::init(), Buzzer::init(), DataFlash_APM1::Init(), ExternalLED::init(), LiquidCrystal::init(), AP_BoardLED::init(), AP_HAL_AVR::APM2RCInput::init(), AP_HAL_AVR::AVRSPI3DeviceDriver::init(), Linux::LinuxDigitalSource::mode(), PX4::PX4AnalogIn::next_stop_pin(), VRBRAIN::VRBRAINAnalogIn::next_stop_pin(), AP_Relay::off(), AP_Relay::on(), AP_HAL_AVR::ADCSource::set_pin(), setup(), setup_pin(), AP_HAL_AVR::ADCSource::setup_read(), AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogSource::setup_read(), AP_HAL_AVR::ADCSource::stop_read(), AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogSource::stop_read(), AP_RangeFinder_PX4_PWM::update(), LiquidCrystal::write4bits(), and LiquidCrystal::write8bits().
virtual uint8_t AP_HAL::GPIO::read (uint8_t pin) pure virtual
Implemented in Linux::LinuxGPIO_BBB, Linux::LinuxGPIO_RPI, AP_HAL_AVR::AVRGPIO, PX4::PX4GPIO, AP_HAL_FLYMAPLE_NS::FLYMAPLEGPIO, VRBRAIN::VRBRAINGPIO, and Empty::EmptyGPIO.
Referenced by loop(), Linux::LinuxDigitalSource::read(), and AP_Relay::toggle().
virtual void AP_HAL::GPIO::toggle (uint8_t pin) pure virtual
Implemented in Linux::LinuxGPIO_BBB, Linux::LinuxGPIO_RPI, AP_HAL_AVR::AVRGPIO, PX4::PX4GPIO, AP_HAL_FLYMAPLE_NS::FLYMAPLEGPIO, VRBRAIN::VRBRAINGPIO, and Empty::EmptyGPIO.
Referenced by AP_BoardLED::update().
virtual bool AP_HAL::GPIO::usb_connected (void) pure virtual
Implemented in Linux::LinuxGPIO_BBB, Linux::LinuxGPIO_RPI, AP_HAL_AVR::AVRGPIO, PX4::PX4GPIO, AP_HAL_FLYMAPLE_NS::FLYMAPLEGPIO, VRBRAIN::VRBRAINGPIO, and Empty::EmptyGPIO.
Referenced by PX4::PX4UARTDriver::_timer_tick(), VRBRAIN::VRBRAINUARTDriver::_timer_tick(), GCS_MAVLINK::handle_log_send(), GCS_MAVLINK::have_flow_control(), OreoLED_PX4::update(), and RGBLed::update_colours().
virtual void AP_HAL::GPIO::write (uint8_t pin, uint8_t value) pure virtual
Implemented in Linux::LinuxGPIO_BBB, Linux::LinuxGPIO_RPI, AP_HAL_AVR::AVRGPIO, PX4::PX4GPIO, AP_HAL_FLYMAPLE_NS::FLYMAPLEGPIO, VRBRAIN::VRBRAINGPIO, and Empty::EmptyGPIO.
Referenced by ExternalLED::armed_led(), LiquidCrystal::begin(), blink_a0(), blink_a1(), blink_a2(), blink_a3(), APM_OBC::check(), delay_toggle(), failsafe_toggle(), ExternalLED::gps_led(), APM_OBC::heartbeat(), VRBoard_LED::hw_init(), VRBoard_LED::hw_set_rgb(), Linux::LinuxRCInput_PRU::init(), DataFlash_APM1::Init(), ExternalLED::init(), AP_BoardLED::init(), loop(), ExternalLED::motor_led1(), ExternalLED::motor_led2(), PX4::PX4AnalogIn::next_stop_pin(), VRBRAIN::VRBRAINAnalogIn::next_stop_pin(), AP_Relay::off(), AP_Relay::on(), Buzzer::on(), LiquidCrystal::pulseEnable(), schedule_toggle_1(), schedule_toggle_2(), schedule_toggle_hang(), LiquidCrystal::send(), AP_HAL_AVR::ADCSource::set_pin(), setup(), setup_pin(), AP_HAL_AVR::ADCSource::setup_read(), AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogSource::setup_read(), AP_HAL_AVR::ADCSource::stop_read(), AP_HAL_FLYMAPLE_NS::FLYMAPLEAnalogSource::stop_read(), AP_RangeFinder_PX4_PWM::update(), AP_BoardLED::update(), Linux::LinuxDigitalSource::write(), LiquidCrystal::write4bits(), and LiquidCrystal::write8bits().
The documentation for this class was generated from the following file:
libraries/AP_HAL/GPIO.h