APM:Libraries: Linux::LinuxSPIDeviceManager Class Reference
Linux::LinuxSPIDeviceManager Class Reference
#include <SPIDriver.h>
Public Member Functions
void init (void *)
AP_HAL::SPIDeviceDriver * device (enum AP_HAL::SPIDevice)
Static Public Member Functions
static AP_HAL::Semaphore * get_semaphore (uint16_t bus)
static void cs_assert (enum AP_HAL::SPIDevice type)
static void cs_release (enum AP_HAL::SPIDevice type)
static void transaction (LinuxSPIDeviceDriver &driver, const uint8_t *tx, uint8_t *rx, uint16_t len)
Static Private Attributes
static LinuxSPIDeviceDriver _device [LINUX_SPI_DEVICE_NUM_DEVICES]
static LinuxSemaphore _semaphore [LINUX_SPI_MAX_BUSES]
Detailed Description
Definition at line 56 of file SPIDriver.h.
Member Function Documentation
void LinuxSPIDeviceManager::cs_assert (enum AP_HAL::SPIDevice type) static
Definition at line 148 of file SPIDriver.cpp.
Referenced by Linux::LinuxSPIDeviceDriver::cs_assert(), and transaction().
void LinuxSPIDeviceManager::cs_release (enum AP_HAL::SPIDevice type) static
Definition at line 184 of file SPIDriver.cpp.
Referenced by Linux::LinuxSPIDeviceDriver::cs_release(), and transaction().
AP_HAL::SPIDeviceDriver * LinuxSPIDeviceManager::device (enum AP_HAL::SPIDevice dev) virtual
Implements AP_HAL::SPIDeviceManager.
Definition at line 239 of file SPIDriver.cpp.
AP_HAL::Semaphore * LinuxSPIDeviceManager::get_semaphore (uint16_t bus) static
Definition at line 252 of file SPIDriver.cpp.
Referenced by Linux::LinuxSPIDeviceDriver::get_semaphore().
void LinuxSPIDeviceManager::init (void *) virtual
Implements AP_HAL::SPIDeviceManager.
Definition at line 126 of file SPIDriver.cpp.
void LinuxSPIDeviceManager::transaction (LinuxSPIDeviceDriver & driver, const uint8_t * tx, uint8_t * rx, uint16_t len) static
Definition at line 210 of file SPIDriver.cpp.
Referenced by Linux::LinuxSPIDeviceDriver::transaction().
Member Data Documentation
LinuxSPIDeviceDriver LinuxSPIDeviceManager::_device static private
Initial value:
= {
    LinuxSPIDeviceDriver(1, 0, AP_HAL::SPIDevice_LSM9DS0_AM, SPI_MODE_3, 8, BBB_P9_17,  10*MHZ,10*MHZ),
    LinuxSPIDeviceDriver(1, 0, AP_HAL::SPIDevice_LSM9DS0_G,  SPI_MODE_3, 8, BBB_P8_9,   10*MHZ,10*MHZ),
    LinuxSPIDeviceDriver(2, 0, AP_HAL::SPIDevice_MS5611,     SPI_MODE_3, 8, BBB_P9_42,  10*MHZ,10*MHZ),
    LinuxSPIDeviceDriver(2, 0, AP_HAL::SPIDevice_MPU6000,    SPI_MODE_3, 8, BBB_P9_28,  500*1000, 20*MHZ),
    LinuxSPIDeviceDriver(2, 0, AP_HAL::SPIDevice_MPU9250,    SPI_MODE_3, 8, BBB_P9_23,  1*MHZ, 20*MHZ),
    LinuxSPIDeviceDriver(2, 0, AP_HAL::SPIDevice_Dataflash,  SPI_MODE_3, 8, BBB_P8_12,  6*MHZ, 6*MHZ),
}
Definition at line 68 of file SPIDriver.h.
Referenced by cs_assert(), cs_release(), device(), and init().
LinuxSemaphore LinuxSPIDeviceManager::_semaphore static private
Definition at line 69 of file SPIDriver.h.
Referenced by get_semaphore().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/SPIDriver.h
libraries/AP_HAL_Linux/SPIDriver.cpp