APM:Libraries: Linux::LinuxRCOutput_Navio Class Reference
Linux::LinuxRCOutput_Navio Class Reference
#include <RCOutput_Navio.h>
Public Member Functions
LinuxRCOutput_Navio ()
~LinuxRCOutput_Navio ()
void init (void *machtnichts)
void reset_all_channels ()
void set_freq (uint32_t chmask, uint16_t freq_hz)
uint16_t get_freq (uint8_t ch)
void enable_ch (uint8_t ch)
void disable_ch (uint8_t ch)
void write (uint8_t ch, uint16_t period_us)
void write (uint8_t ch, uint16_t *period_us, uint8_t len)
uint16_t read (uint8_t ch)
void read (uint16_t *period_us, uint8_t len)
Public Member Functions inherited from AP_HAL::RCOutput
virtual void set_safety_pwm (uint32_t chmask, uint16_t period_us)
virtual void set_failsafe_pwm (uint32_t chmask, uint16_t period_us)
virtual bool force_safety_on (void)
virtual void force_safety_off (void)
virtual void set_esc_scaling (uint16_t min_pwm, uint16_t max_pwm)
Private Member Functions
void reset ()
Private Attributes
AP_HAL::Semaphore * _i2c_sem
AP_HAL::DigitalSource * enable_pin
uint16_t _frequency
uint16_t * _pulses_buffer
Detailed Description
Definition at line 7 of file RCOutput_Navio.h.
Constructor & Destructor Documentation
LinuxRCOutput_Navio::LinuxRCOutput_Navio ()
Definition at line 54 of file RCOutput_Navio.cpp.
LinuxRCOutput_Navio::~LinuxRCOutput_Navio ()
Definition at line 62 of file RCOutput_Navio.cpp.
Member Function Documentation
void LinuxRCOutput_Navio::disable_ch (uint8_t ch) virtual
Implements AP_HAL::RCOutput.
Definition at line 148 of file RCOutput_Navio.cpp.
void LinuxRCOutput_Navio::enable_ch (uint8_t ch) virtual
Implements AP_HAL::RCOutput.
Definition at line 143 of file RCOutput_Navio.cpp.
uint16_t LinuxRCOutput_Navio::get_freq (uint8_t ch) virtual
Implements AP_HAL::RCOutput.
Definition at line 138 of file RCOutput_Navio.cpp.
void LinuxRCOutput_Navio::init (void * machtnichts) virtual
Implements AP_HAL::RCOutput.
Definition at line 67 of file RCOutput_Navio.cpp.
uint16_t LinuxRCOutput_Navio::read (uint8_t ch) virtual
Implements AP_HAL::RCOutput.
Definition at line 187 of file RCOutput_Navio.cpp.
Referenced by read().
void LinuxRCOutput_Navio::read (uint16_t * period_us, uint8_t len) virtual
Implements AP_HAL::RCOutput.
Definition at line 192 of file RCOutput_Navio.cpp.
void Linux::LinuxRCOutput_Navio::reset () private
void LinuxRCOutput_Navio::reset_all_channels ()
Definition at line 87 of file RCOutput_Navio.cpp.
Referenced by init().
void LinuxRCOutput_Navio::set_freq (uint32_t chmask, uint16_t freq_hz) virtual
Implements AP_HAL::RCOutput.
Definition at line 102 of file RCOutput_Navio.cpp.
Referenced by init().
void LinuxRCOutput_Navio::write (uint8_t ch, uint16_t period_us) virtual
Implements AP_HAL::RCOutput.
Definition at line 153 of file RCOutput_Navio.cpp.
Referenced by disable_ch(), set_freq(), and write().
void LinuxRCOutput_Navio::write (uint8_t ch, uint16_t * period_us, uint8_t len) virtual
Implements AP_HAL::RCOutput.
Definition at line 181 of file RCOutput_Navio.cpp.
Member Data Documentation
uint16_t Linux::LinuxRCOutput_Navio::_frequency private
Definition at line 27 of file RCOutput_Navio.h.
Referenced by get_freq(), set_freq(), and write().
AP_HAL::Semaphore* Linux::LinuxRCOutput_Navio::_i2c_sem private
Definition at line 25 of file RCOutput_Navio.h.
Referenced by init(), reset_all_channels(), set_freq(), and write().
uint16_t* Linux::LinuxRCOutput_Navio::_pulses_buffer private
Definition at line 29 of file RCOutput_Navio.h.
Referenced by read(), set_freq(), write(), and ~LinuxRCOutput_Navio().
AP_HAL::DigitalSource* Linux::LinuxRCOutput_Navio::enable_pin private
Definition at line 26 of file RCOutput_Navio.h.
Referenced by init().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/RCOutput_Navio.h
libraries/AP_HAL_Linux/RCOutput_Navio.cpp