APM:Libraries: AK8963_Backend Class Reference
AK8963_Backend Class Reference abstract
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
#include <AP_Compass_AK8963.h>
Public Member Functions
virtual ~AK8963_Backend ()
virtual void read (uint8_t address, uint8_t *buf, uint32_t count)=0
virtual void write (uint8_t address, const uint8_t *buf, uint32_t count)=0
virtual bool sem_take_nonblocking ()=0
virtual bool sem_take_blocking ()=0
virtual bool sem_give ()=0
virtual bool init ()=0
virtual uint8_t read (uint8_t address)
virtual void write (uint8_t address, uint8_t value)
Detailed Description
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 12 of file AP_Compass_AK8963.h.
Constructor & Destructor Documentation
virtual AK8963_Backend::~AK8963_Backend () inline virtual
Definition at line 15 of file AP_Compass_AK8963.h.
Member Function Documentation
virtual bool AK8963_Backend::init () pure virtual
Implemented in AK8963_MPU9250_SPI_Backend.
Referenced by AP_Compass_AK8963_MPU9250::init().
virtual void AK8963_Backend::read (uint8_t address, uint8_t * buf, uint32_t count) pure virtual
Implemented in AK8963_MPU9250_SPI_Backend.
Referenced by AP_Compass_AK8963_MPU9250::_dump_registers(), AP_Compass_AK8963_MPU9250::_register_read(), read(), and AP_Compass_AK8963_MPU9250::read_raw().
virtual uint8_t AK8963_Backend::read (uint8_t address) inline virtual
Definition at line 22 of file AP_Compass_AK8963.h.
virtual bool AK8963_Backend::sem_give () pure virtual
Implemented in AK8963_MPU9250_SPI_Backend.
Referenced by AP_Compass_AK8963::_update(), and AP_Compass_AK8963::init().
virtual bool AK8963_Backend::sem_take_blocking () pure virtual
Implemented in AK8963_MPU9250_SPI_Backend.
Referenced by AP_Compass_AK8963::init().
virtual bool AK8963_Backend::sem_take_nonblocking () pure virtual
Implemented in AK8963_MPU9250_SPI_Backend.
Referenced by AP_Compass_AK8963::_update().
virtual void AK8963_Backend::write (uint8_t address, const uint8_t * buf, uint32_t count) pure virtual
Implemented in AK8963_MPU9250_SPI_Backend.
Referenced by AP_Compass_AK8963_MPU9250::_backend_init(), AP_Compass_AK8963_MPU9250::_backend_reset(), AP_Compass_AK8963_MPU9250::_register_read(), AP_Compass_AK8963_MPU9250::_register_write(), AP_Compass_AK8963::_start_conversion(), and write().
virtual void AK8963_Backend::write (uint8_t address, uint8_t value) inline virtual
Definition at line 29 of file AP_Compass_AK8963.h.
The documentation for this class was generated from the following file:
libraries/AP_Compass/AP_Compass_AK8963.h