APM:Libraries: fastdelegate::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr > Class Template Reference
fastdelegate::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr > Class Template Reference
#include <FastDelegate.h>
Public Member Functions
template<class X , class XMemFunc >
void bindmemfunc (X *pthis, XMemFunc function_to_bind)
template<class X , class XMemFunc >
void bindconstmemfunc (const X *pthis, XMemFunc function_to_bind)
GenericClass * GetClosureThis () const
GenericMemFunc GetClosureMemPtr () const
template<class DerivedClass >
void CopyFrom (DerivedClass *pParent, const DelegateMemento &right)
template<class DerivedClass , class ParentInvokerSig >
void bindstaticfunc (DerivedClass *pParent, ParentInvokerSig static_function_invoker, StaticFuncPtr function_to_bind)
UnvoidStaticFuncPtr GetStaticFunction () const
bool IsEqualToStaticFuncPtr (StaticFuncPtr funcptr)
Public Member Functions inherited from fastdelegate::DelegateMemento
DelegateMemento ()
void clear ()
bool IsEqual (const DelegateMemento &x) const
bool IsLess (const DelegateMemento &right) const
bool operator! () const
bool empty () const
DelegateMemento & operator= (const DelegateMemento &right)
bool operator< (const DelegateMemento &right)
bool operator> (const DelegateMemento &right)
DelegateMemento (const DelegateMemento &right)
Additional Inherited Members
Protected Types inherited from fastdelegate::DelegateMemento
typedef void(detail::GenericClass::* GenericMemFuncType)()
Protected Member Functions inherited from fastdelegate::DelegateMemento
void SetMementoFrom (const DelegateMemento &right)
Protected Attributes inherited from fastdelegate::DelegateMemento
detail::GenericClass * m_pthis
GenericMemFuncType m_pFunction
Detailed Description
template<class GenericMemFunc, class StaticFuncPtr, class UnvoidStaticFuncPtr>
class fastdelegate::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >
Definition at line 664 of file FastDelegate.h.
Member Function Documentation
template<class GenericMemFunc, class StaticFuncPtr, class UnvoidStaticFuncPtr> template<class X , class XMemFunc > void fastdelegate::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindconstmemfunc (const X * pthis, XMemFunc function_to_bind) inline
Definition at line 684 of file FastDelegate.h.
Referenced by fastdelegate::FastDelegate0< RetType >::bind(), fastdelegate::FastDelegate1< Param1, RetType >::bind(), fastdelegate::FastDelegate2< Param1, Param2, RetType >::bind(), fastdelegate::FastDelegate3< Param1, Param2, Param3, RetType >::bind(), fastdelegate::FastDelegate4< Param1, Param2, Param3, Param4, RetType >::bind(), fastdelegate::FastDelegate5< Param1, Param2, Param3, Param4, Param5, RetType >::bind(), fastdelegate::FastDelegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::bind(), fastdelegate::FastDelegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::bind(), fastdelegate::FastDelegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::bind(), fastdelegate::FastDelegate0< RetType >::FastDelegate0(), fastdelegate::FastDelegate1< Param1, RetType >::FastDelegate1(), fastdelegate::FastDelegate2< Param1, Param2, RetType >::FastDelegate2(), fastdelegate::FastDelegate3< Param1, Param2, Param3, RetType >::FastDelegate3(), fastdelegate::FastDelegate4< Param1, Param2, Param3, Param4, RetType >::FastDelegate4(), fastdelegate::FastDelegate5< Param1, Param2, Param3, Param4, Param5, RetType >::FastDelegate5(), fastdelegate::FastDelegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::FastDelegate6(), fastdelegate::FastDelegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::FastDelegate7(), and fastdelegate::FastDelegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::FastDelegate8().
template<class GenericMemFunc, class StaticFuncPtr, class UnvoidStaticFuncPtr> template<class X , class XMemFunc > void fastdelegate::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindmemfunc (X * pthis, XMemFunc function_to_bind) inline
Definition at line 672 of file FastDelegate.h.
Referenced by fastdelegate::FastDelegate0< RetType >::bind(), fastdelegate::FastDelegate1< Param1, RetType >::bind(), fastdelegate::FastDelegate2< Param1, Param2, RetType >::bind(), fastdelegate::FastDelegate3< Param1, Param2, Param3, RetType >::bind(), fastdelegate::FastDelegate4< Param1, Param2, Param3, Param4, RetType >::bind(), fastdelegate::FastDelegate5< Param1, Param2, Param3, Param4, Param5, RetType >::bind(), fastdelegate::FastDelegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::bind(), fastdelegate::FastDelegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::bind(), fastdelegate::FastDelegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::bind(), fastdelegate::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::bindstaticfunc(), fastdelegate::FastDelegate0< RetType >::FastDelegate0(), fastdelegate::FastDelegate1< Param1, RetType >::FastDelegate1(), fastdelegate::FastDelegate2< Param1, Param2, RetType >::FastDelegate2(), fastdelegate::FastDelegate3< Param1, Param2, Param3, RetType >::FastDelegate3(), fastdelegate::FastDelegate4< Param1, Param2, Param3, Param4, RetType >::FastDelegate4(), fastdelegate::FastDelegate5< Param1, Param2, Param3, Param4, Param5, RetType >::FastDelegate5(), fastdelegate::FastDelegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::FastDelegate6(), fastdelegate::FastDelegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::FastDelegate7(), and fastdelegate::FastDelegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::FastDelegate8().
template<class GenericMemFunc, class StaticFuncPtr, class UnvoidStaticFuncPtr> template<class DerivedClass , class ParentInvokerSig > void fastdelegate::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::bindstaticfunc (DerivedClass * pParent, ParentInvokerSig static_function_invoker, StaticFuncPtr function_to_bind) inline
Definition at line 767 of file FastDelegate.h.
Referenced by fastdelegate::FastDelegate0< RetType >::bind(), fastdelegate::FastDelegate1< Param1, RetType >::bind(), fastdelegate::FastDelegate2< Param1, Param2, RetType >::bind(), fastdelegate::FastDelegate3< Param1, Param2, Param3, RetType >::bind(), fastdelegate::FastDelegate4< Param1, Param2, Param3, Param4, RetType >::bind(), fastdelegate::FastDelegate5< Param1, Param2, Param3, Param4, Param5, RetType >::bind(), fastdelegate::FastDelegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::bind(), fastdelegate::FastDelegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::bind(), and fastdelegate::FastDelegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::bind().
template<class GenericMemFunc, class StaticFuncPtr, class UnvoidStaticFuncPtr> template<class DerivedClass > void fastdelegate::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::CopyFrom (DerivedClass * pParent, const DelegateMemento & right) inline
Definition at line 759 of file FastDelegate.h.
Referenced by fastdelegate::FastDelegate0< RetType >::FastDelegate0(), fastdelegate::FastDelegate1< Param1, RetType >::FastDelegate1(), fastdelegate::FastDelegate2< Param1, Param2, RetType >::FastDelegate2(), fastdelegate::FastDelegate3< Param1, Param2, Param3, RetType >::FastDelegate3(), fastdelegate::FastDelegate4< Param1, Param2, Param3, Param4, RetType >::FastDelegate4(), fastdelegate::FastDelegate5< Param1, Param2, Param3, Param4, Param5, RetType >::FastDelegate5(), fastdelegate::FastDelegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::FastDelegate6(), fastdelegate::FastDelegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::FastDelegate7(), fastdelegate::FastDelegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::FastDelegate8(), fastdelegate::FastDelegate0< RetType >::operator=(), fastdelegate::FastDelegate1< Param1, RetType >::operator=(), fastdelegate::FastDelegate2< Param1, Param2, RetType >::operator=(), fastdelegate::FastDelegate3< Param1, Param2, Param3, RetType >::operator=(), fastdelegate::FastDelegate4< Param1, Param2, Param3, Param4, RetType >::operator=(), fastdelegate::FastDelegate5< Param1, Param2, Param3, Param4, Param5, RetType >::operator=(), fastdelegate::FastDelegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator=(), fastdelegate::FastDelegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::operator=(), fastdelegate::FastDelegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator=(), fastdelegate::FastDelegate0< RetType >::SetMemento(), fastdelegate::FastDelegate1< Param1, RetType >::SetMemento(), fastdelegate::FastDelegate2< Param1, Param2, RetType >::SetMemento(), fastdelegate::FastDelegate3< Param1, Param2, Param3, RetType >::SetMemento(), fastdelegate::FastDelegate4< Param1, Param2, Param3, Param4, RetType >::SetMemento(), fastdelegate::FastDelegate5< Param1, Param2, Param3, Param4, Param5, RetType >::SetMemento(), fastdelegate::FastDelegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::SetMemento(), fastdelegate::FastDelegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::SetMemento(), and fastdelegate::FastDelegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::SetMemento().
template<class GenericMemFunc, class StaticFuncPtr, class UnvoidStaticFuncPtr> GenericMemFunc fastdelegate::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetClosureMemPtr () const inline
Definition at line 702 of file FastDelegate.h.
Referenced by fastdelegate::FastDelegate0< RetType >::operator()(), fastdelegate::FastDelegate1< Param1, RetType >::operator()(), fastdelegate::FastDelegate2< Param1, Param2, RetType >::operator()(), fastdelegate::FastDelegate3< Param1, Param2, Param3, RetType >::operator()(), fastdelegate::FastDelegate4< Param1, Param2, Param3, Param4, RetType >::operator()(), fastdelegate::FastDelegate5< Param1, Param2, Param3, Param4, Param5, RetType >::operator()(), fastdelegate::FastDelegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator()(), fastdelegate::FastDelegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::operator()(), and fastdelegate::FastDelegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator()().
template<class GenericMemFunc, class StaticFuncPtr, class UnvoidStaticFuncPtr> GenericClass* fastdelegate::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetClosureThis () const inline
Definition at line 701 of file FastDelegate.h.
Referenced by fastdelegate::FastDelegate0< RetType >::operator()(), fastdelegate::FastDelegate1< Param1, RetType >::operator()(), fastdelegate::FastDelegate2< Param1, Param2, RetType >::operator()(), fastdelegate::FastDelegate3< Param1, Param2, Param3, RetType >::operator()(), fastdelegate::FastDelegate4< Param1, Param2, Param3, Param4, RetType >::operator()(), fastdelegate::FastDelegate5< Param1, Param2, Param3, Param4, Param5, RetType >::operator()(), fastdelegate::FastDelegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator()(), fastdelegate::FastDelegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::operator()(), and fastdelegate::FastDelegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator()().
template<class GenericMemFunc, class StaticFuncPtr, class UnvoidStaticFuncPtr> UnvoidStaticFuncPtr fastdelegate::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::GetStaticFunction () const inline
Definition at line 792 of file FastDelegate.h.
Referenced by fastdelegate::FastDelegate0< RetType >::InvokeStaticFunction(), fastdelegate::FastDelegate1< Param1, RetType >::InvokeStaticFunction(), fastdelegate::FastDelegate2< Param1, Param2, RetType >::InvokeStaticFunction(), fastdelegate::FastDelegate3< Param1, Param2, Param3, RetType >::InvokeStaticFunction(), fastdelegate::FastDelegate4< Param1, Param2, Param3, Param4, RetType >::InvokeStaticFunction(), fastdelegate::FastDelegate5< Param1, Param2, Param3, Param4, Param5, RetType >::InvokeStaticFunction(), fastdelegate::FastDelegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::InvokeStaticFunction(), fastdelegate::FastDelegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::InvokeStaticFunction(), fastdelegate::FastDelegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::InvokeStaticFunction(), and fastdelegate::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::IsEqualToStaticFuncPtr().
template<class GenericMemFunc, class StaticFuncPtr, class UnvoidStaticFuncPtr> bool fastdelegate::detail::ClosurePtr< GenericMemFunc, StaticFuncPtr, UnvoidStaticFuncPtr >::IsEqualToStaticFuncPtr (StaticFuncPtr funcptr) inline
Definition at line 802 of file FastDelegate.h.
Referenced by fastdelegate::FastDelegate0< RetType >::operator!=(), fastdelegate::FastDelegate1< Param1, RetType >::operator!=(), fastdelegate::FastDelegate2< Param1, Param2, RetType >::operator!=(), fastdelegate::FastDelegate3< Param1, Param2, Param3, RetType >::operator!=(), fastdelegate::FastDelegate4< Param1, Param2, Param3, Param4, RetType >::operator!=(), fastdelegate::FastDelegate5< Param1, Param2, Param3, Param4, Param5, RetType >::operator!=(), fastdelegate::FastDelegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator!=(), fastdelegate::FastDelegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::operator!=(), fastdelegate::FastDelegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator!=(), fastdelegate::FastDelegate0< RetType >::operator==(), fastdelegate::FastDelegate1< Param1, RetType >::operator==(), fastdelegate::FastDelegate2< Param1, Param2, RetType >::operator==(), fastdelegate::FastDelegate3< Param1, Param2, Param3, RetType >::operator==(), fastdelegate::FastDelegate4< Param1, Param2, Param3, Param4, RetType >::operator==(), fastdelegate::FastDelegate5< Param1, Param2, Param3, Param4, Param5, RetType >::operator==(), fastdelegate::FastDelegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator==(), fastdelegate::FastDelegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::operator==(), and fastdelegate::FastDelegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator==().
The documentation for this class was generated from the following file:
libraries/AP_HAL/utility/FastDelegate.h