APM:Libraries: AP_InertialSensor_LSM9DS0 Class Reference
AP_InertialSensor_LSM9DS0 Class Reference
#include <AP_InertialSensor_LSM9DS0.h>
Public Member Functions
AP_InertialSensor_LSM9DS0 ()
bool update ()
float get_gyro_drift_rate ()
bool wait_for_sample (uint16_t timeout_ms)
float get_delta_time () const
uint16_t error_count (void) const
bool healthy (void) const
bool get_gyro_health (uint8_t instance) const
bool get_accel_health (uint8_t instance) const
Public Member Functions inherited from AP_InertialSensor
AP_InertialSensor ()
void init (Start_style style, Sample_rate sample_rate)
uint8_t register_gyro (void)
uint8_t register_accel (void)
bool calibrate_accel (AP_InertialSensor_UserInteract *interact, float &trim_roll, float &trim_pitch)
bool calibrate_trim (float &trim_roll, float &trim_pitch)
bool calibrating () const
calibrating - returns true if the gyros or accels are currently being calibrated
void init_gyro (void)
const Vector3f & get_gyro (uint8_t i) const
const Vector3f & get_gyro (void) const
void set_gyro (uint8_t instance, const Vector3f &gyro)
const Vector3f & get_gyro_offsets (uint8_t i) const
const Vector3f & get_gyro_offsets (void) const
bool get_delta_angle (uint8_t i, Vector3f &delta_angle) const
bool get_delta_angle (Vector3f &delta_angle) const
bool get_delta_velocity (uint8_t i, Vector3f &delta_velocity) const
bool get_delta_velocity (Vector3f &delta_velocity) const
float get_delta_velocity_dt (uint8_t i) const
float get_delta_velocity () const
const Vector3f & get_accel (uint8_t i) const
const Vector3f & get_accel (void) const
void set_accel (uint8_t instance, const Vector3f &accel)
uint32_t get_gyro_error_count (uint8_t i) const
uint32_t get_accel_error_count (uint8_t i) const
bool get_gyro_health (uint8_t instance) const
bool get_gyro_health (void) const
bool get_gyro_health_all (void) const
uint8_t get_gyro_count (void) const
bool gyro_calibrated_ok (uint8_t instance) const
bool gyro_calibrated_ok_all () const
bool get_accel_health (uint8_t instance) const
bool get_accel_health (void) const
bool get_accel_health_all (void) const
uint8_t get_accel_count (void) const
bool accel_calibrated_ok_all () const
const Vector3f & get_accel_offsets (uint8_t i) const
const Vector3f & get_accel_offsets (void) const
const Vector3f & get_accel_scale (uint8_t i) const
const Vector3f & get_accel_scale (void) const
float get_temperature (uint8_t instance) const
float get_delta_time () const
float get_gyro_drift_rate (void) const
void update (void)
void wait_for_sample (void)
void set_board_orientation (enum Rotation orientation)
Sample_rate get_sample_rate (void) const
uint16_t error_count (void) const
bool healthy (void) const
uint8_t get_primary_accel (void) const
uint8_t get_primary_gyro (void) const
void set_hil_mode (void)
uint8_t get_gyro_filter_hz (void) const
uint8_t get_accel_filter_hz (void) const
void set_dataflash (DataFlash_Class *dataflash)
void set_raw_logging (bool enable)
Protected Member Functions
uint16_t _init_sensor (Sample_rate sample_rate)
Private Member Functions
void _calcgRes (gyro_scale_lsm9ds0 gScl)
void _calcaRes (accel_scale aScl)
void _calcmRes (mag_scale mScl)
void _initGyro ()
void _initAccel ()
void _initMag ()
bool _sample_available ()
void _read_data_transaction_g ()
void _read_data_transaction_xm ()
uint8_t _data_ready ()
void _poll_data (void)
uint8_t _register_read_xm (uint8_t reg)
uint8_t _register_read_g (uint8_t reg)
void _register_write_xm (uint8_t reg, uint8_t val)
void _register_write_g (uint8_t reg, uint8_t val)
bool _hardware_init (Sample_rate sample_rate)
void _set_filter_register (uint8_t filter_hz, uint8_t default_filter)
void _dump_registers (void)
Private Attributes
AP_HAL::DigitalSource * _drdy_pin_a
AP_HAL::DigitalSource * _drdy_pin_m
AP_HAL::DigitalSource * _drdy_pin_g
uint32_t _gRes
uint32_t _aRes
uint32_t _mRes
AP_HAL::SPIDeviceDriver * _spi
AP_HAL::Semaphore * _spi_sem
uint16_t _num_samples_g
uint16_t _num_samples_xm
uint32_t _last_sample_time_micros
bool _initialised
int16_t _lsm9ds0_product_id
uint8_t _sample_shift
uint8_t _last_filter_hz
uint16_t _error_count
Vector3l _accel_sum
Vector3l _gyro_sum
Vector3l _mag_sum
volatile int16_t _sum_count_g
volatile int16_t _sum_count_xm
Static Private Attributes
static const float _gyro_scale
Additional Inherited Members
Public Types inherited from AP_InertialSensor
enum Start_style { COLD_START = 0, WARM_START }
enum Sample_rate { RATE_50HZ = 50, RATE_100HZ = 100, RATE_200HZ = 200, RATE_400HZ = 400 }
Static Public Attributes inherited from AP_InertialSensor
static const struct
AP_Param::GroupInfo var_info []
Detailed Description
Definition at line 95 of file AP_InertialSensor_LSM9DS0.h.
Constructor & Destructor Documentation
AP_InertialSensor_LSM9DS0::AP_InertialSensor_LSM9DS0 ()
Definition at line 119 of file AP_InertialSensor_LSM9DS0.cpp.
Member Function Documentation
void AP_InertialSensor_LSM9DS0::_calcaRes (accel_scale aScl) private
Definition at line 767 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _hardware_init().
void AP_InertialSensor_LSM9DS0::_calcgRes (gyro_scale_lsm9ds0 gScl) private
Definition at line 748 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _hardware_init().
void AP_InertialSensor_LSM9DS0::_calcmRes (mag_scale mScl) private
Definition at line 776 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _hardware_init().
uint8_t AP_InertialSensor_LSM9DS0::_data_ready () private
Return true if the LSM9DS0 has new data available for reading.
We use the data ready pin if it is available. Returns 1 if LSM9DS0 gyro is available, 2 if either the mag or the accel is available and 3 if both are.
TODO, read the status register.
Definition at line 355 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _init_sensor(), and _poll_data().
void AP_InertialSensor_LSM9DS0::_dump_registers (void) private
Definition at line 788 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _init_sensor().
bool AP_InertialSensor_LSM9DS0::_hardware_init (Sample_rate sample_rate) private
Definition at line 283 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _init_sensor().
uint16_t AP_InertialSensor_LSM9DS0::_init_sensor (Sample_rate sample_rate) protected
Definition at line 129 of file AP_InertialSensor_LSM9DS0.cpp.
void AP_InertialSensor_LSM9DS0::_initAccel () private
Definition at line 640 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _hardware_init().
void AP_InertialSensor_LSM9DS0::_initGyro () private
Definition at line 578 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _hardware_init().
void AP_InertialSensor_LSM9DS0::_initMag () private
Definition at line 689 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _hardware_init().
void AP_InertialSensor_LSM9DS0::_poll_data (void) private
Timer process to poll for new data from the LSM9DS0.
Definition at line 383 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _init_sensor(), and _sample_available().
void AP_InertialSensor_LSM9DS0::_read_data_transaction_g () private
Definition at line 431 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _init_sensor(), and _poll_data().
void AP_InertialSensor_LSM9DS0::_read_data_transaction_xm () private
Definition at line 454 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _init_sensor(), and _poll_data().
uint8_t AP_InertialSensor_LSM9DS0::_register_read_g (uint8_t reg) private
Definition at line 543 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _dump_registers(), _hardware_init(), and _read_data_transaction_g().
uint8_t AP_InertialSensor_LSM9DS0::_register_read_xm (uint8_t reg) private
Definition at line 529 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _dump_registers(), _hardware_init(), and _read_data_transaction_xm().
void AP_InertialSensor_LSM9DS0::_register_write_g (uint8_t reg, uint8_t val) private
Definition at line 568 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _initGyro().
void AP_InertialSensor_LSM9DS0::_register_write_xm (uint8_t reg, uint8_t val) private
Definition at line 558 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by _initAccel(), and _initMag().
bool AP_InertialSensor_LSM9DS0::_sample_available (void) private
Definition at line 523 of file AP_InertialSensor_LSM9DS0.cpp.
Referenced by wait_for_sample().
void AP_InertialSensor_LSM9DS0::_set_filter_register (uint8_t filter_hz, uint8_t default_filter) private
uint16_t AP_InertialSensor_LSM9DS0::error_count (void) const inline
Definition at line 110 of file AP_InertialSensor_LSM9DS0.h.
bool AP_InertialSensor_LSM9DS0::get_accel_health (uint8_t instance) const inline
Definition at line 113 of file AP_InertialSensor_LSM9DS0.h.
float AP_InertialSensor_LSM9DS0::get_delta_time () const
Definition at line 273 of file AP_InertialSensor_LSM9DS0.cpp.
float AP_InertialSensor_LSM9DS0::get_gyro_drift_rate (void)
Definition at line 266 of file AP_InertialSensor_LSM9DS0.cpp.
bool AP_InertialSensor_LSM9DS0::get_gyro_health (uint8_t instance) const inline
Definition at line 112 of file AP_InertialSensor_LSM9DS0.h.
bool AP_InertialSensor_LSM9DS0::healthy (void) const inline
Definition at line 111 of file AP_InertialSensor_LSM9DS0.h.
Referenced by get_accel_health(), and get_gyro_health().
bool AP_InertialSensor_LSM9DS0::update (void)
Definition at line 211 of file AP_InertialSensor_LSM9DS0.cpp.
bool AP_InertialSensor_LSM9DS0::wait_for_sample (uint16_t timeout_ms)
Definition at line 195 of file AP_InertialSensor_LSM9DS0.cpp.
Member Data Documentation
Vector3l AP_InertialSensor_LSM9DS0::_accel_sum private
Definition at line 199 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _read_data_transaction_xm(), and update().
uint32_t AP_InertialSensor_LSM9DS0::_aRes private
Definition at line 122 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _calcaRes(), and update().
AP_HAL::DigitalSource* AP_InertialSensor_LSM9DS0::_drdy_pin_a private
Definition at line 119 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _data_ready(), and _init_sensor().
AP_HAL::DigitalSource* AP_InertialSensor_LSM9DS0::_drdy_pin_g private
Definition at line 121 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _data_ready(), and _init_sensor().
AP_HAL::DigitalSource* AP_InertialSensor_LSM9DS0::_drdy_pin_m private
Definition at line 120 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _init_sensor().
uint16_t AP_InertialSensor_LSM9DS0::_error_count private
Definition at line 195 of file AP_InertialSensor_LSM9DS0.h.
Referenced by error_count(), and healthy().
uint32_t AP_InertialSensor_LSM9DS0::_gRes private
Definition at line 122 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _calcgRes(), and update().
const float AP_InertialSensor_LSM9DS0::_gyro_scale static private
Definition at line 179 of file AP_InertialSensor_LSM9DS0.h.
Vector3l AP_InertialSensor_LSM9DS0::_gyro_sum private
Definition at line 200 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _read_data_transaction_g(), _read_data_transaction_xm(), and update().
bool AP_InertialSensor_LSM9DS0::_initialised private
Definition at line 184 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _init_sensor().
uint8_t AP_InertialSensor_LSM9DS0::_last_filter_hz private
Definition at line 191 of file AP_InertialSensor_LSM9DS0.h.
uint32_t AP_InertialSensor_LSM9DS0::_last_sample_time_micros private
Definition at line 181 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _init_sensor(), and _poll_data().
int16_t AP_InertialSensor_LSM9DS0::_lsm9ds0_product_id private
Definition at line 185 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _init_sensor().
Vector3l AP_InertialSensor_LSM9DS0::_mag_sum private
Definition at line 201 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _read_data_transaction_xm().
uint32_t AP_InertialSensor_LSM9DS0::_mRes private
Definition at line 122 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _calcmRes().
uint16_t AP_InertialSensor_LSM9DS0::_num_samples_g private
Definition at line 177 of file AP_InertialSensor_LSM9DS0.h.
Referenced by get_delta_time(), and update().
uint16_t AP_InertialSensor_LSM9DS0::_num_samples_xm private
Definition at line 178 of file AP_InertialSensor_LSM9DS0.h.
Referenced by update().
uint8_t AP_InertialSensor_LSM9DS0::_sample_shift private
Definition at line 188 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _hardware_init(), and _sample_available().
AP_HAL::SPIDeviceDriver* AP_InertialSensor_LSM9DS0::_spi private
Definition at line 174 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _hardware_init(), _init_sensor(), _register_read_g(), _register_read_xm(), _register_write_g(), and _register_write_xm().
AP_HAL::Semaphore* AP_InertialSensor_LSM9DS0::_spi_sem private
Definition at line 175 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _hardware_init(), _init_sensor(), and _poll_data().
volatile int16_t AP_InertialSensor_LSM9DS0::_sum_count_g private
Definition at line 202 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _read_data_transaction_g(), _sample_available(), and update().
volatile int16_t AP_InertialSensor_LSM9DS0::_sum_count_xm private
Definition at line 203 of file AP_InertialSensor_LSM9DS0.h.
Referenced by _read_data_transaction_xm(), _sample_available(), and update().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/LSM9DS0/AP_InertialSensor_LSM9DS0.h
libraries/AP_InertialSensor/LSM9DS0/AP_InertialSensor_LSM9DS0.cpp