APM:Libraries: LowPassFilterFloat Class Reference
LowPassFilterFloat Class Reference
#include <LowPassFilter.h>
Public Member Functions
LowPassFilterFloat ()
LowPassFilterFloat (float cutoff_freq)
float apply (float sample, float dt)
float get () const
void reset (float value)
Public Member Functions inherited from LowPassFilter
LowPassFilter ()
LowPassFilter (float cutoff_freq)
void set_cutoff_frequency (float cutoff_freq)
float get_cutoff_freq (void) const
Private Attributes
DigitalLPF _filter
Additional Inherited Members
Protected Attributes inherited from LowPassFilter
float _cutoff_freq
Detailed Description
Definition at line 92 of file LowPassFilter.h.
Constructor & Destructor Documentation
LowPassFilterFloat::LowPassFilterFloat () inline
Definition at line 95 of file LowPassFilter.h.
LowPassFilterFloat::LowPassFilterFloat (float cutoff_freq) inline
Definition at line 98 of file LowPassFilter.h.
Member Function Documentation
float LowPassFilterFloat::apply (float sample, float dt) inline
Definition at line 101 of file LowPassFilter.h.
Referenced by loop(), AC_AttitudeControl_Heli::rate_bf_to_motor_roll_pitch(), AC_AttitudeControl_Heli::rate_bf_to_motor_yaw(), AC_PosControl::rate_to_accel_z(), AP_Motors::update_lift_max_from_batt_voltage(), and AP_Motors::update_throttle_filter().
float LowPassFilterFloat::get () const inline
Definition at line 105 of file LowPassFilter.h.
Referenced by AP_Motors::apply_thrust_curve_and_volt_scaling(), AP_Motors::get_batt_voltage_filt(), and AP_Motors::update_throttle_filter().
void LowPassFilterFloat::reset (float value) inline
Definition at line 109 of file LowPassFilter.h.
Referenced by AP_Motors::AP_Motors(), loop(), AC_PosControl::rate_to_accel_z(), AP_Motors::update_lift_max_from_batt_voltage(), and AP_Motors::update_throttle_filter().
Member Data Documentation
DigitalLPF LowPassFilterFloat::_filter private
Definition at line 113 of file LowPassFilter.h.
Referenced by apply(), get(), and reset().
The documentation for this class was generated from the following file:
libraries/Filter/LowPassFilter.h