APM:Libraries: JSBSim Class Reference
JSBSim Class Reference
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
#include <SIM_JSBSim.h>
Public Member Functions
JSBSim (const char *home_str, const char *frame_str)
void update (const struct sitl_input &input)
Public Member Functions inherited from Aircraft
Aircraft (const char *home_str, const char *frame_str)
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
void set_speedup (float speedup)
void set_instance (uint8_t _instance)
void fill_fdm (struct sitl_fdm &fdm) const
Static Public Member Functions
static Aircraft * create (const char *home_str, const char *frame_str)
Private Types
enum { FRAME_NORMAL, FRAME_ELEVON, FRAME_VTAIL }
Private Member Functions
bool create_templates (void)
bool start_JSBSim (void)
bool open_control_socket (void)
bool open_fdm_socket (void)
void send_servos (const struct sitl_input &input)
void recv_fdm (const struct sitl_input &input)
void check_stdout (void)
bool expect (const char *str)
Private Attributes
SocketAPM sock_control
SocketAPM sock_fgfdm
bool initialised
uint16_t control_port
uint16_t fdm_port
char * autotest_dir
char * jsbsim_script
char * jsbsim_fgout
int jsbsim_stdout
bool created_templates
bool started_jsbsim
bool opened_control_socket
bool opened_fdm_socket
enum JSBSim:: { ... } frame
Additional Inherited Members
Protected Member Functions inherited from Aircraft
bool on_ground (const Vector3f &pos) const
void update_position (void)
void set_yaw_degrees (float yaw_degrees)
void time_advance (float deltat)
void setup_frame_time (float rate, float speedup)
void adjust_frame_time (float rate)
void sync_frame_time (void)
void add_noise (float throttle)
uint64_t get_wall_time_us (void) const
double rand_normal (double mean, double stddev)
Protected Attributes inherited from Aircraft
Location home
Location location
float ground_level
float frame_height
Matrix3f dcm
Vector3f gyro
Vector3f velocity_ef
Vector3f position
float mass
Vector3f accel_body
uint64_t time_now_us
const float gyro_noise
const float accel_noise
float rate_hz
float achieved_rate_hz
float target_speedup
uint64_t frame_time_us
float scaled_frame_time_us
uint64_t last_wall_time_us
uint8_t instance
Detailed Description
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 29 of file SIM_JSBSim.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
FRAME_NORMAL
FRAME_ELEVON
FRAME_VTAIL
Definition at line 63 of file SIM_JSBSim.h.
Constructor & Destructor Documentation
JSBSim::JSBSim (const char * home_str, const char * frame_str)
Definition at line 40 of file SIM_JSBSim.cpp.
Referenced by create().
Member Function Documentation
void JSBSim::check_stdout (void) private
Definition at line 235 of file SIM_JSBSim.cpp.
Referenced by open_fdm_socket(), recv_fdm(), and start_JSBSim().
static Aircraft* JSBSim::create (const char * home_str, const char * frame_str) inline static
Definition at line 38 of file SIM_JSBSim.h.
bool JSBSim::create_templates (void) private
Definition at line 65 of file SIM_JSBSim.cpp.
Referenced by update().
bool JSBSim::expect (const char * str) private
Definition at line 249 of file SIM_JSBSim.cpp.
Referenced by start_JSBSim().
bool JSBSim::open_control_socket (void) private
Definition at line 272 of file SIM_JSBSim.cpp.
Referenced by start_JSBSim(), and update().
bool JSBSim::open_fdm_socket (void) private
Definition at line 292 of file SIM_JSBSim.cpp.
Referenced by start_JSBSim(), and update().
void JSBSim::recv_fdm (const struct sitl_input & input) private
Definition at line 370 of file SIM_JSBSim.cpp.
Referenced by update().
void JSBSim::send_servos (const struct sitl_input & input) private
Definition at line 311 of file SIM_JSBSim.cpp.
Referenced by recv_fdm(), and update().
bool JSBSim::start_JSBSim (void) private
Definition at line 161 of file SIM_JSBSim.cpp.
Referenced by update().
void JSBSim::update (const struct sitl_input & input) virtual
Implements Aircraft.
Definition at line 401 of file SIM_JSBSim.cpp.
Member Data Documentation
char* JSBSim::autotest_dir private
Definition at line 53 of file SIM_JSBSim.h.
Referenced by create_templates(), and start_JSBSim().
uint16_t JSBSim::control_port private
Definition at line 51 of file SIM_JSBSim.h.
Referenced by create_templates(), and open_control_socket().
bool JSBSim::created_templates private
Definition at line 58 of file SIM_JSBSim.h.
Referenced by create_templates().
uint16_t JSBSim::fdm_port private
Definition at line 52 of file SIM_JSBSim.h.
Referenced by create_templates(), and open_fdm_socket().
enum { ... } JSBSim::frame
Referenced by JSBSim(), and send_servos().
bool JSBSim::initialised private
Definition at line 49 of file SIM_JSBSim.h.
Referenced by update().
char* JSBSim::jsbsim_fgout private
Definition at line 55 of file SIM_JSBSim.h.
Referenced by create_templates(), and start_JSBSim().
char* JSBSim::jsbsim_script private
Definition at line 54 of file SIM_JSBSim.h.
Referenced by create_templates(), and start_JSBSim().
int JSBSim::jsbsim_stdout private
Definition at line 56 of file SIM_JSBSim.h.
Referenced by check_stdout(), expect(), and start_JSBSim().
bool JSBSim::opened_control_socket private
Definition at line 60 of file SIM_JSBSim.h.
Referenced by open_control_socket().
bool JSBSim::opened_fdm_socket private
Definition at line 61 of file SIM_JSBSim.h.
Referenced by open_fdm_socket().
SocketAPM JSBSim::sock_control private
Definition at line 44 of file SIM_JSBSim.h.
Referenced by open_control_socket(), and send_servos().
SocketAPM JSBSim::sock_fgfdm private
Definition at line 47 of file SIM_JSBSim.h.
Referenced by open_fdm_socket(), and recv_fdm().
bool JSBSim::started_jsbsim private
Definition at line 59 of file SIM_JSBSim.h.
Referenced by start_JSBSim().
The documentation for this class was generated from the following files:
libraries/SITL/SIM_JSBSim.h
libraries/SITL/SIM_JSBSim.cpp