APM:Libraries: Linux::LinuxScheduler Class Reference
Linux::LinuxScheduler Class Reference
#include <Scheduler.h>
Public Member Functions
LinuxScheduler ()
void init (void *machtnichts)
void delay (uint16_t ms)
uint32_t millis ()
uint32_t micros ()
uint64_t millis64 ()
uint64_t micros64 ()
void delay_microseconds (uint16_t us)
void register_delay_callback (AP_HAL::Proc, uint16_t min_time_ms)
void register_timer_process (AP_HAL::MemberProc)
void register_io_process (AP_HAL::MemberProc)
void suspend_timer_procs ()
void resume_timer_procs ()
bool in_timerprocess ()
void register_timer_failsafe (AP_HAL::Proc, uint32_t period_us)
void begin_atomic ()
void end_atomic ()
bool system_initializing ()
void system_initialized ()
void panic (const prog_char_t *errormsg)
void reboot (bool hold_in_bootloader)
void stop_clock (uint64_t time_usec)
Public Member Functions inherited from AP_HAL::Scheduler
Scheduler ()
virtual void delay_microseconds_boost (uint16_t us)
virtual void set_timer_speed (uint16_t speed_hz)
Private Types
typedef void *(* pthread_startroutine_t)(void *)
Private Member Functions
void _timer_handler (int signum)
void _microsleep (uint32_t usec)
void _run_timers (bool called_from_timer_thread)
void _run_io (void)
void _create_realtime_thread (pthread_t *ctx, int rtprio, const char *name, pthread_startroutine_t start_routine)
Static Private Member Functions
static void * _timer_thread (void *arg)
static void * _io_thread (void *arg)
static void * _rcin_thread (void *arg)
static void * _uart_thread (void *arg)
static void * _tonealarm_thread (void *arg)
Private Attributes
struct timespec _sketch_start_time
AP_HAL::Proc _delay_cb
uint16_t _min_delay_cb_ms
AP_HAL::Proc _failsafe
bool _initialized
volatile bool _timer_pending
AP_HAL::MemberProc _timer_proc [LINUX_SCHEDULER_MAX_TIMER_PROCS]
uint8_t _num_timer_procs
volatile bool _in_timer_proc
AP_HAL::MemberProc _io_proc [LINUX_SCHEDULER_MAX_IO_PROCS]
uint8_t _num_io_procs
volatile bool _in_io_proc
volatile bool _timer_event_missed
pthread_t _timer_thread_ctx
pthread_t _io_thread_ctx
pthread_t _rcin_thread_ctx
pthread_t _uart_thread_ctx
pthread_t _tonealarm_thread_ctx
uint64_t stopped_clock_usec
LinuxSemaphore _timer_semaphore
LinuxSemaphore _io_semaphore
Detailed Description
Definition at line 15 of file Scheduler.h.
Member Typedef Documentation
typedef void*(* Linux::LinuxScheduler::pthread_startroutine_t)(void *) private
Definition at line 17 of file Scheduler.h.
Constructor & Destructor Documentation
LinuxScheduler::LinuxScheduler ()
Definition at line 30 of file Scheduler.cpp.
Member Function Documentation
void LinuxScheduler::_create_realtime_thread (pthread_t * ctx, int rtprio, const char * name, pthread_startroutine_t start_routine) private
Definition at line 33 of file Scheduler.cpp.
Referenced by init().
void * LinuxScheduler::_io_thread (void * arg) static private
Definition at line 360 of file Scheduler.cpp.
Referenced by init().
void LinuxScheduler::_microsleep (uint32_t usec) private
Definition at line 117 of file Scheduler.cpp.
Referenced by _io_thread(), _rcin_thread(), _timer_thread(), _tonealarm_thread(), _uart_thread(), delay(), and delay_microseconds().
void * LinuxScheduler::_rcin_thread (void * arg) static private
Definition at line 310 of file Scheduler.cpp.
Referenced by init().
void LinuxScheduler::_run_io (void) private
Definition at line 294 of file Scheduler.cpp.
Referenced by _io_thread(), and stop_clock().
void LinuxScheduler::_run_timers (bool called_from_timer_thread) private
Definition at line 241 of file Scheduler.cpp.
Referenced by _timer_thread().
void Linux::LinuxScheduler::_timer_handler (int signum) private
void * LinuxScheduler::_timer_thread (void * arg) static private
Definition at line 267 of file Scheduler.cpp.
Referenced by init().
void * LinuxScheduler::_tonealarm_thread (void * arg) static private
Definition at line 344 of file Scheduler.cpp.
Referenced by init().
void * LinuxScheduler::_uart_thread (void * arg) static private
Definition at line 325 of file Scheduler.cpp.
Referenced by init().
void LinuxScheduler::begin_atomic ()
Definition at line 392 of file Scheduler.cpp.
void LinuxScheduler::delay (uint16_t ms) virtual
Implements AP_HAL::Scheduler.
Definition at line 125 of file Scheduler.cpp.
void LinuxScheduler::delay_microseconds (uint16_t us) virtual
Implements AP_HAL::Scheduler.
Definition at line 177 of file Scheduler.cpp.
void LinuxScheduler::end_atomic ()
Definition at line 395 of file Scheduler.cpp.
bool LinuxScheduler::in_timerprocess () virtual
Implements AP_HAL::Scheduler.
Definition at line 387 of file Scheduler.cpp.
void LinuxScheduler::init (void * machtnichts) virtual
Implements AP_HAL::Scheduler.
Definition at line 65 of file Scheduler.cpp.
uint32_t LinuxScheduler::micros () virtual
Implements AP_HAL::Scheduler.
Definition at line 172 of file Scheduler.cpp.
uint64_t LinuxScheduler::micros64 () virtual
Implements AP_HAL::Scheduler.
Definition at line 155 of file Scheduler.cpp.
Referenced by _timer_thread(), and micros().
uint32_t LinuxScheduler::millis () virtual
Implements AP_HAL::Scheduler.
Definition at line 167 of file Scheduler.cpp.
uint64_t LinuxScheduler::millis64 () virtual
Implements AP_HAL::Scheduler.
Definition at line 143 of file Scheduler.cpp.
Referenced by delay(), and millis().
void LinuxScheduler::panic (const prog_char_t * errormsg) virtual
Implements AP_HAL::Scheduler.
Definition at line 379 of file Scheduler.cpp.
Referenced by _create_realtime_thread(), and system_initialized().
void LinuxScheduler::reboot (bool hold_in_bootloader) virtual
Implements AP_HAL::Scheduler.
Definition at line 410 of file Scheduler.cpp.
void LinuxScheduler::register_delay_callback (AP_HAL::Proc proc, uint16_t min_time_ms) virtual
Implements AP_HAL::Scheduler.
Definition at line 185 of file Scheduler.cpp.
void LinuxScheduler::register_io_process (AP_HAL::MemberProc proc) virtual
Implements AP_HAL::Scheduler.
Definition at line 208 of file Scheduler.cpp.
void LinuxScheduler::register_timer_failsafe (AP_HAL::Proc failsafe, uint32_t period_us) virtual
Implements AP_HAL::Scheduler.
Definition at line 224 of file Scheduler.cpp.
void LinuxScheduler::register_timer_process (AP_HAL::MemberProc proc) virtual
Implements AP_HAL::Scheduler.
Definition at line 192 of file Scheduler.cpp.
void LinuxScheduler::resume_timer_procs () virtual
Implements AP_HAL::Scheduler.
Definition at line 236 of file Scheduler.cpp.
void LinuxScheduler::stop_clock (uint64_t time_usec) virtual
optional function to stop clock at a given time, used by log replay
Reimplemented from AP_HAL::Scheduler.
Definition at line 415 of file Scheduler.cpp.
void LinuxScheduler::suspend_timer_procs () virtual
Implements AP_HAL::Scheduler.
Definition at line 229 of file Scheduler.cpp.
void LinuxScheduler::system_initialized () virtual
Implements AP_HAL::Scheduler.
Definition at line 402 of file Scheduler.cpp.
bool LinuxScheduler::system_initializing () virtual
Implements AP_HAL::Scheduler.
Definition at line 398 of file Scheduler.cpp.
Referenced by _io_thread(), _rcin_thread(), _timer_thread(), _tonealarm_thread(), and _uart_thread().
Member Data Documentation
AP_HAL::Proc Linux::LinuxScheduler::_delay_cb private
Definition at line 56 of file Scheduler.h.
Referenced by delay(), and register_delay_callback().
AP_HAL::Proc Linux::LinuxScheduler::_failsafe private
Definition at line 59 of file Scheduler.h.
Referenced by _run_timers(), and register_timer_failsafe().
volatile bool Linux::LinuxScheduler::_in_io_proc private
Definition at line 70 of file Scheduler.h.
volatile bool Linux::LinuxScheduler::_in_timer_proc private
Definition at line 66 of file Scheduler.h.
Referenced by _run_timers(), and in_timerprocess().
bool Linux::LinuxScheduler::_initialized private
Definition at line 61 of file Scheduler.h.
Referenced by system_initialized(), and system_initializing().
AP_HAL::MemberProc Linux::LinuxScheduler::_io_proc[LINUX_SCHEDULER_MAX_IO_PROCS] private
Definition at line 68 of file Scheduler.h.
Referenced by _run_io(), and register_io_process().
LinuxSemaphore Linux::LinuxScheduler::_io_semaphore private
Definition at line 94 of file Scheduler.h.
Referenced by _run_io().
pthread_t Linux::LinuxScheduler::_io_thread_ctx private
Definition at line 75 of file Scheduler.h.
Referenced by init().
uint16_t Linux::LinuxScheduler::_min_delay_cb_ms private
Definition at line 57 of file Scheduler.h.
Referenced by delay(), and register_delay_callback().
uint8_t Linux::LinuxScheduler::_num_io_procs private
Definition at line 69 of file Scheduler.h.
Referenced by _run_io(), and register_io_process().
uint8_t Linux::LinuxScheduler::_num_timer_procs private
Definition at line 65 of file Scheduler.h.
Referenced by _run_timers(), and register_timer_process().
pthread_t Linux::LinuxScheduler::_rcin_thread_ctx private
Definition at line 76 of file Scheduler.h.
Referenced by init().
struct timespec Linux::LinuxScheduler::_sketch_start_time private
Definition at line 52 of file Scheduler.h.
Referenced by init(), micros64(), and millis64().
volatile bool Linux::LinuxScheduler::_timer_event_missed private
Definition at line 72 of file Scheduler.h.
volatile bool Linux::LinuxScheduler::_timer_pending private
Definition at line 62 of file Scheduler.h.
AP_HAL::MemberProc Linux::LinuxScheduler::_timer_proc[LINUX_SCHEDULER_MAX_TIMER_PROCS] private
Definition at line 64 of file Scheduler.h.
Referenced by _run_timers(), and register_timer_process().
LinuxSemaphore Linux::LinuxScheduler::_timer_semaphore private
Definition at line 93 of file Scheduler.h.
Referenced by _run_timers(), resume_timer_procs(), and suspend_timer_procs().
pthread_t Linux::LinuxScheduler::_timer_thread_ctx private
Definition at line 74 of file Scheduler.h.
Referenced by init().
pthread_t Linux::LinuxScheduler::_tonealarm_thread_ctx private
Definition at line 78 of file Scheduler.h.
Referenced by init().
pthread_t Linux::LinuxScheduler::_uart_thread_ctx private
Definition at line 77 of file Scheduler.h.
Referenced by init().
uint64_t Linux::LinuxScheduler::stopped_clock_usec private
Definition at line 91 of file Scheduler.h.
Referenced by delay(), delay_microseconds(), micros64(), millis64(), and stop_clock().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/Scheduler.h
libraries/AP_HAL_Linux/Scheduler.cpp