APM:Libraries: Quaternion Class Reference
Quaternion Class Reference
#include <quaternion.h>
Public Member Functions
Quaternion ()
Quaternion (const float _q1, const float _q2, const float _q3, const float _q4)
void operator() (const float _q1, const float _q2, const float _q3, const float _q4)
bool is_nan (void) const
void rotation_matrix (Matrix3f &m) const
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
void from_rotation_matrix (const Matrix3f &m)
void earth_to_body (Vector3f &v) const
void from_euler (float roll, float pitch, float yaw)
void from_vector312 (float roll, float pitch, float yaw)
void to_axis_angle (Vector3f &v)
void from_axis_angle (Vector3f v)
void from_axis_angle (const Vector3f &axis, float theta)
void rotate (const Vector3f &v)
void from_axis_angle_fast (Vector3f v)
void from_axis_angle_fast (const Vector3f &axis, float theta)
void rotate_fast (const Vector3f &v)
float get_euler_roll () const
float get_euler_pitch () const
float get_euler_yaw () const
void to_euler (float &roll, float &pitch, float &yaw) const
void to_vector312 (float &roll, float &pitch, float &yaw) const
float length (void) const
void normalize ()
void initialise ()
Quaternion inverse (void) const
float & operator[] (uint8_t i)
const float & operator[] (uint8_t i) const
Quaternion operator* (const Quaternion &v) const
Quaternion & operator*= (const Quaternion &v)
Quaternion operator/ (const Quaternion &v) const
Public Attributes
float q1
float q2
float q3
float q4
Detailed Description
Definition at line 28 of file quaternion.h.
Constructor & Destructor Documentation
Quaternion::Quaternion () inline
Definition at line 35 of file quaternion.h.
Referenced by inverse().
Quaternion::Quaternion (const float _q1, const float _q2, const float _q3, const float _q4) inline
Definition at line 40 of file quaternion.h.
Member Function Documentation
void Quaternion::earth_to_body (Vector3f & v) const
Definition at line 95 of file quaternion.cpp.
Referenced by test_frame_transforms().
void Quaternion::from_axis_angle (Vector3f v)
Definition at line 142 of file quaternion.cpp.
Referenced by rotate(), and NavEKF::UpdateStrapdownEquationsNED().
void Quaternion::from_axis_angle (const Vector3f & axis, float theta)
Definition at line 153 of file quaternion.cpp.
void Quaternion::from_axis_angle_fast (Vector3f v)
Definition at line 181 of file quaternion.cpp.
void Quaternion::from_axis_angle_fast (const Vector3f & axis, float theta)
Definition at line 191 of file quaternion.cpp.
void Quaternion::from_euler (float roll, float pitch, float yaw)
Definition at line 103 of file quaternion.cpp.
Referenced by NavEKF::alignYawGPS(), NavEKF::calcQuatAndFieldStates(), test_conversion(), test_frame_transforms(), and test_quaternion().
void Quaternion::from_rotation_matrix (const Matrix3f & m)
Definition at line 49 of file quaternion.cpp.
Referenced by from_vector312(), and test_quaternion().
void Quaternion::from_vector312 (float roll, float pitch, float yaw)
Definition at line 119 of file quaternion.cpp.
float Quaternion::get_euler_pitch () const
Definition at line 236 of file quaternion.cpp.
Referenced by to_euler().
float Quaternion::get_euler_roll () const
Definition at line 230 of file quaternion.cpp.
Referenced by to_euler().
float Quaternion::get_euler_yaw () const
Definition at line 242 of file quaternion.cpp.
Referenced by to_euler().
void Quaternion::initialise () inline
Definition at line 102 of file quaternion.h.
Referenced by NavEKF::UpdateFilter().
Quaternion Quaternion::inverse (void) const
Definition at line 275 of file quaternion.cpp.
bool Quaternion::is_nan (void) const inline
Definition at line 51 of file quaternion.h.
Referenced by NavEKF::getFilterFaults(), and NavEKF::getFilterStatus().
float Quaternion::length (void) const
Definition at line 270 of file quaternion.cpp.
Referenced by normalize().
void Quaternion::normalize (void)
Definition at line 280 of file quaternion.cpp.
Referenced by SmallEKF::alignHeading(), NavEKF::FuseAirspeed(), SmallEKF::fuseCompass(), NavEKF::FuseMagnetometer(), NavEKF::FuseOptFlow(), NavEKF::FuseSideslip(), SmallEKF::fuseVelocity(), NavEKF::FuseVelPosNED(), SmallEKF::predictStates(), test_frame_transforms(), and NavEKF::UpdateStrapdownEquationsNED().
void Quaternion::operator() (const float _q1, const float _q2, const float _q3, const float _q4) inline
Definition at line 45 of file quaternion.h.
Quaternion Quaternion::operator* (const Quaternion & v) const
Definition at line 293 of file quaternion.cpp.
Quaternion & Quaternion::operator*= (const Quaternion & v)
Definition at line 313 of file quaternion.cpp.
Quaternion Quaternion::operator/ (const Quaternion & v) const
Definition at line 332 of file quaternion.cpp.
float& Quaternion::operator[] (uint8_t i) inline
Definition at line 107 of file quaternion.h.
const float& Quaternion::operator[] (uint8_t i) const inline
Definition at line 115 of file quaternion.h.
void Quaternion::rotate (const Vector3f & v)
Definition at line 166 of file quaternion.cpp.
void Quaternion::rotate_fast (const Vector3f & v)
Definition at line 202 of file quaternion.cpp.
void Quaternion::rotation_matrix (Matrix3f & m) const
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 23 of file quaternion.cpp.
Referenced by NavEKF::calcQuatAndFieldStates(), earth_to_body(), NavEKF::getRotationBodyToNED(), SmallEKF::predictStates(), NavEKF::quat2Tbn(), test_conversion(), test_quaternion(), to_vector312(), NavEKF::UpdateStrapdownEquationsNED(), and NavEKF::writeOptFlowMeas().
void Quaternion::to_axis_angle (Vector3f & v)
Definition at line 172 of file quaternion.cpp.
void Quaternion::to_euler (float & roll, float & pitch, float & yaw) const
Definition at line 248 of file quaternion.cpp.
Referenced by NavEKF::alignYawGPS(), SmallEKF::getDebug(), NavEKF::getEulerAngles(), test_conversion(), and test_quaternion().
void Quaternion::to_vector312 (float & roll, float & pitch, float & yaw) const
Definition at line 256 of file quaternion.cpp.
Member Data Documentation
float Quaternion::q1
Definition at line 31 of file quaternion.h.
Referenced by from_axis_angle(), from_axis_angle_fast(), from_euler(), from_rotation_matrix(), get_euler_pitch(), get_euler_roll(), get_euler_yaw(), initialise(), inverse(), is_nan(), length(), normalize(), operator()(), operator*(), operator*=(), operator/(), operator[](), Quaternion(), rotate_fast(), rotation_matrix(), and to_axis_angle().
float Quaternion::q2
Definition at line 31 of file quaternion.h.
Referenced by from_axis_angle(), from_axis_angle_fast(), from_euler(), from_rotation_matrix(), get_euler_pitch(), get_euler_roll(), get_euler_yaw(), initialise(), inverse(), is_nan(), length(), normalize(), operator()(), operator*(), operator*=(), operator/(), Quaternion(), rotate_fast(), rotation_matrix(), and to_axis_angle().
float Quaternion::q3
Definition at line 31 of file quaternion.h.
Referenced by from_axis_angle(), from_axis_angle_fast(), from_euler(), from_rotation_matrix(), get_euler_pitch(), get_euler_roll(), get_euler_yaw(), initialise(), inverse(), is_nan(), length(), normalize(), operator()(), operator*(), operator*=(), operator/(), Quaternion(), rotate_fast(), rotation_matrix(), and to_axis_angle().
float Quaternion::q4
Definition at line 31 of file quaternion.h.
Referenced by from_axis_angle(), from_axis_angle_fast(), from_euler(), from_rotation_matrix(), get_euler_pitch(), get_euler_roll(), get_euler_yaw(), initialise(), inverse(), is_nan(), length(), normalize(), operator()(), operator*(), operator*=(), operator/(), Quaternion(), rotate_fast(), rotation_matrix(), and to_axis_angle().
The documentation for this class was generated from the following files:
libraries/AP_Math/quaternion.h
libraries/AP_Math/quaternion.cpp