APM:Libraries: Linux::LinuxStorage_FRAM Class Reference
Linux::LinuxStorage_FRAM Class Reference
#include <Storage_FRAM.h>
Public Member Functions
LinuxStorage_FRAM ()
void _timer_tick (void)
Public Member Functions inherited from Linux::LinuxStorage
LinuxStorage ()
void init (void *machtnichts)
uint8_t read_byte (uint16_t loc)
uint16_t read_word (uint16_t loc)
uint32_t read_dword (uint16_t loc)
void read_block (void *dst, uint16_t src, size_t n)
void write_byte (uint16_t loc, uint8_t value)
void write_word (uint16_t loc, uint16_t value)
void write_dword (uint16_t loc, uint32_t value)
void write_block (uint16_t dst, const void *src, size_t n)
Private Member Functions
int32_t write (uint16_t fd, uint8_t *Buff, uint16_t NumBytes)
int32_t read (uint16_t fd, uint8_t *Buff, uint16_t NumBytes)
uint32_t lseek (uint16_t fd, uint32_t offset, uint16_t whence)
int8_t open ()
int8_t _register_write (uint8_t *src, uint16_t addr, uint16_t len)
int8_t _register_read (uint16_t addr, uint8_t opcode)
int8_t _write_enable (bool enable)
int8_t transaction (uint8_t *tx, uint8_t *rx, uint16_t len)
void _storage_create (void)
void _storage_open (void)
Private Attributes
uint32_t fptr
AP_HAL::SPIDeviceDriver * _spi
AP_HAL::Semaphore * _spi_sem
Additional Inherited Members
Protected Member Functions inherited from Linux::LinuxStorage
void _mark_dirty (uint16_t loc, uint16_t length)
Protected Attributes inherited from Linux::LinuxStorage
int _fd
volatile bool _initialised
uint8_t _buffer [LINUX_STORAGE_SIZE]
volatile uint32_t _dirty_mask
Detailed Description
Definition at line 15 of file Storage_FRAM.h.
Constructor & Destructor Documentation
LinuxStorage_FRAM::LinuxStorage_FRAM ()
Definition at line 24 of file Storage_FRAM.cpp.
Member Function Documentation
int8_t LinuxStorage_FRAM::_register_read (uint16_t addr, uint8_t opcode) private
Definition at line 239 of file Storage_FRAM.cpp.
Referenced by open(), and read().
int8_t LinuxStorage_FRAM::_register_write (uint8_t * src, uint16_t addr, uint16_t len) private
Definition at line 197 of file Storage_FRAM.cpp.
Referenced by open(), and write().
void LinuxStorage_FRAM::_storage_create (void) private virtual
Reimplemented from Linux::LinuxStorage.
Definition at line 29 of file Storage_FRAM.cpp.
Referenced by _storage_open().
void LinuxStorage_FRAM::_storage_open (void) private virtual
Reimplemented from Linux::LinuxStorage.
Definition at line 50 of file Storage_FRAM.cpp.
void LinuxStorage_FRAM::_timer_tick (void) virtual
Reimplemented from Linux::LinuxStorage.
Definition at line 79 of file Storage_FRAM.cpp.
int8_t LinuxStorage_FRAM::_write_enable (bool enable) private
Definition at line 222 of file Storage_FRAM.cpp.
Referenced by _register_write().
uint32_t LinuxStorage_FRAM::lseek (uint16_t fd, uint32_t offset, uint16_t whence) private
Definition at line 190 of file Storage_FRAM.cpp.
Referenced by _timer_tick().
int8_t LinuxStorage_FRAM::open () private
Definition at line 133 of file Storage_FRAM.cpp.
Referenced by _storage_create(), _storage_open(), and _timer_tick().
int32_t LinuxStorage_FRAM::read (uint16_t fd, uint8_t * Buff, uint16_t NumBytes) private
Definition at line 179 of file Storage_FRAM.cpp.
Referenced by _storage_open().
int8_t LinuxStorage_FRAM::transaction (uint8_t * tx, uint8_t * rx, uint16_t len) private
Definition at line 250 of file Storage_FRAM.cpp.
Referenced by _register_read(), _register_write(), and _write_enable().
int32_t LinuxStorage_FRAM::write (uint16_t fd, uint8_t * Buff, uint16_t NumBytes) private
Definition at line 173 of file Storage_FRAM.cpp.
Referenced by _storage_create(), and _timer_tick().
Member Data Documentation
AP_HAL::SPIDeviceDriver* Linux::LinuxStorage_FRAM::_spi private
Definition at line 37 of file Storage_FRAM.h.
Referenced by open(), and transaction().
AP_HAL::Semaphore* Linux::LinuxStorage_FRAM::_spi_sem private
Definition at line 38 of file Storage_FRAM.h.
Referenced by transaction().
uint32_t Linux::LinuxStorage_FRAM::fptr private
Definition at line 22 of file Storage_FRAM.h.
Referenced by lseek(), read(), and write().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/Storage_FRAM.h
libraries/AP_HAL_Linux/Storage_FRAM.cpp