APM:Libraries: AP_HAL_AVR::AVRSemaphore Class Reference
AP_HAL_AVR::AVRSemaphore Class Reference
#include <Semaphores.h>
Public Member Functions
AVRSemaphore ()
bool give ()
bool take (uint32_t timeout_ms)
bool take_nonblocking ()
Protected Member Functions
bool _take_from_mainloop (uint32_t timeout_ms)
bool _take_nonblocking ()
Protected Attributes
volatile bool _taken
Detailed Description
Definition at line 8 of file Semaphores.h.
Constructor & Destructor Documentation
AVRSemaphore::AVRSemaphore ()
Definition at line 18 of file Semaphores.cpp.
Member Function Documentation
bool AVRSemaphore::_take_from_mainloop (uint32_t timeout_ms) protected
Definition at line 46 of file Semaphores.cpp.
Referenced by take(), and take_nonblocking().
bool AVRSemaphore::_take_nonblocking () protected
Definition at line 68 of file Semaphores.cpp.
Referenced by _take_from_mainloop(), and take_nonblocking().
bool AVRSemaphore::give () virtual
Implements AP_HAL::Semaphore.
Definition at line 20 of file Semaphores.cpp.
bool AVRSemaphore::take (uint32_t timeout_ms) virtual
Implements AP_HAL::Semaphore.
Definition at line 29 of file Semaphores.cpp.
bool AVRSemaphore::take_nonblocking () virtual
Implements AP_HAL::Semaphore.
Definition at line 38 of file Semaphores.cpp.
Member Data Documentation
volatile bool AP_HAL_AVR::AVRSemaphore::_taken protected
Definition at line 20 of file Semaphores.h.
Referenced by _take_nonblocking(), and give().
The documentation for this class was generated from the following files:
libraries/AP_HAL_AVR/Semaphores.h
libraries/AP_HAL_AVR/Semaphores.cpp