APM:Libraries: AP_HAL_AVR::AVRSPI2DeviceDriver Class Reference
AP_HAL_AVR::AVRSPI2DeviceDriver Class Reference
#include <SPIDevices.h>
Public Member Functions
AVRSPI2DeviceDriver (AP_HAL_AVR::AVRDigitalSource *cs_pin, uint8_t ucsr2c, uint16_t ubrr2)
void init ()
AP_HAL::Semaphore * get_semaphore ()
void transaction (const uint8_t *tx, uint8_t *rx, uint16_t len)
void cs_assert ()
void cs_release ()
uint8_t transfer (uint8_t data)
void transfer (const uint8_t *data, uint16_t len)
Public Member Functions inherited from AP_HAL::SPIDeviceDriver
virtual void set_bus_speed (enum bus_speed speed)
Private Member Functions
void _cs_assert ()
void _cs_release ()
uint8_t _transfer (uint8_t data)
void _transfer17 (const uint8_t *tx, uint8_t *rx)
Private Attributes
AP_HAL_AVR::AVRDigitalSource * _cs_pin
uint8_t _ucsr2c
uint16_t _ubrr2
Static Private Attributes
static AP_HAL_AVR::AVRSemaphore _semaphore
Additional Inherited Members
Public Types inherited from AP_HAL::SPIDeviceDriver
enum bus_speed { SPI_SPEED_LOW, SPI_SPEED_HIGH }
Detailed Description
Definition at line 52 of file SPIDevices.h.
Constructor & Destructor Documentation
AP_HAL_AVR::AVRSPI2DeviceDriver::AVRSPI2DeviceDriver (AP_HAL_AVR::AVRDigitalSource * cs_pin, uint8_t ucsr2c, uint16_t ubrr2) inline
Definition at line 54 of file SPIDevices.h.
Member Function Documentation
void AVRSPI2DeviceDriver::_cs_assert () inline private
Definition at line 42 of file SPIDevice_SPI2.cpp.
Referenced by cs_assert(), and transaction().
void AVRSPI2DeviceDriver::_cs_release () inline private
Definition at line 54 of file SPIDevice_SPI2.cpp.
Referenced by cs_release(), and transaction().
uint8_t AVRSPI2DeviceDriver::_transfer (uint8_t data) inline private
Definition at line 58 of file SPIDevice_SPI2.cpp.
Referenced by transaction(), and transfer().
void AVRSPI2DeviceDriver::_transfer17 (const uint8_t * tx, uint8_t * rx) private
a specialist transfer function for the APM1 ADC
Definition at line 75 of file SPIDevice_SPI2.cpp.
Referenced by transaction().
void AVRSPI2DeviceDriver::cs_assert () virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 121 of file SPIDevice_SPI2.cpp.
void AVRSPI2DeviceDriver::cs_release () virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 125 of file SPIDevice_SPI2.cpp.
AP_HAL::Semaphore * AVRSPI2DeviceDriver::get_semaphore () virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 38 of file SPIDevice_SPI2.cpp.
void AVRSPI2DeviceDriver::init (void) virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 18 of file SPIDevice_SPI2.cpp.
Referenced by AP_HAL_AVR::APM1SPIDeviceManager::init().
void AVRSPI2DeviceDriver::transaction (const uint8_t * tx, uint8_t * rx, uint16_t len) virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 100 of file SPIDevice_SPI2.cpp.
uint8_t AVRSPI2DeviceDriver::transfer (uint8_t data) virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 129 of file SPIDevice_SPI2.cpp.
void AVRSPI2DeviceDriver::transfer (const uint8_t * data, uint16_t len) virtual
Implements AP_HAL::SPIDeviceDriver.
Definition at line 133 of file SPIDevice_SPI2.cpp.
Member Data Documentation
AP_HAL_AVR::AVRDigitalSource* AP_HAL_AVR::AVRSPI2DeviceDriver::_cs_pin private
Definition at line 83 of file SPIDevices.h.
Referenced by _cs_assert(), _cs_release(), and init().
AVRSemaphore AVRSPI2DeviceDriver::_semaphore static private
Definition at line 81 of file SPIDevices.h.
Referenced by get_semaphore().
uint16_t AP_HAL_AVR::AVRSPI2DeviceDriver::_ubrr2 private
Definition at line 85 of file SPIDevices.h.
Referenced by _cs_assert().
uint8_t AP_HAL_AVR::AVRSPI2DeviceDriver::_ucsr2c private
Definition at line 84 of file SPIDevices.h.
Referenced by _cs_assert().
The documentation for this class was generated from the following files:
libraries/AP_HAL_AVR/SPIDevices.h
libraries/AP_HAL_AVR/SPIDevice_SPI2.cpp