APM:Libraries: AP_InertialSensor_Oilpan Class Reference
AP_InertialSensor_Oilpan Class Reference
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
#include <AP_InertialSensor_Oilpan.h>
Public Member Functions
AP_InertialSensor_Oilpan (AP_InertialSensor &imu)
bool update ()
bool gyro_sample_available (void)
bool accel_sample_available (void)
Public Member Functions inherited from AP_InertialSensor_Backend
AP_InertialSensor_Backend (AP_InertialSensor &imu)
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
virtual ~AP_InertialSensor_Backend (void)
int16_t product_id (void) const
Static Public Member Functions
static AP_InertialSensor_Backend * detect (AP_InertialSensor &imu)
Private Member Functions
bool _init_sensor (void)
bool _sample_available () const
Private Attributes
uint8_t _sample_threshold
uint8_t _gyro_instance
uint8_t _accel_instance
Static Private Attributes
static const uint8_t _sensors [6] = { 1, 2, 0, 4, 5, 6 }
static const int8_t _sensor_signs [6]
static const float _gyro_gain_x = radians(0.4f)
static const float _gyro_gain_y = radians(0.41f)
static const float _gyro_gain_z = radians(0.41f)
static const float _adc_constraint = 900
Additional Inherited Members
Protected Member Functions inherited from AP_InertialSensor_Backend
void _rotate_and_correct_accel (uint8_t instance, Vector3f &accel)
void _rotate_and_correct_gyro (uint8_t instance, Vector3f &gyro)
void _publish_delta_velocity (uint8_t instance, const Vector3f &delta_velocity, float dt)
void _publish_delta_angle (uint8_t instance, const Vector3f &delta_angle)
void _publish_gyro (uint8_t instance, const Vector3f &gyro, bool rotate_and_correct=true)
void _publish_accel (uint8_t instance, const Vector3f &accel, bool rotate_and_correct=true)
void _publish_temperature (uint8_t instance, float temperature)
void _set_accel_error_count (uint8_t instance, uint32_t error_count)
void _set_gyro_error_count (uint8_t instance, uint32_t error_count)
uint8_t _accel_filter_cutoff (void) const
uint8_t _gyro_filter_cutoff (void) const
uint16_t get_sample_rate_hz (void) const
DataFlash_Class * get_dataflash (void) const
Protected Attributes inherited from AP_InertialSensor_Backend
AP_InertialSensor & _imu
int16_t _product_id
Detailed Description
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 9 of file AP_InertialSensor_Oilpan.h.
Constructor & Destructor Documentation
AP_InertialSensor_Oilpan::AP_InertialSensor_Oilpan (AP_InertialSensor & imu)
Definition at line 44 of file AP_InertialSensor_Oilpan.cpp.
Referenced by detect().
Member Function Documentation
bool AP_InertialSensor_Oilpan::_init_sensor (void) private
Definition at line 66 of file AP_InertialSensor_Oilpan.cpp.
Referenced by detect().
bool AP_InertialSensor_Oilpan::_sample_available () const private
Definition at line 120 of file AP_InertialSensor_Oilpan.cpp.
Referenced by accel_sample_available(), and gyro_sample_available().
bool AP_InertialSensor_Oilpan::accel_sample_available (void) inline virtual
Implements AP_InertialSensor_Backend.
Definition at line 18 of file AP_InertialSensor_Oilpan.h.
AP_InertialSensor_Backend * AP_InertialSensor_Oilpan::detect (AP_InertialSensor & imu) static
Definition at line 52 of file AP_InertialSensor_Oilpan.cpp.
Referenced by AP_InertialSensor::_detect_backends().
bool AP_InertialSensor_Oilpan::gyro_sample_available (void) inline virtual
Implements AP_InertialSensor_Backend.
Definition at line 17 of file AP_InertialSensor_Oilpan.h.
bool AP_InertialSensor_Oilpan::update (void) virtual
Implements AP_InertialSensor_Backend.
Definition at line 96 of file AP_InertialSensor_Oilpan.cpp.
Member Data Documentation
uint8_t AP_InertialSensor_Oilpan::_accel_instance private
Definition at line 34 of file AP_InertialSensor_Oilpan.h.
Referenced by _init_sensor(), and update().
const float AP_InertialSensor_Oilpan::_adc_constraint = 900 static private
Definition at line 31 of file AP_InertialSensor_Oilpan.h.
const float AP_InertialSensor_Oilpan::_gyro_gain_x = radians(0.4f) static private
Definition at line 28 of file AP_InertialSensor_Oilpan.h.
Referenced by update().
const float AP_InertialSensor_Oilpan::_gyro_gain_y = radians(0.41f) static private
Definition at line 29 of file AP_InertialSensor_Oilpan.h.
Referenced by update().
const float AP_InertialSensor_Oilpan::_gyro_gain_z = radians(0.41f) static private
Definition at line 30 of file AP_InertialSensor_Oilpan.h.
Referenced by update().
uint8_t AP_InertialSensor_Oilpan::_gyro_instance private
Definition at line 33 of file AP_InertialSensor_Oilpan.h.
Referenced by _init_sensor(), and update().
uint8_t AP_InertialSensor_Oilpan::_sample_threshold private
Definition at line 32 of file AP_InertialSensor_Oilpan.h.
Referenced by _init_sensor(), and _sample_available().
const int8_t AP_InertialSensor_Oilpan::_sensor_signs static private
Initial value:
=
{ 1, -1, -1, 1, -1, -1 }
Definition at line 27 of file AP_InertialSensor_Oilpan.h.
Referenced by update().
const uint8_t AP_InertialSensor_Oilpan::_sensors = { 1, 2, 0, 4, 5, 6 } static private
Definition at line 26 of file AP_InertialSensor_Oilpan.h.
Referenced by _sample_available(), and update().
The documentation for this class was generated from the following files:
libraries/AP_InertialSensor/AP_InertialSensor_Oilpan.h
libraries/AP_InertialSensor/AP_InertialSensor_Oilpan.cpp