APM:Libraries: DataFlash_Class Class Reference
DataFlash_Class Class Reference abstract
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
#include <DataFlash.h>
Classes
struct log_Header
Public Member Functions
virtual void Init (const struct LogStructure *structure, uint8_t num_types)
virtual bool CardInserted (void)=0
virtual bool NeedErase (void)=0
virtual void EraseAll ()=0
virtual void WriteBlock (const void *pBuffer, uint16_t size)=0
virtual uint16_t find_last_log (void)=0
virtual void get_log_boundaries (uint16_t log_num, uint16_t &start_page, uint16_t &end_page)=0
virtual void get_log_info (uint16_t log_num, uint32_t &size, uint32_t &time_utc)=0
virtual int16_t get_log_data (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t *data)=0
virtual uint16_t get_num_logs (void)=0
virtual void LogReadProcess (uint16_t log_num, uint16_t start_page, uint16_t end_page, void(*printMode)(AP_HAL::BetterStream *port, uint8_t mode), AP_HAL::BetterStream *port)=0
virtual void DumpPageInfo (AP_HAL::BetterStream *port)=0
virtual void ShowDeviceInfo (AP_HAL::BetterStream *port)=0
virtual void ListAvailableLogs (AP_HAL::BetterStream *port)=0
uint16_t StartNewLog (void)
void AddLogFormats (const struct LogStructure *structures, uint8_t num_types)
void EnableWrites (bool enable)
void Log_Write_Format (const struct LogStructure *structure)
void Log_Write_Parameter (const char *name, float value)
void Log_Write_GPS (const AP_GPS &gps, uint8_t instance, int32_t relative_alt)
void Log_Write_IMU (const AP_InertialSensor &ins)
void Log_Write_RCIN (void)
void Log_Write_RCOUT (void)
void Log_Write_Baro (AP_Baro &baro)
void Log_Write_Power (void)
void Log_Write_AHRS2 (AP_AHRS &ahrs)
void Log_Write_POS (AP_AHRS &ahrs)
void Log_Write_MavCmd (uint16_t cmd_total, const mavlink_mission_item_t &mav_cmd)
void Log_Write_Radio (const mavlink_radio_t &packet)
void Log_Write_Message (const char *message)
void Log_Write_Message_P (const prog_char_t *message)
void Log_Write_Camera (const AP_AHRS &ahrs, const AP_GPS &gps, const Location &current_loc)
void Log_Write_ESC (void)
void Log_Write_Airspeed (AP_Airspeed &airspeed)
void Log_Write_Attitude (AP_AHRS &ahrs, const Vector3f &targets)
void Log_Write_Current (const AP_BattMonitor &battery, int16_t throttle)
void Log_Write_Compass (const Compass &compass)
void Log_Write_Mode (uint8_t mode)
bool logging_started (void) const
Protected Member Functions
void _print_log_entry (uint8_t msg_type, void(*print_mode)(AP_HAL::BetterStream *port, uint8_t mode), AP_HAL::BetterStream *port)
void Log_Fill_Format (const struct LogStructure *structure, struct log_Format &pkt)
void Log_Write_Parameter (const AP_Param *ap, const AP_Param::ParamToken &token, enum ap_var_type type)
void Log_Write_Parameters (void)
virtual uint16_t start_new_log (void)=0
virtual void ReadBlock (void *pkt, uint16_t size)=0
Protected Attributes
const struct LogStructure * _structures
uint8_t _num_types
bool _writes_enabled
bool log_write_started
Detailed Description
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 28 of file DataFlash.h.
Member Function Documentation
void DataFlash_Class::_print_log_entry (uint8_t msg_type, void(*)(AP_HAL::BetterStream *port, uint8_t mode) print_mode, AP_HAL::BetterStream * port) protected
Definition at line 279 of file LogFile.cpp.
Referenced by DataFlash_Block::LogReadProcess().
void DataFlash_Class::AddLogFormats (const struct LogStructure * structures, uint8_t num_types)
Definition at line 583 of file LogFile.cpp.
Referenced by AP_GPS_SBP::logging_write_headers().
virtual bool DataFlash_Class::CardInserted (void) pure virtual
Implemented in DataFlash_APM1, DataFlash_APM2, DataFlash_SITL, DataFlash_Empty, DataFlash_File, and DataFlash_Block.
virtual void DataFlash_Class::DumpPageInfo (AP_HAL::BetterStream * port) pure virtual
Implemented in DataFlash_File, and DataFlash_Block.
void DataFlash_Class::EnableWrites (bool enable) inline
Definition at line 61 of file DataFlash.h.
virtual void DataFlash_Class::EraseAll () pure virtual
Implemented in DataFlash_File, and DataFlash_Block.
Referenced by GCS_MAVLINK::handle_log_request_erase().
virtual uint16_t DataFlash_Class::find_last_log (void) pure virtual
Implemented in DataFlash_File, and DataFlash_Block.
Referenced by GCS_MAVLINK::handle_log_request_data(), and GCS_MAVLINK::handle_log_request_list().
virtual void DataFlash_Class::get_log_boundaries (uint16_t log_num, uint16_t & start_page, uint16_t & end_page) pure virtual
Implemented in DataFlash_File, and DataFlash_Block.
Referenced by GCS_MAVLINK::handle_log_request_data().
virtual int16_t DataFlash_Class::get_log_data (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t * data) pure virtual
Implemented in DataFlash_File, and DataFlash_Block.
Referenced by GCS_MAVLINK::handle_log_send_data().
virtual void DataFlash_Class::get_log_info (uint16_t log_num, uint32_t & size, uint32_t & time_utc) pure virtual
Implemented in DataFlash_File, and DataFlash_Block.
Referenced by GCS_MAVLINK::handle_log_request_data(), and GCS_MAVLINK::handle_log_send_listing().
virtual uint16_t DataFlash_Class::get_num_logs (void) pure virtual
Implemented in DataFlash_File, and DataFlash_Block.
Referenced by GCS_MAVLINK::handle_log_request_data(), and GCS_MAVLINK::handle_log_request_list().
void DataFlash_Class::Init (const struct LogStructure * structure, uint8_t num_types) virtual
Reimplemented in DataFlash_APM1, DataFlash_APM2, DataFlash_SITL, DataFlash_Empty, DataFlash_File, and DataFlash_Block.
Definition at line 15 of file LogFile.cpp.
Referenced by DataFlash_Empty::Init(), DataFlash_SITL::Init(), and DataFlash_APM1::Init().
virtual void DataFlash_Class::ListAvailableLogs (AP_HAL::BetterStream * port) pure virtual
Implemented in DataFlash_File, and DataFlash_Block.
void DataFlash_Class::Log_Fill_Format (const struct LogStructure * structure, struct log_Format & pkt) protected
Definition at line 594 of file LogFile.cpp.
Referenced by DataFlash_Block::get_log_data(), and Log_Write_Format().
void DataFlash_Class::Log_Write_AHRS2 (AP_AHRS & ahrs)
Definition at line 893 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Airspeed (AP_Airspeed & airspeed)
Definition at line 1296 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Attitude (AP_AHRS & ahrs, const Vector3f & targets)
Definition at line 1140 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Baro (AP_Baro & baro)
Definition at line 760 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Camera (const AP_AHRS & ahrs, const AP_GPS & gps, const Location & current_loc)
Definition at line 1113 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Compass (const Compass & compass)
Definition at line 1175 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Current (const AP_BattMonitor & battery, int16_t throttle)
Definition at line 1158 of file LogFile.cpp.
void DataFlash_Class::Log_Write_ESC (void)
Definition at line 1255 of file LogFile.cpp.
Referenced by Log_Write_RCOUT().
void DataFlash_Class::Log_Write_Format (const struct LogStructure * structure)
Definition at line 610 of file LogFile.cpp.
Referenced by AddLogFormats(), and StartNewLog().
void DataFlash_Class::Log_Write_GPS (const AP_GPS & gps, uint8_t instance, int32_t relative_alt)
Definition at line 664 of file LogFile.cpp.
void DataFlash_Class::Log_Write_IMU (const AP_InertialSensor & ins)
Definition at line 788 of file LogFile.cpp.
void DataFlash_Class::Log_Write_MavCmd (uint16_t cmd_total, const mavlink_mission_item_t & mav_cmd)
Definition at line 1077 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Message (const char * message)
Definition at line 856 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Message_P (const prog_char_t * message)
Definition at line 867 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Mode (uint8_t mode)
Definition at line 1243 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Parameter (const char * name, float value)
Definition at line 620 of file LogFile.cpp.
Referenced by GCS_MAVLINK::handle_param_set(), AP_AutoTune::log_param_change(), Log_Write_Parameter(), and Log_Write_Parameters().
void DataFlash_Class::Log_Write_Parameter (const AP_Param * ap, const AP_Param::ParamToken & token, enum ap_var_type type) protected
Definition at line 634 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Parameters (void) protected
Definition at line 647 of file LogFile.cpp.
Referenced by StartNewLog().
void DataFlash_Class::Log_Write_POS (AP_AHRS & ahrs)
Definition at line 914 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Power (void)
Definition at line 878 of file LogFile.cpp.
void DataFlash_Class::Log_Write_Radio (const mavlink_radio_t & packet)
Definition at line 1096 of file LogFile.cpp.
Referenced by GCS_MAVLINK::handle_radio_status().
void DataFlash_Class::Log_Write_RCIN (void)
Definition at line 712 of file LogFile.cpp.
void DataFlash_Class::Log_Write_RCOUT (void)
Definition at line 737 of file LogFile.cpp.
bool DataFlash_Class::logging_started (void) const inline
Definition at line 87 of file DataFlash.h.
Referenced by AP_GPS_UBLOX::log_accuracy(), AP_GPS_UBLOX::log_mon_hw(), AP_GPS_UBLOX::log_mon_hw2(), AP_AutoTune::log_param_change(), AP_GPS_UBLOX::log_rxm_raw(), AP_GPS_SBP::logging_log_full_update(), AP_GPS_SBP::logging_log_raw_sbp(), and AP_AutoTune::write_log().
virtual void DataFlash_Class::LogReadProcess (uint16_t log_num, uint16_t start_page, uint16_t end_page, void(*)(AP_HAL::BetterStream *port, uint8_t mode) printMode, AP_HAL::BetterStream * port) pure virtual
Implemented in DataFlash_File, and DataFlash_Block.
virtual bool DataFlash_Class::NeedErase (void) pure virtual
Implemented in DataFlash_File, and DataFlash_Block.
virtual void DataFlash_Class::ReadBlock (void * pkt, uint16_t size) protected pure virtual
Implemented in DataFlash_Block, and DataFlash_File.
Referenced by _print_log_entry().
virtual void DataFlash_Class::ShowDeviceInfo (AP_HAL::BetterStream * port) pure virtual
Implemented in DataFlash_File, and DataFlash_Block.
virtual uint16_t DataFlash_Class::start_new_log (void) protected pure virtual
Implemented in DataFlash_File, and DataFlash_Block.
Referenced by StartNewLog().
uint16_t DataFlash_Class::StartNewLog (void)
Definition at line 561 of file LogFile.cpp.
Referenced by setup().
virtual void DataFlash_Class::WriteBlock (const void * pBuffer, uint16_t size) pure virtual
Implemented in DataFlash_File, and DataFlash_Block.
Referenced by AP_InertialSensor_PX4::_get_accel_sample(), AP_InertialSensor_PX4::_get_gyro_sample(), AP_GPS_UBLOX::log_accuracy(), AP_TECS::log_data(), AP_GPS_UBLOX::log_mon_hw(), AP_GPS_UBLOX::log_mon_hw2(), AP_GPS_UBLOX::log_rxm_raw(), Log_Write_AHRS2(), Log_Write_Airspeed(), Log_Write_Attitude(), Log_Write_Baro(), Log_Write_Camera(), Log_Write_Compass(), Log_Write_Current(), Log_Write_ESC(), Log_Write_Format(), Log_Write_GPS(), Log_Write_IMU(), Log_Write_MavCmd(), Log_Write_Message(), Log_Write_Message_P(), Log_Write_Mode(), Log_Write_Parameter(), Log_Write_POS(), Log_Write_Power(), Log_Write_Radio(), Log_Write_RCIN(), Log_Write_RCOUT(), SITL::Log_Write_SIMSTATE(), AP_GPS_SBP::logging_log_full_update(), AP_GPS_SBP::logging_log_raw_sbp(), and AP_AutoTune::write_log().
Member Data Documentation
uint8_t DataFlash_Class::_num_types protected
Definition at line 111 of file DataFlash.h.
Referenced by _print_log_entry(), DataFlash_Block::_print_log_formats(), DataFlash_Block::get_log_data(), Init(), and StartNewLog().
const struct LogStructure* DataFlash_Class::_structures protected
Definition at line 110 of file DataFlash.h.
Referenced by _print_log_entry(), DataFlash_Block::_print_log_formats(), DataFlash_Block::get_log_data(), Init(), and StartNewLog().
bool DataFlash_Class::_writes_enabled protected
Definition at line 112 of file DataFlash.h.
Referenced by DataFlash_SITL::BlockWrite(), EnableWrites(), DataFlash_Block::EraseAll(), Init(), and DataFlash_Block::WriteBlock().
bool DataFlash_Class::log_write_started protected
Definition at line 113 of file DataFlash.h.
Referenced by DataFlash_Block::EraseAll(), DataFlash_Block::get_log_data_raw(), logging_started(), DataFlash_Block::start_new_log(), DataFlash_Block::StartRead(), and DataFlash_Block::WriteBlock().
The documentation for this class was generated from the following files:
libraries/DataFlash/DataFlash.h
libraries/DataFlash/LogFile.cpp