APM:Libraries: fastdelegate::DelegateMemento Class Reference
fastdelegate::DelegateMemento Class Reference
#include <FastDelegate.h>
Public Member Functions
DelegateMemento ()
void clear ()
bool IsEqual (const DelegateMemento &x) const
bool IsLess (const DelegateMemento &right) const
bool operator! () const
bool empty () const
DelegateMemento & operator= (const DelegateMemento &right)
bool operator< (const DelegateMemento &right)
bool operator> (const DelegateMemento &right)
DelegateMemento (const DelegateMemento &right)
Protected Types
typedef void(detail::GenericClass::* GenericMemFuncType)()
Protected Member Functions
void SetMementoFrom (const DelegateMemento &right)
Protected Attributes
detail::GenericClass * m_pthis
GenericMemFuncType m_pFunction
Detailed Description
Definition at line 559 of file FastDelegate.h.
Member Typedef Documentation
typedef void(detail::GenericClass::* fastdelegate::DelegateMemento::GenericMemFuncType)() protected
Definition at line 563 of file FastDelegate.h.
Constructor & Destructor Documentation
fastdelegate::DelegateMemento::DelegateMemento () inline
Definition at line 579 of file FastDelegate.h.
fastdelegate::DelegateMemento::DelegateMemento (const DelegateMemento & right) inline
Definition at line 629 of file FastDelegate.h.
Member Function Documentation
void fastdelegate::DelegateMemento::clear () inline
Definition at line 580 of file FastDelegate.h.
Referenced by fastdelegate::FastDelegate0< RetType >::clear(), fastdelegate::FastDelegate1< Param1, RetType >::clear(), fastdelegate::FastDelegate2< Param1, Param2, RetType >::clear(), fastdelegate::FastDelegate3< Param1, Param2, Param3, RetType >::clear(), fastdelegate::FastDelegate4< Param1, Param2, Param3, Param4, RetType >::clear(), fastdelegate::FastDelegate5< Param1, Param2, Param3, Param4, Param5, RetType >::clear(), fastdelegate::FastDelegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::clear(), fastdelegate::FastDelegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::clear(), and fastdelegate::FastDelegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::clear().
bool fastdelegate::DelegateMemento::empty () const inline
Definition at line 616 of file FastDelegate.h.
Referenced by fastdelegate::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::IsEqualToStaticFuncPtr().
bool fastdelegate::DelegateMemento::IsEqual (const DelegateMemento & x) const inline
Definition at line 593 of file FastDelegate.h.
Referenced by fastdelegate::FastDelegate0< RetType >::operator!=(), fastdelegate::FastDelegate1< Param1, RetType >::operator!=(), fastdelegate::FastDelegate2< Param1, Param2, RetType >::operator!=(), fastdelegate::FastDelegate3< Param1, Param2, Param3, RetType >::operator!=(), fastdelegate::FastDelegate4< Param1, Param2, Param3, Param4, RetType >::operator!=(), fastdelegate::FastDelegate5< Param1, Param2, Param3, Param4, Param5, RetType >::operator!=(), fastdelegate::FastDelegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator!=(), fastdelegate::FastDelegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::operator!=(), fastdelegate::FastDelegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator!=(), fastdelegate::FastDelegate0< RetType >::operator==(), fastdelegate::FastDelegate1< Param1, RetType >::operator==(), fastdelegate::FastDelegate2< Param1, Param2, RetType >::operator==(), fastdelegate::FastDelegate3< Param1, Param2, Param3, RetType >::operator==(), fastdelegate::FastDelegate4< Param1, Param2, Param3, Param4, RetType >::operator==(), fastdelegate::FastDelegate5< Param1, Param2, Param3, Param4, Param5, RetType >::operator==(), fastdelegate::FastDelegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator==(), fastdelegate::FastDelegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::operator==(), and fastdelegate::FastDelegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator==().
bool fastdelegate::DelegateMemento::IsLess (const DelegateMemento & right) const inline
Definition at line 598 of file FastDelegate.h.
Referenced by operator<(), fastdelegate::FastDelegate0< RetType >::operator<(), fastdelegate::FastDelegate1< Param1, RetType >::operator<(), fastdelegate::FastDelegate2< Param1, Param2, RetType >::operator<(), fastdelegate::FastDelegate3< Param1, Param2, Param3, RetType >::operator<(), fastdelegate::FastDelegate4< Param1, Param2, Param3, Param4, RetType >::operator<(), fastdelegate::FastDelegate5< Param1, Param2, Param3, Param4, Param5, RetType >::operator<(), fastdelegate::FastDelegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator<(), fastdelegate::FastDelegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::operator<(), fastdelegate::FastDelegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator<(), operator>(), fastdelegate::FastDelegate0< RetType >::operator>(), fastdelegate::FastDelegate1< Param1, RetType >::operator>(), fastdelegate::FastDelegate2< Param1, Param2, RetType >::operator>(), fastdelegate::FastDelegate3< Param1, Param2, Param3, RetType >::operator>(), fastdelegate::FastDelegate4< Param1, Param2, Param3, Param4, RetType >::operator>(), fastdelegate::FastDelegate5< Param1, Param2, Param3, Param4, Param5, RetType >::operator>(), fastdelegate::FastDelegate6< Param1, Param2, Param3, Param4, Param5, Param6, RetType >::operator>(), fastdelegate::FastDelegate7< Param1, Param2, Param3, Param4, Param5, Param6, Param7, RetType >::operator>(), and fastdelegate::FastDelegate8< Param1, Param2, Param3, Param4, Param5, Param6, Param7, Param8, RetType >::operator>().
bool fastdelegate::DelegateMemento::operator! () const inline
Definition at line 614 of file FastDelegate.h.
bool fastdelegate::DelegateMemento::operator< (const DelegateMemento & right) inline
Definition at line 623 of file FastDelegate.h.
DelegateMemento& fastdelegate::DelegateMemento::operator= (const DelegateMemento & right) inline
Definition at line 619 of file FastDelegate.h.
bool fastdelegate::DelegateMemento::operator> (const DelegateMemento & right) inline
Definition at line 626 of file FastDelegate.h.
void fastdelegate::DelegateMemento::SetMementoFrom (const DelegateMemento & right) inline protected
Definition at line 636 of file FastDelegate.h.
Referenced by fastdelegate::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::CopyFrom(), and operator=().
Member Data Documentation
GenericMemFuncType fastdelegate::DelegateMemento::m_pFunction protected
Definition at line 565 of file FastDelegate.h.
Referenced by fastdelegate::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::bindconstmemfunc(), fastdelegate::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::bindmemfunc(), fastdelegate::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::bindstaticfunc(), clear(), empty(), fastdelegate::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::GetClosureMemPtr(), IsEqual(), IsLess(), operator!(), and SetMementoFrom().
detail::GenericClass* fastdelegate::DelegateMemento::m_pthis protected
Definition at line 564 of file FastDelegate.h.
Referenced by fastdelegate::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::bindconstmemfunc(), fastdelegate::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::bindmemfunc(), fastdelegate::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::bindstaticfunc(), clear(), empty(), fastdelegate::detail::ClosurePtr< GenericMemFn, StaticFunctionPtr, UnvoidStaticFunctionPtr >::GetClosureThis(), IsEqual(), IsLess(), operator!(), and SetMementoFrom().
The documentation for this class was generated from the following file:
libraries/AP_HAL/utility/FastDelegate.h