APM:Libraries: AP_HAL::BetterStream Class Reference
AP_HAL::BetterStream Class Reference abstract
#include <BetterStream.h>
Public Member Functions
BetterStream (void)
virtual void print_P (const prog_char_t *)=0
virtual void println_P (const prog_char_t *)=0
virtual void printf (const char *,...) __attribute__((format(__printf__
virtual void virtual void _printf_P (const prog_char *,...)=0
virtual void vprintf (const char *, va_list)=0
virtual void vprintf_P (const prog_char *, va_list)=0
Public Member Functions inherited from AP_HAL::Stream
virtual int16_t available ()=0
virtual int16_t txspace ()=0
virtual int16_t read ()=0
Public Member Functions inherited from AP_HAL::Print
Print ()
virtual size_t write (uint8_t)=0
virtual size_t write (const uint8_t *buffer, size_t size)=0
size_t write (const char *str)
size_t print (const char[])
size_t print (char)
size_t print (unsigned char, int=BASE_DEC)
size_t print (int, int=BASE_DEC)
size_t print (unsigned int, int=BASE_DEC)
size_t print (long, int=BASE_DEC)
size_t print (unsigned long, int=BASE_DEC)
size_t print (float, int=2)
size_t print (double, int=2)
size_t println (const char[])
size_t println (char)
size_t println (unsigned char, int=BASE_DEC)
size_t println (int, int=BASE_DEC)
size_t println (unsigned int, int=BASE_DEC)
size_t println (long, int=BASE_DEC)
size_t println (unsigned long, int=BASE_DEC)
size_t println (float, int=2)
size_t println (double, int=2)
size_t println (void)
Detailed Description
Definition at line 42 of file BetterStream.h.
Constructor & Destructor Documentation
AP_HAL::BetterStream::BetterStream (void) inline
Definition at line 44 of file BetterStream.h.
Member Function Documentation
virtual void virtual void AP_HAL::BetterStream::_printf_P (const prog_char * , ...) pure virtual
Implemented in AP_HAL::UARTDriver.
virtual void AP_HAL::BetterStream::print_P (const prog_char_t *) pure virtual
Implemented in AP_HAL::UARTDriver.
Referenced by AP_Curve< T, SIZE >::dump_curve().
virtual void AP_HAL::BetterStream::printf (const char * , ...) virtual
Reimplemented in AP_HAL::UARTDriver.
virtual void AP_HAL::BetterStream::println_P (const prog_char_t *) pure virtual
Implemented in AP_HAL::UARTDriver.
Referenced by Menu::_help(), Menu::_run_command(), AP_Curve< T, SIZE >::dump_curve(), and DataFlash_Block::ShowDeviceInfo().
virtual void AP_HAL::BetterStream::vprintf (const char * , va_list) pure virtual
Implemented in AP_HAL::UARTDriver.
virtual void AP_HAL::BetterStream::vprintf_P (const prog_char * , va_list) pure virtual
Implemented in AP_HAL::UARTDriver.
Referenced by AP_InertialSensor_UserInteractStream::_printf_P().
The documentation for this class was generated from the following file:
libraries/AP_HAL/utility/BetterStream.h