APM:Libraries: AP_HAL_AVR::AVRTimer Class Reference
AP_HAL_AVR::AVRTimer Class Reference
#include <Scheduler.h>
Static Public Member Functions
static void init ()
static uint32_t millis ()
static uint32_t micros ()
static void delay_microseconds (uint16_t us)
Detailed Description
Definition at line 11 of file Scheduler.h.
Member Function Documentation
void AVRTimer::delay_microseconds (uint16_t us) static
Definition at line 134 of file Scheduler_Timer.cpp.
Referenced by AP_HAL_AVR::AVRScheduler::delay_microseconds().
void AVRTimer::init (void) static
Definition at line 49 of file Scheduler_Timer.cpp.
Referenced by AP_HAL_AVR::AVRScheduler::init().
uint32_t AVRTimer::micros () static
Definition at line 91 of file Scheduler_Timer.cpp.
Referenced by AP_HAL_AVR::AVRScheduler::delay(), and AP_HAL_AVR::AVRScheduler::micros().
uint32_t AVRTimer::millis () static
Definition at line 112 of file Scheduler_Timer.cpp.
Referenced by AP_HAL_AVR::AVRScheduler::millis().
The documentation for this class was generated from the following files:
libraries/AP_HAL_AVR/Scheduler.h
libraries/AP_HAL_AVR/Scheduler_Timer.cpp