APM:Libraries: LiquidCrystal Class Reference
LiquidCrystal Class Reference
#include <LCrystal.h>
Public Member Functions
LiquidCrystal (uint8_t rs, uint8_t enable, uint8_t d0, uint8_t d1, uint8_t d2, uint8_t d3, uint8_t d4, uint8_t d5, uint8_t d6, uint8_t d7)
LiquidCrystal (uint8_t rs, uint8_t rw, uint8_t enable, uint8_t d0, uint8_t d1, uint8_t d2, uint8_t d3, uint8_t d4, uint8_t d5, uint8_t d6, uint8_t d7)
LiquidCrystal (uint8_t rs, uint8_t rw, uint8_t enable, uint8_t d0, uint8_t d1, uint8_t d2, uint8_t d3)
LiquidCrystal (uint8_t rs, uint8_t enable, uint8_t d0, uint8_t d1, uint8_t d2, uint8_t d3)
void init (uint8_t fourbitmode, uint8_t rs, uint8_t rw, uint8_t enable, uint8_t d0, uint8_t d1, uint8_t d2, uint8_t d3, uint8_t d4, uint8_t d5, uint8_t d6, uint8_t d7)
void begin (uint8_t cols, uint8_t rows, uint8_t charsize=LCD_5x8DOTS)
void clear ()
void home ()
void noDisplay ()
void display ()
void noBlink ()
void blink ()
void noCursor ()
void cursor ()
void scrollDisplayLeft ()
void scrollDisplayRight ()
void leftToRight ()
void rightToLeft ()
void autoscroll ()
void noAutoscroll ()
void createChar (uint8_t, uint8_t[])
void setCursor (uint8_t, uint8_t)
virtual size_t write (uint8_t)
void command (uint8_t)
Public Member Functions inherited from AP_HAL::Print
Print ()
virtual size_t write (const uint8_t *buffer, size_t size)=0
size_t write (const char *str)
size_t print (const char[])
size_t print (char)
size_t print (unsigned char, int=BASE_DEC)
size_t print (int, int=BASE_DEC)
size_t print (unsigned int, int=BASE_DEC)
size_t print (long, int=BASE_DEC)
size_t print (unsigned long, int=BASE_DEC)
size_t print (float, int=2)
size_t print (double, int=2)
size_t println (const char[])
size_t println (char)
size_t println (unsigned char, int=BASE_DEC)
size_t println (int, int=BASE_DEC)
size_t println (unsigned int, int=BASE_DEC)
size_t println (long, int=BASE_DEC)
size_t println (unsigned long, int=BASE_DEC)
size_t println (float, int=2)
size_t println (double, int=2)
size_t println (void)
Private Member Functions
void send (uint8_t, uint8_t)
void write4bits (uint8_t)
void write8bits (uint8_t)
void pulseEnable ()
Private Attributes
uint8_t _rs_pin
uint8_t _rw_pin
uint8_t _enable_pin
uint8_t _data_pins [8]
uint8_t _displayfunction
uint8_t _displaycontrol
uint8_t _displaymode
uint8_t _initialized
uint8_t _numlines
uint8_t _currline
Detailed Description
Definition at line 45 of file LCrystal.h.
Constructor & Destructor Documentation
LiquidCrystal::LiquidCrystal (uint8_t rs, uint8_t enable, uint8_t d0, uint8_t d1, uint8_t d2, uint8_t d3, uint8_t d4, uint8_t d5, uint8_t d6, uint8_t d7)
Definition at line 37 of file LCrystal.cpp.
LiquidCrystal::LiquidCrystal (uint8_t rs, uint8_t rw, uint8_t enable, uint8_t d0, uint8_t d1, uint8_t d2, uint8_t d3, uint8_t d4, uint8_t d5, uint8_t d6, uint8_t d7)
Definition at line 30 of file LCrystal.cpp.
LiquidCrystal::LiquidCrystal (uint8_t rs, uint8_t rw, uint8_t enable, uint8_t d0, uint8_t d1, uint8_t d2, uint8_t d3)
Definition at line 44 of file LCrystal.cpp.
LiquidCrystal::LiquidCrystal (uint8_t rs, uint8_t enable, uint8_t d0, uint8_t d1, uint8_t d2, uint8_t d3)
Definition at line 50 of file LCrystal.cpp.
Member Function Documentation
void LiquidCrystal::autoscroll (void)
Definition at line 237 of file LCrystal.cpp.
void LiquidCrystal::begin (uint8_t cols, uint8_t rows, uint8_t charsize = LCD_5x8DOTS)
Definition at line 88 of file LCrystal.cpp.
Referenced by init(), and setup().
void LiquidCrystal::blink ()
Definition at line 211 of file LCrystal.cpp.
void LiquidCrystal::clear ()
Definition at line 164 of file LCrystal.cpp.
Referenced by begin().
void LiquidCrystal::command (uint8_t value) inline
Definition at line 260 of file LCrystal.cpp.
Referenced by autoscroll(), begin(), blink(), clear(), createChar(), cursor(), display(), home(), leftToRight(), noAutoscroll(), noBlink(), noCursor(), noDisplay(), rightToLeft(), scrollDisplayLeft(), scrollDisplayRight(), and setCursor().
void LiquidCrystal::createChar (uint8_t location, uint8_t charmap[])
Definition at line 250 of file LCrystal.cpp.
void LiquidCrystal::cursor ()
Definition at line 201 of file LCrystal.cpp.
void LiquidCrystal::display ()
Definition at line 191 of file LCrystal.cpp.
Referenced by begin().
void LiquidCrystal::home ()
Definition at line 170 of file LCrystal.cpp.
void LiquidCrystal::init (uint8_t fourbitmode, uint8_t rs, uint8_t rw, uint8_t enable, uint8_t d0, uint8_t d1, uint8_t d2, uint8_t d3, uint8_t d4, uint8_t d5, uint8_t d6, uint8_t d7)
Definition at line 56 of file LCrystal.cpp.
Referenced by LiquidCrystal().
void LiquidCrystal::leftToRight (void)
Definition at line 225 of file LCrystal.cpp.
void LiquidCrystal::noAutoscroll (void)
Definition at line 243 of file LCrystal.cpp.
void LiquidCrystal::noBlink ()
Definition at line 207 of file LCrystal.cpp.
void LiquidCrystal::noCursor ()
Definition at line 197 of file LCrystal.cpp.
void LiquidCrystal::noDisplay ()
Definition at line 187 of file LCrystal.cpp.
void LiquidCrystal::pulseEnable (void) private
Definition at line 288 of file LCrystal.cpp.
Referenced by write4bits(), and write8bits().
void LiquidCrystal::rightToLeft (void)
Definition at line 231 of file LCrystal.cpp.
void LiquidCrystal::scrollDisplayLeft (void)
Definition at line 217 of file LCrystal.cpp.
void LiquidCrystal::scrollDisplayRight (void)
Definition at line 220 of file LCrystal.cpp.
void LiquidCrystal::send (uint8_t value, uint8_t mode) private
Definition at line 272 of file LCrystal.cpp.
Referenced by command(), and write().
void LiquidCrystal::setCursor (uint8_t col, uint8_t row)
Definition at line 176 of file LCrystal.cpp.
Referenced by loop().
size_t LiquidCrystal::write (uint8_t value) inline virtual
Implements AP_HAL::Print.
Definition at line 264 of file LCrystal.cpp.
Referenced by createChar().
void LiquidCrystal::write4bits (uint8_t value) private
Definition at line 297 of file LCrystal.cpp.
Referenced by begin(), and send().
void LiquidCrystal::write8bits (uint8_t value) private
Definition at line 306 of file LCrystal.cpp.
Referenced by send().
Member Data Documentation
uint8_t LiquidCrystal::_currline private
Definition at line 103 of file LCrystal.h.
Referenced by begin().
uint8_t LiquidCrystal::_data_pins[8] private
Definition at line 95 of file LCrystal.h.
Referenced by init(), write4bits(), and write8bits().
uint8_t LiquidCrystal::_displaycontrol private
Definition at line 98 of file LCrystal.h.
Referenced by begin(), blink(), cursor(), display(), noBlink(), noCursor(), and noDisplay().
uint8_t LiquidCrystal::_displayfunction private
Definition at line 97 of file LCrystal.h.
Referenced by begin(), init(), and send().
uint8_t LiquidCrystal::_displaymode private
Definition at line 99 of file LCrystal.h.
Referenced by autoscroll(), begin(), leftToRight(), noAutoscroll(), and rightToLeft().
uint8_t LiquidCrystal::_enable_pin private
Definition at line 94 of file LCrystal.h.
Referenced by begin(), init(), and pulseEnable().
uint8_t LiquidCrystal::_initialized private
Definition at line 101 of file LCrystal.h.
uint8_t LiquidCrystal::_numlines private
Definition at line 103 of file LCrystal.h.
Referenced by begin(), and setCursor().
uint8_t LiquidCrystal::_rs_pin private
Definition at line 92 of file LCrystal.h.
Referenced by begin(), init(), and send().
uint8_t LiquidCrystal::_rw_pin private
Definition at line 93 of file LCrystal.h.
Referenced by begin(), init(), and send().
The documentation for this class was generated from the following files:
libraries/AP_HAL_AVR/examples/LCDTest/LCrystal.h
libraries/AP_HAL_AVR/examples/LCDTest/LCrystal.cpp