APM:Libraries: AP_HAL_AVR::AVRI2CDriver Class Reference
AP_HAL_AVR::AVRI2CDriver Class Reference
#include <I2CDriver.h>
Public Member Functions
AVRI2CDriver (AP_HAL::Semaphore *sem)
void begin ()
void end ()
void setTimeout (uint16_t ms)
void setHighSpeed (bool active)
uint8_t write (uint8_t addr, uint8_t len, uint8_t *data)
uint8_t writeRegister (uint8_t addr, uint8_t reg, uint8_t val)
uint8_t writeRegisters (uint8_t addr, uint8_t reg, uint8_t len, uint8_t *data)
uint8_t read (uint8_t addr, uint8_t len, uint8_t *data)
uint8_t readRegister (uint8_t addr, uint8_t reg, uint8_t *data)
uint8_t readRegisters (uint8_t addr, uint8_t reg, uint8_t len, uint8_t *data)
uint8_t lockup_count ()
AP_HAL::Semaphore * get_semaphore ()
Public Member Functions inherited from AP_HAL::I2CDriver
virtual uint8_t readRegistersMultiple (uint8_t addr, uint8_t reg, uint8_t len, uint8_t count, uint8_t *data)=0
void ignore_errors (bool b)
Private Member Functions
uint8_t _start ()
uint8_t _stop ()
uint8_t _sendAddress (uint8_t addr)
uint8_t _sendByte (uint8_t data)
uint8_t _receiveByte (bool ack)
void _handleLockup ()
uint8_t _waitInterrupt ()
uint8_t _waitStop ()
Private Attributes
uint8_t _lockup_count
uint16_t _timeoutDelay
AP_HAL::Semaphore * _sem
Additional Inherited Members
Protected Attributes inherited from AP_HAL::I2CDriver
bool _ignore_errors
Detailed Description
Definition at line 10 of file I2CDriver.h.
Constructor & Destructor Documentation
AP_HAL_AVR::AVRI2CDriver::AVRI2CDriver (AP_HAL::Semaphore * sem) inline
Definition at line 12 of file I2CDriver.h.
Member Function Documentation
void AVRI2CDriver::_handleLockup () private
Definition at line 263 of file I2CDriver.cpp.
Referenced by _waitInterrupt(), and _waitStop().
uint8_t AVRI2CDriver::_receiveByte (bool ack) private
Definition at line 252 of file I2CDriver.cpp.
Referenced by read(), and readRegisters().
uint8_t AVRI2CDriver::_sendAddress (uint8_t addr) private
Definition at line 233 of file I2CDriver.cpp.
Referenced by read(), readRegisters(), write(), and writeRegisters().
uint8_t AVRI2CDriver::_sendByte (uint8_t data) private
Definition at line 239 of file I2CDriver.cpp.
Referenced by readRegisters(), write(), and writeRegisters().
uint8_t AVRI2CDriver::_start () private
Definition at line 216 of file I2CDriver.cpp.
Referenced by read(), readRegisters(), write(), and writeRegisters().
uint8_t AVRI2CDriver::_stop () private
Definition at line 228 of file I2CDriver.cpp.
Referenced by read(), readRegisters(), write(), and writeRegisters().
uint8_t AVRI2CDriver::_waitInterrupt () private
Definition at line 269 of file I2CDriver.cpp.
Referenced by _receiveByte(), _sendAddress(), _sendByte(), and _start().
uint8_t AVRI2CDriver::_waitStop () private
Definition at line 287 of file I2CDriver.cpp.
Referenced by _stop().
void AVRI2CDriver::begin () virtual
Implements AP_HAL::I2CDriver.
Definition at line 71 of file I2CDriver.cpp.
void AVRI2CDriver::end () virtual
Implements AP_HAL::I2CDriver.
Definition at line 89 of file I2CDriver.cpp.
AP_HAL::Semaphore* AP_HAL_AVR::AVRI2CDriver::get_semaphore () inline virtual
Implements AP_HAL::I2CDriver.
Definition at line 29 of file I2CDriver.h.
uint8_t AP_HAL_AVR::AVRI2CDriver::lockup_count () inline virtual
Implements AP_HAL::I2CDriver.
Definition at line 27 of file I2CDriver.h.
uint8_t AVRI2CDriver::read (uint8_t addr, uint8_t len, uint8_t * data) virtual
Implements AP_HAL::I2CDriver.
Definition at line 149 of file I2CDriver.cpp.
uint8_t AVRI2CDriver::readRegister (uint8_t addr, uint8_t reg, uint8_t * data) virtual
Implements AP_HAL::I2CDriver.
Definition at line 212 of file I2CDriver.cpp.
uint8_t AVRI2CDriver::readRegisters (uint8_t addr, uint8_t reg, uint8_t len, uint8_t * data) virtual
Implements AP_HAL::I2CDriver.
Definition at line 177 of file I2CDriver.cpp.
Referenced by readRegister().
void AVRI2CDriver::setHighSpeed (bool active) virtual
Implements AP_HAL::I2CDriver.
Definition at line 93 of file I2CDriver.cpp.
Referenced by begin().
void AP_HAL_AVR::AVRI2CDriver::setTimeout (uint16_t ms) inline virtual
Implements AP_HAL::I2CDriver.
Definition at line 16 of file I2CDriver.h.
uint8_t AVRI2CDriver::write (uint8_t addr, uint8_t len, uint8_t * data) virtual
Implements AP_HAL::I2CDriver.
Definition at line 101 of file I2CDriver.cpp.
uint8_t AVRI2CDriver::writeRegister (uint8_t addr, uint8_t reg, uint8_t val) virtual
Implements AP_HAL::I2CDriver.
Definition at line 142 of file I2CDriver.cpp.
uint8_t AVRI2CDriver::writeRegisters (uint8_t addr, uint8_t reg, uint8_t len, uint8_t * data) virtual
Implements AP_HAL::I2CDriver.
Definition at line 119 of file I2CDriver.cpp.
Referenced by writeRegister().
Member Data Documentation
uint8_t AP_HAL_AVR::AVRI2CDriver::_lockup_count private
Definition at line 42 of file I2CDriver.h.
Referenced by _handleLockup(), lockup_count(), read(), readRegisters(), write(), and writeRegisters().
AP_HAL::Semaphore* AP_HAL_AVR::AVRI2CDriver::_sem private
Definition at line 45 of file I2CDriver.h.
Referenced by get_semaphore().
uint16_t AP_HAL_AVR::AVRI2CDriver::_timeoutDelay private
Definition at line 43 of file I2CDriver.h.
Referenced by _waitInterrupt(), _waitStop(), and setTimeout().
The documentation for this class was generated from the following files:
libraries/AP_HAL_AVR/I2CDriver.h
libraries/AP_HAL_AVR/I2CDriver.cpp