APM:Libraries: DataFlash_APM1 Class Reference
DataFlash_APM1 Class Reference
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
#include <DataFlash_APM1.h>
Public Member Functions
void Init (const struct LogStructure *structure, uint8_t num_types)
void ReadManufacturerID ()
bool CardInserted ()
Public Member Functions inherited from DataFlash_Block
bool NeedErase (void)
void EraseAll ()
void WriteBlock (const void *pBuffer, uint16_t size)
uint16_t find_last_log (void)
void get_log_boundaries (uint16_t log_num, uint16_t &start_page, uint16_t &end_page)
void get_log_info (uint16_t log_num, uint32_t &size, uint32_t &time_utc)
int16_t get_log_data_raw (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t *data)
int16_t get_log_data (uint16_t log_num, uint16_t page, uint32_t offset, uint16_t len, uint8_t *data)
uint16_t get_num_logs (void)
uint16_t start_new_log (void)
void LogReadProcess (uint16_t log_num, uint16_t start_page, uint16_t end_page, void(*print_mode)(AP_HAL::BetterStream *port, uint8_t mode), AP_HAL::BetterStream *port)
void DumpPageInfo (AP_HAL::BetterStream *port)
void ShowDeviceInfo (AP_HAL::BetterStream *port)
void ListAvailableLogs (AP_HAL::BetterStream *port)
Public Member Functions inherited from DataFlash_Class
uint16_t StartNewLog (void)
void AddLogFormats (const struct LogStructure *structures, uint8_t num_types)
void EnableWrites (bool enable)
void Log_Write_Format (const struct LogStructure *structure)
void Log_Write_Parameter (const char *name, float value)
void Log_Write_GPS (const AP_GPS &gps, uint8_t instance, int32_t relative_alt)
void Log_Write_IMU (const AP_InertialSensor &ins)
void Log_Write_RCIN (void)
void Log_Write_RCOUT (void)
void Log_Write_Baro (AP_Baro &baro)
void Log_Write_Power (void)
void Log_Write_AHRS2 (AP_AHRS &ahrs)
void Log_Write_POS (AP_AHRS &ahrs)
void Log_Write_MavCmd (uint16_t cmd_total, const mavlink_mission_item_t &mav_cmd)
void Log_Write_Radio (const mavlink_radio_t &packet)
void Log_Write_Message (const char *message)
void Log_Write_Message_P (const prog_char_t *message)
void Log_Write_Camera (const AP_AHRS &ahrs, const AP_GPS &gps, const Location &current_loc)
void Log_Write_ESC (void)
void Log_Write_Airspeed (AP_Airspeed &airspeed)
void Log_Write_Attitude (AP_AHRS &ahrs, const Vector3f &targets)
void Log_Write_Current (const AP_BattMonitor &battery, int16_t throttle)
void Log_Write_Compass (const Compass &compass)
void Log_Write_Mode (uint8_t mode)
bool logging_started (void) const
Private Member Functions
void BufferToPage (uint8_t BufferNum, uint16_t PageAdr, uint8_t wait)
void PageToBuffer (uint8_t BufferNum, uint16_t PageAdr)
void WaitReady ()
uint8_t ReadStatusReg ()
uint8_t ReadStatus ()
uint16_t PageSize ()
void PageErase (uint16_t PageAdr)
void BlockErase (uint16_t BlockAdr)
void ChipErase ()
void BlockWrite (uint8_t BufferNum, uint16_t IntPageAdr, const void *pHeader, uint8_t hdr_size, const void *pBuffer, uint16_t size)
bool BlockRead (uint8_t BufferNum, uint16_t IntPageAdr, void *pBuffer, uint16_t size)
bool _sem_take (uint8_t timeout)
Private Attributes
AP_HAL::SPIDeviceDriver * _spi
AP_HAL::Semaphore * _spi_sem
Additional Inherited Members
Protected Member Functions inherited from DataFlash_Class
void _print_log_entry (uint8_t msg_type, void(*print_mode)(AP_HAL::BetterStream *port, uint8_t mode), AP_HAL::BetterStream *port)
void Log_Fill_Format (const struct LogStructure *structure, struct log_Format &pkt)
void Log_Write_Parameter (const AP_Param *ap, const AP_Param::ParamToken &token, enum ap_var_type type)
void Log_Write_Parameters (void)
Protected Attributes inherited from DataFlash_Block
uint8_t df_manufacturer
uint16_t df_device
uint16_t df_PageSize
uint16_t df_NumPages
Protected Attributes inherited from DataFlash_Class
const struct LogStructure * _structures
uint8_t _num_types
bool _writes_enabled
bool log_write_started
Detailed Description
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 12 of file DataFlash_APM1.h.
Member Function Documentation
bool DataFlash_APM1::_sem_take (uint8_t timeout) private
Definition at line 80 of file DataFlash_APM1.cpp.
Referenced by BlockErase(), BlockRead(), BlockWrite(), BufferToPage(), ChipErase(), PageErase(), PageSize(), PageToBuffer(), and ReadManufacturerID().
void DataFlash_APM1::BlockErase (uint16_t BlockAdr) private virtual
Implements DataFlash_Block.
Definition at line 342 of file DataFlash_APM1.cpp.
bool DataFlash_APM1::BlockRead (uint8_t BufferNum, uint16_t IntPageAdr, void * pBuffer, uint16_t size) private virtual
Implements DataFlash_Block.
Definition at line 284 of file DataFlash_APM1.cpp.
void DataFlash_APM1::BlockWrite (uint8_t BufferNum, uint16_t IntPageAdr, const void * pHeader, uint8_t hdr_size, const void * pBuffer, uint16_t size) private virtual
Implements DataFlash_Block.
Definition at line 254 of file DataFlash_APM1.cpp.
void DataFlash_APM1::BufferToPage (uint8_t BufferNum, uint16_t PageAdr, uint8_t wait) private virtual
Implements DataFlash_Block.
Definition at line 224 of file DataFlash_APM1.cpp.
bool DataFlash_APM1::CardInserted (void) virtual
Implements DataFlash_Block.
Definition at line 146 of file DataFlash_APM1.cpp.
void DataFlash_APM1::ChipErase () private virtual
Implements DataFlash_Block.
Definition at line 380 of file DataFlash_APM1.cpp.
void DataFlash_APM1::Init (const struct LogStructure * structure, uint8_t num_types) virtual
Implements DataFlash_Block.
Definition at line 90 of file DataFlash_APM1.cpp.
void DataFlash_APM1::PageErase (uint16_t PageAdr) private virtual
Implements DataFlash_Block.
Definition at line 314 of file DataFlash_APM1.cpp.
uint16_t DataFlash_APM1::PageSize () inline private
Definition at line 179 of file DataFlash_APM1.cpp.
Referenced by Init().
void DataFlash_APM1::PageToBuffer (uint8_t BufferNum, uint16_t PageAdr) private virtual
Implements DataFlash_Block.
Definition at line 197 of file DataFlash_APM1.cpp.
void DataFlash_APM1::ReadManufacturerID () virtual
Implements DataFlash_Block.
Definition at line 124 of file DataFlash_APM1.cpp.
uint8_t DataFlash_APM1::ReadStatus () inline private
Definition at line 173 of file DataFlash_APM1.cpp.
Referenced by BlockErase(), BufferToPage(), ChipErase(), PageErase(), PageToBuffer(), and WaitReady().
uint8_t DataFlash_APM1::ReadStatusReg () private
Definition at line 153 of file DataFlash_APM1.cpp.
Referenced by PageSize(), and ReadStatus().
void DataFlash_APM1::WaitReady () private virtual
Implements DataFlash_Block.
Definition at line 192 of file DataFlash_APM1.cpp.
Member Data Documentation
AP_HAL::SPIDeviceDriver* DataFlash_APM1::_spi private
Definition at line 40 of file DataFlash_APM1.h.
Referenced by BlockErase(), BlockRead(), BlockWrite(), BufferToPage(), ChipErase(), Init(), PageErase(), PageToBuffer(), ReadManufacturerID(), and ReadStatusReg().
AP_HAL::Semaphore* DataFlash_APM1::_spi_sem private
Definition at line 41 of file DataFlash_APM1.h.
Referenced by _sem_take(), BlockErase(), BlockRead(), BlockWrite(), BufferToPage(), ChipErase(), Init(), PageErase(), PageSize(), PageToBuffer(), and ReadManufacturerID().
The documentation for this class was generated from the following files:
libraries/DataFlash/DataFlash_APM1.h
libraries/DataFlash/DataFlash_APM1.cpp