APM:Libraries: Linux::LinuxGPIO_RPI Class Reference
Linux::LinuxGPIO_RPI Class Reference
#include <GPIO_RPI.h>
Public Member Functions
LinuxGPIO_RPI ()
void init ()
void pinMode (uint8_t pin, uint8_t output)
int8_t analogPinToDigitalPin (uint8_t pin)
uint8_t read (uint8_t pin)
void write (uint8_t pin, uint8_t value)
void toggle (uint8_t pin)
AP_HAL::DigitalSource * channel (uint16_t n)
bool attach_interrupt (uint8_t interrupt_num, AP_HAL::Proc p, uint8_t mode)
bool usb_connected (void)
Public Member Functions inherited from AP_HAL::GPIO
GPIO ()
Private Member Functions
int getRaspberryPiVersion () const
Private Attributes
int mem_fd
void * gpio_map
volatile uint32_t * gpio
Detailed Description
Definition at line 49 of file GPIO_RPI.h.
Constructor & Destructor Documentation
LinuxGPIO_RPI::LinuxGPIO_RPI ()
Definition at line 21 of file GPIO_RPI.cpp.
Member Function Documentation
int8_t LinuxGPIO_RPI::analogPinToDigitalPin (uint8_t pin) virtual
Implements AP_HAL::GPIO.
Definition at line 94 of file GPIO_RPI.cpp.
bool LinuxGPIO_RPI::attach_interrupt (uint8_t interrupt_num, AP_HAL::Proc p, uint8_t mode) virtual
Implements AP_HAL::GPIO.
Definition at line 125 of file GPIO_RPI.cpp.
AP_HAL::DigitalSource * LinuxGPIO_RPI::channel (uint16_t n) virtual
Implements AP_HAL::GPIO.
Definition at line 120 of file GPIO_RPI.cpp.
int LinuxGPIO_RPI::getRaspberryPiVersion () const private
Definition at line 24 of file GPIO_RPI.cpp.
Referenced by init().
void LinuxGPIO_RPI::init (void) virtual
Implements AP_HAL::GPIO.
Definition at line 57 of file GPIO_RPI.cpp.
void LinuxGPIO_RPI::pinMode (uint8_t pin, uint8_t output) virtual
Implements AP_HAL::GPIO.
Definition at line 84 of file GPIO_RPI.cpp.
uint8_t LinuxGPIO_RPI::read (uint8_t pin) virtual
Implements AP_HAL::GPIO.
Definition at line 99 of file GPIO_RPI.cpp.
Referenced by toggle().
void LinuxGPIO_RPI::toggle (uint8_t pin) virtual
Implements AP_HAL::GPIO.
Definition at line 114 of file GPIO_RPI.cpp.
bool LinuxGPIO_RPI::usb_connected (void) virtual
Implements AP_HAL::GPIO.
Definition at line 130 of file GPIO_RPI.cpp.
void LinuxGPIO_RPI::write (uint8_t pin, uint8_t value) virtual
Implements AP_HAL::GPIO.
Definition at line 105 of file GPIO_RPI.cpp.
Referenced by toggle().
Member Data Documentation
volatile uint32_t* Linux::LinuxGPIO_RPI::gpio private
Definition at line 53 of file GPIO_RPI.h.
Referenced by init().
void* Linux::LinuxGPIO_RPI::gpio_map private
Definition at line 52 of file GPIO_RPI.h.
Referenced by init().
int Linux::LinuxGPIO_RPI::mem_fd private
Definition at line 51 of file GPIO_RPI.h.
Referenced by init().
The documentation for this class was generated from the following files:
libraries/AP_HAL_Linux/GPIO_RPI.h
libraries/AP_HAL_Linux/GPIO_RPI.cpp