APM:Libraries: libraries/DataFlash/examples/DataFlash_test/DataFlash_test.pde File Reference
DataFlash_test.pde File Reference
#include <AP_HAL.h>
#include <AP_HAL_AVR.h>
#include <AP_HAL_SITL.h>
#include <AP_HAL_Empty.h>
#include <AP_HAL_PX4.h>
#include <AP_Common.h>
#include <AP_Param.h>
#include <AP_Progmem.h>
#include <AP_Math.h>
#include <AP_Compass.h>
#include <Filter.h>
#include <AP_Declination.h>
#include <AP_Airspeed.h>
#include <AP_Baro.h>
#include <AP_AHRS.h>
#include <AP_ADC.h>
#include <AP_ADC_AnalogSource.h>
#include <AP_InertialSensor.h>
#include <AP_GPS.h>
#include <DataFlash.h>
#include <GCS_MAVLink.h>
#include <AP_Mission.h>
#include <StorageManager.h>
#include <AP_Terrain.h>
#include <AP_Notify.h>
#include <AP_Vehicle.h>
#include <AP_NavEKF.h>
#include <AP_Rally.h>
#include <AP_Scheduler.h>
#include <AP_BattMonitor.h>
Classes
struct log_Test
Macros
#define LOG_TEST_MSG 1
#define NUM_PACKETS 500
Functions
void setup ()
static void print_mode (AP_HAL::BetterStream *port, uint8_t mode)
void loop ()
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL_BOARD_DRIVER
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
DataFlash_APM2 DataFlash
static const struct
LogStructure log_structure[] PROGMEM
static uint16_t log_num
Macro Definition Documentation
#define LOG_TEST_MSG 1
Definition at line 51 of file DataFlash_test.pde.
Referenced by setup().
#define NUM_PACKETS 500
Definition at line 65 of file DataFlash_test.pde.
Referenced by setup().
Function Documentation
AP_HAL_MAIN ()
void loop (void)
Definition at line 127 of file DataFlash_test.pde.
static void print_mode (AP_HAL::BetterStream * port, uint8_t mode) static
Definition at line 122 of file DataFlash_test.pde.
Referenced by DataFlash_Class::_print_log_entry(), DataFlash_Block::LogReadProcess(), and loop().
void setup (void)
Definition at line 69 of file DataFlash_test.pde.
Variable Documentation
DataFlash_APM2 DataFlash
Definition at line 44 of file DataFlash_test.pde.
const AP_HAL::HAL& hal = AP_HAL_BOARD_DRIVER
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 41 of file DataFlash_test.pde.
uint16_t log_num static
Definition at line 67 of file DataFlash_test.pde.
const struct LogStructure log_structure [] PROGMEM static
Initial value:
= {
    LOG_COMMON_STRUCTURES,
    { LOG_TEST_MSG, sizeof(log_Test),
      "TEST", "HHHHii",        "V1,V2,V3,V4,L1,L2" }
}
Definition at line 59 of file DataFlash_test.pde.