APM:Libraries: libraries/AP_Math/examples/eulers/eulers.pde File Reference
eulers.pde File Reference
#include <AP_HAL.h>
#include <stdlib.h>
#include <AP_Common.h>
#include <AP_Progmem.h>
#include <AP_Param.h>
#include <AP_HAL_AVR.h>
#include <AP_HAL_SITL.h>
#include <AP_HAL_Empty.h>
#include <AP_HAL_PX4.h>
#include <AP_HAL_Linux.h>
#include <AP_Math.h>
#include <Filter.h>
#include <AP_ADC.h>
#include <SITL.h>
#include <AP_Compass.h>
#include <AP_Baro.h>
#include <AP_Notify.h>
#include <AP_InertialSensor.h>
#include <AP_GPS.h>
#include <DataFlash.h>
#include <GCS_MAVLink.h>
#include <AP_Mission.h>
#include <StorageManager.h>
#include <AP_Terrain.h>
#include <AP_Declination.h>
#include <AP_AHRS.h>
#include <AP_NavEKF.h>
#include <AP_Airspeed.h>
#include <AP_Vehicle.h>
#include <AP_ADC_AnalogSource.h>
#include <AP_Rally.h>
#include <AP_BattMonitor.h>
#include <AP_RangeFinder.h>
Macros
#define SHOW_POLES_BREAKDOWN 0
#define ARRAY_LENGTH(x) (sizeof((x))/sizeof((x)[0]))
Functions
static float rad_diff (float rad1, float rad2)
static void check_result (const char *msg, float roll, float pitch, float yaw, float roll2, float pitch2, float yaw2)
static void test_euler (float roll, float pitch, float yaw)
void test_matrix_eulers (void)
static void test_quaternion (float roll, float pitch, float yaw)
void test_quaternion_eulers (void)
static void test_conversion (float roll, float pitch, float yaw)
void test_conversions (void)
void test_frame_transforms (void)
static float rand_num (void)
void test_matrix_rotate (void)
void setup (void)
void loop (void)
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL_BOARD_DRIVER
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
static const float angles []
Macro Definition Documentation
#define ARRAY_LENGTH (x) (sizeof((x))/sizeof((x)[0]))
Definition at line 111 of file eulers.pde.
Referenced by test_conversions(), test_matrix_eulers(), and test_quaternion_eulers().
#define SHOW_POLES_BREAKDOWN 0
Definition at line 42 of file eulers.pde.
Function Documentation
AP_HAL_MAIN ()
static void check_result (const char * msg, float roll, float pitch, float yaw, float roll2, float pitch2, float yaw2) static
Definition at line 56 of file eulers.pde.
Referenced by test_conversion(), test_euler(), and test_quaternion().
void loop (void)
Definition at line 329 of file eulers.pde.
static float rad_diff (float rad1, float rad2) static
Definition at line 44 of file eulers.pde.
Referenced by check_result().
static float rand_num (void) static
Definition at line 268 of file eulers.pde.
Referenced by test_matrix_rotate().
void setup (void)
Definition at line 316 of file eulers.pde.
static void test_conversion (float roll, float pitch, float yaw) static
Definition at line 189 of file eulers.pde.
Referenced by setup(), and test_conversions().
void test_conversions (void)
Definition at line 215 of file eulers.pde.
Referenced by setup().
static void test_euler (float roll, float pitch, float yaw) static
Definition at line 101 of file eulers.pde.
Referenced by test_matrix_eulers().
void test_frame_transforms (void)
Definition at line 236 of file eulers.pde.
Referenced by setup().
void test_matrix_eulers (void)
Definition at line 116 of file eulers.pde.
Referenced by setup().
void test_matrix_rotate (void)
Definition at line 274 of file eulers.pde.
Referenced by setup().
static void test_quaternion (float roll, float pitch, float yaw) static
Definition at line 131 of file eulers.pde.
Referenced by test_quaternion_eulers().
void test_quaternion_eulers (void)
Definition at line 155 of file eulers.pde.
Referenced by setup().
Variable Documentation
const float angles[] static
Initial value:
= { 0, PI/8, PI/4, PI/2, PI,
                                -PI/8, -PI/4, -PI/2, -PI}
Definition at line 113 of file eulers.pde.
Referenced by test_conversions(), test_matrix_eulers(), and test_quaternion_eulers().
const AP_HAL::HAL& hal = AP_HAL_BOARD_DRIVER
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 40 of file eulers.pde.