APM:Libraries: libraries/GCS_MAVLink/GCS_MAVLink.h File Reference
GCS_MAVLink.h File Reference
One size fits all header for MAVLink integration.
#include <AP_HAL.h>
#include <AP_Param.h>
#include <AP_Math.h>
#include <util/crc16.h>
#include "include/mavlink/v1.0/ardupilotmega/version.h"
#include "include/mavlink/v1.0/mavlink_types.h"
#include "include/mavlink/v1.0/ardupilotmega/mavlink.h"
Macros
#define MAVLINK_SEPARATE_HELPERS
#define MAVLINK_SEND_UART_BYTES(chan, buf, len) comm_send_buffer(chan, buf, len)
#define MAVLINK_MESSAGE_CRC(msgid) mavlink_get_message_crc(msgid)
#define HAVE_CRC_ACCUMULATE
#define MAVLINK_COMM_NUM_BUFFERS 2
#define MAVLINK_MAX_PAYLOAD_LEN 104
#define MAVLINK_USE_CONVENIENCE_FUNCTIONS
Enumerations
enum gcs_severity {
SEVERITY_LOW =1, SEVERITY_MEDIUM, SEVERITY_HIGH, SEVERITY_CRITICAL,
SEVERITY_USER_RESPONSE
}
Functions
static void comm_send_ch (mavlink_channel_t chan, uint8_t ch)
void comm_send_buffer (mavlink_channel_t chan, const uint8_t *buf, uint8_t len)
uint8_t comm_receive_ch (mavlink_channel_t chan)
uint16_t comm_get_available (mavlink_channel_t chan)
uint16_t comm_get_txspace (mavlink_channel_t chan)
static void crc_accumulate (uint8_t data, uint16_t *crcAccum)
bool comm_is_idle (mavlink_channel_t chan)
uint8_t mav_var_type (enum ap_var_type t)
uint8_t mavlink_get_message_crc (uint8_t msgid)
Variables
AP_HAL::UARTDriver * mavlink_comm_port [MAVLINK_COMM_NUM_BUFFERS]
MAVLink stream used for uartA.
mavlink_system_t mavlink_system
MAVLink system definition.
Detailed Description
One size fits all header for MAVLink integration.
Definition in file GCS_MAVLink.h.
Macro Definition Documentation
#define HAVE_CRC_ACCUMULATE
Definition at line 25 of file GCS_MAVLink.h.
#define MAVLINK_COMM_NUM_BUFFERS 2
Definition at line 27 of file GCS_MAVLink.h.
Referenced by comm_get_available(), comm_get_txspace(), comm_receive_ch(), comm_send_buffer(), comm_send_ch(), MAVLink_routing::handle_heartbeat(), GCS_MAVLINK::have_flow_control(), GCS_MAVLINK::init(), GCS_MAVLINK::lock_channel(), mavlink_get_channel_buffer(), mavlink_get_channel_status(), AP_GPS::send_mavlink_gps_raw(), GCS_MAVLINK::send_statustext_all(), and MAVLink_routing::send_to_components().
#define MAVLINK_MAX_PAYLOAD_LEN 104
Definition at line 46 of file GCS_MAVLink.h.
Referenced by mavlink_frame_char_buffer(), and mavlink_parse_char().
#define MAVLINK_MESSAGE_CRC (msgid) mavlink_get_message_crc(msgid)
Definition at line 21 of file GCS_MAVLink.h.
Referenced by mavlink_frame_char_buffer(), and mavlink_parse_char().
#define MAVLINK_SEND_UART_BYTES (chan, buf, len) comm_send_buffer(chan, buf, len)
Definition at line 17 of file GCS_MAVLink.h.
#define MAVLINK_SEPARATE_HELPERS
Definition at line 15 of file GCS_MAVLink.h.
#define MAVLINK_USE_CONVENIENCE_FUNCTIONS
Definition at line 110 of file GCS_MAVLink.h.
Enumeration Type Documentation
enum gcs_severity
Enumerator
SEVERITY_LOW
SEVERITY_MEDIUM
SEVERITY_HIGH
SEVERITY_CRITICAL
SEVERITY_USER_RESPONSE
Definition at line 120 of file GCS_MAVLink.h.
Function Documentation
uint16_t comm_get_available (mavlink_channel_t chan)
Check for available data on the nominated MAVLink channel
Parameters
chan Channel to check
Returns
Number of bytes available
Definition at line 119 of file GCS_MAVLink.cpp.
Referenced by simplegcs_update(), and GCS_MAVLINK::update().
uint16_t comm_get_txspace (mavlink_channel_t chan)
Check for available transmit space on the nominated MAVLink channel
Parameters
chan Channel to check
Returns
Number of bytes available
Definition at line 99 of file GCS_MAVLink.cpp.
Referenced by MAVLink_routing::check_and_forward(), gcs_console_send(), MAVLink_routing::handle_heartbeat(), GCS_MAVLINK::handle_log_send_data(), GCS_MAVLINK::handle_log_send_listing(), GCS_MAVLINK::handle_mission_item(), GCS_MAVLINK::queued_param_send(), GCS_MAVLINK::send_gps_raw(), GCS_MAVLINK::send_radio_in(), GCS_MAVLINK::send_statustext_all(), GCS_MAVLINK::send_text(), MAVLink_routing::send_to_components(), try_send_message(), and try_send_statustext().
bool comm_is_idle (mavlink_channel_t chan)
Definition at line 161 of file GCS_MAVLink.cpp.
Referenced by GCS_MAVLINK::update().
uint8_t comm_receive_ch (mavlink_channel_t chan)
Read a byte from the nominated MAVLink channel
Parameters
chan Channel to receive on
Returns
Byte read
Definition at line 85 of file GCS_MAVLink.cpp.
Referenced by simplegcs_update(), and GCS_MAVLINK::update().
void comm_send_buffer (mavlink_channel_t chan, const uint8_t * buf, uint8_t len)
Definition at line 138 of file GCS_MAVLink.cpp.
static void comm_send_ch (mavlink_channel_t chan, uint8_t ch) inline static
Send a byte to the nominated MAVLink channel
Parameters
chan Channel to send to
ch Byte to send
Definition at line 64 of file GCS_MAVLink.h.
Referenced by mavlink_test_action(), mavlink_test_action_ack(), mavlink_test_actuator_control_target(), mavlink_test_ahrs(), mavlink_test_ahrs2(), mavlink_test_ahrs3(), mavlink_test_airspeed_autocal(), mavlink_test_ap_adc(), mavlink_test_att_pos_mocap(), mavlink_test_attitude(), mavlink_test_attitude_quaternion(), mavlink_test_attitude_quaternion_cov(), mavlink_test_attitude_target(), mavlink_test_auth_key(), mavlink_test_autopilot_version(), mavlink_test_autopilot_version_request(), mavlink_test_battery2(), mavlink_test_battery_status(), mavlink_test_boot(), mavlink_test_camera_feedback(), mavlink_test_camera_status(), mavlink_test_change_operator_control(), mavlink_test_change_operator_control_ack(), mavlink_test_command(), mavlink_test_command_ack(), mavlink_test_command_int(), mavlink_test_command_long(), mavlink_test_compassmot_status(), mavlink_test_control_status(), mavlink_test_data16(), mavlink_test_data32(), mavlink_test_data64(), mavlink_test_data96(), mavlink_test_data_stream(), mavlink_test_data_transmission_handshake(), mavlink_test_debug(), mavlink_test_debug_vect(), mavlink_test_digicam_configure(), mavlink_test_digicam_control(), mavlink_test_distance_sensor(), mavlink_test_ekf_status_report(), mavlink_test_encapsulated_data(), mavlink_test_fence_fetch_point(), mavlink_test_fence_point(), mavlink_test_fence_status(), mavlink_test_file_transfer_protocol(), mavlink_test_gimbal_axis_calibration_progress(), mavlink_test_gimbal_control(), mavlink_test_gimbal_erase_firmware_and_config(), mavlink_test_gimbal_factory_parameters_loaded(), mavlink_test_gimbal_home_offset_calibration_result(), mavlink_test_gimbal_perform_factory_tests(), mavlink_test_gimbal_report(), mavlink_test_gimbal_report_axis_calibration_status(), mavlink_test_gimbal_report_factory_tests_progress(), mavlink_test_gimbal_request_axis_calibration(), mavlink_test_gimbal_request_axis_calibration_status(), mavlink_test_gimbal_reset(), mavlink_test_gimbal_set_factory_parameters(), mavlink_test_gimbal_set_home_offsets(), mavlink_test_global_position(), mavlink_test_global_position_int(), mavlink_test_global_position_int_cov(), mavlink_test_global_vision_position_estimate(), mavlink_test_gopro_get_request(), mavlink_test_gopro_get_response(), mavlink_test_gopro_heartbeat(), mavlink_test_gopro_set_request(), mavlink_test_gopro_set_response(), mavlink_test_gps2_raw(), mavlink_test_gps2_rtk(), mavlink_test_gps_global_origin(), mavlink_test_gps_inject_data(), mavlink_test_gps_local_origin_set(), mavlink_test_gps_raw(), mavlink_test_gps_raw_int(), mavlink_test_gps_rtk(), mavlink_test_gps_set_global_origin(), mavlink_test_gps_status(), mavlink_test_heartbeat(), mavlink_test_highres_imu(), mavlink_test_hil_controls(), mavlink_test_hil_gps(), mavlink_test_hil_optical_flow(), mavlink_test_hil_rc_inputs_raw(), mavlink_test_hil_sensor(), mavlink_test_hil_state(), mavlink_test_hil_state_quaternion(), mavlink_test_hwstatus(), mavlink_test_led_control(), mavlink_test_limits_status(), mavlink_test_local_position(), mavlink_test_local_position_ned(), mavlink_test_local_position_ned_cov(), mavlink_test_local_position_ned_system_global_offset(), mavlink_test_local_position_setpoint(), mavlink_test_local_position_setpoint_set(), mavlink_test_log_data(), mavlink_test_log_entry(), mavlink_test_log_erase(), mavlink_test_log_request_data(), mavlink_test_log_request_end(), mavlink_test_log_request_list(), mavlink_test_manual_control(), mavlink_test_manual_setpoint(), mavlink_test_meminfo(), mavlink_test_memory_vect(), mavlink_test_mission_ack(), mavlink_test_mission_clear_all(), mavlink_test_mission_count(), mavlink_test_mission_current(), mavlink_test_mission_item(), mavlink_test_mission_item_int(), mavlink_test_mission_item_reached(), mavlink_test_mission_request(), mavlink_test_mission_request_list(), mavlink_test_mission_request_partial_list(), mavlink_test_mission_set_current(), mavlink_test_mission_write_partial_list(), mavlink_test_mount_configure(), mavlink_test_mount_control(), mavlink_test_mount_status(), mavlink_test_named_value_float(), mavlink_test_named_value_int(), mavlink_test_nav_controller_output(), mavlink_test_object_detection_event(), mavlink_test_optical_flow(), mavlink_test_optical_flow_rad(), mavlink_test_param_map_rc(), mavlink_test_param_request_list(), mavlink_test_param_request_read(), mavlink_test_param_set(), mavlink_test_param_value(), mavlink_test_ping(), mavlink_test_position_target(), mavlink_test_position_target_global_int(), mavlink_test_position_target_local_ned(), mavlink_test_power_status(), mavlink_test_radio(), mavlink_test_radio_status(), mavlink_test_rally_fetch_point(), mavlink_test_rally_point(), mavlink_test_rangefinder(), mavlink_test_raw_imu(), mavlink_test_raw_pressure(), mavlink_test_rc_channels(), mavlink_test_rc_channels_override(), mavlink_test_rc_channels_raw(), mavlink_test_rc_channels_scaled(), mavlink_test_request_data_stream(), mavlink_test_roll_pitch_yaw_speed_thrust_setpoint(), mavlink_test_roll_pitch_yaw_thrust_setpoint(), mavlink_test_safety_allowed_area(), mavlink_test_safety_set_allowed_area(), mavlink_test_scaled_imu(), mavlink_test_scaled_imu2(), mavlink_test_scaled_imu3(), mavlink_test_scaled_pressure(), mavlink_test_scaled_pressure2(), mavlink_test_sensor_offsets(), mavlink_test_serial_control(), mavlink_test_servo_output_raw(), mavlink_test_set_actuator_control_target(), mavlink_test_set_altitude(), mavlink_test_set_attitude_target(), mavlink_test_set_gps_global_origin(), mavlink_test_set_mag_offsets(), mavlink_test_set_mode(), mavlink_test_set_nav_mode(), mavlink_test_set_position_target_global_int(), mavlink_test_set_position_target_local_ned(), mavlink_test_set_roll_pitch_yaw_speed_thrust(), mavlink_test_set_roll_pitch_yaw_thrust(), mavlink_test_sim_state(), mavlink_test_simstate(), mavlink_test_state_correction(), mavlink_test_statustext(), mavlink_test_sys_status(), mavlink_test_system_time(), mavlink_test_system_time_utc(), mavlink_test_terrain_check(), mavlink_test_terrain_data(), mavlink_test_terrain_report(), mavlink_test_terrain_request(), mavlink_test_timesync(), mavlink_test_v2_extension(), mavlink_test_vfr_hud(), mavlink_test_vicon_position_estimate(), mavlink_test_vision_position_estimate(), mavlink_test_vision_speed_estimate(), mavlink_test_waypoint(), mavlink_test_waypoint_ack(), mavlink_test_waypoint_clear_all(), mavlink_test_waypoint_count(), mavlink_test_waypoint_current(), mavlink_test_waypoint_reached(), mavlink_test_waypoint_request(), mavlink_test_waypoint_request_list(), mavlink_test_waypoint_set_current(), and mavlink_test_wind().
static void crc_accumulate (uint8_t data, uint16_t * crcAccum) inline static
Definition at line 98 of file GCS_MAVLink.h.
Referenced by mavlink_finalize_message_chan(), and mavlink_update_checksum().
uint8_t mav_var_type (enum ap_var_type t)
Definition at line 64 of file GCS_MAVLink.cpp.
Referenced by GCS_MAVLINK::handle_param_request_read(), GCS_MAVLINK::handle_param_set(), and GCS_MAVLINK::queued_param_send().
uint8_t mavlink_get_message_crc (uint8_t msgid)
Definition at line 150 of file GCS_MAVLink.cpp.
Variable Documentation
AP_HAL::UARTDriver* mavlink_comm_port[MAVLINK_COMM_NUM_BUFFERS]
MAVLink stream used for uartA.
Definition at line 34 of file GCS_MAVLink.cpp.
Referenced by GCS_MAVLINK::have_flow_control(), GCS_MAVLINK::init(), and setup().
mavlink_system_t mavlink_system
MAVLink system definition.
Definition at line 36 of file GCS_MAVLink.cpp.