APM:Libraries: libraries/AP_HAL_Linux/HAL_Linux_Class.cpp File Reference
HAL_Linux_Class.cpp File Reference
#include <AP_HAL.h>
#include "HAL_Linux_Class.h"
#include "AP_HAL_Linux_Private.h"
#include <getopt.h>
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <AP_HAL_Empty.h>
#include <AP_HAL_Empty_Private.h>
Functions
void _usage (void)
Variables
static LinuxUARTDriver uartADriver (true)
static LinuxSPIUARTDriver uartBDriver
static LinuxUARTDriver uartCDriver (false)
static LinuxUARTDriver uartEDriver (false)
static LinuxSemaphore i2cSemaphore
static LinuxSPIDeviceManager spiDeviceManager
static NavioAnalogIn analogIn
static LinuxStorage_FRAM storageDriver
static LinuxGPIO_BBB gpioDriver
static LinuxRCInput_PRU rcinDriver
static LinuxRCOutput_PRU rcoutDriver
static LinuxScheduler schedulerInstance
static LinuxUtil utilInstance
const HAL_Linux AP_HAL_Linux
Function Documentation
void _usage (void)
Definition at line 114 of file HAL_Linux_Class.cpp.
Referenced by HAL_Linux::init().
Variable Documentation
NavioAnalogIn analogIn static
Definition at line 31 of file HAL_Linux_Class.cpp.
const HAL_Linux AP_HAL_Linux
Definition at line 165 of file HAL_Linux_Class.cpp.
LinuxGPIO_BBB gpioDriver static
Definition at line 49 of file HAL_Linux_Class.cpp.
static LinuxI2CDriver i2cDriver & i2cSemaphore static
Definition at line 27 of file HAL_Linux_Class.cpp.
LinuxRCInput_PRU rcinDriver static
Definition at line 63 of file HAL_Linux_Class.cpp.
LinuxRCOutput_PRU rcoutDriver static
Definition at line 78 of file HAL_Linux_Class.cpp.
LinuxScheduler schedulerInstance static
Definition at line 92 of file HAL_Linux_Class.cpp.
LinuxSPIDeviceManager spiDeviceManager static
Definition at line 29 of file HAL_Linux_Class.cpp.
LinuxStorage_FRAM storageDriver static
Definition at line 40 of file HAL_Linux_Class.cpp.
LinuxUARTDriver uartADriver(true) static
Referenced by HAL_Linux::init().
LinuxSPIUARTDriver uartBDriver static
Definition at line 20 of file HAL_Linux_Class.cpp.
Referenced by HAL_Linux::init().
LinuxUARTDriver uartCDriver(false) static
Referenced by HAL_Linux::init().
LinuxUARTDriver uartEDriver(false) static
Referenced by HAL_Linux::init().
LinuxUtil utilInstance static
Definition at line 93 of file HAL_Linux_Class.cpp.
Referenced by HAL_Linux::init().