APM:Libraries: libraries/AP_InertialSensor/examples/INS_generic/INS_generic.pde File Reference
INS_generic.pde File Reference
#include <stdarg.h>
#include <AP_Common.h>
#include <AP_Progmem.h>
#include <AP_HAL.h>
#include <AP_HAL_AVR.h>
#include <AP_HAL_SITL.h>
#include <AP_HAL_Linux.h>
#include <AP_HAL_FLYMAPLE.h>
#include <AP_HAL_PX4.h>
#include <AP_HAL_Empty.h>
#include <AP_Math.h>
#include <AP_Param.h>
#include <StorageManager.h>
#include <AP_ADC.h>
#include <AP_InertialSensor.h>
#include <AP_Notify.h>
#include <AP_GPS.h>
#include <AP_Baro.h>
#include <Filter.h>
#include <DataFlash.h>
#include <GCS_MAVLink.h>
#include <AP_Mission.h>
#include <AP_Terrain.h>
#include <AP_AHRS.h>
#include <AP_Airspeed.h>
#include <AP_Vehicle.h>
#include <AP_ADC_AnalogSource.h>
#include <AP_Compass.h>
#include <AP_Declination.h>
#include <AP_NavEKF.h>
#include <AP_Rally.h>
#include <AP_Scheduler.h>
#include <AP_BattMonitor.h>
#include <AP_RangeFinder.h>
Functions
void setup (void)
void loop (void)
void run_calibration ()
void display_offsets_and_scaling ()
void run_test ()
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL_BOARD_DRIVER
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
AP_InertialSensor ins
AP_ADC_ADS7844 apm1_adc
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Function Documentation
AP_HAL_MAIN ()
void display_offsets_and_scaling ()
Definition at line 128 of file INS_generic.pde.
Referenced by loop(), and setup().
void loop (void)
Definition at line 70 of file INS_generic.pde.
void run_calibration ()
Definition at line 111 of file INS_generic.pde.
Referenced by loop().
void run_test ()
Definition at line 152 of file INS_generic.pde.
Referenced by loop().
void setup (void)
Definition at line 52 of file INS_generic.pde.
Variable Documentation
AP_ADC_ADS7844 apm1_adc
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Definition at line 49 of file INS_generic.pde.
const AP_HAL::HAL& hal = AP_HAL_BOARD_DRIVER
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 44 of file INS_generic.pde.
AP_InertialSensor ins
Definition at line 46 of file INS_generic.pde.