APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_waypoint_current.h File Reference
mavlink_msg_waypoint_current.h File Reference
Classes
struct __mavlink_waypoint_current_t
Macros
#define MAVLINK_MSG_ID_WAYPOINT_CURRENT 42
#define MAVLINK_MSG_ID_WAYPOINT_CURRENT_LEN 2
#define MAVLINK_MSG_ID_42_LEN 2
#define MAVLINK_MESSAGE_INFO_WAYPOINT_CURRENT
Typedefs
typedef struct
__mavlink_waypoint_current_t mavlink_waypoint_current_t
Functions
static uint16_t mavlink_msg_waypoint_current_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint16_t seq)
Pack a waypoint_current message.
static uint16_t mavlink_msg_waypoint_current_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint16_t seq)
Pack a waypoint_current message on a channel.
static uint16_t mavlink_msg_waypoint_current_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_waypoint_current_t *waypoint_current)
Encode a waypoint_current struct into a message.
static uint16_t mavlink_msg_waypoint_current_get_seq (const mavlink_message_t *msg)
Send a waypoint_current message.
static void mavlink_msg_waypoint_current_decode (const mavlink_message_t *msg, mavlink_waypoint_current_t *waypoint_current)
Decode a waypoint_current message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_WAYPOINT_CURRENT
Value:
{ \
    "WAYPOINT_CURRENT", \
    1, \
    {  { "seq", NULL, MAVLINK_TYPE_UINT16_T, 0, 0, offsetof(mavlink_waypoint_current_t, seq) }, \
         } \
}
Definition at line 15 of file mavlink_msg_waypoint_current.h.
#define MAVLINK_MSG_ID_42_LEN 2
Definition at line 11 of file mavlink_msg_waypoint_current.h.
#define MAVLINK_MSG_ID_WAYPOINT_CURRENT 42
Definition at line 3 of file mavlink_msg_waypoint_current.h.
Referenced by mavlink_msg_waypoint_current_pack(), and mavlink_msg_waypoint_current_pack_chan().
#define MAVLINK_MSG_ID_WAYPOINT_CURRENT_LEN 2
Definition at line 10 of file mavlink_msg_waypoint_current.h.
Typedef Documentation
typedef struct __mavlink_waypoint_current_t mavlink_waypoint_current_t
Function Documentation
static void mavlink_msg_waypoint_current_decode (const mavlink_message_t * msg, mavlink_waypoint_current_t * waypoint_current) inline static
Decode a waypoint_current message into a struct.
Parameters
msg The message to decode
waypoint_current C-struct to decode the message contents into
Definition at line 137 of file mavlink_msg_waypoint_current.h.
Referenced by mavlink_test_waypoint_current().
static uint16_t mavlink_msg_waypoint_current_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_waypoint_current_t * waypoint_current) inline static
Encode a waypoint_current struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
waypoint_current C-struct to read the message contents from
Definition at line 88 of file mavlink_msg_waypoint_current.h.
Referenced by mavlink_test_waypoint_current().
static uint16_t mavlink_msg_waypoint_current_get_seq (const mavlink_message_t * msg) inline static
Send a waypoint_current message.
Parameters
chan MAVLink channel to send the message
seq Sequence Get field seq from waypoint_current message
Returns
Sequence
Definition at line 126 of file mavlink_msg_waypoint_current.h.
Referenced by mavlink_msg_waypoint_current_decode().
static uint16_t mavlink_msg_waypoint_current_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint16_t seq) inline static
Pack a waypoint_current message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
seq Sequence
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 32 of file mavlink_msg_waypoint_current.h.
Referenced by mavlink_msg_waypoint_current_encode(), and mavlink_test_waypoint_current().
static uint16_t mavlink_msg_waypoint_current_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint16_t seq) inline static
Pack a waypoint_current message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
seq Sequence
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 60 of file mavlink_msg_waypoint_current.h.
Referenced by mavlink_test_waypoint_current().