APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_set_altitude.h File Reference
mavlink_msg_set_altitude.h File Reference
Classes
struct __mavlink_set_altitude_t
Macros
#define MAVLINK_MSG_ID_SET_ALTITUDE 65
#define MAVLINK_MSG_ID_SET_ALTITUDE_LEN 5
#define MAVLINK_MSG_ID_65_LEN 5
#define MAVLINK_MESSAGE_INFO_SET_ALTITUDE
Typedefs
typedef struct
__mavlink_set_altitude_t mavlink_set_altitude_t
Functions
static uint16_t mavlink_msg_set_altitude_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target, uint32_t mode)
Pack a set_altitude message.
static uint16_t mavlink_msg_set_altitude_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target, uint32_t mode)
Pack a set_altitude message on a channel.
static uint16_t mavlink_msg_set_altitude_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_set_altitude_t *set_altitude)
Encode a set_altitude struct into a message.
static uint8_t mavlink_msg_set_altitude_get_target (const mavlink_message_t *msg)
Send a set_altitude message.
static uint32_t mavlink_msg_set_altitude_get_mode (const mavlink_message_t *msg)
Get field mode from set_altitude message.
static void mavlink_msg_set_altitude_decode (const mavlink_message_t *msg, mavlink_set_altitude_t *set_altitude)
Decode a set_altitude message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_SET_ALTITUDE
Value:
{ \
    "SET_ALTITUDE", \
    2, \
    {  { "target", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_set_altitude_t, target) }, \
         { "mode", NULL, MAVLINK_TYPE_UINT32_T, 0, 1, offsetof(mavlink_set_altitude_t, mode) }, \
         } \
}
Definition at line 16 of file mavlink_msg_set_altitude.h.
#define MAVLINK_MSG_ID_65_LEN 5
Definition at line 12 of file mavlink_msg_set_altitude.h.
#define MAVLINK_MSG_ID_SET_ALTITUDE 65
Definition at line 3 of file mavlink_msg_set_altitude.h.
Referenced by mavlink_msg_set_altitude_pack(), and mavlink_msg_set_altitude_pack_chan().
#define MAVLINK_MSG_ID_SET_ALTITUDE_LEN 5
Definition at line 11 of file mavlink_msg_set_altitude.h.
Typedef Documentation
typedef struct __mavlink_set_altitude_t mavlink_set_altitude_t
Function Documentation
static void mavlink_msg_set_altitude_decode (const mavlink_message_t * msg, mavlink_set_altitude_t * set_altitude) inline static
Decode a set_altitude message into a struct.
Parameters
msg The message to decode
set_altitude C-struct to decode the message contents into
Definition at line 158 of file mavlink_msg_set_altitude.h.
Referenced by mavlink_test_set_altitude().
static uint16_t mavlink_msg_set_altitude_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_set_altitude_t * set_altitude) inline static
Encode a set_altitude struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
set_altitude C-struct to read the message contents from
Definition at line 96 of file mavlink_msg_set_altitude.h.
Referenced by mavlink_test_set_altitude().
static uint32_t mavlink_msg_set_altitude_get_mode (const mavlink_message_t * msg) inline static
Get field mode from set_altitude message.
Returns
The new altitude in meters
Definition at line 147 of file mavlink_msg_set_altitude.h.
Referenced by mavlink_msg_set_altitude_decode().
static uint8_t mavlink_msg_set_altitude_get_target (const mavlink_message_t * msg) inline static
Send a set_altitude message.
Parameters
chan MAVLink channel to send the message
target The system setting the altitude
mode The new altitude in meters Get field target from set_altitude message
Returns
The system setting the altitude
Definition at line 137 of file mavlink_msg_set_altitude.h.
Referenced by mavlink_msg_set_altitude_decode().
static uint16_t mavlink_msg_set_altitude_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target, uint32_t mode) inline static
Pack a set_altitude message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target The system setting the altitude
mode The new altitude in meters
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 35 of file mavlink_msg_set_altitude.h.
Referenced by mavlink_msg_set_altitude_encode(), and mavlink_test_set_altitude().
static uint16_t mavlink_msg_set_altitude_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target, uint32_t mode) inline static
Pack a set_altitude message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
target The system setting the altitude
mode The new altitude in meters
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 66 of file mavlink_msg_set_altitude.h.
Referenced by mavlink_test_set_altitude().