APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_action_ack.h File Reference
mavlink_msg_action_ack.h File Reference
Classes
struct __mavlink_action_ack_t
Macros
#define MAVLINK_MSG_ID_ACTION_ACK 9
#define MAVLINK_MSG_ID_ACTION_ACK_LEN 2
#define MAVLINK_MSG_ID_9_LEN 2
#define MAVLINK_MESSAGE_INFO_ACTION_ACK
Typedefs
typedef struct
__mavlink_action_ack_t mavlink_action_ack_t
Functions
static uint16_t mavlink_msg_action_ack_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t action, uint8_t result)
Pack a action_ack message.
static uint16_t mavlink_msg_action_ack_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t action, uint8_t result)
Pack a action_ack message on a channel.
static uint16_t mavlink_msg_action_ack_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_action_ack_t *action_ack)
Encode a action_ack struct into a message.
static uint8_t mavlink_msg_action_ack_get_action (const mavlink_message_t *msg)
Send a action_ack message.
static uint8_t mavlink_msg_action_ack_get_result (const mavlink_message_t *msg)
Get field result from action_ack message.
static void mavlink_msg_action_ack_decode (const mavlink_message_t *msg, mavlink_action_ack_t *action_ack)
Decode a action_ack message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_ACTION_ACK
Value:
{ \
    "ACTION_ACK", \
    2, \
    {  { "action", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_action_ack_t, action) }, \
         { "result", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_action_ack_t, result) }, \
         } \
}
Definition at line 16 of file mavlink_msg_action_ack.h.
#define MAVLINK_MSG_ID_9_LEN 2
Definition at line 12 of file mavlink_msg_action_ack.h.
#define MAVLINK_MSG_ID_ACTION_ACK 9
Definition at line 3 of file mavlink_msg_action_ack.h.
Referenced by mavlink_msg_action_ack_pack(), and mavlink_msg_action_ack_pack_chan().
#define MAVLINK_MSG_ID_ACTION_ACK_LEN 2
Definition at line 11 of file mavlink_msg_action_ack.h.
Typedef Documentation
typedef struct __mavlink_action_ack_t mavlink_action_ack_t
Function Documentation
static void mavlink_msg_action_ack_decode (const mavlink_message_t * msg, mavlink_action_ack_t * action_ack) inline static
Decode a action_ack message into a struct.
Parameters
msg The message to decode
action_ack C-struct to decode the message contents into
Definition at line 158 of file mavlink_msg_action_ack.h.
Referenced by mavlink_test_action_ack().
static uint16_t mavlink_msg_action_ack_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_action_ack_t * action_ack) inline static
Encode a action_ack struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
action_ack C-struct to read the message contents from
Definition at line 96 of file mavlink_msg_action_ack.h.
Referenced by mavlink_test_action_ack().
static uint8_t mavlink_msg_action_ack_get_action (const mavlink_message_t * msg) inline static
Send a action_ack message.
Parameters
chan MAVLink channel to send the message
action The action id
result 0: Action DENIED, 1: Action executed Get field action from action_ack message
Returns
The action id
Definition at line 137 of file mavlink_msg_action_ack.h.
Referenced by mavlink_msg_action_ack_decode().
static uint8_t mavlink_msg_action_ack_get_result (const mavlink_message_t * msg) inline static
Get field result from action_ack message.
Returns
0: Action DENIED, 1: Action executed
Definition at line 147 of file mavlink_msg_action_ack.h.
Referenced by mavlink_msg_action_ack_decode().
static uint16_t mavlink_msg_action_ack_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t action, uint8_t result) inline static
Pack a action_ack message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
action The action id
result 0: Action DENIED, 1: Action executed
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 35 of file mavlink_msg_action_ack.h.
Referenced by mavlink_msg_action_ack_encode(), and mavlink_test_action_ack().
static uint16_t mavlink_msg_action_ack_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t action, uint8_t result) inline static
Pack a action_ack message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
action The action id
result 0: Action DENIED, 1: Action executed
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 66 of file mavlink_msg_action_ack.h.
Referenced by mavlink_test_action_ack().