APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_gps_set_global_origin.h File Reference
mavlink_msg_gps_set_global_origin.h File Reference
Classes
struct __mavlink_gps_set_global_origin_t
Macros
#define MAVLINK_MSG_ID_GPS_SET_GLOBAL_ORIGIN 48
#define MAVLINK_MSG_ID_GPS_SET_GLOBAL_ORIGIN_LEN 14
#define MAVLINK_MSG_ID_48_LEN 14
#define MAVLINK_MESSAGE_INFO_GPS_SET_GLOBAL_ORIGIN
Typedefs
typedef struct
__mavlink_gps_set_global_origin_t mavlink_gps_set_global_origin_t
Functions
static uint16_t mavlink_msg_gps_set_global_origin_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, int32_t latitude, int32_t longitude, int32_t altitude)
Pack a gps_set_global_origin message.
static uint16_t mavlink_msg_gps_set_global_origin_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, int32_t latitude, int32_t longitude, int32_t altitude)
Pack a gps_set_global_origin message on a channel.
static uint16_t mavlink_msg_gps_set_global_origin_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_gps_set_global_origin_t *gps_set_global_origin)
Encode a gps_set_global_origin struct into a message.
static uint8_t mavlink_msg_gps_set_global_origin_get_target_system (const mavlink_message_t *msg)
Send a gps_set_global_origin message.
static uint8_t mavlink_msg_gps_set_global_origin_get_target_component (const mavlink_message_t *msg)
Get field target_component from gps_set_global_origin message.
static int32_t mavlink_msg_gps_set_global_origin_get_latitude (const mavlink_message_t *msg)
Get field latitude from gps_set_global_origin message.
static int32_t mavlink_msg_gps_set_global_origin_get_longitude (const mavlink_message_t *msg)
Get field longitude from gps_set_global_origin message.
static int32_t mavlink_msg_gps_set_global_origin_get_altitude (const mavlink_message_t *msg)
Get field altitude from gps_set_global_origin message.
static void mavlink_msg_gps_set_global_origin_decode (const mavlink_message_t *msg, mavlink_gps_set_global_origin_t *gps_set_global_origin)
Decode a gps_set_global_origin message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GPS_SET_GLOBAL_ORIGIN
Value:
{ \
    "GPS_SET_GLOBAL_ORIGIN", \
    5, \
    {  { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_gps_set_global_origin_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_gps_set_global_origin_t, target_component) }, \
         { "latitude", NULL, MAVLINK_TYPE_INT32_T, 0, 2, offsetof(mavlink_gps_set_global_origin_t, latitude) }, \
         { "longitude", NULL, MAVLINK_TYPE_INT32_T, 0, 6, offsetof(mavlink_gps_set_global_origin_t, longitude) }, \
         { "altitude", NULL, MAVLINK_TYPE_INT32_T, 0, 10, offsetof(mavlink_gps_set_global_origin_t, altitude) }, \
         } \
}
Definition at line 19 of file mavlink_msg_gps_set_global_origin.h.
#define MAVLINK_MSG_ID_48_LEN 14
Definition at line 15 of file mavlink_msg_gps_set_global_origin.h.
#define MAVLINK_MSG_ID_GPS_SET_GLOBAL_ORIGIN 48
Definition at line 3 of file mavlink_msg_gps_set_global_origin.h.
Referenced by mavlink_msg_gps_set_global_origin_pack(), and mavlink_msg_gps_set_global_origin_pack_chan().
#define MAVLINK_MSG_ID_GPS_SET_GLOBAL_ORIGIN_LEN 14
Definition at line 14 of file mavlink_msg_gps_set_global_origin.h.
Typedef Documentation
typedef struct __mavlink_gps_set_global_origin_t mavlink_gps_set_global_origin_t
Function Documentation
static void mavlink_msg_gps_set_global_origin_decode (const mavlink_message_t * msg, mavlink_gps_set_global_origin_t * gps_set_global_origin) inline static
Decode a gps_set_global_origin message into a struct.
Parameters
msg The message to decode
gps_set_global_origin C-struct to decode the message contents into
Definition at line 221 of file mavlink_msg_gps_set_global_origin.h.
Referenced by mavlink_test_gps_set_global_origin().
static uint16_t mavlink_msg_gps_set_global_origin_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_gps_set_global_origin_t * gps_set_global_origin) inline static
Encode a gps_set_global_origin struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gps_set_global_origin C-struct to read the message contents from
Definition at line 120 of file mavlink_msg_gps_set_global_origin.h.
Referenced by mavlink_test_gps_set_global_origin().
static int32_t mavlink_msg_gps_set_global_origin_get_altitude (const mavlink_message_t * msg) inline static
Get field altitude from gps_set_global_origin message.
Returns
global position * 1000
Definition at line 210 of file mavlink_msg_gps_set_global_origin.h.
Referenced by mavlink_msg_gps_set_global_origin_decode().
static int32_t mavlink_msg_gps_set_global_origin_get_latitude (const mavlink_message_t * msg) inline static
Get field latitude from gps_set_global_origin message.
Returns
global position * 1E7
Definition at line 190 of file mavlink_msg_gps_set_global_origin.h.
Referenced by mavlink_msg_gps_set_global_origin_decode().
static int32_t mavlink_msg_gps_set_global_origin_get_longitude (const mavlink_message_t * msg) inline static
Get field longitude from gps_set_global_origin message.
Returns
global position * 1E7
Definition at line 200 of file mavlink_msg_gps_set_global_origin.h.
Referenced by mavlink_msg_gps_set_global_origin_decode().
static uint8_t mavlink_msg_gps_set_global_origin_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from gps_set_global_origin message.
Returns
Component ID
Definition at line 180 of file mavlink_msg_gps_set_global_origin.h.
Referenced by mavlink_msg_gps_set_global_origin_decode().
static uint8_t mavlink_msg_gps_set_global_origin_get_target_system (const mavlink_message_t * msg) inline static
Send a gps_set_global_origin message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
latitude global position * 1E7
longitude global position * 1E7
altitude global position * 1000 Get field target_system from gps_set_global_origin message
Returns
System ID
Definition at line 170 of file mavlink_msg_gps_set_global_origin.h.
Referenced by mavlink_msg_gps_set_global_origin_decode().
static uint16_t mavlink_msg_gps_set_global_origin_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, int32_t latitude, int32_t longitude, int32_t altitude) inline static
Pack a gps_set_global_origin message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
latitude global position * 1E7
longitude global position * 1E7
altitude global position * 1000
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 44 of file mavlink_msg_gps_set_global_origin.h.
Referenced by mavlink_msg_gps_set_global_origin_encode(), and mavlink_test_gps_set_global_origin().
static uint16_t mavlink_msg_gps_set_global_origin_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, int32_t latitude, int32_t longitude, int32_t altitude) inline static
Pack a gps_set_global_origin message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
latitude global position * 1E7
longitude global position * 1E7
altitude global position * 1000
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 84 of file mavlink_msg_gps_set_global_origin.h.
Referenced by mavlink_test_gps_set_global_origin().