APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_set_roll_pitch_yaw_speed_thrust.h File Reference
mavlink_msg_set_roll_pitch_yaw_speed_thrust.h File Reference
Classes
struct __mavlink_set_roll_pitch_yaw_speed_thrust_t
Macros
#define MAVLINK_MSG_ID_SET_ROLL_PITCH_YAW_SPEED_THRUST 56
#define MAVLINK_MSG_ID_SET_ROLL_PITCH_YAW_SPEED_THRUST_LEN 18
#define MAVLINK_MSG_ID_56_LEN 18
#define MAVLINK_MESSAGE_INFO_SET_ROLL_PITCH_YAW_SPEED_THRUST
Typedefs
typedef struct
__mavlink_set_roll_pitch_yaw_speed_thrust_t mavlink_set_roll_pitch_yaw_speed_thrust_t
Functions
static uint16_t mavlink_msg_set_roll_pitch_yaw_speed_thrust_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, float roll_speed, float pitch_speed, float yaw_speed, float thrust)
Pack a set_roll_pitch_yaw_speed_thrust message.
static uint16_t mavlink_msg_set_roll_pitch_yaw_speed_thrust_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, float roll_speed, float pitch_speed, float yaw_speed, float thrust)
Pack a set_roll_pitch_yaw_speed_thrust message on a channel.
static uint16_t mavlink_msg_set_roll_pitch_yaw_speed_thrust_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_set_roll_pitch_yaw_speed_thrust_t *set_roll_pitch_yaw_speed_thrust)
Encode a set_roll_pitch_yaw_speed_thrust struct into a message.
static uint8_t mavlink_msg_set_roll_pitch_yaw_speed_thrust_get_target_system (const mavlink_message_t *msg)
Send a set_roll_pitch_yaw_speed_thrust message.
static uint8_t mavlink_msg_set_roll_pitch_yaw_speed_thrust_get_target_component (const mavlink_message_t *msg)
Get field target_component from set_roll_pitch_yaw_speed_thrust message.
static float mavlink_msg_set_roll_pitch_yaw_speed_thrust_get_roll_speed (const mavlink_message_t *msg)
Get field roll_speed from set_roll_pitch_yaw_speed_thrust message.
static float mavlink_msg_set_roll_pitch_yaw_speed_thrust_get_pitch_speed (const mavlink_message_t *msg)
Get field pitch_speed from set_roll_pitch_yaw_speed_thrust message.
static float mavlink_msg_set_roll_pitch_yaw_speed_thrust_get_yaw_speed (const mavlink_message_t *msg)
Get field yaw_speed from set_roll_pitch_yaw_speed_thrust message.
static float mavlink_msg_set_roll_pitch_yaw_speed_thrust_get_thrust (const mavlink_message_t *msg)
Get field thrust from set_roll_pitch_yaw_speed_thrust message.
static void mavlink_msg_set_roll_pitch_yaw_speed_thrust_decode (const mavlink_message_t *msg, mavlink_set_roll_pitch_yaw_speed_thrust_t *set_roll_pitch_yaw_speed_thrust)
Decode a set_roll_pitch_yaw_speed_thrust message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_SET_ROLL_PITCH_YAW_SPEED_THRUST
Value:
{ \
    "SET_ROLL_PITCH_YAW_SPEED_THRUST", \
    6, \
    {  { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_set_roll_pitch_yaw_speed_thrust_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_set_roll_pitch_yaw_speed_thrust_t, target_component) }, \
         { "roll_speed", NULL, MAVLINK_TYPE_FLOAT, 0, 2, offsetof(mavlink_set_roll_pitch_yaw_speed_thrust_t, roll_speed) }, \
         { "pitch_speed", NULL, MAVLINK_TYPE_FLOAT, 0, 6, offsetof(mavlink_set_roll_pitch_yaw_speed_thrust_t, pitch_speed) }, \
         { "yaw_speed", NULL, MAVLINK_TYPE_FLOAT, 0, 10, offsetof(mavlink_set_roll_pitch_yaw_speed_thrust_t, yaw_speed) }, \
         { "thrust", NULL, MAVLINK_TYPE_FLOAT, 0, 14, offsetof(mavlink_set_roll_pitch_yaw_speed_thrust_t, thrust) }, \
         } \
}
Definition at line 20 of file mavlink_msg_set_roll_pitch_yaw_speed_thrust.h.
#define MAVLINK_MSG_ID_56_LEN 18
Definition at line 16 of file mavlink_msg_set_roll_pitch_yaw_speed_thrust.h.
#define MAVLINK_MSG_ID_SET_ROLL_PITCH_YAW_SPEED_THRUST 56
Definition at line 3 of file mavlink_msg_set_roll_pitch_yaw_speed_thrust.h.
Referenced by mavlink_msg_set_roll_pitch_yaw_speed_thrust_pack(), and mavlink_msg_set_roll_pitch_yaw_speed_thrust_pack_chan().
#define MAVLINK_MSG_ID_SET_ROLL_PITCH_YAW_SPEED_THRUST_LEN 18
Definition at line 15 of file mavlink_msg_set_roll_pitch_yaw_speed_thrust.h.
Typedef Documentation
typedef struct __mavlink_set_roll_pitch_yaw_speed_thrust_t mavlink_set_roll_pitch_yaw_speed_thrust_t
Function Documentation
static void mavlink_msg_set_roll_pitch_yaw_speed_thrust_decode (const mavlink_message_t * msg, mavlink_set_roll_pitch_yaw_speed_thrust_t * set_roll_pitch_yaw_speed_thrust) inline static
Decode a set_roll_pitch_yaw_speed_thrust message into a struct.
Parameters
msg The message to decode
set_roll_pitch_yaw_speed_thrust C-struct to decode the message contents into
Definition at line 242 of file mavlink_msg_set_roll_pitch_yaw_speed_thrust.h.
Referenced by mavlink_test_set_roll_pitch_yaw_speed_thrust().
static uint16_t mavlink_msg_set_roll_pitch_yaw_speed_thrust_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_set_roll_pitch_yaw_speed_thrust_t * set_roll_pitch_yaw_speed_thrust) inline static
Encode a set_roll_pitch_yaw_speed_thrust struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
set_roll_pitch_yaw_speed_thrust C-struct to read the message contents from
Definition at line 128 of file mavlink_msg_set_roll_pitch_yaw_speed_thrust.h.
Referenced by mavlink_test_set_roll_pitch_yaw_speed_thrust().
static float mavlink_msg_set_roll_pitch_yaw_speed_thrust_get_pitch_speed (const mavlink_message_t * msg) inline static
Get field pitch_speed from set_roll_pitch_yaw_speed_thrust message.
Returns
Desired pitch angular speed in rad/s
Definition at line 211 of file mavlink_msg_set_roll_pitch_yaw_speed_thrust.h.
Referenced by mavlink_msg_set_roll_pitch_yaw_speed_thrust_decode().
static float mavlink_msg_set_roll_pitch_yaw_speed_thrust_get_roll_speed (const mavlink_message_t * msg) inline static
Get field roll_speed from set_roll_pitch_yaw_speed_thrust message.
Returns
Desired roll angular speed in rad/s
Definition at line 201 of file mavlink_msg_set_roll_pitch_yaw_speed_thrust.h.
Referenced by mavlink_msg_set_roll_pitch_yaw_speed_thrust_decode().
static uint8_t mavlink_msg_set_roll_pitch_yaw_speed_thrust_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from set_roll_pitch_yaw_speed_thrust message.
Returns
Component ID
Definition at line 191 of file mavlink_msg_set_roll_pitch_yaw_speed_thrust.h.
Referenced by mavlink_msg_set_roll_pitch_yaw_speed_thrust_decode().
static uint8_t mavlink_msg_set_roll_pitch_yaw_speed_thrust_get_target_system (const mavlink_message_t * msg) inline static
Send a set_roll_pitch_yaw_speed_thrust message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
roll_speed Desired roll angular speed in rad/s
pitch_speed Desired pitch angular speed in rad/s
yaw_speed Desired yaw angular speed in rad/s
thrust Collective thrust, normalized to 0 .. 1 Get field target_system from set_roll_pitch_yaw_speed_thrust message
Returns
System ID
Definition at line 181 of file mavlink_msg_set_roll_pitch_yaw_speed_thrust.h.
Referenced by mavlink_msg_set_roll_pitch_yaw_speed_thrust_decode().
static float mavlink_msg_set_roll_pitch_yaw_speed_thrust_get_thrust (const mavlink_message_t * msg) inline static
Get field thrust from set_roll_pitch_yaw_speed_thrust message.
Returns
Collective thrust, normalized to 0 .. 1
Definition at line 231 of file mavlink_msg_set_roll_pitch_yaw_speed_thrust.h.
Referenced by mavlink_msg_set_roll_pitch_yaw_speed_thrust_decode().
static float mavlink_msg_set_roll_pitch_yaw_speed_thrust_get_yaw_speed (const mavlink_message_t * msg) inline static
Get field yaw_speed from set_roll_pitch_yaw_speed_thrust message.
Returns
Desired yaw angular speed in rad/s
Definition at line 221 of file mavlink_msg_set_roll_pitch_yaw_speed_thrust.h.
Referenced by mavlink_msg_set_roll_pitch_yaw_speed_thrust_decode().
static uint16_t mavlink_msg_set_roll_pitch_yaw_speed_thrust_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, float roll_speed, float pitch_speed, float yaw_speed, float thrust) inline static
Pack a set_roll_pitch_yaw_speed_thrust message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
roll_speed Desired roll angular speed in rad/s
pitch_speed Desired pitch angular speed in rad/s
yaw_speed Desired yaw angular speed in rad/s
thrust Collective thrust, normalized to 0 .. 1
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 47 of file mavlink_msg_set_roll_pitch_yaw_speed_thrust.h.
Referenced by mavlink_msg_set_roll_pitch_yaw_speed_thrust_encode(), and mavlink_test_set_roll_pitch_yaw_speed_thrust().
static uint16_t mavlink_msg_set_roll_pitch_yaw_speed_thrust_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, float roll_speed, float pitch_speed, float yaw_speed, float thrust) inline static
Pack a set_roll_pitch_yaw_speed_thrust message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
roll_speed Desired roll angular speed in rad/s
pitch_speed Desired pitch angular speed in rad/s
yaw_speed Desired yaw angular speed in rad/s
thrust Collective thrust, normalized to 0 .. 1
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 90 of file mavlink_msg_set_roll_pitch_yaw_speed_thrust.h.
Referenced by mavlink_test_set_roll_pitch_yaw_speed_thrust().