APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_state_correction.h File Reference
mavlink_msg_state_correction.h File Reference
Classes
struct __mavlink_state_correction_t
Macros
#define MAVLINK_MSG_ID_STATE_CORRECTION 64
#define MAVLINK_MSG_ID_STATE_CORRECTION_LEN 36
#define MAVLINK_MSG_ID_64_LEN 36
#define MAVLINK_MESSAGE_INFO_STATE_CORRECTION
Typedefs
typedef struct
__mavlink_state_correction_t mavlink_state_correction_t
Functions
static uint16_t mavlink_msg_state_correction_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, float xErr, float yErr, float zErr, float rollErr, float pitchErr, float yawErr, float vxErr, float vyErr, float vzErr)
Pack a state_correction message.
static uint16_t mavlink_msg_state_correction_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, float xErr, float yErr, float zErr, float rollErr, float pitchErr, float yawErr, float vxErr, float vyErr, float vzErr)
Pack a state_correction message on a channel.
static uint16_t mavlink_msg_state_correction_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_state_correction_t *state_correction)
Encode a state_correction struct into a message.
static float mavlink_msg_state_correction_get_xErr (const mavlink_message_t *msg)
Send a state_correction message.
static float mavlink_msg_state_correction_get_yErr (const mavlink_message_t *msg)
Get field yErr from state_correction message.
static float mavlink_msg_state_correction_get_zErr (const mavlink_message_t *msg)
Get field zErr from state_correction message.
static float mavlink_msg_state_correction_get_rollErr (const mavlink_message_t *msg)
Get field rollErr from state_correction message.
static float mavlink_msg_state_correction_get_pitchErr (const mavlink_message_t *msg)
Get field pitchErr from state_correction message.
static float mavlink_msg_state_correction_get_yawErr (const mavlink_message_t *msg)
Get field yawErr from state_correction message.
static float mavlink_msg_state_correction_get_vxErr (const mavlink_message_t *msg)
Get field vxErr from state_correction message.
static float mavlink_msg_state_correction_get_vyErr (const mavlink_message_t *msg)
Get field vyErr from state_correction message.
static float mavlink_msg_state_correction_get_vzErr (const mavlink_message_t *msg)
Get field vzErr from state_correction message.
static void mavlink_msg_state_correction_decode (const mavlink_message_t *msg, mavlink_state_correction_t *state_correction)
Decode a state_correction message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_STATE_CORRECTION
Value:
{ \
    "STATE_CORRECTION", \
    9, \
    {  { "xErr", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_state_correction_t, xErr) }, \
         { "yErr", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_state_correction_t, yErr) }, \
         { "zErr", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_state_correction_t, zErr) }, \
         { "rollErr", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_state_correction_t, rollErr) }, \
         { "pitchErr", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_state_correction_t, pitchErr) }, \
         { "yawErr", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_state_correction_t, yawErr) }, \
         { "vxErr", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_state_correction_t, vxErr) }, \
         { "vyErr", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_state_correction_t, vyErr) }, \
         { "vzErr", NULL, MAVLINK_TYPE_FLOAT, 0, 32, offsetof(mavlink_state_correction_t, vzErr) }, \
         } \
}
Definition at line 23 of file mavlink_msg_state_correction.h.
#define MAVLINK_MSG_ID_64_LEN 36
Definition at line 19 of file mavlink_msg_state_correction.h.
#define MAVLINK_MSG_ID_STATE_CORRECTION 64
Definition at line 3 of file mavlink_msg_state_correction.h.
Referenced by mavlink_msg_state_correction_pack(), and mavlink_msg_state_correction_pack_chan().
#define MAVLINK_MSG_ID_STATE_CORRECTION_LEN 36
Definition at line 18 of file mavlink_msg_state_correction.h.
Typedef Documentation
typedef struct __mavlink_state_correction_t mavlink_state_correction_t
Function Documentation
static void mavlink_msg_state_correction_decode (const mavlink_message_t * msg, mavlink_state_correction_t * state_correction) inline static
Decode a state_correction message into a struct.
Parameters
msg The message to decode
state_correction C-struct to decode the message contents into
Definition at line 305 of file mavlink_msg_state_correction.h.
Referenced by mavlink_test_state_correction().
static uint16_t mavlink_msg_state_correction_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_state_correction_t * state_correction) inline static
Encode a state_correction struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
state_correction C-struct to read the message contents from
Definition at line 152 of file mavlink_msg_state_correction.h.
Referenced by mavlink_test_state_correction().
static float mavlink_msg_state_correction_get_pitchErr (const mavlink_message_t * msg) inline static
Get field pitchErr from state_correction message.
Returns
pitch error (radians)
Definition at line 254 of file mavlink_msg_state_correction.h.
Referenced by mavlink_msg_state_correction_decode().
static float mavlink_msg_state_correction_get_rollErr (const mavlink_message_t * msg) inline static
Get field rollErr from state_correction message.
Returns
roll error (radians)
Definition at line 244 of file mavlink_msg_state_correction.h.
Referenced by mavlink_msg_state_correction_decode().
static float mavlink_msg_state_correction_get_vxErr (const mavlink_message_t * msg) inline static
Get field vxErr from state_correction message.
Returns
x velocity
Definition at line 274 of file mavlink_msg_state_correction.h.
Referenced by mavlink_msg_state_correction_decode().
static float mavlink_msg_state_correction_get_vyErr (const mavlink_message_t * msg) inline static
Get field vyErr from state_correction message.
Returns
y velocity
Definition at line 284 of file mavlink_msg_state_correction.h.
Referenced by mavlink_msg_state_correction_decode().
static float mavlink_msg_state_correction_get_vzErr (const mavlink_message_t * msg) inline static
Get field vzErr from state_correction message.
Returns
z velocity
Definition at line 294 of file mavlink_msg_state_correction.h.
Referenced by mavlink_msg_state_correction_decode().
static float mavlink_msg_state_correction_get_xErr (const mavlink_message_t * msg) inline static
Send a state_correction message.
Parameters
chan MAVLink channel to send the message
xErr x position error
yErr y position error
zErr z position error
rollErr roll error (radians)
pitchErr pitch error (radians)
yawErr yaw error (radians)
vxErr x velocity
vyErr y velocity
vzErr z velocity Get field xErr from state_correction message
Returns
x position error
Definition at line 214 of file mavlink_msg_state_correction.h.
Referenced by mavlink_msg_state_correction_decode().
static float mavlink_msg_state_correction_get_yawErr (const mavlink_message_t * msg) inline static
Get field yawErr from state_correction message.
Returns
yaw error (radians)
Definition at line 264 of file mavlink_msg_state_correction.h.
Referenced by mavlink_msg_state_correction_decode().
static float mavlink_msg_state_correction_get_yErr (const mavlink_message_t * msg) inline static
Get field yErr from state_correction message.
Returns
y position error
Definition at line 224 of file mavlink_msg_state_correction.h.
Referenced by mavlink_msg_state_correction_decode().
static float mavlink_msg_state_correction_get_zErr (const mavlink_message_t * msg) inline static
Get field zErr from state_correction message.
Returns
z position error
Definition at line 234 of file mavlink_msg_state_correction.h.
Referenced by mavlink_msg_state_correction_decode().
static uint16_t mavlink_msg_state_correction_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, float xErr, float yErr, float zErr, float rollErr, float pitchErr, float yawErr, float vxErr, float vyErr, float vzErr) inline static
Pack a state_correction message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
xErr x position error
yErr y position error
zErr z position error
rollErr roll error (radians)
pitchErr pitch error (radians)
yawErr yaw error (radians)
vxErr x velocity
vyErr y velocity
vzErr z velocity
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 56 of file mavlink_msg_state_correction.h.
Referenced by mavlink_msg_state_correction_encode(), and mavlink_test_state_correction().
static uint16_t mavlink_msg_state_correction_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, float xErr, float yErr, float zErr, float rollErr, float pitchErr, float yawErr, float vxErr, float vyErr, float vzErr) inline static
Pack a state_correction message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
xErr x position error
yErr y position error
zErr z position error
rollErr roll error (radians)
pitchErr pitch error (radians)
yawErr yaw error (radians)
vxErr x velocity
vyErr y velocity
vzErr z velocity
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 108 of file mavlink_msg_state_correction.h.
Referenced by mavlink_test_state_correction().