APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_local_position.h File Reference
mavlink_msg_local_position.h File Reference
Classes
struct __mavlink_local_position_t
Macros
#define MAVLINK_MSG_ID_LOCAL_POSITION 31
#define MAVLINK_MSG_ID_LOCAL_POSITION_LEN 32
#define MAVLINK_MSG_ID_31_LEN 32
#define MAVLINK_MESSAGE_INFO_LOCAL_POSITION
Typedefs
typedef struct
__mavlink_local_position_t mavlink_local_position_t
Functions
static uint16_t mavlink_msg_local_position_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t usec, float x, float y, float z, float vx, float vy, float vz)
Pack a local_position message.
static uint16_t mavlink_msg_local_position_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t usec, float x, float y, float z, float vx, float vy, float vz)
Pack a local_position message on a channel.
static uint16_t mavlink_msg_local_position_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_local_position_t *local_position)
Encode a local_position struct into a message.
static uint64_t mavlink_msg_local_position_get_usec (const mavlink_message_t *msg)
Send a local_position message.
static float mavlink_msg_local_position_get_x (const mavlink_message_t *msg)
Get field x from local_position message.
static float mavlink_msg_local_position_get_y (const mavlink_message_t *msg)
Get field y from local_position message.
static float mavlink_msg_local_position_get_z (const mavlink_message_t *msg)
Get field z from local_position message.
static float mavlink_msg_local_position_get_vx (const mavlink_message_t *msg)
Get field vx from local_position message.
static float mavlink_msg_local_position_get_vy (const mavlink_message_t *msg)
Get field vy from local_position message.
static float mavlink_msg_local_position_get_vz (const mavlink_message_t *msg)
Get field vz from local_position message.
static void mavlink_msg_local_position_decode (const mavlink_message_t *msg, mavlink_local_position_t *local_position)
Decode a local_position message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_LOCAL_POSITION
Value:
{ \
    "LOCAL_POSITION", \
    7, \
    {  { "usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_local_position_t, usec) }, \
         { "x", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_local_position_t, x) }, \
         { "y", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_local_position_t, y) }, \
         { "z", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_local_position_t, z) }, \
         { "vx", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_local_position_t, vx) }, \
         { "vy", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_local_position_t, vy) }, \
         { "vz", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_local_position_t, vz) }, \
         } \
}
Definition at line 21 of file mavlink_msg_local_position.h.
#define MAVLINK_MSG_ID_31_LEN 32
Definition at line 17 of file mavlink_msg_local_position.h.
#define MAVLINK_MSG_ID_LOCAL_POSITION 31
Definition at line 3 of file mavlink_msg_local_position.h.
Referenced by mavlink_msg_local_position_pack(), and mavlink_msg_local_position_pack_chan().
#define MAVLINK_MSG_ID_LOCAL_POSITION_LEN 32
Definition at line 16 of file mavlink_msg_local_position.h.
Typedef Documentation
typedef struct __mavlink_local_position_t mavlink_local_position_t
Function Documentation
static void mavlink_msg_local_position_decode (const mavlink_message_t * msg, mavlink_local_position_t * local_position) inline static
Decode a local_position message into a struct.
Parameters
msg The message to decode
local_position C-struct to decode the message contents into
Definition at line 263 of file mavlink_msg_local_position.h.
Referenced by mavlink_test_local_position().
static uint16_t mavlink_msg_local_position_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_local_position_t * local_position) inline static
Encode a local_position struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
local_position C-struct to read the message contents from
Definition at line 136 of file mavlink_msg_local_position.h.
Referenced by mavlink_test_local_position().
static uint64_t mavlink_msg_local_position_get_usec (const mavlink_message_t * msg) inline static
Send a local_position message.
Parameters
chan MAVLink channel to send the message
usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
x X Position
y Y Position
z Z Position
vx X Speed
vy Y Speed
vz Z Speed Get field usec from local_position message
Returns
Timestamp (microseconds since UNIX epoch or microseconds since system boot)
Definition at line 192 of file mavlink_msg_local_position.h.
Referenced by mavlink_msg_local_position_decode().
static float mavlink_msg_local_position_get_vx (const mavlink_message_t * msg) inline static
Get field vx from local_position message.
Returns
X Speed
Definition at line 232 of file mavlink_msg_local_position.h.
Referenced by mavlink_msg_local_position_decode().
static float mavlink_msg_local_position_get_vy (const mavlink_message_t * msg) inline static
Get field vy from local_position message.
Returns
Y Speed
Definition at line 242 of file mavlink_msg_local_position.h.
Referenced by mavlink_msg_local_position_decode().
static float mavlink_msg_local_position_get_vz (const mavlink_message_t * msg) inline static
Get field vz from local_position message.
Returns
Z Speed
Definition at line 252 of file mavlink_msg_local_position.h.
Referenced by mavlink_msg_local_position_decode().
static float mavlink_msg_local_position_get_x (const mavlink_message_t * msg) inline static
Get field x from local_position message.
Returns
X Position
Definition at line 202 of file mavlink_msg_local_position.h.
Referenced by mavlink_msg_local_position_decode().
static float mavlink_msg_local_position_get_y (const mavlink_message_t * msg) inline static
Get field y from local_position message.
Returns
Y Position
Definition at line 212 of file mavlink_msg_local_position.h.
Referenced by mavlink_msg_local_position_decode().
static float mavlink_msg_local_position_get_z (const mavlink_message_t * msg) inline static
Get field z from local_position message.
Returns
Z Position
Definition at line 222 of file mavlink_msg_local_position.h.
Referenced by mavlink_msg_local_position_decode().
static uint16_t mavlink_msg_local_position_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t usec, float x, float y, float z, float vx, float vy, float vz) inline static
Pack a local_position message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
x X Position
y Y Position
z Z Position
vx X Speed
vy Y Speed
vz Z Speed
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 50 of file mavlink_msg_local_position.h.
Referenced by mavlink_msg_local_position_encode(), and mavlink_test_local_position().
static uint16_t mavlink_msg_local_position_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t usec, float x, float y, float z, float vx, float vy, float vz) inline static
Pack a local_position message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
x X Position
y Y Position
z Z Position
vx X Speed
vy Y Speed
vz Z Speed
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 96 of file mavlink_msg_local_position.h.
Referenced by mavlink_test_local_position().