APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_waypoint_reached.h File Reference
mavlink_msg_waypoint_reached.h File Reference
Classes
struct __mavlink_waypoint_reached_t
Macros
#define MAVLINK_MSG_ID_WAYPOINT_REACHED 46
#define MAVLINK_MSG_ID_WAYPOINT_REACHED_LEN 2
#define MAVLINK_MSG_ID_46_LEN 2
#define MAVLINK_MESSAGE_INFO_WAYPOINT_REACHED
Typedefs
typedef struct
__mavlink_waypoint_reached_t mavlink_waypoint_reached_t
Functions
static uint16_t mavlink_msg_waypoint_reached_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint16_t seq)
Pack a waypoint_reached message.
static uint16_t mavlink_msg_waypoint_reached_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint16_t seq)
Pack a waypoint_reached message on a channel.
static uint16_t mavlink_msg_waypoint_reached_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_waypoint_reached_t *waypoint_reached)
Encode a waypoint_reached struct into a message.
static uint16_t mavlink_msg_waypoint_reached_get_seq (const mavlink_message_t *msg)
Send a waypoint_reached message.
static void mavlink_msg_waypoint_reached_decode (const mavlink_message_t *msg, mavlink_waypoint_reached_t *waypoint_reached)
Decode a waypoint_reached message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_WAYPOINT_REACHED
Value:
{ \
    "WAYPOINT_REACHED", \
    1, \
    {  { "seq", NULL, MAVLINK_TYPE_UINT16_T, 0, 0, offsetof(mavlink_waypoint_reached_t, seq) }, \
         } \
}
Definition at line 15 of file mavlink_msg_waypoint_reached.h.
#define MAVLINK_MSG_ID_46_LEN 2
Definition at line 11 of file mavlink_msg_waypoint_reached.h.
#define MAVLINK_MSG_ID_WAYPOINT_REACHED 46
Definition at line 3 of file mavlink_msg_waypoint_reached.h.
Referenced by mavlink_msg_waypoint_reached_pack(), and mavlink_msg_waypoint_reached_pack_chan().
#define MAVLINK_MSG_ID_WAYPOINT_REACHED_LEN 2
Definition at line 10 of file mavlink_msg_waypoint_reached.h.
Typedef Documentation
typedef struct __mavlink_waypoint_reached_t mavlink_waypoint_reached_t
Function Documentation
static void mavlink_msg_waypoint_reached_decode (const mavlink_message_t * msg, mavlink_waypoint_reached_t * waypoint_reached) inline static
Decode a waypoint_reached message into a struct.
Parameters
msg The message to decode
waypoint_reached C-struct to decode the message contents into
Definition at line 137 of file mavlink_msg_waypoint_reached.h.
Referenced by mavlink_test_waypoint_reached().
static uint16_t mavlink_msg_waypoint_reached_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_waypoint_reached_t * waypoint_reached) inline static
Encode a waypoint_reached struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
waypoint_reached C-struct to read the message contents from
Definition at line 88 of file mavlink_msg_waypoint_reached.h.
Referenced by mavlink_test_waypoint_reached().
static uint16_t mavlink_msg_waypoint_reached_get_seq (const mavlink_message_t * msg) inline static
Send a waypoint_reached message.
Parameters
chan MAVLink channel to send the message
seq Sequence Get field seq from waypoint_reached message
Returns
Sequence
Definition at line 126 of file mavlink_msg_waypoint_reached.h.
Referenced by mavlink_msg_waypoint_reached_decode().
static uint16_t mavlink_msg_waypoint_reached_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint16_t seq) inline static
Pack a waypoint_reached message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
seq Sequence
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 32 of file mavlink_msg_waypoint_reached.h.
Referenced by mavlink_msg_waypoint_reached_encode(), and mavlink_test_waypoint_reached().
static uint16_t mavlink_msg_waypoint_reached_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint16_t seq) inline static
Pack a waypoint_reached message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
seq Sequence
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 60 of file mavlink_msg_waypoint_reached.h.
Referenced by mavlink_test_waypoint_reached().