APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_global_position.h File Reference
mavlink_msg_global_position.h File Reference
Classes
struct __mavlink_global_position_t
Macros
#define MAVLINK_MSG_ID_GLOBAL_POSITION 33
#define MAVLINK_MSG_ID_GLOBAL_POSITION_LEN 32
#define MAVLINK_MSG_ID_33_LEN 32
#define MAVLINK_MESSAGE_INFO_GLOBAL_POSITION
Typedefs
typedef struct
__mavlink_global_position_t mavlink_global_position_t
Functions
static uint16_t mavlink_msg_global_position_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t usec, float lat, float lon, float alt, float vx, float vy, float vz)
Pack a global_position message.
static uint16_t mavlink_msg_global_position_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t usec, float lat, float lon, float alt, float vx, float vy, float vz)
Pack a global_position message on a channel.
static uint16_t mavlink_msg_global_position_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_global_position_t *global_position)
Encode a global_position struct into a message.
static uint64_t mavlink_msg_global_position_get_usec (const mavlink_message_t *msg)
Send a global_position message.
static float mavlink_msg_global_position_get_lat (const mavlink_message_t *msg)
Get field lat from global_position message.
static float mavlink_msg_global_position_get_lon (const mavlink_message_t *msg)
Get field lon from global_position message.
static float mavlink_msg_global_position_get_alt (const mavlink_message_t *msg)
Get field alt from global_position message.
static float mavlink_msg_global_position_get_vx (const mavlink_message_t *msg)
Get field vx from global_position message.
static float mavlink_msg_global_position_get_vy (const mavlink_message_t *msg)
Get field vy from global_position message.
static float mavlink_msg_global_position_get_vz (const mavlink_message_t *msg)
Get field vz from global_position message.
static void mavlink_msg_global_position_decode (const mavlink_message_t *msg, mavlink_global_position_t *global_position)
Decode a global_position message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GLOBAL_POSITION
Value:
{ \
    "GLOBAL_POSITION", \
    7, \
    {  { "usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_global_position_t, usec) }, \
         { "lat", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_global_position_t, lat) }, \
         { "lon", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_global_position_t, lon) }, \
         { "alt", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_global_position_t, alt) }, \
         { "vx", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_global_position_t, vx) }, \
         { "vy", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_global_position_t, vy) }, \
         { "vz", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_global_position_t, vz) }, \
         } \
}
Definition at line 21 of file mavlink_msg_global_position.h.
#define MAVLINK_MSG_ID_33_LEN 32
Definition at line 17 of file mavlink_msg_global_position.h.
#define MAVLINK_MSG_ID_GLOBAL_POSITION 33
Definition at line 3 of file mavlink_msg_global_position.h.
Referenced by mavlink_msg_global_position_pack(), and mavlink_msg_global_position_pack_chan().
#define MAVLINK_MSG_ID_GLOBAL_POSITION_LEN 32
Definition at line 16 of file mavlink_msg_global_position.h.
Typedef Documentation
typedef struct __mavlink_global_position_t mavlink_global_position_t
Function Documentation
static void mavlink_msg_global_position_decode (const mavlink_message_t * msg, mavlink_global_position_t * global_position) inline static
Decode a global_position message into a struct.
Parameters
msg The message to decode
global_position C-struct to decode the message contents into
Definition at line 263 of file mavlink_msg_global_position.h.
Referenced by mavlink_test_global_position().
static uint16_t mavlink_msg_global_position_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_global_position_t * global_position) inline static
Encode a global_position struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
global_position C-struct to read the message contents from
Definition at line 136 of file mavlink_msg_global_position.h.
Referenced by mavlink_test_global_position().
static float mavlink_msg_global_position_get_alt (const mavlink_message_t * msg) inline static
Get field alt from global_position message.
Returns
Absolute altitude, in meters
Definition at line 222 of file mavlink_msg_global_position.h.
Referenced by mavlink_msg_global_position_decode().
static float mavlink_msg_global_position_get_lat (const mavlink_message_t * msg) inline static
Get field lat from global_position message.
Returns
Latitude, in degrees
Definition at line 202 of file mavlink_msg_global_position.h.
Referenced by mavlink_msg_global_position_decode().
static float mavlink_msg_global_position_get_lon (const mavlink_message_t * msg) inline static
Get field lon from global_position message.
Returns
Longitude, in degrees
Definition at line 212 of file mavlink_msg_global_position.h.
Referenced by mavlink_msg_global_position_decode().
static uint64_t mavlink_msg_global_position_get_usec (const mavlink_message_t * msg) inline static
Send a global_position message.
Parameters
chan MAVLink channel to send the message
usec Timestamp (microseconds since unix epoch)
lat Latitude, in degrees
lon Longitude, in degrees
alt Absolute altitude, in meters
vx X Speed (in Latitude direction, positive: going north)
vy Y Speed (in Longitude direction, positive: going east)
vz Z Speed (in Altitude direction, positive: going up) Get field usec from global_position message
Returns
Timestamp (microseconds since unix epoch)
Definition at line 192 of file mavlink_msg_global_position.h.
Referenced by mavlink_msg_global_position_decode().
static float mavlink_msg_global_position_get_vx (const mavlink_message_t * msg) inline static
Get field vx from global_position message.
Returns
X Speed (in Latitude direction, positive: going north)
Definition at line 232 of file mavlink_msg_global_position.h.
Referenced by mavlink_msg_global_position_decode().
static float mavlink_msg_global_position_get_vy (const mavlink_message_t * msg) inline static
Get field vy from global_position message.
Returns
Y Speed (in Longitude direction, positive: going east)
Definition at line 242 of file mavlink_msg_global_position.h.
Referenced by mavlink_msg_global_position_decode().
static float mavlink_msg_global_position_get_vz (const mavlink_message_t * msg) inline static
Get field vz from global_position message.
Returns
Z Speed (in Altitude direction, positive: going up)
Definition at line 252 of file mavlink_msg_global_position.h.
Referenced by mavlink_msg_global_position_decode().
static uint16_t mavlink_msg_global_position_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t usec, float lat, float lon, float alt, float vx, float vy, float vz) inline static
Pack a global_position message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
usec Timestamp (microseconds since unix epoch)
lat Latitude, in degrees
lon Longitude, in degrees
alt Absolute altitude, in meters
vx X Speed (in Latitude direction, positive: going north)
vy Y Speed (in Longitude direction, positive: going east)
vz Z Speed (in Altitude direction, positive: going up)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 50 of file mavlink_msg_global_position.h.
Referenced by mavlink_msg_global_position_encode(), and mavlink_test_global_position().
static uint16_t mavlink_msg_global_position_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t usec, float lat, float lon, float alt, float vx, float vy, float vz) inline static
Pack a global_position message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
usec Timestamp (microseconds since unix epoch)
lat Latitude, in degrees
lon Longitude, in degrees
alt Absolute altitude, in meters
vx X Speed (in Latitude direction, positive: going north)
vy Y Speed (in Longitude direction, positive: going east)
vz Z Speed (in Altitude direction, positive: going up)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 96 of file mavlink_msg_global_position.h.
Referenced by mavlink_test_global_position().