APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_control_status.h File Reference
mavlink_msg_control_status.h File Reference
Classes
struct __mavlink_control_status_t
Macros
#define MAVLINK_MSG_ID_CONTROL_STATUS 52
#define MAVLINK_MSG_ID_CONTROL_STATUS_LEN 8
#define MAVLINK_MSG_ID_52_LEN 8
#define MAVLINK_MESSAGE_INFO_CONTROL_STATUS
Typedefs
typedef struct
__mavlink_control_status_t mavlink_control_status_t
Functions
static uint16_t mavlink_msg_control_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t position_fix, uint8_t vision_fix, uint8_t gps_fix, uint8_t ahrs_health, uint8_t control_att, uint8_t control_pos_xy, uint8_t control_pos_z, uint8_t control_pos_yaw)
Pack a control_status message.
static uint16_t mavlink_msg_control_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t position_fix, uint8_t vision_fix, uint8_t gps_fix, uint8_t ahrs_health, uint8_t control_att, uint8_t control_pos_xy, uint8_t control_pos_z, uint8_t control_pos_yaw)
Pack a control_status message on a channel.
static uint16_t mavlink_msg_control_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_control_status_t *control_status)
Encode a control_status struct into a message.
static uint8_t mavlink_msg_control_status_get_position_fix (const mavlink_message_t *msg)
Send a control_status message.
static uint8_t mavlink_msg_control_status_get_vision_fix (const mavlink_message_t *msg)
Get field vision_fix from control_status message.
static uint8_t mavlink_msg_control_status_get_gps_fix (const mavlink_message_t *msg)
Get field gps_fix from control_status message.
static uint8_t mavlink_msg_control_status_get_ahrs_health (const mavlink_message_t *msg)
Get field ahrs_health from control_status message.
static uint8_t mavlink_msg_control_status_get_control_att (const mavlink_message_t *msg)
Get field control_att from control_status message.
static uint8_t mavlink_msg_control_status_get_control_pos_xy (const mavlink_message_t *msg)
Get field control_pos_xy from control_status message.
static uint8_t mavlink_msg_control_status_get_control_pos_z (const mavlink_message_t *msg)
Get field control_pos_z from control_status message.
static uint8_t mavlink_msg_control_status_get_control_pos_yaw (const mavlink_message_t *msg)
Get field control_pos_yaw from control_status message.
static void mavlink_msg_control_status_decode (const mavlink_message_t *msg, mavlink_control_status_t *control_status)
Decode a control_status message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_CONTROL_STATUS
Value:
{ \
    "CONTROL_STATUS", \
    8, \
    {  { "position_fix", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_control_status_t, position_fix) }, \
         { "vision_fix", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_control_status_t, vision_fix) }, \
         { "gps_fix", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_control_status_t, gps_fix) }, \
         { "ahrs_health", NULL, MAVLINK_TYPE_UINT8_T, 0, 3, offsetof(mavlink_control_status_t, ahrs_health) }, \
         { "control_att", NULL, MAVLINK_TYPE_UINT8_T, 0, 4, offsetof(mavlink_control_status_t, control_att) }, \
         { "control_pos_xy", NULL, MAVLINK_TYPE_UINT8_T, 0, 5, offsetof(mavlink_control_status_t, control_pos_xy) }, \
         { "control_pos_z", NULL, MAVLINK_TYPE_UINT8_T, 0, 6, offsetof(mavlink_control_status_t, control_pos_z) }, \
         { "control_pos_yaw", NULL, MAVLINK_TYPE_UINT8_T, 0, 7, offsetof(mavlink_control_status_t, control_pos_yaw) }, \
         } \
}
Definition at line 22 of file mavlink_msg_control_status.h.
#define MAVLINK_MSG_ID_52_LEN 8
Definition at line 18 of file mavlink_msg_control_status.h.
#define MAVLINK_MSG_ID_CONTROL_STATUS 52
Definition at line 3 of file mavlink_msg_control_status.h.
Referenced by mavlink_msg_control_status_pack(), and mavlink_msg_control_status_pack_chan().
#define MAVLINK_MSG_ID_CONTROL_STATUS_LEN 8
Definition at line 17 of file mavlink_msg_control_status.h.
Typedef Documentation
typedef struct __mavlink_control_status_t mavlink_control_status_t
Function Documentation
static void mavlink_msg_control_status_decode (const mavlink_message_t * msg, mavlink_control_status_t * control_status) inline static
Decode a control_status message into a struct.
Parameters
msg The message to decode
control_status C-struct to decode the message contents into
Definition at line 284 of file mavlink_msg_control_status.h.
Referenced by mavlink_test_control_status().
static uint16_t mavlink_msg_control_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_control_status_t * control_status) inline static
Encode a control_status struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
control_status C-struct to read the message contents from
Definition at line 144 of file mavlink_msg_control_status.h.
Referenced by mavlink_test_control_status().
static uint8_t mavlink_msg_control_status_get_ahrs_health (const mavlink_message_t * msg) inline static
Get field ahrs_health from control_status message.
Returns
Attitude estimation health: 0: poor, 255: excellent
Definition at line 233 of file mavlink_msg_control_status.h.
Referenced by mavlink_msg_control_status_decode().
static uint8_t mavlink_msg_control_status_get_control_att (const mavlink_message_t * msg) inline static
Get field control_att from control_status message.
Returns
0: Attitude control disabled, 1: enabled
Definition at line 243 of file mavlink_msg_control_status.h.
Referenced by mavlink_msg_control_status_decode().
static uint8_t mavlink_msg_control_status_get_control_pos_xy (const mavlink_message_t * msg) inline static
Get field control_pos_xy from control_status message.
Returns
0: X, Y position control disabled, 1: enabled
Definition at line 253 of file mavlink_msg_control_status.h.
Referenced by mavlink_msg_control_status_decode().
static uint8_t mavlink_msg_control_status_get_control_pos_yaw (const mavlink_message_t * msg) inline static
Get field control_pos_yaw from control_status message.
Returns
0: Yaw angle control disabled, 1: enabled
Definition at line 273 of file mavlink_msg_control_status.h.
Referenced by mavlink_msg_control_status_decode().
static uint8_t mavlink_msg_control_status_get_control_pos_z (const mavlink_message_t * msg) inline static
Get field control_pos_z from control_status message.
Returns
0: Z position control disabled, 1: enabled
Definition at line 263 of file mavlink_msg_control_status.h.
Referenced by mavlink_msg_control_status_decode().
static uint8_t mavlink_msg_control_status_get_gps_fix (const mavlink_message_t * msg) inline static
Get field gps_fix from control_status message.
Returns
GPS position fix: 0: no reception, 1: Minimum 1 satellite, but no position fix, 2: 2D position fix, 3: 3D position fix
Definition at line 223 of file mavlink_msg_control_status.h.
Referenced by mavlink_msg_control_status_decode().
static uint8_t mavlink_msg_control_status_get_position_fix (const mavlink_message_t * msg) inline static
Send a control_status message.
Parameters
chan MAVLink channel to send the message
position_fix Position fix: 0: lost, 2: 2D position fix, 3: 3D position fix
vision_fix Vision position fix: 0: lost, 1: 2D local position hold, 2: 2D global position fix, 3: 3D global position fix
gps_fix GPS position fix: 0: no reception, 1: Minimum 1 satellite, but no position fix, 2: 2D position fix, 3: 3D position fix
ahrs_health Attitude estimation health: 0: poor, 255: excellent
control_att 0: Attitude control disabled, 1: enabled
control_pos_xy 0: X, Y position control disabled, 1: enabled
control_pos_z 0: Z position control disabled, 1: enabled
control_pos_yaw 0: Yaw angle control disabled, 1: enabled Get field position_fix from control_status message
Returns
Position fix: 0: lost, 2: 2D position fix, 3: 3D position fix
Definition at line 203 of file mavlink_msg_control_status.h.
Referenced by mavlink_msg_control_status_decode().
static uint8_t mavlink_msg_control_status_get_vision_fix (const mavlink_message_t * msg) inline static
Get field vision_fix from control_status message.
Returns
Vision position fix: 0: lost, 1: 2D local position hold, 2: 2D global position fix, 3: 3D global position fix
Definition at line 213 of file mavlink_msg_control_status.h.
Referenced by mavlink_msg_control_status_decode().
static uint16_t mavlink_msg_control_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t position_fix, uint8_t vision_fix, uint8_t gps_fix, uint8_t ahrs_health, uint8_t control_att, uint8_t control_pos_xy, uint8_t control_pos_z, uint8_t control_pos_yaw) inline static
Pack a control_status message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
position_fix Position fix: 0: lost, 2: 2D position fix, 3: 3D position fix
vision_fix Vision position fix: 0: lost, 1: 2D local position hold, 2: 2D global position fix, 3: 3D global position fix
gps_fix GPS position fix: 0: no reception, 1: Minimum 1 satellite, but no position fix, 2: 2D position fix, 3: 3D position fix
ahrs_health Attitude estimation health: 0: poor, 255: excellent
control_att 0: Attitude control disabled, 1: enabled
control_pos_xy 0: X, Y position control disabled, 1: enabled
control_pos_z 0: Z position control disabled, 1: enabled
control_pos_yaw 0: Yaw angle control disabled, 1: enabled
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 53 of file mavlink_msg_control_status.h.
Referenced by mavlink_msg_control_status_encode(), and mavlink_test_control_status().
static uint16_t mavlink_msg_control_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t position_fix, uint8_t vision_fix, uint8_t gps_fix, uint8_t ahrs_health, uint8_t control_att, uint8_t control_pos_xy, uint8_t control_pos_z, uint8_t control_pos_yaw) inline static
Pack a control_status message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
position_fix Position fix: 0: lost, 2: 2D position fix, 3: 3D position fix
vision_fix Vision position fix: 0: lost, 1: 2D local position hold, 2: 2D global position fix, 3: 3D global position fix
gps_fix GPS position fix: 0: no reception, 1: Minimum 1 satellite, but no position fix, 2: 2D position fix, 3: 3D position fix
ahrs_health Attitude estimation health: 0: poor, 255: excellent
control_att 0: Attitude control disabled, 1: enabled
control_pos_xy 0: X, Y position control disabled, 1: enabled
control_pos_z 0: Z position control disabled, 1: enabled
control_pos_yaw 0: Yaw angle control disabled, 1: enabled
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 102 of file mavlink_msg_control_status.h.
Referenced by mavlink_test_control_status().