APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_system_time_utc.h File Reference
mavlink_msg_system_time_utc.h File Reference
Classes
struct __mavlink_system_time_utc_t
Macros
#define MAVLINK_MSG_ID_SYSTEM_TIME_UTC 4
#define MAVLINK_MSG_ID_SYSTEM_TIME_UTC_LEN 8
#define MAVLINK_MSG_ID_4_LEN 8
#define MAVLINK_MESSAGE_INFO_SYSTEM_TIME_UTC
Typedefs
typedef struct
__mavlink_system_time_utc_t mavlink_system_time_utc_t
Functions
static uint16_t mavlink_msg_system_time_utc_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint32_t utc_date, uint32_t utc_time)
Pack a system_time_utc message.
static uint16_t mavlink_msg_system_time_utc_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint32_t utc_date, uint32_t utc_time)
Pack a system_time_utc message on a channel.
static uint16_t mavlink_msg_system_time_utc_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_system_time_utc_t *system_time_utc)
Encode a system_time_utc struct into a message.
static uint32_t mavlink_msg_system_time_utc_get_utc_date (const mavlink_message_t *msg)
Send a system_time_utc message.
static uint32_t mavlink_msg_system_time_utc_get_utc_time (const mavlink_message_t *msg)
Get field utc_time from system_time_utc message.
static void mavlink_msg_system_time_utc_decode (const mavlink_message_t *msg, mavlink_system_time_utc_t *system_time_utc)
Decode a system_time_utc message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_SYSTEM_TIME_UTC
Value:
{ \
    "SYSTEM_TIME_UTC", \
    2, \
    {  { "utc_date", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_system_time_utc_t, utc_date) }, \
         { "utc_time", NULL, MAVLINK_TYPE_UINT32_T, 0, 4, offsetof(mavlink_system_time_utc_t, utc_time) }, \
         } \
}
Definition at line 16 of file mavlink_msg_system_time_utc.h.
#define MAVLINK_MSG_ID_4_LEN 8
Definition at line 12 of file mavlink_msg_system_time_utc.h.
#define MAVLINK_MSG_ID_SYSTEM_TIME_UTC 4
Definition at line 3 of file mavlink_msg_system_time_utc.h.
Referenced by mavlink_msg_system_time_utc_pack(), and mavlink_msg_system_time_utc_pack_chan().
#define MAVLINK_MSG_ID_SYSTEM_TIME_UTC_LEN 8
Definition at line 11 of file mavlink_msg_system_time_utc.h.
Typedef Documentation
typedef struct __mavlink_system_time_utc_t mavlink_system_time_utc_t
Function Documentation
static void mavlink_msg_system_time_utc_decode (const mavlink_message_t * msg, mavlink_system_time_utc_t * system_time_utc) inline static
Decode a system_time_utc message into a struct.
Parameters
msg The message to decode
system_time_utc C-struct to decode the message contents into
Definition at line 158 of file mavlink_msg_system_time_utc.h.
Referenced by mavlink_test_system_time_utc().
static uint16_t mavlink_msg_system_time_utc_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_system_time_utc_t * system_time_utc) inline static
Encode a system_time_utc struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
system_time_utc C-struct to read the message contents from
Definition at line 96 of file mavlink_msg_system_time_utc.h.
Referenced by mavlink_test_system_time_utc().
static uint32_t mavlink_msg_system_time_utc_get_utc_date (const mavlink_message_t * msg) inline static
Send a system_time_utc message.
Parameters
chan MAVLink channel to send the message
utc_date GPS UTC date ddmmyy
utc_time GPS UTC time hhmmss Get field utc_date from system_time_utc message
Returns
GPS UTC date ddmmyy
Definition at line 137 of file mavlink_msg_system_time_utc.h.
Referenced by mavlink_msg_system_time_utc_decode().
static uint32_t mavlink_msg_system_time_utc_get_utc_time (const mavlink_message_t * msg) inline static
Get field utc_time from system_time_utc message.
Returns
GPS UTC time hhmmss
Definition at line 147 of file mavlink_msg_system_time_utc.h.
Referenced by mavlink_msg_system_time_utc_decode().
static uint16_t mavlink_msg_system_time_utc_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint32_t utc_date, uint32_t utc_time) inline static
Pack a system_time_utc message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
utc_date GPS UTC date ddmmyy
utc_time GPS UTC time hhmmss
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 35 of file mavlink_msg_system_time_utc.h.
Referenced by mavlink_msg_system_time_utc_encode(), and mavlink_test_system_time_utc().
static uint16_t mavlink_msg_system_time_utc_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint32_t utc_date, uint32_t utc_time) inline static
Pack a system_time_utc message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
utc_date GPS UTC date ddmmyy
utc_time GPS UTC time hhmmss
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 66 of file mavlink_msg_system_time_utc.h.
Referenced by mavlink_test_system_time_utc().