APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_local_position_setpoint_set.h File Reference
mavlink_msg_local_position_setpoint_set.h File Reference
Classes
struct __mavlink_local_position_setpoint_set_t
Macros
#define MAVLINK_MSG_ID_LOCAL_POSITION_SETPOINT_SET 50
#define MAVLINK_MSG_ID_LOCAL_POSITION_SETPOINT_SET_LEN 18
#define MAVLINK_MSG_ID_50_LEN 18
#define MAVLINK_MESSAGE_INFO_LOCAL_POSITION_SETPOINT_SET
Typedefs
typedef struct
__mavlink_local_position_setpoint_set_t mavlink_local_position_setpoint_set_t
Functions
static uint16_t mavlink_msg_local_position_setpoint_set_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, float x, float y, float z, float yaw)
Pack a local_position_setpoint_set message.
static uint16_t mavlink_msg_local_position_setpoint_set_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, float x, float y, float z, float yaw)
Pack a local_position_setpoint_set message on a channel.
static uint16_t mavlink_msg_local_position_setpoint_set_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_local_position_setpoint_set_t *local_position_setpoint_set)
Encode a local_position_setpoint_set struct into a message.
static uint8_t mavlink_msg_local_position_setpoint_set_get_target_system (const mavlink_message_t *msg)
Send a local_position_setpoint_set message.
static uint8_t mavlink_msg_local_position_setpoint_set_get_target_component (const mavlink_message_t *msg)
Get field target_component from local_position_setpoint_set message.
static float mavlink_msg_local_position_setpoint_set_get_x (const mavlink_message_t *msg)
Get field x from local_position_setpoint_set message.
static float mavlink_msg_local_position_setpoint_set_get_y (const mavlink_message_t *msg)
Get field y from local_position_setpoint_set message.
static float mavlink_msg_local_position_setpoint_set_get_z (const mavlink_message_t *msg)
Get field z from local_position_setpoint_set message.
static float mavlink_msg_local_position_setpoint_set_get_yaw (const mavlink_message_t *msg)
Get field yaw from local_position_setpoint_set message.
static void mavlink_msg_local_position_setpoint_set_decode (const mavlink_message_t *msg, mavlink_local_position_setpoint_set_t *local_position_setpoint_set)
Decode a local_position_setpoint_set message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_LOCAL_POSITION_SETPOINT_SET
Value:
{ \
    "LOCAL_POSITION_SETPOINT_SET", \
    6, \
    {  { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_local_position_setpoint_set_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_local_position_setpoint_set_t, target_component) }, \
         { "x", NULL, MAVLINK_TYPE_FLOAT, 0, 2, offsetof(mavlink_local_position_setpoint_set_t, x) }, \
         { "y", NULL, MAVLINK_TYPE_FLOAT, 0, 6, offsetof(mavlink_local_position_setpoint_set_t, y) }, \
         { "z", NULL, MAVLINK_TYPE_FLOAT, 0, 10, offsetof(mavlink_local_position_setpoint_set_t, z) }, \
         { "yaw", NULL, MAVLINK_TYPE_FLOAT, 0, 14, offsetof(mavlink_local_position_setpoint_set_t, yaw) }, \
         } \
}
Definition at line 20 of file mavlink_msg_local_position_setpoint_set.h.
#define MAVLINK_MSG_ID_50_LEN 18
Definition at line 16 of file mavlink_msg_local_position_setpoint_set.h.
#define MAVLINK_MSG_ID_LOCAL_POSITION_SETPOINT_SET 50
Definition at line 3 of file mavlink_msg_local_position_setpoint_set.h.
Referenced by mavlink_msg_local_position_setpoint_set_pack(), and mavlink_msg_local_position_setpoint_set_pack_chan().
#define MAVLINK_MSG_ID_LOCAL_POSITION_SETPOINT_SET_LEN 18
Definition at line 15 of file mavlink_msg_local_position_setpoint_set.h.
Typedef Documentation
typedef struct __mavlink_local_position_setpoint_set_t mavlink_local_position_setpoint_set_t
Function Documentation
static void mavlink_msg_local_position_setpoint_set_decode (const mavlink_message_t * msg, mavlink_local_position_setpoint_set_t * local_position_setpoint_set) inline static
Decode a local_position_setpoint_set message into a struct.
Parameters
msg The message to decode
local_position_setpoint_set C-struct to decode the message contents into
Definition at line 242 of file mavlink_msg_local_position_setpoint_set.h.
Referenced by mavlink_test_local_position_setpoint_set().
static uint16_t mavlink_msg_local_position_setpoint_set_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_local_position_setpoint_set_t * local_position_setpoint_set) inline static
Encode a local_position_setpoint_set struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
local_position_setpoint_set C-struct to read the message contents from
Definition at line 128 of file mavlink_msg_local_position_setpoint_set.h.
Referenced by mavlink_test_local_position_setpoint_set().
static uint8_t mavlink_msg_local_position_setpoint_set_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from local_position_setpoint_set message.
Returns
Component ID
Definition at line 191 of file mavlink_msg_local_position_setpoint_set.h.
Referenced by mavlink_msg_local_position_setpoint_set_decode().
static uint8_t mavlink_msg_local_position_setpoint_set_get_target_system (const mavlink_message_t * msg) inline static
Send a local_position_setpoint_set message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
x x position
y y position
z z position
yaw Desired yaw angle Get field target_system from local_position_setpoint_set message
Returns
System ID
Definition at line 181 of file mavlink_msg_local_position_setpoint_set.h.
Referenced by mavlink_msg_local_position_setpoint_set_decode().
static float mavlink_msg_local_position_setpoint_set_get_x (const mavlink_message_t * msg) inline static
Get field x from local_position_setpoint_set message.
Returns
x position
Definition at line 201 of file mavlink_msg_local_position_setpoint_set.h.
Referenced by mavlink_msg_local_position_setpoint_set_decode().
static float mavlink_msg_local_position_setpoint_set_get_y (const mavlink_message_t * msg) inline static
Get field y from local_position_setpoint_set message.
Returns
y position
Definition at line 211 of file mavlink_msg_local_position_setpoint_set.h.
Referenced by mavlink_msg_local_position_setpoint_set_decode().
static float mavlink_msg_local_position_setpoint_set_get_yaw (const mavlink_message_t * msg) inline static
Get field yaw from local_position_setpoint_set message.
Returns
Desired yaw angle
Definition at line 231 of file mavlink_msg_local_position_setpoint_set.h.
Referenced by mavlink_msg_local_position_setpoint_set_decode().
static float mavlink_msg_local_position_setpoint_set_get_z (const mavlink_message_t * msg) inline static
Get field z from local_position_setpoint_set message.
Returns
z position
Definition at line 221 of file mavlink_msg_local_position_setpoint_set.h.
Referenced by mavlink_msg_local_position_setpoint_set_decode().
static uint16_t mavlink_msg_local_position_setpoint_set_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, float x, float y, float z, float yaw) inline static
Pack a local_position_setpoint_set message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
x x position
y y position
z z position
yaw Desired yaw angle
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 47 of file mavlink_msg_local_position_setpoint_set.h.
Referenced by mavlink_msg_local_position_setpoint_set_encode(), and mavlink_test_local_position_setpoint_set().
static uint16_t mavlink_msg_local_position_setpoint_set_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, float x, float y, float z, float yaw) inline static
Pack a local_position_setpoint_set message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
x x position
y y position
z z position
yaw Desired yaw angle
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 90 of file mavlink_msg_local_position_setpoint_set.h.
Referenced by mavlink_test_local_position_setpoint_set().