APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_boot.h File Reference
mavlink_msg_boot.h File Reference
Classes
struct __mavlink_boot_t
Macros
#define MAVLINK_MSG_ID_BOOT 1
#define MAVLINK_MSG_ID_BOOT_LEN 4
#define MAVLINK_MSG_ID_1_LEN 4
#define MAVLINK_MESSAGE_INFO_BOOT
Typedefs
typedef struct __mavlink_boot_t mavlink_boot_t
Functions
static uint16_t mavlink_msg_boot_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint32_t version)
Pack a boot message.
static uint16_t mavlink_msg_boot_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint32_t version)
Pack a boot message on a channel.
static uint16_t mavlink_msg_boot_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_boot_t *boot)
Encode a boot struct into a message.
static uint32_t mavlink_msg_boot_get_version (const mavlink_message_t *msg)
Send a boot message.
static void mavlink_msg_boot_decode (const mavlink_message_t *msg, mavlink_boot_t *boot)
Decode a boot message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_BOOT
Value:
{ \
    "BOOT", \
    1, \
    {  { "version", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_boot_t, version) }, \
         } \
}
Definition at line 15 of file mavlink_msg_boot.h.
#define MAVLINK_MSG_ID_1_LEN 4
Definition at line 11 of file mavlink_msg_boot.h.
#define MAVLINK_MSG_ID_BOOT 1
Definition at line 3 of file mavlink_msg_boot.h.
Referenced by mavlink_msg_boot_pack(), and mavlink_msg_boot_pack_chan().
#define MAVLINK_MSG_ID_BOOT_LEN 4
Definition at line 10 of file mavlink_msg_boot.h.
Typedef Documentation
typedef struct __mavlink_boot_t mavlink_boot_t
Function Documentation
static void mavlink_msg_boot_decode (const mavlink_message_t * msg, mavlink_boot_t * boot) inline static
Decode a boot message into a struct.
Parameters
msg The message to decode
boot C-struct to decode the message contents into
Definition at line 137 of file mavlink_msg_boot.h.
Referenced by mavlink_test_boot().
static uint16_t mavlink_msg_boot_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_boot_t * boot) inline static
Encode a boot struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
boot C-struct to read the message contents from
Definition at line 88 of file mavlink_msg_boot.h.
Referenced by mavlink_test_boot().
static uint32_t mavlink_msg_boot_get_version (const mavlink_message_t * msg) inline static
Send a boot message.
Parameters
chan MAVLink channel to send the message
version The onboard software version Get field version from boot message
Returns
The onboard software version
Definition at line 126 of file mavlink_msg_boot.h.
Referenced by mavlink_msg_boot_decode().
static uint16_t mavlink_msg_boot_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint32_t version) inline static
Pack a boot message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
version The onboard software version
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 32 of file mavlink_msg_boot.h.
Referenced by mavlink_msg_boot_encode(), and mavlink_test_boot().
static uint16_t mavlink_msg_boot_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint32_t version) inline static
Pack a boot message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
version The onboard software version
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 60 of file mavlink_msg_boot.h.
Referenced by mavlink_test_boot().