APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_waypoint.h File Reference
mavlink_msg_waypoint.h File Reference
Classes
struct __mavlink_waypoint_t
Macros
#define MAVLINK_MSG_ID_WAYPOINT 39
#define MAVLINK_MSG_ID_WAYPOINT_LEN 36
#define MAVLINK_MSG_ID_39_LEN 36
#define MAVLINK_MESSAGE_INFO_WAYPOINT
Typedefs
typedef struct __mavlink_waypoint_t mavlink_waypoint_t
Functions
static uint16_t mavlink_msg_waypoint_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint16_t seq, uint8_t frame, uint8_t command, uint8_t current, uint8_t autocontinue, float param1, float param2, float param3, float param4, float x, float y, float z)
Pack a waypoint message.
static uint16_t mavlink_msg_waypoint_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint16_t seq, uint8_t frame, uint8_t command, uint8_t current, uint8_t autocontinue, float param1, float param2, float param3, float param4, float x, float y, float z)
Pack a waypoint message on a channel.
static uint16_t mavlink_msg_waypoint_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_waypoint_t *waypoint)
Encode a waypoint struct into a message.
static uint8_t mavlink_msg_waypoint_get_target_system (const mavlink_message_t *msg)
Send a waypoint message.
static uint8_t mavlink_msg_waypoint_get_target_component (const mavlink_message_t *msg)
Get field target_component from waypoint message.
static uint16_t mavlink_msg_waypoint_get_seq (const mavlink_message_t *msg)
Get field seq from waypoint message.
static uint8_t mavlink_msg_waypoint_get_frame (const mavlink_message_t *msg)
Get field frame from waypoint message.
static uint8_t mavlink_msg_waypoint_get_command (const mavlink_message_t *msg)
Get field command from waypoint message.
static uint8_t mavlink_msg_waypoint_get_current (const mavlink_message_t *msg)
Get field current from waypoint message.
static uint8_t mavlink_msg_waypoint_get_autocontinue (const mavlink_message_t *msg)
Get field autocontinue from waypoint message.
static float mavlink_msg_waypoint_get_param1 (const mavlink_message_t *msg)
Get field param1 from waypoint message.
static float mavlink_msg_waypoint_get_param2 (const mavlink_message_t *msg)
Get field param2 from waypoint message.
static float mavlink_msg_waypoint_get_param3 (const mavlink_message_t *msg)
Get field param3 from waypoint message.
static float mavlink_msg_waypoint_get_param4 (const mavlink_message_t *msg)
Get field param4 from waypoint message.
static float mavlink_msg_waypoint_get_x (const mavlink_message_t *msg)
Get field x from waypoint message.
static float mavlink_msg_waypoint_get_y (const mavlink_message_t *msg)
Get field y from waypoint message.
static float mavlink_msg_waypoint_get_z (const mavlink_message_t *msg)
Get field z from waypoint message.
static void mavlink_msg_waypoint_decode (const mavlink_message_t *msg, mavlink_waypoint_t *waypoint)
Decode a waypoint message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_WAYPOINT
Value:
{ \
    "WAYPOINT", \
    14, \
    {  { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_waypoint_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_waypoint_t, target_component) }, \
         { "seq", NULL, MAVLINK_TYPE_UINT16_T, 0, 2, offsetof(mavlink_waypoint_t, seq) }, \
         { "frame", NULL, MAVLINK_TYPE_UINT8_T, 0, 4, offsetof(mavlink_waypoint_t, frame) }, \
         { "command", NULL, MAVLINK_TYPE_UINT8_T, 0, 5, offsetof(mavlink_waypoint_t, command) }, \
         { "current", NULL, MAVLINK_TYPE_UINT8_T, 0, 6, offsetof(mavlink_waypoint_t, current) }, \
         { "autocontinue", NULL, MAVLINK_TYPE_UINT8_T, 0, 7, offsetof(mavlink_waypoint_t, autocontinue) }, \
         { "param1", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_waypoint_t, param1) }, \
         { "param2", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_waypoint_t, param2) }, \
         { "param3", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_waypoint_t, param3) }, \
         { "param4", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_waypoint_t, param4) }, \
         { "x", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_waypoint_t, x) }, \
         { "y", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_waypoint_t, y) }, \
         { "z", NULL, MAVLINK_TYPE_FLOAT, 0, 32, offsetof(mavlink_waypoint_t, z) }, \
         } \
}
Definition at line 28 of file mavlink_msg_waypoint.h.
#define MAVLINK_MSG_ID_39_LEN 36
Definition at line 24 of file mavlink_msg_waypoint.h.
#define MAVLINK_MSG_ID_WAYPOINT 39
Definition at line 3 of file mavlink_msg_waypoint.h.
Referenced by mavlink_msg_waypoint_pack(), and mavlink_msg_waypoint_pack_chan().
#define MAVLINK_MSG_ID_WAYPOINT_LEN 36
Definition at line 23 of file mavlink_msg_waypoint.h.
Typedef Documentation
typedef struct __mavlink_waypoint_t mavlink_waypoint_t
Function Documentation
static void mavlink_msg_waypoint_decode (const mavlink_message_t * msg, mavlink_waypoint_t * waypoint) inline static
Decode a waypoint message into a struct.
Parameters
msg The message to decode
waypoint C-struct to decode the message contents into
Definition at line 410 of file mavlink_msg_waypoint.h.
Referenced by mavlink_test_waypoint().
static uint16_t mavlink_msg_waypoint_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_waypoint_t * waypoint) inline static
Encode a waypoint struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
waypoint C-struct to read the message contents from
Definition at line 192 of file mavlink_msg_waypoint.h.
Referenced by mavlink_test_waypoint().
static uint8_t mavlink_msg_waypoint_get_autocontinue (const mavlink_message_t * msg) inline static
Get field autocontinue from waypoint message.
Returns
autocontinue to next wp
Definition at line 329 of file mavlink_msg_waypoint.h.
Referenced by mavlink_msg_waypoint_decode().
static uint8_t mavlink_msg_waypoint_get_command (const mavlink_message_t * msg) inline static
Get field command from waypoint message.
Returns
The scheduled action for the waypoint. see MAV_COMMAND in common.xml MAVLink specs
Definition at line 309 of file mavlink_msg_waypoint.h.
Referenced by mavlink_msg_waypoint_decode().
static uint8_t mavlink_msg_waypoint_get_current (const mavlink_message_t * msg) inline static
Get field current from waypoint message.
Returns
false:0, true:1
Definition at line 319 of file mavlink_msg_waypoint.h.
Referenced by mavlink_msg_waypoint_decode().
static uint8_t mavlink_msg_waypoint_get_frame (const mavlink_message_t * msg) inline static
Get field frame from waypoint message.
Returns
The coordinate system of the waypoint. see MAV_FRAME in mavlink_types.h
Definition at line 299 of file mavlink_msg_waypoint.h.
Referenced by mavlink_msg_waypoint_decode().
static float mavlink_msg_waypoint_get_param1 (const mavlink_message_t * msg) inline static
Get field param1 from waypoint message.
Returns
PARAM1 / For NAV command waypoints: Radius in which the waypoint is accepted as reached, in meters
Definition at line 339 of file mavlink_msg_waypoint.h.
Referenced by mavlink_msg_waypoint_decode().
static float mavlink_msg_waypoint_get_param2 (const mavlink_message_t * msg) inline static
Get field param2 from waypoint message.
Returns
PARAM2 / For NAV command waypoints: Time that the MAV should stay inside the PARAM1 radius before advancing, in milliseconds
Definition at line 349 of file mavlink_msg_waypoint.h.
Referenced by mavlink_msg_waypoint_decode().
static float mavlink_msg_waypoint_get_param3 (const mavlink_message_t * msg) inline static
Get field param3 from waypoint message.
Returns
PARAM3 / For LOITER command waypoints: Orbit to circle around the waypoint, in meters. If positive the orbit direction should be clockwise, if negative the orbit direction should be counter-clockwise.
Definition at line 359 of file mavlink_msg_waypoint.h.
Referenced by mavlink_msg_waypoint_decode().
static float mavlink_msg_waypoint_get_param4 (const mavlink_message_t * msg) inline static
Get field param4 from waypoint message.
Returns
PARAM4 / For NAV and LOITER command waypoints: Yaw orientation in degrees, [0..360] 0 = NORTH
Definition at line 369 of file mavlink_msg_waypoint.h.
Referenced by mavlink_msg_waypoint_decode().
static uint16_t mavlink_msg_waypoint_get_seq (const mavlink_message_t * msg) inline static
Get field seq from waypoint message.
Returns
Sequence
Definition at line 289 of file mavlink_msg_waypoint.h.
Referenced by mavlink_msg_waypoint_decode().
static uint8_t mavlink_msg_waypoint_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from waypoint message.
Returns
Component ID
Definition at line 279 of file mavlink_msg_waypoint.h.
Referenced by mavlink_msg_waypoint_decode().
static uint8_t mavlink_msg_waypoint_get_target_system (const mavlink_message_t * msg) inline static
Send a waypoint message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
seq Sequence
frame The coordinate system of the waypoint. see MAV_FRAME in mavlink_types.h
command The scheduled action for the waypoint. see MAV_COMMAND in common.xml MAVLink specs
current false:0, true:1
autocontinue autocontinue to next wp
param1 PARAM1 / For NAV command waypoints: Radius in which the waypoint is accepted as reached, in meters
param2 PARAM2 / For NAV command waypoints: Time that the MAV should stay inside the PARAM1 radius before advancing, in milliseconds
param3 PARAM3 / For LOITER command waypoints: Orbit to circle around the waypoint, in meters. If positive the orbit direction should be clockwise, if negative the orbit direction should be counter-clockwise.
param4 PARAM4 / For NAV and LOITER command waypoints: Yaw orientation in degrees, [0..360] 0 = NORTH
x PARAM5 / local: x position, global: latitude
y PARAM6 / y position: global: longitude
z PARAM7 / z position: global: altitude Get field target_system from waypoint message
Returns
System ID
Definition at line 269 of file mavlink_msg_waypoint.h.
Referenced by mavlink_msg_waypoint_decode().
static float mavlink_msg_waypoint_get_x (const mavlink_message_t * msg) inline static
Get field x from waypoint message.
Returns
PARAM5 / local: x position, global: latitude
Definition at line 379 of file mavlink_msg_waypoint.h.
Referenced by mavlink_msg_waypoint_decode().
static float mavlink_msg_waypoint_get_y (const mavlink_message_t * msg) inline static
Get field y from waypoint message.
Returns
PARAM6 / y position: global: longitude
Definition at line 389 of file mavlink_msg_waypoint.h.
Referenced by mavlink_msg_waypoint_decode().
static float mavlink_msg_waypoint_get_z (const mavlink_message_t * msg) inline static
Get field z from waypoint message.
Returns
PARAM7 / z position: global: altitude
Definition at line 399 of file mavlink_msg_waypoint.h.
Referenced by mavlink_msg_waypoint_decode().
static uint16_t mavlink_msg_waypoint_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint16_t seq, uint8_t frame, uint8_t command, uint8_t current, uint8_t autocontinue, float param1, float param2, float param3, float param4, float x, float y, float z) inline static
Pack a waypoint message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
seq Sequence
frame The coordinate system of the waypoint. see MAV_FRAME in mavlink_types.h
command The scheduled action for the waypoint. see MAV_COMMAND in common.xml MAVLink specs
current false:0, true:1
autocontinue autocontinue to next wp
param1 PARAM1 / For NAV command waypoints: Radius in which the waypoint is accepted as reached, in meters
param2 PARAM2 / For NAV command waypoints: Time that the MAV should stay inside the PARAM1 radius before advancing, in milliseconds
param3 PARAM3 / For LOITER command waypoints: Orbit to circle around the waypoint, in meters. If positive the orbit direction should be clockwise, if negative the orbit direction should be counter-clockwise.
param4 PARAM4 / For NAV and LOITER command waypoints: Yaw orientation in degrees, [0..360] 0 = NORTH
x PARAM5 / local: x position, global: latitude
y PARAM6 / y position: global: longitude
z PARAM7 / z position: global: altitude
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 71 of file mavlink_msg_waypoint.h.
Referenced by mavlink_msg_waypoint_encode(), and mavlink_test_waypoint().
static uint16_t mavlink_msg_waypoint_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint16_t seq, uint8_t frame, uint8_t command, uint8_t current, uint8_t autocontinue, float param1, float param2, float param3, float param4, float x, float y, float z) inline static
Pack a waypoint message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
seq Sequence
frame The coordinate system of the waypoint. see MAV_FRAME in mavlink_types.h
command The scheduled action for the waypoint. see MAV_COMMAND in common.xml MAVLink specs
current false:0, true:1
autocontinue autocontinue to next wp
param1 PARAM1 / For NAV command waypoints: Radius in which the waypoint is accepted as reached, in meters
param2 PARAM2 / For NAV command waypoints: Time that the MAV should stay inside the PARAM1 radius before advancing, in milliseconds
param3 PARAM3 / For LOITER command waypoints: Orbit to circle around the waypoint, in meters. If positive the orbit direction should be clockwise, if negative the orbit direction should be counter-clockwise.
param4 PARAM4 / For NAV and LOITER command waypoints: Yaw orientation in degrees, [0..360] 0 = NORTH
x PARAM5 / local: x position, global: latitude
y PARAM6 / y position: global: longitude
z PARAM7 / z position: global: altitude
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 138 of file mavlink_msg_waypoint.h.
Referenced by mavlink_test_waypoint().