APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_local_position_setpoint.h File Reference
mavlink_msg_local_position_setpoint.h File Reference
Classes
struct __mavlink_local_position_setpoint_t
Macros
#define MAVLINK_MSG_ID_LOCAL_POSITION_SETPOINT 51
#define MAVLINK_MSG_ID_LOCAL_POSITION_SETPOINT_LEN 16
#define MAVLINK_MSG_ID_51_LEN 16
#define MAVLINK_MESSAGE_INFO_LOCAL_POSITION_SETPOINT
Typedefs
typedef struct
__mavlink_local_position_setpoint_t mavlink_local_position_setpoint_t
Functions
static uint16_t mavlink_msg_local_position_setpoint_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, float x, float y, float z, float yaw)
Pack a local_position_setpoint message.
static uint16_t mavlink_msg_local_position_setpoint_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, float x, float y, float z, float yaw)
Pack a local_position_setpoint message on a channel.
static uint16_t mavlink_msg_local_position_setpoint_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_local_position_setpoint_t *local_position_setpoint)
Encode a local_position_setpoint struct into a message.
static float mavlink_msg_local_position_setpoint_get_x (const mavlink_message_t *msg)
Send a local_position_setpoint message.
static float mavlink_msg_local_position_setpoint_get_y (const mavlink_message_t *msg)
Get field y from local_position_setpoint message.
static float mavlink_msg_local_position_setpoint_get_z (const mavlink_message_t *msg)
Get field z from local_position_setpoint message.
static float mavlink_msg_local_position_setpoint_get_yaw (const mavlink_message_t *msg)
Get field yaw from local_position_setpoint message.
static void mavlink_msg_local_position_setpoint_decode (const mavlink_message_t *msg, mavlink_local_position_setpoint_t *local_position_setpoint)
Decode a local_position_setpoint message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_LOCAL_POSITION_SETPOINT
Value:
{ \
    "LOCAL_POSITION_SETPOINT", \
    4, \
    {  { "x", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_local_position_setpoint_t, x) }, \
         { "y", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_local_position_setpoint_t, y) }, \
         { "z", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_local_position_setpoint_t, z) }, \
         { "yaw", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_local_position_setpoint_t, yaw) }, \
         } \
}
Definition at line 18 of file mavlink_msg_local_position_setpoint.h.
#define MAVLINK_MSG_ID_51_LEN 16
Definition at line 14 of file mavlink_msg_local_position_setpoint.h.
#define MAVLINK_MSG_ID_LOCAL_POSITION_SETPOINT 51
Definition at line 3 of file mavlink_msg_local_position_setpoint.h.
Referenced by mavlink_msg_local_position_setpoint_pack(), and mavlink_msg_local_position_setpoint_pack_chan().
#define MAVLINK_MSG_ID_LOCAL_POSITION_SETPOINT_LEN 16
Definition at line 13 of file mavlink_msg_local_position_setpoint.h.
Typedef Documentation
typedef struct __mavlink_local_position_setpoint_t mavlink_local_position_setpoint_t
Function Documentation
static void mavlink_msg_local_position_setpoint_decode (const mavlink_message_t * msg, mavlink_local_position_setpoint_t * local_position_setpoint) inline static
Decode a local_position_setpoint message into a struct.
Parameters
msg The message to decode
local_position_setpoint C-struct to decode the message contents into
Definition at line 200 of file mavlink_msg_local_position_setpoint.h.
Referenced by mavlink_test_local_position_setpoint().
static uint16_t mavlink_msg_local_position_setpoint_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_local_position_setpoint_t * local_position_setpoint) inline static
Encode a local_position_setpoint struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
local_position_setpoint C-struct to read the message contents from
Definition at line 112 of file mavlink_msg_local_position_setpoint.h.
Referenced by mavlink_test_local_position_setpoint().
static float mavlink_msg_local_position_setpoint_get_x (const mavlink_message_t * msg) inline static
Send a local_position_setpoint message.
Parameters
chan MAVLink channel to send the message
x x position
y y position
z z position
yaw Desired yaw angle Get field x from local_position_setpoint message
Returns
x position
Definition at line 159 of file mavlink_msg_local_position_setpoint.h.
Referenced by mavlink_msg_local_position_setpoint_decode().
static float mavlink_msg_local_position_setpoint_get_y (const mavlink_message_t * msg) inline static
Get field y from local_position_setpoint message.
Returns
y position
Definition at line 169 of file mavlink_msg_local_position_setpoint.h.
Referenced by mavlink_msg_local_position_setpoint_decode().
static float mavlink_msg_local_position_setpoint_get_yaw (const mavlink_message_t * msg) inline static
Get field yaw from local_position_setpoint message.
Returns
Desired yaw angle
Definition at line 189 of file mavlink_msg_local_position_setpoint.h.
Referenced by mavlink_msg_local_position_setpoint_decode().
static float mavlink_msg_local_position_setpoint_get_z (const mavlink_message_t * msg) inline static
Get field z from local_position_setpoint message.
Returns
z position
Definition at line 179 of file mavlink_msg_local_position_setpoint.h.
Referenced by mavlink_msg_local_position_setpoint_decode().
static uint16_t mavlink_msg_local_position_setpoint_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, float x, float y, float z, float yaw) inline static
Pack a local_position_setpoint message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
x x position
y y position
z z position
yaw Desired yaw angle
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 41 of file mavlink_msg_local_position_setpoint.h.
Referenced by mavlink_msg_local_position_setpoint_encode(), and mavlink_test_local_position_setpoint().
static uint16_t mavlink_msg_local_position_setpoint_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, float x, float y, float z, float yaw) inline static
Pack a local_position_setpoint message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
x x position
y y position
z z position
yaw Desired yaw angle
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 78 of file mavlink_msg_local_position_setpoint.h.
Referenced by mavlink_test_local_position_setpoint().