APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_position_target.h File Reference
mavlink_msg_position_target.h File Reference
Classes
struct __mavlink_position_target_t
Macros
#define MAVLINK_MSG_ID_POSITION_TARGET 63
#define MAVLINK_MSG_ID_POSITION_TARGET_LEN 16
#define MAVLINK_MSG_ID_63_LEN 16
#define MAVLINK_MESSAGE_INFO_POSITION_TARGET
Typedefs
typedef struct
__mavlink_position_target_t mavlink_position_target_t
Functions
static uint16_t mavlink_msg_position_target_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, float x, float y, float z, float yaw)
Pack a position_target message.
static uint16_t mavlink_msg_position_target_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, float x, float y, float z, float yaw)
Pack a position_target message on a channel.
static uint16_t mavlink_msg_position_target_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_position_target_t *position_target)
Encode a position_target struct into a message.
static float mavlink_msg_position_target_get_x (const mavlink_message_t *msg)
Send a position_target message.
static float mavlink_msg_position_target_get_y (const mavlink_message_t *msg)
Get field y from position_target message.
static float mavlink_msg_position_target_get_z (const mavlink_message_t *msg)
Get field z from position_target message.
static float mavlink_msg_position_target_get_yaw (const mavlink_message_t *msg)
Get field yaw from position_target message.
static void mavlink_msg_position_target_decode (const mavlink_message_t *msg, mavlink_position_target_t *position_target)
Decode a position_target message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_POSITION_TARGET
Value:
{ \
    "POSITION_TARGET", \
    4, \
    {  { "x", NULL, MAVLINK_TYPE_FLOAT, 0, 0, offsetof(mavlink_position_target_t, x) }, \
         { "y", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_position_target_t, y) }, \
         { "z", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_position_target_t, z) }, \
         { "yaw", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_position_target_t, yaw) }, \
         } \
}
Definition at line 18 of file mavlink_msg_position_target.h.
#define MAVLINK_MSG_ID_63_LEN 16
Definition at line 14 of file mavlink_msg_position_target.h.
#define MAVLINK_MSG_ID_POSITION_TARGET 63
Definition at line 3 of file mavlink_msg_position_target.h.
Referenced by mavlink_msg_position_target_pack(), and mavlink_msg_position_target_pack_chan().
#define MAVLINK_MSG_ID_POSITION_TARGET_LEN 16
Definition at line 13 of file mavlink_msg_position_target.h.
Typedef Documentation
typedef struct __mavlink_position_target_t mavlink_position_target_t
Function Documentation
static void mavlink_msg_position_target_decode (const mavlink_message_t * msg, mavlink_position_target_t * position_target) inline static
Decode a position_target message into a struct.
Parameters
msg The message to decode
position_target C-struct to decode the message contents into
Definition at line 200 of file mavlink_msg_position_target.h.
Referenced by mavlink_test_position_target().
static uint16_t mavlink_msg_position_target_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_position_target_t * position_target) inline static
Encode a position_target struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
position_target C-struct to read the message contents from
Definition at line 112 of file mavlink_msg_position_target.h.
Referenced by mavlink_test_position_target().
static float mavlink_msg_position_target_get_x (const mavlink_message_t * msg) inline static
Send a position_target message.
Parameters
chan MAVLink channel to send the message
x x position
y y position
z z position
yaw yaw orientation in radians, 0 = NORTH Get field x from position_target message
Returns
x position
Definition at line 159 of file mavlink_msg_position_target.h.
Referenced by mavlink_msg_position_target_decode().
static float mavlink_msg_position_target_get_y (const mavlink_message_t * msg) inline static
Get field y from position_target message.
Returns
y position
Definition at line 169 of file mavlink_msg_position_target.h.
Referenced by mavlink_msg_position_target_decode().
static float mavlink_msg_position_target_get_yaw (const mavlink_message_t * msg) inline static
Get field yaw from position_target message.
Returns
yaw orientation in radians, 0 = NORTH
Definition at line 189 of file mavlink_msg_position_target.h.
Referenced by mavlink_msg_position_target_decode().
static float mavlink_msg_position_target_get_z (const mavlink_message_t * msg) inline static
Get field z from position_target message.
Returns
z position
Definition at line 179 of file mavlink_msg_position_target.h.
Referenced by mavlink_msg_position_target_decode().
static uint16_t mavlink_msg_position_target_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, float x, float y, float z, float yaw) inline static
Pack a position_target message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
x x position
y y position
z z position
yaw yaw orientation in radians, 0 = NORTH
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 41 of file mavlink_msg_position_target.h.
Referenced by mavlink_msg_position_target_encode(), and mavlink_test_position_target().
static uint16_t mavlink_msg_position_target_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, float x, float y, float z, float yaw) inline static
Pack a position_target message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
x x position
y y position
z z position
yaw yaw orientation in radians, 0 = NORTH
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 78 of file mavlink_msg_position_target.h.
Referenced by mavlink_test_position_target().