APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_command.h File Reference
mavlink_msg_command.h File Reference
Classes
struct __mavlink_command_t
Macros
#define MAVLINK_MSG_ID_COMMAND 75
#define MAVLINK_MSG_ID_COMMAND_LEN 20
#define MAVLINK_MSG_ID_75_LEN 20
#define MAVLINK_MESSAGE_INFO_COMMAND
Typedefs
typedef struct __mavlink_command_t mavlink_command_t
Functions
static uint16_t mavlink_msg_command_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t command, uint8_t confirmation, float param1, float param2, float param3, float param4)
Pack a command message.
static uint16_t mavlink_msg_command_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t command, uint8_t confirmation, float param1, float param2, float param3, float param4)
Pack a command message on a channel.
static uint16_t mavlink_msg_command_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_command_t *command)
Encode a command struct into a message.
static uint8_t mavlink_msg_command_get_target_system (const mavlink_message_t *msg)
Send a command message.
static uint8_t mavlink_msg_command_get_target_component (const mavlink_message_t *msg)
Get field target_component from command message.
static uint8_t mavlink_msg_command_get_command (const mavlink_message_t *msg)
Get field command from command message.
static uint8_t mavlink_msg_command_get_confirmation (const mavlink_message_t *msg)
Get field confirmation from command message.
static float mavlink_msg_command_get_param1 (const mavlink_message_t *msg)
Get field param1 from command message.
static float mavlink_msg_command_get_param2 (const mavlink_message_t *msg)
Get field param2 from command message.
static float mavlink_msg_command_get_param3 (const mavlink_message_t *msg)
Get field param3 from command message.
static float mavlink_msg_command_get_param4 (const mavlink_message_t *msg)
Get field param4 from command message.
static void mavlink_msg_command_decode (const mavlink_message_t *msg, mavlink_command_t *command)
Decode a command message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_COMMAND
Value:
{ \
    "COMMAND", \
    8, \
    {  { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_command_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_command_t, target_component) }, \
         { "command", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_command_t, command) }, \
         { "confirmation", NULL, MAVLINK_TYPE_UINT8_T, 0, 3, offsetof(mavlink_command_t, confirmation) }, \
         { "param1", NULL, MAVLINK_TYPE_FLOAT, 0, 4, offsetof(mavlink_command_t, param1) }, \
         { "param2", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_command_t, param2) }, \
         { "param3", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_command_t, param3) }, \
         { "param4", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_command_t, param4) }, \
         } \
}
Definition at line 22 of file mavlink_msg_command.h.
#define MAVLINK_MSG_ID_75_LEN 20
Definition at line 18 of file mavlink_msg_command.h.
#define MAVLINK_MSG_ID_COMMAND 75
Definition at line 3 of file mavlink_msg_command.h.
Referenced by mavlink_msg_command_pack(), and mavlink_msg_command_pack_chan().
#define MAVLINK_MSG_ID_COMMAND_LEN 20
Definition at line 17 of file mavlink_msg_command.h.
Typedef Documentation
typedef struct __mavlink_command_t mavlink_command_t
Function Documentation
static void mavlink_msg_command_decode (const mavlink_message_t * msg, mavlink_command_t * command) inline static
Decode a command message into a struct.
Parameters
msg The message to decode
command C-struct to decode the message contents into
Definition at line 284 of file mavlink_msg_command.h.
Referenced by mavlink_test_command().
static uint16_t mavlink_msg_command_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_command_t * command) inline static
Encode a command struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
command C-struct to read the message contents from
Definition at line 144 of file mavlink_msg_command.h.
Referenced by mavlink_test_command().
static uint8_t mavlink_msg_command_get_command (const mavlink_message_t * msg) inline static
Get field command from command message.
Returns
Command ID, as defined by MAV_CMD enum.
Definition at line 223 of file mavlink_msg_command.h.
Referenced by mavlink_msg_command_decode().
static uint8_t mavlink_msg_command_get_confirmation (const mavlink_message_t * msg) inline static
Get field confirmation from command message.
Returns
0: First transmission of this command. 1-255: Confirmation transmissions (e.g. for kill command)
Definition at line 233 of file mavlink_msg_command.h.
Referenced by mavlink_msg_command_decode().
static float mavlink_msg_command_get_param1 (const mavlink_message_t * msg) inline static
Get field param1 from command message.
Returns
Parameter 1, as defined by MAV_CMD enum.
Definition at line 243 of file mavlink_msg_command.h.
Referenced by mavlink_msg_command_decode().
static float mavlink_msg_command_get_param2 (const mavlink_message_t * msg) inline static
Get field param2 from command message.
Returns
Parameter 2, as defined by MAV_CMD enum.
Definition at line 253 of file mavlink_msg_command.h.
Referenced by mavlink_msg_command_decode().
static float mavlink_msg_command_get_param3 (const mavlink_message_t * msg) inline static
Get field param3 from command message.
Returns
Parameter 3, as defined by MAV_CMD enum.
Definition at line 263 of file mavlink_msg_command.h.
Referenced by mavlink_msg_command_decode().
static float mavlink_msg_command_get_param4 (const mavlink_message_t * msg) inline static
Get field param4 from command message.
Returns
Parameter 4, as defined by MAV_CMD enum.
Definition at line 273 of file mavlink_msg_command.h.
Referenced by mavlink_msg_command_decode().
static uint8_t mavlink_msg_command_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from command message.
Returns
Component which should execute the command, 0 for all components
Definition at line 213 of file mavlink_msg_command.h.
Referenced by mavlink_msg_command_decode().
static uint8_t mavlink_msg_command_get_target_system (const mavlink_message_t * msg) inline static
Send a command message.
Parameters
chan MAVLink channel to send the message
target_system System which should execute the command
target_component Component which should execute the command, 0 for all components
command Command ID, as defined by MAV_CMD enum.
confirmation 0: First transmission of this command. 1-255: Confirmation transmissions (e.g. for kill command)
param1 Parameter 1, as defined by MAV_CMD enum.
param2 Parameter 2, as defined by MAV_CMD enum.
param3 Parameter 3, as defined by MAV_CMD enum.
param4 Parameter 4, as defined by MAV_CMD enum. Get field target_system from command message
Returns
System which should execute the command
Definition at line 203 of file mavlink_msg_command.h.
Referenced by mavlink_msg_command_decode().
static uint16_t mavlink_msg_command_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t command, uint8_t confirmation, float param1, float param2, float param3, float param4) inline static
Pack a command message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System which should execute the command
target_component Component which should execute the command, 0 for all components
command Command ID, as defined by MAV_CMD enum.
confirmation 0: First transmission of this command. 1-255: Confirmation transmissions (e.g. for kill command)
param1 Parameter 1, as defined by MAV_CMD enum.
param2 Parameter 2, as defined by MAV_CMD enum.
param3 Parameter 3, as defined by MAV_CMD enum.
param4 Parameter 4, as defined by MAV_CMD enum.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 53 of file mavlink_msg_command.h.
Referenced by mavlink_msg_command_encode(), and mavlink_test_command().
static uint16_t mavlink_msg_command_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t command, uint8_t confirmation, float param1, float param2, float param3, float param4) inline static
Pack a command message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
target_system System which should execute the command
target_component Component which should execute the command, 0 for all components
command Command ID, as defined by MAV_CMD enum.
confirmation 0: First transmission of this command. 1-255: Confirmation transmissions (e.g. for kill command)
param1 Parameter 1, as defined by MAV_CMD enum.
param2 Parameter 2, as defined by MAV_CMD enum.
param3 Parameter 3, as defined by MAV_CMD enum.
param4 Parameter 4, as defined by MAV_CMD enum.
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 102 of file mavlink_msg_command.h.
Referenced by mavlink_test_command().