APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_waypoint_set_current.h File Reference
mavlink_msg_waypoint_set_current.h File Reference
Classes
struct __mavlink_waypoint_set_current_t
Macros
#define MAVLINK_MSG_ID_WAYPOINT_SET_CURRENT 41
#define MAVLINK_MSG_ID_WAYPOINT_SET_CURRENT_LEN 4
#define MAVLINK_MSG_ID_41_LEN 4
#define MAVLINK_MESSAGE_INFO_WAYPOINT_SET_CURRENT
Typedefs
typedef struct
__mavlink_waypoint_set_current_t mavlink_waypoint_set_current_t
Functions
static uint16_t mavlink_msg_waypoint_set_current_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint16_t seq)
Pack a waypoint_set_current message.
static uint16_t mavlink_msg_waypoint_set_current_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint16_t seq)
Pack a waypoint_set_current message on a channel.
static uint16_t mavlink_msg_waypoint_set_current_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_waypoint_set_current_t *waypoint_set_current)
Encode a waypoint_set_current struct into a message.
static uint8_t mavlink_msg_waypoint_set_current_get_target_system (const mavlink_message_t *msg)
Send a waypoint_set_current message.
static uint8_t mavlink_msg_waypoint_set_current_get_target_component (const mavlink_message_t *msg)
Get field target_component from waypoint_set_current message.
static uint16_t mavlink_msg_waypoint_set_current_get_seq (const mavlink_message_t *msg)
Get field seq from waypoint_set_current message.
static void mavlink_msg_waypoint_set_current_decode (const mavlink_message_t *msg, mavlink_waypoint_set_current_t *waypoint_set_current)
Decode a waypoint_set_current message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_WAYPOINT_SET_CURRENT
Value:
{ \
    "WAYPOINT_SET_CURRENT", \
    3, \
    {  { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_waypoint_set_current_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_waypoint_set_current_t, target_component) }, \
         { "seq", NULL, MAVLINK_TYPE_UINT16_T, 0, 2, offsetof(mavlink_waypoint_set_current_t, seq) }, \
         } \
}
Definition at line 17 of file mavlink_msg_waypoint_set_current.h.
#define MAVLINK_MSG_ID_41_LEN 4
Definition at line 13 of file mavlink_msg_waypoint_set_current.h.
#define MAVLINK_MSG_ID_WAYPOINT_SET_CURRENT 41
Definition at line 3 of file mavlink_msg_waypoint_set_current.h.
Referenced by mavlink_msg_waypoint_set_current_pack(), and mavlink_msg_waypoint_set_current_pack_chan().
#define MAVLINK_MSG_ID_WAYPOINT_SET_CURRENT_LEN 4
Definition at line 12 of file mavlink_msg_waypoint_set_current.h.
Typedef Documentation
typedef struct __mavlink_waypoint_set_current_t mavlink_waypoint_set_current_t
Function Documentation
static void mavlink_msg_waypoint_set_current_decode (const mavlink_message_t * msg, mavlink_waypoint_set_current_t * waypoint_set_current) inline static
Decode a waypoint_set_current message into a struct.
Parameters
msg The message to decode
waypoint_set_current C-struct to decode the message contents into
Definition at line 179 of file mavlink_msg_waypoint_set_current.h.
Referenced by mavlink_test_waypoint_set_current().
static uint16_t mavlink_msg_waypoint_set_current_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_waypoint_set_current_t * waypoint_set_current) inline static
Encode a waypoint_set_current struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
waypoint_set_current C-struct to read the message contents from
Definition at line 104 of file mavlink_msg_waypoint_set_current.h.
Referenced by mavlink_test_waypoint_set_current().
static uint16_t mavlink_msg_waypoint_set_current_get_seq (const mavlink_message_t * msg) inline static
Get field seq from waypoint_set_current message.
Returns
Sequence
Definition at line 168 of file mavlink_msg_waypoint_set_current.h.
Referenced by mavlink_msg_waypoint_set_current_decode().
static uint8_t mavlink_msg_waypoint_set_current_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from waypoint_set_current message.
Returns
Component ID
Definition at line 158 of file mavlink_msg_waypoint_set_current.h.
Referenced by mavlink_msg_waypoint_set_current_decode().
static uint8_t mavlink_msg_waypoint_set_current_get_target_system (const mavlink_message_t * msg) inline static
Send a waypoint_set_current message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
seq Sequence Get field target_system from waypoint_set_current message
Returns
System ID
Definition at line 148 of file mavlink_msg_waypoint_set_current.h.
Referenced by mavlink_msg_waypoint_set_current_decode().
static uint16_t mavlink_msg_waypoint_set_current_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint16_t seq) inline static
Pack a waypoint_set_current message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
seq Sequence
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_waypoint_set_current.h.
Referenced by mavlink_msg_waypoint_set_current_encode(), and mavlink_test_waypoint_set_current().
static uint16_t mavlink_msg_waypoint_set_current_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint16_t seq) inline static
Pack a waypoint_set_current message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
seq Sequence
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 72 of file mavlink_msg_waypoint_set_current.h.
Referenced by mavlink_test_waypoint_set_current().