APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_action.h File Reference
mavlink_msg_action.h File Reference
Classes
struct __mavlink_action_t
Macros
#define MAVLINK_MSG_ID_ACTION 10
#define MAVLINK_MSG_ID_ACTION_LEN 3
#define MAVLINK_MSG_ID_10_LEN 3
#define MAVLINK_MESSAGE_INFO_ACTION
Typedefs
typedef struct __mavlink_action_t mavlink_action_t
Functions
static uint16_t mavlink_msg_action_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target, uint8_t target_component, uint8_t action)
Pack a action message.
static uint16_t mavlink_msg_action_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target, uint8_t target_component, uint8_t action)
Pack a action message on a channel.
static uint16_t mavlink_msg_action_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_action_t *action)
Encode a action struct into a message.
static uint8_t mavlink_msg_action_get_target (const mavlink_message_t *msg)
Send a action message.
static uint8_t mavlink_msg_action_get_target_component (const mavlink_message_t *msg)
Get field target_component from action message.
static uint8_t mavlink_msg_action_get_action (const mavlink_message_t *msg)
Get field action from action message.
static void mavlink_msg_action_decode (const mavlink_message_t *msg, mavlink_action_t *action)
Decode a action message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_ACTION
Value:
{ \
    "ACTION", \
    3, \
    {  { "target", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_action_t, target) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_action_t, target_component) }, \
         { "action", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_action_t, action) }, \
         } \
}
Definition at line 17 of file mavlink_msg_action.h.
#define MAVLINK_MSG_ID_10_LEN 3
Definition at line 13 of file mavlink_msg_action.h.
#define MAVLINK_MSG_ID_ACTION 10
Definition at line 3 of file mavlink_msg_action.h.
Referenced by mavlink_msg_action_pack(), and mavlink_msg_action_pack_chan().
#define MAVLINK_MSG_ID_ACTION_LEN 3
Definition at line 12 of file mavlink_msg_action.h.
Typedef Documentation
typedef struct __mavlink_action_t mavlink_action_t
Function Documentation
static void mavlink_msg_action_decode (const mavlink_message_t * msg, mavlink_action_t * action) inline static
Decode a action message into a struct.
Parameters
msg The message to decode
action C-struct to decode the message contents into
Definition at line 179 of file mavlink_msg_action.h.
Referenced by mavlink_test_action().
static uint16_t mavlink_msg_action_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_action_t * action) inline static
Encode a action struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
action C-struct to read the message contents from
Definition at line 104 of file mavlink_msg_action.h.
Referenced by mavlink_test_action().
static uint8_t mavlink_msg_action_get_action (const mavlink_message_t * msg) inline static
Get field action from action message.
Returns
The action id
Definition at line 168 of file mavlink_msg_action.h.
Referenced by mavlink_msg_action_decode().
static uint8_t mavlink_msg_action_get_target (const mavlink_message_t * msg) inline static
Send a action message.
Parameters
chan MAVLink channel to send the message
target The system executing the action
target_component The component executing the action
action The action id Get field target from action message
Returns
The system executing the action
Definition at line 148 of file mavlink_msg_action.h.
Referenced by mavlink_msg_action_decode().
static uint8_t mavlink_msg_action_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from action message.
Returns
The component executing the action
Definition at line 158 of file mavlink_msg_action.h.
Referenced by mavlink_msg_action_decode().
static uint16_t mavlink_msg_action_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target, uint8_t target_component, uint8_t action) inline static
Pack a action message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target The system executing the action
target_component The component executing the action
action The action id
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_action.h.
Referenced by mavlink_msg_action_encode(), and mavlink_test_action().
static uint16_t mavlink_msg_action_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target, uint8_t target_component, uint8_t action) inline static
Pack a action message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
target The system executing the action
target_component The component executing the action
action The action id
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 72 of file mavlink_msg_action.h.
Referenced by mavlink_test_action().