APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_set_nav_mode.h File Reference
mavlink_msg_set_nav_mode.h File Reference
Classes
struct __mavlink_set_nav_mode_t
Macros
#define MAVLINK_MSG_ID_SET_NAV_MODE 12
#define MAVLINK_MSG_ID_SET_NAV_MODE_LEN 2
#define MAVLINK_MSG_ID_12_LEN 2
#define MAVLINK_MESSAGE_INFO_SET_NAV_MODE
Typedefs
typedef struct
__mavlink_set_nav_mode_t mavlink_set_nav_mode_t
Functions
static uint16_t mavlink_msg_set_nav_mode_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target, uint8_t nav_mode)
Pack a set_nav_mode message.
static uint16_t mavlink_msg_set_nav_mode_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target, uint8_t nav_mode)
Pack a set_nav_mode message on a channel.
static uint16_t mavlink_msg_set_nav_mode_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_set_nav_mode_t *set_nav_mode)
Encode a set_nav_mode struct into a message.
static uint8_t mavlink_msg_set_nav_mode_get_target (const mavlink_message_t *msg)
Send a set_nav_mode message.
static uint8_t mavlink_msg_set_nav_mode_get_nav_mode (const mavlink_message_t *msg)
Get field nav_mode from set_nav_mode message.
static void mavlink_msg_set_nav_mode_decode (const mavlink_message_t *msg, mavlink_set_nav_mode_t *set_nav_mode)
Decode a set_nav_mode message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_SET_NAV_MODE
Value:
{ \
    "SET_NAV_MODE", \
    2, \
    {  { "target", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_set_nav_mode_t, target) }, \
         { "nav_mode", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_set_nav_mode_t, nav_mode) }, \
         } \
}
Definition at line 16 of file mavlink_msg_set_nav_mode.h.
#define MAVLINK_MSG_ID_12_LEN 2
Definition at line 12 of file mavlink_msg_set_nav_mode.h.
#define MAVLINK_MSG_ID_SET_NAV_MODE 12
Definition at line 3 of file mavlink_msg_set_nav_mode.h.
Referenced by mavlink_msg_set_nav_mode_pack(), and mavlink_msg_set_nav_mode_pack_chan().
#define MAVLINK_MSG_ID_SET_NAV_MODE_LEN 2
Definition at line 11 of file mavlink_msg_set_nav_mode.h.
Typedef Documentation
typedef struct __mavlink_set_nav_mode_t mavlink_set_nav_mode_t
Function Documentation
static void mavlink_msg_set_nav_mode_decode (const mavlink_message_t * msg, mavlink_set_nav_mode_t * set_nav_mode) inline static
Decode a set_nav_mode message into a struct.
Parameters
msg The message to decode
set_nav_mode C-struct to decode the message contents into
Definition at line 158 of file mavlink_msg_set_nav_mode.h.
Referenced by mavlink_test_set_nav_mode().
static uint16_t mavlink_msg_set_nav_mode_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_set_nav_mode_t * set_nav_mode) inline static
Encode a set_nav_mode struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
set_nav_mode C-struct to read the message contents from
Definition at line 96 of file mavlink_msg_set_nav_mode.h.
Referenced by mavlink_test_set_nav_mode().
static uint8_t mavlink_msg_set_nav_mode_get_nav_mode (const mavlink_message_t * msg) inline static
Get field nav_mode from set_nav_mode message.
Returns
The new navigation mode
Definition at line 147 of file mavlink_msg_set_nav_mode.h.
Referenced by mavlink_msg_set_nav_mode_decode().
static uint8_t mavlink_msg_set_nav_mode_get_target (const mavlink_message_t * msg) inline static
Send a set_nav_mode message.
Parameters
chan MAVLink channel to send the message
target The system setting the mode
nav_mode The new navigation mode Get field target from set_nav_mode message
Returns
The system setting the mode
Definition at line 137 of file mavlink_msg_set_nav_mode.h.
Referenced by mavlink_msg_set_nav_mode_decode().
static uint16_t mavlink_msg_set_nav_mode_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target, uint8_t nav_mode) inline static
Pack a set_nav_mode message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target The system setting the mode
nav_mode The new navigation mode
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 35 of file mavlink_msg_set_nav_mode.h.
Referenced by mavlink_msg_set_nav_mode_encode(), and mavlink_test_set_nav_mode().
static uint16_t mavlink_msg_set_nav_mode_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target, uint8_t nav_mode) inline static
Pack a set_nav_mode message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
target The system setting the mode
nav_mode The new navigation mode
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 66 of file mavlink_msg_set_nav_mode.h.
Referenced by mavlink_test_set_nav_mode().