APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint.h File Reference
mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint.h File Reference
Classes
struct __mavlink_roll_pitch_yaw_speed_thrust_setpoint_t
Macros
#define MAVLINK_MSG_ID_ROLL_PITCH_YAW_SPEED_THRUST_SETPOINT 58
#define MAVLINK_MSG_ID_ROLL_PITCH_YAW_SPEED_THRUST_SETPOINT_LEN 24
#define MAVLINK_MSG_ID_58_LEN 24
#define MAVLINK_MESSAGE_INFO_ROLL_PITCH_YAW_SPEED_THRUST_SETPOINT
Typedefs
typedef struct
__mavlink_roll_pitch_yaw_speed_thrust_setpoint_t mavlink_roll_pitch_yaw_speed_thrust_setpoint_t
Functions
static uint16_t mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t time_us, float roll_speed, float pitch_speed, float yaw_speed, float thrust)
Pack a roll_pitch_yaw_speed_thrust_setpoint message.
static uint16_t mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t time_us, float roll_speed, float pitch_speed, float yaw_speed, float thrust)
Pack a roll_pitch_yaw_speed_thrust_setpoint message on a channel.
static uint16_t mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_roll_pitch_yaw_speed_thrust_setpoint_t *roll_pitch_yaw_speed_thrust_setpoint)
Encode a roll_pitch_yaw_speed_thrust_setpoint struct into a message.
static uint64_t mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_get_time_us (const mavlink_message_t *msg)
Send a roll_pitch_yaw_speed_thrust_setpoint message.
static float mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_get_roll_speed (const mavlink_message_t *msg)
Get field roll_speed from roll_pitch_yaw_speed_thrust_setpoint message.
static float mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_get_pitch_speed (const mavlink_message_t *msg)
Get field pitch_speed from roll_pitch_yaw_speed_thrust_setpoint message.
static float mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_get_yaw_speed (const mavlink_message_t *msg)
Get field yaw_speed from roll_pitch_yaw_speed_thrust_setpoint message.
static float mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_get_thrust (const mavlink_message_t *msg)
Get field thrust from roll_pitch_yaw_speed_thrust_setpoint message.
static void mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_decode (const mavlink_message_t *msg, mavlink_roll_pitch_yaw_speed_thrust_setpoint_t *roll_pitch_yaw_speed_thrust_setpoint)
Decode a roll_pitch_yaw_speed_thrust_setpoint message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_ROLL_PITCH_YAW_SPEED_THRUST_SETPOINT
Value:
{ \
    "ROLL_PITCH_YAW_SPEED_THRUST_SETPOINT", \
    5, \
    {  { "time_us", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_roll_pitch_yaw_speed_thrust_setpoint_t, time_us) }, \
         { "roll_speed", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_roll_pitch_yaw_speed_thrust_setpoint_t, roll_speed) }, \
         { "pitch_speed", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_roll_pitch_yaw_speed_thrust_setpoint_t, pitch_speed) }, \
         { "yaw_speed", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_roll_pitch_yaw_speed_thrust_setpoint_t, yaw_speed) }, \
         { "thrust", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_roll_pitch_yaw_speed_thrust_setpoint_t, thrust) }, \
         } \
}
Definition at line 19 of file mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint.h.
#define MAVLINK_MSG_ID_58_LEN 24
Definition at line 15 of file mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint.h.
#define MAVLINK_MSG_ID_ROLL_PITCH_YAW_SPEED_THRUST_SETPOINT 58
Definition at line 3 of file mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint.h.
Referenced by mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_pack(), and mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_pack_chan().
#define MAVLINK_MSG_ID_ROLL_PITCH_YAW_SPEED_THRUST_SETPOINT_LEN 24
Definition at line 14 of file mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint.h.
Typedef Documentation
typedef struct __mavlink_roll_pitch_yaw_speed_thrust_setpoint_t mavlink_roll_pitch_yaw_speed_thrust_setpoint_t
Function Documentation
static void mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_decode (const mavlink_message_t * msg, mavlink_roll_pitch_yaw_speed_thrust_setpoint_t * roll_pitch_yaw_speed_thrust_setpoint) inline static
Decode a roll_pitch_yaw_speed_thrust_setpoint message into a struct.
Parameters
msg The message to decode
roll_pitch_yaw_speed_thrust_setpoint C-struct to decode the message contents into
Definition at line 221 of file mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint.h.
Referenced by mavlink_test_roll_pitch_yaw_speed_thrust_setpoint().
static uint16_t mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_roll_pitch_yaw_speed_thrust_setpoint_t * roll_pitch_yaw_speed_thrust_setpoint) inline static
Encode a roll_pitch_yaw_speed_thrust_setpoint struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
roll_pitch_yaw_speed_thrust_setpoint C-struct to read the message contents from
Definition at line 120 of file mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint.h.
Referenced by mavlink_test_roll_pitch_yaw_speed_thrust_setpoint().
static float mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_get_pitch_speed (const mavlink_message_t * msg) inline static
Get field pitch_speed from roll_pitch_yaw_speed_thrust_setpoint message.
Returns
Desired pitch angular speed in rad/s
Definition at line 190 of file mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint.h.
Referenced by mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_decode().
static float mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_get_roll_speed (const mavlink_message_t * msg) inline static
Get field roll_speed from roll_pitch_yaw_speed_thrust_setpoint message.
Returns
Desired roll angular speed in rad/s
Definition at line 180 of file mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint.h.
Referenced by mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_decode().
static float mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_get_thrust (const mavlink_message_t * msg) inline static
Get field thrust from roll_pitch_yaw_speed_thrust_setpoint message.
Returns
Collective thrust, normalized to 0 .. 1
Definition at line 210 of file mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint.h.
Referenced by mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_decode().
static uint64_t mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_get_time_us (const mavlink_message_t * msg) inline static
Send a roll_pitch_yaw_speed_thrust_setpoint message.
Parameters
chan MAVLink channel to send the message
time_us Timestamp in micro seconds since unix epoch
roll_speed Desired roll angular speed in rad/s
pitch_speed Desired pitch angular speed in rad/s
yaw_speed Desired yaw angular speed in rad/s
thrust Collective thrust, normalized to 0 .. 1 Get field time_us from roll_pitch_yaw_speed_thrust_setpoint message
Returns
Timestamp in micro seconds since unix epoch
Definition at line 170 of file mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint.h.
Referenced by mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_decode().
static float mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_get_yaw_speed (const mavlink_message_t * msg) inline static
Get field yaw_speed from roll_pitch_yaw_speed_thrust_setpoint message.
Returns
Desired yaw angular speed in rad/s
Definition at line 200 of file mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint.h.
Referenced by mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_decode().
static uint16_t mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t time_us, float roll_speed, float pitch_speed, float yaw_speed, float thrust) inline static
Pack a roll_pitch_yaw_speed_thrust_setpoint message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time_us Timestamp in micro seconds since unix epoch
roll_speed Desired roll angular speed in rad/s
pitch_speed Desired pitch angular speed in rad/s
yaw_speed Desired yaw angular speed in rad/s
thrust Collective thrust, normalized to 0 .. 1
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 44 of file mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint.h.
Referenced by mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_encode(), and mavlink_test_roll_pitch_yaw_speed_thrust_setpoint().
static uint16_t mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t time_us, float roll_speed, float pitch_speed, float yaw_speed, float thrust) inline static
Pack a roll_pitch_yaw_speed_thrust_setpoint message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
time_us Timestamp in micro seconds since unix epoch
roll_speed Desired roll angular speed in rad/s
pitch_speed Desired pitch angular speed in rad/s
yaw_speed Desired yaw angular speed in rad/s
thrust Collective thrust, normalized to 0 .. 1
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 84 of file mavlink_msg_roll_pitch_yaw_speed_thrust_setpoint.h.
Referenced by mavlink_test_roll_pitch_yaw_speed_thrust_setpoint().