APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_object_detection_event.h File Reference
mavlink_msg_object_detection_event.h File Reference
Classes
struct __mavlink_object_detection_event_t
Macros
#define MAVLINK_MSG_ID_OBJECT_DETECTION_EVENT 140
#define MAVLINK_MSG_ID_OBJECT_DETECTION_EVENT_LEN 36
#define MAVLINK_MSG_ID_140_LEN 36
#define MAVLINK_MSG_OBJECT_DETECTION_EVENT_FIELD_NAME_LEN 20
#define MAVLINK_MESSAGE_INFO_OBJECT_DETECTION_EVENT
Typedefs
typedef struct
__mavlink_object_detection_event_t mavlink_object_detection_event_t
Functions
static uint16_t mavlink_msg_object_detection_event_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint32_t time, uint16_t object_id, uint8_t type, const char *name, uint8_t quality, float bearing, float distance)
Pack a object_detection_event message.
static uint16_t mavlink_msg_object_detection_event_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint32_t time, uint16_t object_id, uint8_t type, const char *name, uint8_t quality, float bearing, float distance)
Pack a object_detection_event message on a channel.
static uint16_t mavlink_msg_object_detection_event_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_object_detection_event_t *object_detection_event)
Encode a object_detection_event struct into a message.
static uint32_t mavlink_msg_object_detection_event_get_time (const mavlink_message_t *msg)
Send a object_detection_event message.
static uint16_t mavlink_msg_object_detection_event_get_object_id (const mavlink_message_t *msg)
Get field object_id from object_detection_event message.
static uint8_t mavlink_msg_object_detection_event_get_type (const mavlink_message_t *msg)
Get field type from object_detection_event message.
static uint16_t mavlink_msg_object_detection_event_get_name (const mavlink_message_t *msg, char *name)
Get field name from object_detection_event message.
static uint8_t mavlink_msg_object_detection_event_get_quality (const mavlink_message_t *msg)
Get field quality from object_detection_event message.
static float mavlink_msg_object_detection_event_get_bearing (const mavlink_message_t *msg)
Get field bearing from object_detection_event message.
static float mavlink_msg_object_detection_event_get_distance (const mavlink_message_t *msg)
Get field distance from object_detection_event message.
static void mavlink_msg_object_detection_event_decode (const mavlink_message_t *msg, mavlink_object_detection_event_t *object_detection_event)
Decode a object_detection_event message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_OBJECT_DETECTION_EVENT
Value:
{ \
    "OBJECT_DETECTION_EVENT", \
    7, \
    {  { "time", NULL, MAVLINK_TYPE_UINT32_T, 0, 0, offsetof(mavlink_object_detection_event_t, time) }, \
         { "object_id", NULL, MAVLINK_TYPE_UINT16_T, 0, 4, offsetof(mavlink_object_detection_event_t, object_id) }, \
         { "type", NULL, MAVLINK_TYPE_UINT8_T, 0, 6, offsetof(mavlink_object_detection_event_t, type) }, \
         { "name", NULL, MAVLINK_TYPE_CHAR, 20, 7, offsetof(mavlink_object_detection_event_t, name) }, \
         { "quality", NULL, MAVLINK_TYPE_UINT8_T, 0, 27, offsetof(mavlink_object_detection_event_t, quality) }, \
         { "bearing", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_object_detection_event_t, bearing) }, \
         { "distance", NULL, MAVLINK_TYPE_FLOAT, 0, 32, offsetof(mavlink_object_detection_event_t, distance) }, \
         } \
}
Definition at line 21 of file mavlink_msg_object_detection_event.h.
#define MAVLINK_MSG_ID_140_LEN 36
Definition at line 17 of file mavlink_msg_object_detection_event.h.
#define MAVLINK_MSG_ID_OBJECT_DETECTION_EVENT 140
Definition at line 3 of file mavlink_msg_object_detection_event.h.
Referenced by mavlink_msg_object_detection_event_pack(), and mavlink_msg_object_detection_event_pack_chan().
#define MAVLINK_MSG_ID_OBJECT_DETECTION_EVENT_LEN 36
Definition at line 16 of file mavlink_msg_object_detection_event.h.
#define MAVLINK_MSG_OBJECT_DETECTION_EVENT_FIELD_NAME_LEN 20
Definition at line 19 of file mavlink_msg_object_detection_event.h.
Typedef Documentation
typedef struct __mavlink_object_detection_event_t mavlink_object_detection_event_t
Function Documentation
static void mavlink_msg_object_detection_event_decode (const mavlink_message_t * msg, mavlink_object_detection_event_t * object_detection_event) inline static
Decode a object_detection_event message into a struct.
Parameters
msg The message to decode
object_detection_event C-struct to decode the message contents into
Definition at line 257 of file mavlink_msg_object_detection_event.h.
Referenced by mavlink_test_object_detection_event().
static uint16_t mavlink_msg_object_detection_event_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_object_detection_event_t * object_detection_event) inline static
Encode a object_detection_event struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
object_detection_event C-struct to read the message contents from
Definition at line 132 of file mavlink_msg_object_detection_event.h.
Referenced by mavlink_test_object_detection_event().
static float mavlink_msg_object_detection_event_get_bearing (const mavlink_message_t * msg) inline static
Get field bearing from object_detection_event message.
Returns
Angle of the object with respect to the body frame in NED coordinates in radians. 0: front
Definition at line 236 of file mavlink_msg_object_detection_event.h.
Referenced by mavlink_msg_object_detection_event_decode().
static float mavlink_msg_object_detection_event_get_distance (const mavlink_message_t * msg) inline static
Get field distance from object_detection_event message.
Returns
Ground distance in meters
Definition at line 246 of file mavlink_msg_object_detection_event.h.
Referenced by mavlink_msg_object_detection_event_decode().
static uint16_t mavlink_msg_object_detection_event_get_name (const mavlink_message_t * msg, char * name) inline static
Get field name from object_detection_event message.
Returns
Name of the object as defined by the detector
Definition at line 216 of file mavlink_msg_object_detection_event.h.
Referenced by mavlink_msg_object_detection_event_decode().
static uint16_t mavlink_msg_object_detection_event_get_object_id (const mavlink_message_t * msg) inline static
Get field object_id from object_detection_event message.
Returns
Object ID
Definition at line 196 of file mavlink_msg_object_detection_event.h.
Referenced by mavlink_msg_object_detection_event_decode().
static uint8_t mavlink_msg_object_detection_event_get_quality (const mavlink_message_t * msg) inline static
Get field quality from object_detection_event message.
Returns
Detection quality / confidence. 0: bad, 255: maximum confidence
Definition at line 226 of file mavlink_msg_object_detection_event.h.
Referenced by mavlink_msg_object_detection_event_decode().
static uint32_t mavlink_msg_object_detection_event_get_time (const mavlink_message_t * msg) inline static
Send a object_detection_event message.
Parameters
chan MAVLink channel to send the message
time Timestamp in milliseconds since system boot
object_id Object ID
type Object type: 0: image, 1: letter, 2: ground vehicle, 3: air vehicle, 4: surface vehicle, 5: sub-surface vehicle, 6: human, 7: animal
name Name of the object as defined by the detector
quality Detection quality / confidence. 0: bad, 255: maximum confidence
bearing Angle of the object with respect to the body frame in NED coordinates in radians. 0: front
distance Ground distance in meters Get field time from object_detection_event message
Returns
Timestamp in milliseconds since system boot
Definition at line 186 of file mavlink_msg_object_detection_event.h.
Referenced by mavlink_msg_object_detection_event_decode().
static uint8_t mavlink_msg_object_detection_event_get_type (const mavlink_message_t * msg) inline static
Get field type from object_detection_event message.
Returns
Object type: 0: image, 1: letter, 2: ground vehicle, 3: air vehicle, 4: surface vehicle, 5: sub-surface vehicle, 6: human, 7: animal
Definition at line 206 of file mavlink_msg_object_detection_event.h.
Referenced by mavlink_msg_object_detection_event_decode().
static uint16_t mavlink_msg_object_detection_event_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint32_t time, uint16_t object_id, uint8_t type, const char * name, uint8_t quality, float bearing, float distance) inline static
Pack a object_detection_event message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
time Timestamp in milliseconds since system boot
object_id Object ID
type Object type: 0: image, 1: letter, 2: ground vehicle, 3: air vehicle, 4: surface vehicle, 5: sub-surface vehicle, 6: human, 7: animal
name Name of the object as defined by the detector
quality Detection quality / confidence. 0: bad, 255: maximum confidence
bearing Angle of the object with respect to the body frame in NED coordinates in radians. 0: front
distance Ground distance in meters
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 50 of file mavlink_msg_object_detection_event.h.
Referenced by mavlink_msg_object_detection_event_encode(), and mavlink_test_object_detection_event().
static uint16_t mavlink_msg_object_detection_event_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint32_t time, uint16_t object_id, uint8_t type, const char * name, uint8_t quality, float bearing, float distance) inline static
Pack a object_detection_event message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
time Timestamp in milliseconds since system boot
object_id Object ID
type Object type: 0: image, 1: letter, 2: ground vehicle, 3: air vehicle, 4: surface vehicle, 5: sub-surface vehicle, 6: human, 7: animal
name Name of the object as defined by the detector
quality Detection quality / confidence. 0: bad, 255: maximum confidence
bearing Angle of the object with respect to the body frame in NED coordinates in radians. 0: front
distance Ground distance in meters
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 94 of file mavlink_msg_object_detection_event.h.
Referenced by mavlink_test_object_detection_event().