APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_waypoint_ack.h File Reference
mavlink_msg_waypoint_ack.h File Reference
Classes
struct __mavlink_waypoint_ack_t
Macros
#define MAVLINK_MSG_ID_WAYPOINT_ACK 47
#define MAVLINK_MSG_ID_WAYPOINT_ACK_LEN 3
#define MAVLINK_MSG_ID_47_LEN 3
#define MAVLINK_MESSAGE_INFO_WAYPOINT_ACK
Typedefs
typedef struct
__mavlink_waypoint_ack_t mavlink_waypoint_ack_t
Functions
static uint16_t mavlink_msg_waypoint_ack_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t type)
Pack a waypoint_ack message.
static uint16_t mavlink_msg_waypoint_ack_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target_system, uint8_t target_component, uint8_t type)
Pack a waypoint_ack message on a channel.
static uint16_t mavlink_msg_waypoint_ack_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_waypoint_ack_t *waypoint_ack)
Encode a waypoint_ack struct into a message.
static uint8_t mavlink_msg_waypoint_ack_get_target_system (const mavlink_message_t *msg)
Send a waypoint_ack message.
static uint8_t mavlink_msg_waypoint_ack_get_target_component (const mavlink_message_t *msg)
Get field target_component from waypoint_ack message.
static uint8_t mavlink_msg_waypoint_ack_get_type (const mavlink_message_t *msg)
Get field type from waypoint_ack message.
static void mavlink_msg_waypoint_ack_decode (const mavlink_message_t *msg, mavlink_waypoint_ack_t *waypoint_ack)
Decode a waypoint_ack message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_WAYPOINT_ACK
Value:
{ \
    "WAYPOINT_ACK", \
    3, \
    {  { "target_system", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_waypoint_ack_t, target_system) }, \
         { "target_component", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_waypoint_ack_t, target_component) }, \
         { "type", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_waypoint_ack_t, type) }, \
         } \
}
Definition at line 17 of file mavlink_msg_waypoint_ack.h.
#define MAVLINK_MSG_ID_47_LEN 3
Definition at line 13 of file mavlink_msg_waypoint_ack.h.
#define MAVLINK_MSG_ID_WAYPOINT_ACK 47
Definition at line 3 of file mavlink_msg_waypoint_ack.h.
Referenced by mavlink_msg_waypoint_ack_pack(), and mavlink_msg_waypoint_ack_pack_chan().
#define MAVLINK_MSG_ID_WAYPOINT_ACK_LEN 3
Definition at line 12 of file mavlink_msg_waypoint_ack.h.
Typedef Documentation
typedef struct __mavlink_waypoint_ack_t mavlink_waypoint_ack_t
Function Documentation
static void mavlink_msg_waypoint_ack_decode (const mavlink_message_t * msg, mavlink_waypoint_ack_t * waypoint_ack) inline static
Decode a waypoint_ack message into a struct.
Parameters
msg The message to decode
waypoint_ack C-struct to decode the message contents into
Definition at line 179 of file mavlink_msg_waypoint_ack.h.
Referenced by mavlink_test_waypoint_ack().
static uint16_t mavlink_msg_waypoint_ack_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_waypoint_ack_t * waypoint_ack) inline static
Encode a waypoint_ack struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
waypoint_ack C-struct to read the message contents from
Definition at line 104 of file mavlink_msg_waypoint_ack.h.
Referenced by mavlink_test_waypoint_ack().
static uint8_t mavlink_msg_waypoint_ack_get_target_component (const mavlink_message_t * msg) inline static
Get field target_component from waypoint_ack message.
Returns
Component ID
Definition at line 158 of file mavlink_msg_waypoint_ack.h.
Referenced by mavlink_msg_waypoint_ack_decode().
static uint8_t mavlink_msg_waypoint_ack_get_target_system (const mavlink_message_t * msg) inline static
Send a waypoint_ack message.
Parameters
chan MAVLink channel to send the message
target_system System ID
target_component Component ID
type 0: OK, 1: Error Get field target_system from waypoint_ack message
Returns
System ID
Definition at line 148 of file mavlink_msg_waypoint_ack.h.
Referenced by mavlink_msg_waypoint_ack_decode().
static uint8_t mavlink_msg_waypoint_ack_get_type (const mavlink_message_t * msg) inline static
Get field type from waypoint_ack message.
Returns
0: OK, 1: Error
Definition at line 168 of file mavlink_msg_waypoint_ack.h.
Referenced by mavlink_msg_waypoint_ack_decode().
static uint16_t mavlink_msg_waypoint_ack_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t type) inline static
Pack a waypoint_ack message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
type 0: OK, 1: Error
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 38 of file mavlink_msg_waypoint_ack.h.
Referenced by mavlink_msg_waypoint_ack_encode(), and mavlink_test_waypoint_ack().
static uint16_t mavlink_msg_waypoint_ack_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target_system, uint8_t target_component, uint8_t type) inline static
Pack a waypoint_ack message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
target_system System ID
target_component Component ID
type 0: OK, 1: Error
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 72 of file mavlink_msg_waypoint_ack.h.
Referenced by mavlink_test_waypoint_ack().