APM:Libraries: libraries/AP_Math/examples/rotations/rotations.pde File Reference
rotations.pde File Reference
#include <AP_HAL.h>
#include <stdlib.h>
#include <AP_Common.h>
#include <AP_Progmem.h>
#include <AP_Param.h>
#include <AP_HAL_AVR.h>
#include <AP_HAL_SITL.h>
#include <AP_HAL_Empty.h>
#include <AP_HAL_PX4.h>
#include <AP_HAL_Linux.h>
#include <AP_Math.h>
#include <Filter.h>
#include <AP_ADC.h>
#include <SITL.h>
#include <AP_Compass.h>
#include <AP_Baro.h>
#include <AP_Notify.h>
#include <AP_InertialSensor.h>
#include <AP_GPS.h>
#include <DataFlash.h>
#include <GCS_MAVLink.h>
#include <AP_Mission.h>
#include <StorageManager.h>
#include <AP_Terrain.h>
#include <AP_Declination.h>
#include <AP_AHRS.h>
#include <AP_NavEKF.h>
#include <AP_Airspeed.h>
#include <AP_Vehicle.h>
#include <AP_ADC_AnalogSource.h>
#include <AP_Rally.h>
#include <AP_BattMonitor.h>
#include <AP_RangeFinder.h>
Functions
static void print_vector (Vector3f &v)
static void test_rotation_accuracy (void)
static void test_euler (enum Rotation rotation, float roll, float pitch, float yaw)
static void test_eulers (void)
static bool have_rotation (const Matrix3f &m)
static void missing_rotations (void)
void setup (void)
void loop (void)
AP_HAL_MAIN ()
Variables
const AP_HAL::HAL & hal = AP_HAL_BOARD_DRIVER
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
Function Documentation
AP_HAL_MAIN ()
static bool have_rotation (const Matrix3f & m) static
Definition at line 156 of file rotations.pde.
Referenced by missing_rotations().
void loop (void)
Definition at line 200 of file rotations.pde.
static void missing_rotations (void) static
Definition at line 173 of file rotations.pde.
Referenced by setup().
static void print_vector (Vector3f & v) static
Definition at line 41 of file rotations.pde.
Referenced by test_euler().
void setup (void)
Definition at line 191 of file rotations.pde.
static void test_euler (enum Rotation rotation, float roll, float pitch, float yaw) static
Definition at line 80 of file rotations.pde.
Referenced by test_eulers().
static void test_eulers (void) static
Definition at line 112 of file rotations.pde.
Referenced by setup().
static void test_rotation_accuracy (void) static
Definition at line 48 of file rotations.pde.
Referenced by setup().
Variable Documentation
const AP_HAL::HAL& hal = AP_HAL_BOARD_DRIVER
-*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-
The strategy for roll/pitch autotune is to give the user a AUTOTUNE flight mode which behaves just like FBWA, but does automatic tuning.
While the user is flying in AUTOTUNE the gains are saved every 10 seconds, but the saved gains are not the current gains, instead it saves the gains from 10s ago. When the user exits AUTOTUNE the gains are restored from 10s ago.
This allows the user to fly as much as they want in AUTOTUNE mode, and if they are ever unhappy they just exit the mode. If they stay in AUTOTUNE for more than 10s then their gains will have changed.
Using this approach users don't need any special switches, they just need to be able to enter and exit AUTOTUNE mode
Definition at line 39 of file rotations.pde.