APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/ardupilotmega/testsuite.h File Reference
testsuite.h File Reference
MAVLink comm protocol testsuite generated from ardupilotmega.xml.
#include "../common/testsuite.h"
Macros
#define MAVLINK_TEST_ALL
Functions
static void mavlink_test_common (uint8_t, uint8_t, mavlink_message_t *last_msg)
static void mavlink_test_ardupilotmega (uint8_t, uint8_t, mavlink_message_t *last_msg)
static void mavlink_test_all (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_sensor_offsets (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_set_mag_offsets (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_meminfo (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_ap_adc (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_digicam_configure (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_digicam_control (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mount_configure (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mount_control (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_mount_status (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_fence_point (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_fence_fetch_point (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_fence_status (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_ahrs (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_simstate (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_hwstatus (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_radio (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
Detailed Description
MAVLink comm protocol testsuite generated from ardupilotmega.xml.
See Also
http://qgroundcontrol.org/mavlink/
Definition in file testsuite.h.
Macro Definition Documentation
#define MAVLINK_TEST_ALL
Definition at line 13 of file testsuite.h.
Function Documentation
static void mavlink_test_ahrs (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 671 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_all (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 17 of file testsuite.h.
static void mavlink_test_ap_adc (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 188 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_ardupilotmega (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 885 of file testsuite.h.
Referenced by mavlink_test_all().
static void mavlink_test_common (uint8_t , uint8_t , mavlink_message_t * last_msg) static
Referenced by mavlink_test_all().
static void mavlink_test_digicam_configure (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 241 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_digicam_control (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 304 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_fence_fetch_point (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 575 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_fence_point (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 522 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_fence_status (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 622 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_hwstatus (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 785 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_meminfo (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 143 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_mount_configure (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 365 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_mount_control (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 418 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_mount_status (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 471 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_radio (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 830 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_sensor_offsets (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 27 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_set_mag_offsets (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 92 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().
static void mavlink_test_simstate (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 726 of file testsuite.h.
Referenced by mavlink_test_ardupilotmega().