APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_attitude.h File Reference
mavlink_msg_attitude.h File Reference
Classes
struct __mavlink_attitude_t
Macros
#define MAVLINK_MSG_ID_ATTITUDE 30
#define MAVLINK_MSG_ID_ATTITUDE_LEN 32
#define MAVLINK_MSG_ID_30_LEN 32
#define MAVLINK_MESSAGE_INFO_ATTITUDE
Typedefs
typedef struct __mavlink_attitude_t mavlink_attitude_t
Functions
static uint16_t mavlink_msg_attitude_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t usec, float roll, float pitch, float yaw, float rollspeed, float pitchspeed, float yawspeed)
Pack a attitude message.
static uint16_t mavlink_msg_attitude_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t usec, float roll, float pitch, float yaw, float rollspeed, float pitchspeed, float yawspeed)
Pack a attitude message on a channel.
static uint16_t mavlink_msg_attitude_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_attitude_t *attitude)
Encode a attitude struct into a message.
static uint64_t mavlink_msg_attitude_get_usec (const mavlink_message_t *msg)
Send a attitude message.
static float mavlink_msg_attitude_get_roll (const mavlink_message_t *msg)
Get field roll from attitude message.
static float mavlink_msg_attitude_get_pitch (const mavlink_message_t *msg)
Get field pitch from attitude message.
static float mavlink_msg_attitude_get_yaw (const mavlink_message_t *msg)
Get field yaw from attitude message.
static float mavlink_msg_attitude_get_rollspeed (const mavlink_message_t *msg)
Get field rollspeed from attitude message.
static float mavlink_msg_attitude_get_pitchspeed (const mavlink_message_t *msg)
Get field pitchspeed from attitude message.
static float mavlink_msg_attitude_get_yawspeed (const mavlink_message_t *msg)
Get field yawspeed from attitude message.
static void mavlink_msg_attitude_decode (const mavlink_message_t *msg, mavlink_attitude_t *attitude)
Decode a attitude message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_ATTITUDE
Value:
{ \
    "ATTITUDE", \
    7, \
    {  { "usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_attitude_t, usec) }, \
         { "roll", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_attitude_t, roll) }, \
         { "pitch", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_attitude_t, pitch) }, \
         { "yaw", NULL, MAVLINK_TYPE_FLOAT, 0, 16, offsetof(mavlink_attitude_t, yaw) }, \
         { "rollspeed", NULL, MAVLINK_TYPE_FLOAT, 0, 20, offsetof(mavlink_attitude_t, rollspeed) }, \
         { "pitchspeed", NULL, MAVLINK_TYPE_FLOAT, 0, 24, offsetof(mavlink_attitude_t, pitchspeed) }, \
         { "yawspeed", NULL, MAVLINK_TYPE_FLOAT, 0, 28, offsetof(mavlink_attitude_t, yawspeed) }, \
         } \
}
Definition at line 21 of file mavlink_msg_attitude.h.
#define MAVLINK_MSG_ID_30_LEN 32
Definition at line 17 of file mavlink_msg_attitude.h.
#define MAVLINK_MSG_ID_ATTITUDE 30
Definition at line 3 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_pack(), and mavlink_msg_attitude_pack_chan().
#define MAVLINK_MSG_ID_ATTITUDE_LEN 32
Definition at line 16 of file mavlink_msg_attitude.h.
Typedef Documentation
typedef struct __mavlink_attitude_t mavlink_attitude_t
Function Documentation
static void mavlink_msg_attitude_decode (const mavlink_message_t * msg, mavlink_attitude_t * attitude) inline static
Decode a attitude message into a struct.
Parameters
msg The message to decode
attitude C-struct to decode the message contents into
Definition at line 263 of file mavlink_msg_attitude.h.
Referenced by mavlink_test_attitude().
static uint16_t mavlink_msg_attitude_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_attitude_t * attitude) inline static
Encode a attitude struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
attitude C-struct to read the message contents from
Definition at line 136 of file mavlink_msg_attitude.h.
Referenced by loop(), and mavlink_test_attitude().
static float mavlink_msg_attitude_get_pitch (const mavlink_message_t * msg) inline static
Get field pitch from attitude message.
Returns
Pitch angle (rad)
Definition at line 212 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_decode().
static float mavlink_msg_attitude_get_pitchspeed (const mavlink_message_t * msg) inline static
Get field pitchspeed from attitude message.
Returns
Pitch angular speed (rad/s)
Definition at line 242 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_decode().
static float mavlink_msg_attitude_get_roll (const mavlink_message_t * msg) inline static
Get field roll from attitude message.
Returns
Roll angle (rad)
Definition at line 202 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_decode().
static float mavlink_msg_attitude_get_rollspeed (const mavlink_message_t * msg) inline static
Get field rollspeed from attitude message.
Returns
Roll angular speed (rad/s)
Definition at line 232 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_decode().
static uint64_t mavlink_msg_attitude_get_usec (const mavlink_message_t * msg) inline static
Send a attitude message.
Parameters
chan MAVLink channel to send the message
usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
roll Roll angle (rad)
pitch Pitch angle (rad)
yaw Yaw angle (rad)
rollspeed Roll angular speed (rad/s)
pitchspeed Pitch angular speed (rad/s)
yawspeed Yaw angular speed (rad/s) Get field usec from attitude message
Returns
Timestamp (microseconds since UNIX epoch or microseconds since system boot)
Definition at line 192 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_decode().
static float mavlink_msg_attitude_get_yaw (const mavlink_message_t * msg) inline static
Get field yaw from attitude message.
Returns
Yaw angle (rad)
Definition at line 222 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_decode().
static float mavlink_msg_attitude_get_yawspeed (const mavlink_message_t * msg) inline static
Get field yawspeed from attitude message.
Returns
Yaw angular speed (rad/s)
Definition at line 252 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_decode().
static uint16_t mavlink_msg_attitude_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t usec, float roll, float pitch, float yaw, float rollspeed, float pitchspeed, float yawspeed) inline static
Pack a attitude message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
roll Roll angle (rad)
pitch Pitch angle (rad)
yaw Yaw angle (rad)
rollspeed Roll angular speed (rad/s)
pitchspeed Pitch angular speed (rad/s)
yawspeed Yaw angular speed (rad/s)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 50 of file mavlink_msg_attitude.h.
Referenced by mavlink_msg_attitude_encode(), and mavlink_test_attitude().
static uint16_t mavlink_msg_attitude_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t usec, float roll, float pitch, float yaw, float rollspeed, float pitchspeed, float yawspeed) inline static
Pack a attitude message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
roll Roll angle (rad)
pitch Pitch angle (rad)
yaw Yaw angle (rad)
rollspeed Roll angular speed (rad/s)
pitchspeed Pitch angular speed (rad/s)
yawspeed Yaw angular speed (rad/s)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 96 of file mavlink_msg_attitude.h.
Referenced by mavlink_test_attitude().