APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_rc_channels_raw.h File Reference
mavlink_msg_rc_channels_raw.h File Reference
Classes
struct __mavlink_rc_channels_raw_t
Macros
#define MAVLINK_MSG_ID_RC_CHANNELS_RAW 35
#define MAVLINK_MSG_ID_RC_CHANNELS_RAW_LEN 17
#define MAVLINK_MSG_ID_35_LEN 17
#define MAVLINK_MESSAGE_INFO_RC_CHANNELS_RAW
Typedefs
typedef struct
__mavlink_rc_channels_raw_t mavlink_rc_channels_raw_t
Functions
static uint16_t mavlink_msg_rc_channels_raw_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw, uint8_t rssi)
Pack a rc_channels_raw message.
static uint16_t mavlink_msg_rc_channels_raw_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw, uint8_t rssi)
Pack a rc_channels_raw message on a channel.
static uint16_t mavlink_msg_rc_channels_raw_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_rc_channels_raw_t *rc_channels_raw)
Encode a rc_channels_raw struct into a message.
static uint16_t mavlink_msg_rc_channels_raw_get_chan1_raw (const mavlink_message_t *msg)
Send a rc_channels_raw message.
static uint16_t mavlink_msg_rc_channels_raw_get_chan2_raw (const mavlink_message_t *msg)
Get field chan2_raw from rc_channels_raw message.
static uint16_t mavlink_msg_rc_channels_raw_get_chan3_raw (const mavlink_message_t *msg)
Get field chan3_raw from rc_channels_raw message.
static uint16_t mavlink_msg_rc_channels_raw_get_chan4_raw (const mavlink_message_t *msg)
Get field chan4_raw from rc_channels_raw message.
static uint16_t mavlink_msg_rc_channels_raw_get_chan5_raw (const mavlink_message_t *msg)
Get field chan5_raw from rc_channels_raw message.
static uint16_t mavlink_msg_rc_channels_raw_get_chan6_raw (const mavlink_message_t *msg)
Get field chan6_raw from rc_channels_raw message.
static uint16_t mavlink_msg_rc_channels_raw_get_chan7_raw (const mavlink_message_t *msg)
Get field chan7_raw from rc_channels_raw message.
static uint16_t mavlink_msg_rc_channels_raw_get_chan8_raw (const mavlink_message_t *msg)
Get field chan8_raw from rc_channels_raw message.
static uint8_t mavlink_msg_rc_channels_raw_get_rssi (const mavlink_message_t *msg)
Get field rssi from rc_channels_raw message.
static void mavlink_msg_rc_channels_raw_decode (const mavlink_message_t *msg, mavlink_rc_channels_raw_t *rc_channels_raw)
Decode a rc_channels_raw message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_RC_CHANNELS_RAW
Value:
{ \
    "RC_CHANNELS_RAW", \
    9, \
    {  { "chan1_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 0, offsetof(mavlink_rc_channels_raw_t, chan1_raw) }, \
         { "chan2_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 2, offsetof(mavlink_rc_channels_raw_t, chan2_raw) }, \
         { "chan3_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 4, offsetof(mavlink_rc_channels_raw_t, chan3_raw) }, \
         { "chan4_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 6, offsetof(mavlink_rc_channels_raw_t, chan4_raw) }, \
         { "chan5_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 8, offsetof(mavlink_rc_channels_raw_t, chan5_raw) }, \
         { "chan6_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 10, offsetof(mavlink_rc_channels_raw_t, chan6_raw) }, \
         { "chan7_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 12, offsetof(mavlink_rc_channels_raw_t, chan7_raw) }, \
         { "chan8_raw", NULL, MAVLINK_TYPE_UINT16_T, 0, 14, offsetof(mavlink_rc_channels_raw_t, chan8_raw) }, \
         { "rssi", NULL, MAVLINK_TYPE_UINT8_T, 0, 16, offsetof(mavlink_rc_channels_raw_t, rssi) }, \
         } \
}
Definition at line 23 of file mavlink_msg_rc_channels_raw.h.
#define MAVLINK_MSG_ID_35_LEN 17
Definition at line 19 of file mavlink_msg_rc_channels_raw.h.
#define MAVLINK_MSG_ID_RC_CHANNELS_RAW 35
Definition at line 3 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_pack(), and mavlink_msg_rc_channels_raw_pack_chan().
#define MAVLINK_MSG_ID_RC_CHANNELS_RAW_LEN 17
Definition at line 18 of file mavlink_msg_rc_channels_raw.h.
Typedef Documentation
typedef struct __mavlink_rc_channels_raw_t mavlink_rc_channels_raw_t
Function Documentation
static void mavlink_msg_rc_channels_raw_decode (const mavlink_message_t * msg, mavlink_rc_channels_raw_t * rc_channels_raw) inline static
Decode a rc_channels_raw message into a struct.
Parameters
msg The message to decode
rc_channels_raw C-struct to decode the message contents into
Definition at line 305 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_test_rc_channels_raw().
static uint16_t mavlink_msg_rc_channels_raw_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_rc_channels_raw_t * rc_channels_raw) inline static
Encode a rc_channels_raw struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
rc_channels_raw C-struct to read the message contents from
Definition at line 152 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_test_rc_channels_raw().
static uint16_t mavlink_msg_rc_channels_raw_get_chan1_raw (const mavlink_message_t * msg) inline static
Send a rc_channels_raw message.
Parameters
chan MAVLink channel to send the message
chan1_raw RC channel 1 value, in microseconds
chan2_raw RC channel 2 value, in microseconds
chan3_raw RC channel 3 value, in microseconds
chan4_raw RC channel 4 value, in microseconds
chan5_raw RC channel 5 value, in microseconds
chan6_raw RC channel 6 value, in microseconds
chan7_raw RC channel 7 value, in microseconds
chan8_raw RC channel 8 value, in microseconds
rssi Receive signal strength indicator, 0: 0%, 255: 100% Get field chan1_raw from rc_channels_raw message
Returns
RC channel 1 value, in microseconds
Definition at line 214 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint16_t mavlink_msg_rc_channels_raw_get_chan2_raw (const mavlink_message_t * msg) inline static
Get field chan2_raw from rc_channels_raw message.
Returns
RC channel 2 value, in microseconds
Definition at line 224 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint16_t mavlink_msg_rc_channels_raw_get_chan3_raw (const mavlink_message_t * msg) inline static
Get field chan3_raw from rc_channels_raw message.
Returns
RC channel 3 value, in microseconds
Definition at line 234 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint16_t mavlink_msg_rc_channels_raw_get_chan4_raw (const mavlink_message_t * msg) inline static
Get field chan4_raw from rc_channels_raw message.
Returns
RC channel 4 value, in microseconds
Definition at line 244 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint16_t mavlink_msg_rc_channels_raw_get_chan5_raw (const mavlink_message_t * msg) inline static
Get field chan5_raw from rc_channels_raw message.
Returns
RC channel 5 value, in microseconds
Definition at line 254 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint16_t mavlink_msg_rc_channels_raw_get_chan6_raw (const mavlink_message_t * msg) inline static
Get field chan6_raw from rc_channels_raw message.
Returns
RC channel 6 value, in microseconds
Definition at line 264 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint16_t mavlink_msg_rc_channels_raw_get_chan7_raw (const mavlink_message_t * msg) inline static
Get field chan7_raw from rc_channels_raw message.
Returns
RC channel 7 value, in microseconds
Definition at line 274 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint16_t mavlink_msg_rc_channels_raw_get_chan8_raw (const mavlink_message_t * msg) inline static
Get field chan8_raw from rc_channels_raw message.
Returns
RC channel 8 value, in microseconds
Definition at line 284 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint8_t mavlink_msg_rc_channels_raw_get_rssi (const mavlink_message_t * msg) inline static
Get field rssi from rc_channels_raw message.
Returns
Receive signal strength indicator, 0: 0%, 255: 100%
Definition at line 294 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_decode().
static uint16_t mavlink_msg_rc_channels_raw_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw, uint8_t rssi) inline static
Pack a rc_channels_raw message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
chan1_raw RC channel 1 value, in microseconds
chan2_raw RC channel 2 value, in microseconds
chan3_raw RC channel 3 value, in microseconds
chan4_raw RC channel 4 value, in microseconds
chan5_raw RC channel 5 value, in microseconds
chan6_raw RC channel 6 value, in microseconds
chan7_raw RC channel 7 value, in microseconds
chan8_raw RC channel 8 value, in microseconds
rssi Receive signal strength indicator, 0: 0%, 255: 100%
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 56 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_msg_rc_channels_raw_encode(), and mavlink_test_rc_channels_raw().
static uint16_t mavlink_msg_rc_channels_raw_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint16_t chan1_raw, uint16_t chan2_raw, uint16_t chan3_raw, uint16_t chan4_raw, uint16_t chan5_raw, uint16_t chan6_raw, uint16_t chan7_raw, uint16_t chan8_raw, uint8_t rssi) inline static
Pack a rc_channels_raw message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
chan1_raw RC channel 1 value, in microseconds
chan2_raw RC channel 2 value, in microseconds
chan3_raw RC channel 3 value, in microseconds
chan4_raw RC channel 4 value, in microseconds
chan5_raw RC channel 5 value, in microseconds
chan6_raw RC channel 6 value, in microseconds
chan7_raw RC channel 7 value, in microseconds
chan8_raw RC channel 8 value, in microseconds
rssi Receive signal strength indicator, 0: 0%, 255: 100%
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 108 of file mavlink_msg_rc_channels_raw.h.
Referenced by mavlink_test_rc_channels_raw().