APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/testsuite.h File Reference
testsuite.h File Reference
MAVLink comm protocol testsuite generated from common.xml.
Macros
#define MAVLINK_TEST_ALL
Functions
static void mavlink_test_common (uint8_t, uint8_t, mavlink_message_t *last_msg)
static void mavlink_test_all (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_heartbeat (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_boot (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_system_time (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_ping (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_system_time_utc (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_change_operator_control (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_change_operator_control_ack (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_auth_key (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_action_ack (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_action (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_set_mode (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_set_nav_mode (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_param_request_read (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_param_request_list (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_param_value (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_param_set (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gps_raw_int (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_scaled_imu (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gps_status (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_raw_imu (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_raw_pressure (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_scaled_pressure (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_attitude (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_local_position (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_global_position (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gps_raw (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_sys_status (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_rc_channels_raw (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_rc_channels_scaled (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_servo_output_raw (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_waypoint (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_waypoint_request (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_waypoint_set_current (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_waypoint_current (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_waypoint_request_list (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_waypoint_count (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_waypoint_clear_all (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_waypoint_reached (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_waypoint_ack (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gps_set_global_origin (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_gps_local_origin_set (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_local_position_setpoint_set (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_local_position_setpoint (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_control_status (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_safety_set_allowed_area (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_safety_allowed_area (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_set_roll_pitch_yaw_thrust (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_set_roll_pitch_yaw_speed_thrust (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_roll_pitch_yaw_thrust_setpoint (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_roll_pitch_yaw_speed_thrust_setpoint (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_nav_controller_output (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_position_target (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_state_correction (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_set_altitude (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_request_data_stream (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_hil_state (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_hil_controls (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_manual_control (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_rc_channels_override (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_global_position_int (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_vfr_hud (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_command (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_command_ack (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_optical_flow (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_object_detection_event (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_debug_vect (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_named_value_float (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_named_value_int (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_statustext (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
static void mavlink_test_debug (uint8_t system_id, uint8_t component_id, mavlink_message_t *last_msg)
Detailed Description
MAVLink comm protocol testsuite generated from common.xml.
See Also
http://qgroundcontrol.org/mavlink/
Definition in file testsuite.h.
Macro Definition Documentation
#define MAVLINK_TEST_ALL
Definition at line 13 of file testsuite.h.
Function Documentation
static void mavlink_test_action (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 438 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_action_ack (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 393 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_all (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 17 of file testsuite.h.
static void mavlink_test_attitude (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1101 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_auth_key (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 350 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_boot (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 74 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_change_operator_control (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 254 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_change_operator_control_ack (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 303 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_command (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3182 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_command_ack (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3239 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_common (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3623 of file testsuite.h.
Referenced by mavlink_test_all().
static void mavlink_test_control_status (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2188 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_debug (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3578 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_debug_vect (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3392 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_global_position (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1211 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_global_position_int (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3076 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_gps_local_origin_set (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2039 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_gps_raw (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1266 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_gps_raw_int (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 767 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_gps_set_global_origin (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1988 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_gps_status (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 887 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_heartbeat (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 27 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_hil_controls (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2901 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_hil_state (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2828 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_local_position (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1156 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_local_position_setpoint (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2139 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_local_position_setpoint_set (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2086 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_manual_control (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2956 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_named_value_float (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3443 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_named_value_int (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3488 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_nav_controller_output (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2567 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_object_detection_event (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3337 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_optical_flow (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3284 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_param_request_list (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 624 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_param_request_read (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 575 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_param_set (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 718 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_param_value (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 669 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_ping (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 160 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_position_target (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2624 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_raw_imu (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 940 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_raw_pressure (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1001 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_rc_channels_override (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3015 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_rc_channels_raw (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1380 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_rc_channels_scaled (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1439 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_request_data_stream (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2777 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_roll_pitch_yaw_speed_thrust_setpoint (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2516 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_roll_pitch_yaw_thrust_setpoint (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2465 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_safety_allowed_area (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2304 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_safety_set_allowed_area (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2245 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_scaled_imu (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 826 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_scaled_pressure (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1052 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_servo_output_raw (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1498 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_set_altitude (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2732 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_set_mode (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 485 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_set_nav_mode (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 530 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_set_roll_pitch_yaw_speed_thrust (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2412 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_set_roll_pitch_yaw_thrust (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2359 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_state_correction (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 2673 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_statustext (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3533 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_sys_status (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1325 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_system_time (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 117 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_system_time_utc (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 209 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_vfr_hud (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 3129 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_waypoint (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1555 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_waypoint_ack (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1941 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_waypoint_clear_all (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1853 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_waypoint_count (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1806 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_waypoint_current (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1718 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_waypoint_reached (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1898 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_waypoint_request (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1624 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_waypoint_request_list (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1761 of file testsuite.h.
Referenced by mavlink_test_common().
static void mavlink_test_waypoint_set_current (uint8_t system_id, uint8_t component_id, mavlink_message_t * last_msg) static
Definition at line 1671 of file testsuite.h.
Referenced by mavlink_test_common().