APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_scaled_pressure.h File Reference
mavlink_msg_scaled_pressure.h File Reference
Classes
struct __mavlink_scaled_pressure_t
Macros
#define MAVLINK_MSG_ID_SCALED_PRESSURE 38
#define MAVLINK_MSG_ID_SCALED_PRESSURE_LEN 18
#define MAVLINK_MSG_ID_38_LEN 18
#define MAVLINK_MESSAGE_INFO_SCALED_PRESSURE
Typedefs
typedef struct
__mavlink_scaled_pressure_t mavlink_scaled_pressure_t
Functions
static uint16_t mavlink_msg_scaled_pressure_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t usec, float press_abs, float press_diff, int16_t temperature)
Pack a scaled_pressure message.
static uint16_t mavlink_msg_scaled_pressure_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t usec, float press_abs, float press_diff, int16_t temperature)
Pack a scaled_pressure message on a channel.
static uint16_t mavlink_msg_scaled_pressure_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_scaled_pressure_t *scaled_pressure)
Encode a scaled_pressure struct into a message.
static uint64_t mavlink_msg_scaled_pressure_get_usec (const mavlink_message_t *msg)
Send a scaled_pressure message.
static float mavlink_msg_scaled_pressure_get_press_abs (const mavlink_message_t *msg)
Get field press_abs from scaled_pressure message.
static float mavlink_msg_scaled_pressure_get_press_diff (const mavlink_message_t *msg)
Get field press_diff from scaled_pressure message.
static int16_t mavlink_msg_scaled_pressure_get_temperature (const mavlink_message_t *msg)
Get field temperature from scaled_pressure message.
static void mavlink_msg_scaled_pressure_decode (const mavlink_message_t *msg, mavlink_scaled_pressure_t *scaled_pressure)
Decode a scaled_pressure message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_SCALED_PRESSURE
Value:
{ \
    "SCALED_PRESSURE", \
    4, \
    {  { "usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_scaled_pressure_t, usec) }, \
         { "press_abs", NULL, MAVLINK_TYPE_FLOAT, 0, 8, offsetof(mavlink_scaled_pressure_t, press_abs) }, \
         { "press_diff", NULL, MAVLINK_TYPE_FLOAT, 0, 12, offsetof(mavlink_scaled_pressure_t, press_diff) }, \
         { "temperature", NULL, MAVLINK_TYPE_INT16_T, 0, 16, offsetof(mavlink_scaled_pressure_t, temperature) }, \
         } \
}
Definition at line 18 of file mavlink_msg_scaled_pressure.h.
#define MAVLINK_MSG_ID_38_LEN 18
Definition at line 14 of file mavlink_msg_scaled_pressure.h.
#define MAVLINK_MSG_ID_SCALED_PRESSURE 38
Definition at line 3 of file mavlink_msg_scaled_pressure.h.
Referenced by mavlink_msg_scaled_pressure_pack(), and mavlink_msg_scaled_pressure_pack_chan().
#define MAVLINK_MSG_ID_SCALED_PRESSURE_LEN 18
Definition at line 13 of file mavlink_msg_scaled_pressure.h.
Typedef Documentation
typedef struct __mavlink_scaled_pressure_t mavlink_scaled_pressure_t
Function Documentation
static void mavlink_msg_scaled_pressure_decode (const mavlink_message_t * msg, mavlink_scaled_pressure_t * scaled_pressure) inline static
Decode a scaled_pressure message into a struct.
Parameters
msg The message to decode
scaled_pressure C-struct to decode the message contents into
Definition at line 200 of file mavlink_msg_scaled_pressure.h.
Referenced by mavlink_test_scaled_pressure().
static uint16_t mavlink_msg_scaled_pressure_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_scaled_pressure_t * scaled_pressure) inline static
Encode a scaled_pressure struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
scaled_pressure C-struct to read the message contents from
Definition at line 112 of file mavlink_msg_scaled_pressure.h.
Referenced by mavlink_test_scaled_pressure().
static float mavlink_msg_scaled_pressure_get_press_abs (const mavlink_message_t * msg) inline static
Get field press_abs from scaled_pressure message.
Returns
Absolute pressure (hectopascal)
Definition at line 169 of file mavlink_msg_scaled_pressure.h.
Referenced by mavlink_msg_scaled_pressure_decode().
static float mavlink_msg_scaled_pressure_get_press_diff (const mavlink_message_t * msg) inline static
Get field press_diff from scaled_pressure message.
Returns
Differential pressure 1 (hectopascal)
Definition at line 179 of file mavlink_msg_scaled_pressure.h.
Referenced by mavlink_msg_scaled_pressure_decode().
static int16_t mavlink_msg_scaled_pressure_get_temperature (const mavlink_message_t * msg) inline static
Get field temperature from scaled_pressure message.
Returns
Temperature measurement (0.01 degrees celsius)
Definition at line 189 of file mavlink_msg_scaled_pressure.h.
Referenced by mavlink_msg_scaled_pressure_decode().
static uint64_t mavlink_msg_scaled_pressure_get_usec (const mavlink_message_t * msg) inline static
Send a scaled_pressure message.
Parameters
chan MAVLink channel to send the message
usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
press_abs Absolute pressure (hectopascal)
press_diff Differential pressure 1 (hectopascal)
temperature Temperature measurement (0.01 degrees celsius) Get field usec from scaled_pressure message
Returns
Timestamp (microseconds since UNIX epoch or microseconds since system boot)
Definition at line 159 of file mavlink_msg_scaled_pressure.h.
Referenced by mavlink_msg_scaled_pressure_decode().
static uint16_t mavlink_msg_scaled_pressure_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t usec, float press_abs, float press_diff, int16_t temperature) inline static
Pack a scaled_pressure message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
press_abs Absolute pressure (hectopascal)
press_diff Differential pressure 1 (hectopascal)
temperature Temperature measurement (0.01 degrees celsius)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 41 of file mavlink_msg_scaled_pressure.h.
Referenced by mavlink_msg_scaled_pressure_encode(), and mavlink_test_scaled_pressure().
static uint16_t mavlink_msg_scaled_pressure_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t usec, float press_abs, float press_diff, int16_t temperature) inline static
Pack a scaled_pressure message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
press_abs Absolute pressure (hectopascal)
press_diff Differential pressure 1 (hectopascal)
temperature Temperature measurement (0.01 degrees celsius)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 78 of file mavlink_msg_scaled_pressure.h.
Referenced by mavlink_test_scaled_pressure().