APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_param_value.h File Reference
mavlink_msg_param_value.h File Reference
Classes
struct __mavlink_param_value_t
Macros
#define MAVLINK_MSG_ID_PARAM_VALUE 22
#define MAVLINK_MSG_ID_PARAM_VALUE_LEN 23
#define MAVLINK_MSG_ID_22_LEN 23
#define MAVLINK_MSG_PARAM_VALUE_FIELD_PARAM_ID_LEN 15
#define MAVLINK_MESSAGE_INFO_PARAM_VALUE
Typedefs
typedef struct
__mavlink_param_value_t mavlink_param_value_t
Functions
static uint16_t mavlink_msg_param_value_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const int8_t *param_id, float param_value, uint16_t param_count, uint16_t param_index)
Pack a param_value message.
static uint16_t mavlink_msg_param_value_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, const int8_t *param_id, float param_value, uint16_t param_count, uint16_t param_index)
Pack a param_value message on a channel.
static uint16_t mavlink_msg_param_value_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_param_value_t *param_value)
Encode a param_value struct into a message.
static uint16_t mavlink_msg_param_value_get_param_id (const mavlink_message_t *msg, int8_t *param_id)
Send a param_value message.
static float mavlink_msg_param_value_get_param_value (const mavlink_message_t *msg)
Get field param_value from param_value message.
static uint16_t mavlink_msg_param_value_get_param_count (const mavlink_message_t *msg)
Get field param_count from param_value message.
static uint16_t mavlink_msg_param_value_get_param_index (const mavlink_message_t *msg)
Get field param_index from param_value message.
static void mavlink_msg_param_value_decode (const mavlink_message_t *msg, mavlink_param_value_t *param_value)
Decode a param_value message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_PARAM_VALUE
Value:
{ \
    "PARAM_VALUE", \
    4, \
    {  { "param_id", NULL, MAVLINK_TYPE_INT8_T, 15, 0, offsetof(mavlink_param_value_t, param_id) }, \
         { "param_value", NULL, MAVLINK_TYPE_FLOAT, 0, 15, offsetof(mavlink_param_value_t, param_value) }, \
         { "param_count", NULL, MAVLINK_TYPE_UINT16_T, 0, 19, offsetof(mavlink_param_value_t, param_count) }, \
         { "param_index", NULL, MAVLINK_TYPE_UINT16_T, 0, 21, offsetof(mavlink_param_value_t, param_index) }, \
         } \
}
Definition at line 18 of file mavlink_msg_param_value.h.
#define MAVLINK_MSG_ID_22_LEN 23
Definition at line 14 of file mavlink_msg_param_value.h.
#define MAVLINK_MSG_ID_PARAM_VALUE 22
Definition at line 3 of file mavlink_msg_param_value.h.
Referenced by mavlink_msg_param_value_pack(), and mavlink_msg_param_value_pack_chan().
#define MAVLINK_MSG_ID_PARAM_VALUE_LEN 23
Definition at line 13 of file mavlink_msg_param_value.h.
Referenced by GCS_MAVLINK::queued_param_send().
#define MAVLINK_MSG_PARAM_VALUE_FIELD_PARAM_ID_LEN 15
Definition at line 16 of file mavlink_msg_param_value.h.
Typedef Documentation
typedef struct __mavlink_param_value_t mavlink_param_value_t
Function Documentation
static void mavlink_msg_param_value_decode (const mavlink_message_t * msg, mavlink_param_value_t * param_value) inline static
Decode a param_value message into a struct.
Parameters
msg The message to decode
param_value C-struct to decode the message contents into
Definition at line 194 of file mavlink_msg_param_value.h.
Referenced by mavlink_test_param_value().
static uint16_t mavlink_msg_param_value_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_param_value_t * param_value) inline static
Encode a param_value struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
param_value C-struct to read the message contents from
Definition at line 108 of file mavlink_msg_param_value.h.
Referenced by mavlink_test_param_value().
static uint16_t mavlink_msg_param_value_get_param_count (const mavlink_message_t * msg) inline static
Get field param_count from param_value message.
Returns
Total number of onboard parameters
Definition at line 173 of file mavlink_msg_param_value.h.
Referenced by mavlink_msg_param_value_decode().
static uint16_t mavlink_msg_param_value_get_param_id (const mavlink_message_t * msg, int8_t * param_id) inline static
Send a param_value message.
Parameters
chan MAVLink channel to send the message
param_id Onboard parameter id
param_value Onboard parameter value
param_count Total number of onboard parameters
param_index Index of this onboard parameter Get field param_id from param_value message
Returns
Onboard parameter id
Definition at line 153 of file mavlink_msg_param_value.h.
Referenced by mavlink_msg_param_value_decode().
static uint16_t mavlink_msg_param_value_get_param_index (const mavlink_message_t * msg) inline static
Get field param_index from param_value message.
Returns
Index of this onboard parameter
Definition at line 183 of file mavlink_msg_param_value.h.
Referenced by mavlink_msg_param_value_decode().
static float mavlink_msg_param_value_get_param_value (const mavlink_message_t * msg) inline static
Get field param_value from param_value message.
Returns
Onboard parameter value
Definition at line 163 of file mavlink_msg_param_value.h.
Referenced by mavlink_msg_param_value_decode().
static uint16_t mavlink_msg_param_value_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const int8_t * param_id, float param_value, uint16_t param_count, uint16_t param_index) inline static
Pack a param_value message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
param_id Onboard parameter id
param_value Onboard parameter value
param_count Total number of onboard parameters
param_index Index of this onboard parameter
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 41 of file mavlink_msg_param_value.h.
Referenced by mavlink_msg_param_value_encode(), and mavlink_test_param_value().
static uint16_t mavlink_msg_param_value_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, const int8_t * param_id, float param_value, uint16_t param_count, uint16_t param_index) inline static
Pack a param_value message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
param_id Onboard parameter id
param_value Onboard parameter value
param_count Total number of onboard parameters
param_index Index of this onboard parameter
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 76 of file mavlink_msg_param_value.h.
Referenced by mavlink_test_param_value().