APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_sys_status.h File Reference
mavlink_msg_sys_status.h File Reference
Classes
struct __mavlink_sys_status_t
Macros
#define MAVLINK_MSG_ID_SYS_STATUS 34
#define MAVLINK_MSG_ID_SYS_STATUS_LEN 11
#define MAVLINK_MSG_ID_34_LEN 11
#define MAVLINK_MESSAGE_INFO_SYS_STATUS
Typedefs
typedef struct
__mavlink_sys_status_t mavlink_sys_status_t
Functions
static uint16_t mavlink_msg_sys_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t mode, uint8_t nav_mode, uint8_t status, uint16_t load, uint16_t vbat, uint16_t battery_remaining, uint16_t packet_drop)
Pack a sys_status message.
static uint16_t mavlink_msg_sys_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t mode, uint8_t nav_mode, uint8_t status, uint16_t load, uint16_t vbat, uint16_t battery_remaining, uint16_t packet_drop)
Pack a sys_status message on a channel.
static uint16_t mavlink_msg_sys_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_sys_status_t *sys_status)
Encode a sys_status struct into a message.
static uint8_t mavlink_msg_sys_status_get_mode (const mavlink_message_t *msg)
Send a sys_status message.
static uint8_t mavlink_msg_sys_status_get_nav_mode (const mavlink_message_t *msg)
Get field nav_mode from sys_status message.
static uint8_t mavlink_msg_sys_status_get_status (const mavlink_message_t *msg)
Get field status from sys_status message.
static uint16_t mavlink_msg_sys_status_get_load (const mavlink_message_t *msg)
Get field load from sys_status message.
static uint16_t mavlink_msg_sys_status_get_vbat (const mavlink_message_t *msg)
Get field vbat from sys_status message.
static uint16_t mavlink_msg_sys_status_get_battery_remaining (const mavlink_message_t *msg)
Get field battery_remaining from sys_status message.
static uint16_t mavlink_msg_sys_status_get_packet_drop (const mavlink_message_t *msg)
Get field packet_drop from sys_status message.
static void mavlink_msg_sys_status_decode (const mavlink_message_t *msg, mavlink_sys_status_t *sys_status)
Decode a sys_status message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_SYS_STATUS
Value:
{ \
    "SYS_STATUS", \
    7, \
    {  { "mode", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_sys_status_t, mode) }, \
         { "nav_mode", NULL, MAVLINK_TYPE_UINT8_T, 0, 1, offsetof(mavlink_sys_status_t, nav_mode) }, \
         { "status", NULL, MAVLINK_TYPE_UINT8_T, 0, 2, offsetof(mavlink_sys_status_t, status) }, \
         { "load", NULL, MAVLINK_TYPE_UINT16_T, 0, 3, offsetof(mavlink_sys_status_t, load) }, \
         { "vbat", NULL, MAVLINK_TYPE_UINT16_T, 0, 5, offsetof(mavlink_sys_status_t, vbat) }, \
         { "battery_remaining", NULL, MAVLINK_TYPE_UINT16_T, 0, 7, offsetof(mavlink_sys_status_t, battery_remaining) }, \
         { "packet_drop", NULL, MAVLINK_TYPE_UINT16_T, 0, 9, offsetof(mavlink_sys_status_t, packet_drop) }, \
         } \
}
Definition at line 21 of file mavlink_msg_sys_status.h.
#define MAVLINK_MSG_ID_34_LEN 11
Definition at line 17 of file mavlink_msg_sys_status.h.
#define MAVLINK_MSG_ID_SYS_STATUS 34
Definition at line 3 of file mavlink_msg_sys_status.h.
Referenced by mavlink_msg_sys_status_pack(), and mavlink_msg_sys_status_pack_chan().
#define MAVLINK_MSG_ID_SYS_STATUS_LEN 11
Definition at line 16 of file mavlink_msg_sys_status.h.
Typedef Documentation
typedef struct __mavlink_sys_status_t mavlink_sys_status_t
Function Documentation
static void mavlink_msg_sys_status_decode (const mavlink_message_t * msg, mavlink_sys_status_t * sys_status) inline static
Decode a sys_status message into a struct.
Parameters
msg The message to decode
sys_status C-struct to decode the message contents into
Definition at line 263 of file mavlink_msg_sys_status.h.
Referenced by mavlink_test_sys_status().
static uint16_t mavlink_msg_sys_status_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_sys_status_t * sys_status) inline static
Encode a sys_status struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
sys_status C-struct to read the message contents from
Definition at line 136 of file mavlink_msg_sys_status.h.
Referenced by mavlink_test_sys_status().
static uint16_t mavlink_msg_sys_status_get_battery_remaining (const mavlink_message_t * msg) inline static
Get field battery_remaining from sys_status message.
Returns
Remaining battery energy: (0%: 0, 100%: 1000)
Definition at line 242 of file mavlink_msg_sys_status.h.
Referenced by mavlink_msg_sys_status_decode().
static uint16_t mavlink_msg_sys_status_get_load (const mavlink_message_t * msg) inline static
Get field load from sys_status message.
Returns
Maximum usage in percent of the mainloop time, (0%: 0, 100%: 1000) should be always below 1000
Definition at line 222 of file mavlink_msg_sys_status.h.
Referenced by mavlink_msg_sys_status_decode().
static uint8_t mavlink_msg_sys_status_get_mode (const mavlink_message_t * msg) inline static
Send a sys_status message.
Parameters
chan MAVLink channel to send the message
mode System mode, see MAV_MODE ENUM in mavlink/include/mavlink_types.h
nav_mode Navigation mode, see MAV_NAV_MODE ENUM
status System status flag, see MAV_STATUS ENUM
load Maximum usage in percent of the mainloop time, (0%: 0, 100%: 1000) should be always below 1000
vbat Battery voltage, in millivolts (1 = 1 millivolt)
battery_remaining Remaining battery energy: (0%: 0, 100%: 1000)
packet_drop Dropped packets (packets that were corrupted on reception on the MAV) Get field mode from sys_status message
Returns
System mode, see MAV_MODE ENUM in mavlink/include/mavlink_types.h
Definition at line 192 of file mavlink_msg_sys_status.h.
Referenced by mavlink_msg_sys_status_decode().
static uint8_t mavlink_msg_sys_status_get_nav_mode (const mavlink_message_t * msg) inline static
Get field nav_mode from sys_status message.
Returns
Navigation mode, see MAV_NAV_MODE ENUM
Definition at line 202 of file mavlink_msg_sys_status.h.
Referenced by mavlink_msg_sys_status_decode().
static uint16_t mavlink_msg_sys_status_get_packet_drop (const mavlink_message_t * msg) inline static
Get field packet_drop from sys_status message.
Returns
Dropped packets (packets that were corrupted on reception on the MAV)
Definition at line 252 of file mavlink_msg_sys_status.h.
Referenced by mavlink_msg_sys_status_decode().
static uint8_t mavlink_msg_sys_status_get_status (const mavlink_message_t * msg) inline static
Get field status from sys_status message.
Returns
System status flag, see MAV_STATUS ENUM
Definition at line 212 of file mavlink_msg_sys_status.h.
Referenced by mavlink_msg_sys_status_decode().
static uint16_t mavlink_msg_sys_status_get_vbat (const mavlink_message_t * msg) inline static
Get field vbat from sys_status message.
Returns
Battery voltage, in millivolts (1 = 1 millivolt)
Definition at line 232 of file mavlink_msg_sys_status.h.
Referenced by mavlink_msg_sys_status_decode().
static uint16_t mavlink_msg_sys_status_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t mode, uint8_t nav_mode, uint8_t status, uint16_t load, uint16_t vbat, uint16_t battery_remaining, uint16_t packet_drop) inline static
Pack a sys_status message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
mode System mode, see MAV_MODE ENUM in mavlink/include/mavlink_types.h
nav_mode Navigation mode, see MAV_NAV_MODE ENUM
status System status flag, see MAV_STATUS ENUM
load Maximum usage in percent of the mainloop time, (0%: 0, 100%: 1000) should be always below 1000
vbat Battery voltage, in millivolts (1 = 1 millivolt)
battery_remaining Remaining battery energy: (0%: 0, 100%: 1000)
packet_drop Dropped packets (packets that were corrupted on reception on the MAV)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 50 of file mavlink_msg_sys_status.h.
Referenced by mavlink_msg_sys_status_encode(), and mavlink_test_sys_status().
static uint16_t mavlink_msg_sys_status_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t mode, uint8_t nav_mode, uint8_t status, uint16_t load, uint16_t vbat, uint16_t battery_remaining, uint16_t packet_drop) inline static
Pack a sys_status message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
mode System mode, see MAV_MODE ENUM in mavlink/include/mavlink_types.h
nav_mode Navigation mode, see MAV_NAV_MODE ENUM
status System status flag, see MAV_STATUS ENUM
load Maximum usage in percent of the mainloop time, (0%: 0, 100%: 1000) should be always below 1000
vbat Battery voltage, in millivolts (1 = 1 millivolt)
battery_remaining Remaining battery energy: (0%: 0, 100%: 1000)
packet_drop Dropped packets (packets that were corrupted on reception on the MAV)
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 96 of file mavlink_msg_sys_status.h.
Referenced by mavlink_test_sys_status().