APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_gps_raw_int.h File Reference
mavlink_msg_gps_raw_int.h File Reference
Classes
struct __mavlink_gps_raw_int_t
Macros
#define MAVLINK_MSG_ID_GPS_RAW_INT 25
#define MAVLINK_MSG_ID_GPS_RAW_INT_LEN 37
#define MAVLINK_MSG_ID_25_LEN 37
#define MAVLINK_MESSAGE_INFO_GPS_RAW_INT
Typedefs
typedef struct
__mavlink_gps_raw_int_t mavlink_gps_raw_int_t
Functions
static uint16_t mavlink_msg_gps_raw_int_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint64_t usec, uint8_t fix_type, int32_t lat, int32_t lon, int32_t alt, float eph, float epv, float v, float hdg)
Pack a gps_raw_int message.
static uint16_t mavlink_msg_gps_raw_int_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint64_t usec, uint8_t fix_type, int32_t lat, int32_t lon, int32_t alt, float eph, float epv, float v, float hdg)
Pack a gps_raw_int message on a channel.
static uint16_t mavlink_msg_gps_raw_int_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_gps_raw_int_t *gps_raw_int)
Encode a gps_raw_int struct into a message.
static uint64_t mavlink_msg_gps_raw_int_get_usec (const mavlink_message_t *msg)
Send a gps_raw_int message.
static uint8_t mavlink_msg_gps_raw_int_get_fix_type (const mavlink_message_t *msg)
Get field fix_type from gps_raw_int message.
static int32_t mavlink_msg_gps_raw_int_get_lat (const mavlink_message_t *msg)
Get field lat from gps_raw_int message.
static int32_t mavlink_msg_gps_raw_int_get_lon (const mavlink_message_t *msg)
Get field lon from gps_raw_int message.
static int32_t mavlink_msg_gps_raw_int_get_alt (const mavlink_message_t *msg)
Get field alt from gps_raw_int message.
static float mavlink_msg_gps_raw_int_get_eph (const mavlink_message_t *msg)
Get field eph from gps_raw_int message.
static float mavlink_msg_gps_raw_int_get_epv (const mavlink_message_t *msg)
Get field epv from gps_raw_int message.
static float mavlink_msg_gps_raw_int_get_v (const mavlink_message_t *msg)
Get field v from gps_raw_int message.
static float mavlink_msg_gps_raw_int_get_hdg (const mavlink_message_t *msg)
Get field hdg from gps_raw_int message.
static void mavlink_msg_gps_raw_int_decode (const mavlink_message_t *msg, mavlink_gps_raw_int_t *gps_raw_int)
Decode a gps_raw_int message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_GPS_RAW_INT
Value:
{ \
    "GPS_RAW_INT", \
    9, \
    {  { "usec", NULL, MAVLINK_TYPE_UINT64_T, 0, 0, offsetof(mavlink_gps_raw_int_t, usec) }, \
         { "fix_type", NULL, MAVLINK_TYPE_UINT8_T, 0, 8, offsetof(mavlink_gps_raw_int_t, fix_type) }, \
         { "lat", NULL, MAVLINK_TYPE_INT32_T, 0, 9, offsetof(mavlink_gps_raw_int_t, lat) }, \
         { "lon", NULL, MAVLINK_TYPE_INT32_T, 0, 13, offsetof(mavlink_gps_raw_int_t, lon) }, \
         { "alt", NULL, MAVLINK_TYPE_INT32_T, 0, 17, offsetof(mavlink_gps_raw_int_t, alt) }, \
         { "eph", NULL, MAVLINK_TYPE_FLOAT, 0, 21, offsetof(mavlink_gps_raw_int_t, eph) }, \
         { "epv", NULL, MAVLINK_TYPE_FLOAT, 0, 25, offsetof(mavlink_gps_raw_int_t, epv) }, \
         { "v", NULL, MAVLINK_TYPE_FLOAT, 0, 29, offsetof(mavlink_gps_raw_int_t, v) }, \
         { "hdg", NULL, MAVLINK_TYPE_FLOAT, 0, 33, offsetof(mavlink_gps_raw_int_t, hdg) }, \
         } \
}
Definition at line 23 of file mavlink_msg_gps_raw_int.h.
#define MAVLINK_MSG_ID_25_LEN 37
Definition at line 19 of file mavlink_msg_gps_raw_int.h.
#define MAVLINK_MSG_ID_GPS_RAW_INT 25
Definition at line 3 of file mavlink_msg_gps_raw_int.h.
Referenced by mavlink_msg_gps_raw_int_pack(), and mavlink_msg_gps_raw_int_pack_chan().
#define MAVLINK_MSG_ID_GPS_RAW_INT_LEN 37
Definition at line 18 of file mavlink_msg_gps_raw_int.h.
Referenced by GCS_MAVLINK::send_gps_raw().
Typedef Documentation
typedef struct __mavlink_gps_raw_int_t mavlink_gps_raw_int_t
Function Documentation
static void mavlink_msg_gps_raw_int_decode (const mavlink_message_t * msg, mavlink_gps_raw_int_t * gps_raw_int) inline static
Decode a gps_raw_int message into a struct.
Parameters
msg The message to decode
gps_raw_int C-struct to decode the message contents into
Definition at line 305 of file mavlink_msg_gps_raw_int.h.
Referenced by mavlink_test_gps_raw_int().
static uint16_t mavlink_msg_gps_raw_int_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_gps_raw_int_t * gps_raw_int) inline static
Encode a gps_raw_int struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
gps_raw_int C-struct to read the message contents from
Definition at line 152 of file mavlink_msg_gps_raw_int.h.
Referenced by mavlink_test_gps_raw_int().
static int32_t mavlink_msg_gps_raw_int_get_alt (const mavlink_message_t * msg) inline static
Get field alt from gps_raw_int message.
Returns
Altitude in 1E3 meters (millimeters)
Definition at line 254 of file mavlink_msg_gps_raw_int.h.
Referenced by mavlink_msg_gps_raw_int_decode().
static float mavlink_msg_gps_raw_int_get_eph (const mavlink_message_t * msg) inline static
Get field eph from gps_raw_int message.
Returns
GPS HDOP
Definition at line 264 of file mavlink_msg_gps_raw_int.h.
Referenced by mavlink_msg_gps_raw_int_decode().
static float mavlink_msg_gps_raw_int_get_epv (const mavlink_message_t * msg) inline static
Get field epv from gps_raw_int message.
Returns
GPS VDOP
Definition at line 274 of file mavlink_msg_gps_raw_int.h.
Referenced by mavlink_msg_gps_raw_int_decode().
static uint8_t mavlink_msg_gps_raw_int_get_fix_type (const mavlink_message_t * msg) inline static
Get field fix_type from gps_raw_int message.
Returns
0-1: no fix, 2: 2D fix, 3: 3D fix. Some applications will not use the value of this field unless it is at least two, so always correctly fill in the fix.
Definition at line 224 of file mavlink_msg_gps_raw_int.h.
Referenced by mavlink_msg_gps_raw_int_decode().
static float mavlink_msg_gps_raw_int_get_hdg (const mavlink_message_t * msg) inline static
Get field hdg from gps_raw_int message.
Returns
Compass heading in degrees, 0..360 degrees
Definition at line 294 of file mavlink_msg_gps_raw_int.h.
Referenced by mavlink_msg_gps_raw_int_decode().
static int32_t mavlink_msg_gps_raw_int_get_lat (const mavlink_message_t * msg) inline static
Get field lat from gps_raw_int message.
Returns
Latitude in 1E7 degrees
Definition at line 234 of file mavlink_msg_gps_raw_int.h.
Referenced by mavlink_msg_gps_raw_int_decode().
static int32_t mavlink_msg_gps_raw_int_get_lon (const mavlink_message_t * msg) inline static
Get field lon from gps_raw_int message.
Returns
Longitude in 1E7 degrees
Definition at line 244 of file mavlink_msg_gps_raw_int.h.
Referenced by mavlink_msg_gps_raw_int_decode().
static uint64_t mavlink_msg_gps_raw_int_get_usec (const mavlink_message_t * msg) inline static
Send a gps_raw_int message.
Parameters
chan MAVLink channel to send the message
usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
fix_type 0-1: no fix, 2: 2D fix, 3: 3D fix. Some applications will not use the value of this field unless it is at least two, so always correctly fill in the fix.
lat Latitude in 1E7 degrees
lon Longitude in 1E7 degrees
alt Altitude in 1E3 meters (millimeters)
eph GPS HDOP
epv GPS VDOP
v GPS ground speed (m/s)
hdg Compass heading in degrees, 0..360 degrees Get field usec from gps_raw_int message
Returns
Timestamp (microseconds since UNIX epoch or microseconds since system boot)
Definition at line 214 of file mavlink_msg_gps_raw_int.h.
Referenced by mavlink_msg_gps_raw_int_decode().
static float mavlink_msg_gps_raw_int_get_v (const mavlink_message_t * msg) inline static
Get field v from gps_raw_int message.
Returns
GPS ground speed (m/s)
Definition at line 284 of file mavlink_msg_gps_raw_int.h.
Referenced by mavlink_msg_gps_raw_int_decode().
static uint16_t mavlink_msg_gps_raw_int_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint64_t usec, uint8_t fix_type, int32_t lat, int32_t lon, int32_t alt, float eph, float epv, float v, float hdg) inline static
Pack a gps_raw_int message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
fix_type 0-1: no fix, 2: 2D fix, 3: 3D fix. Some applications will not use the value of this field unless it is at least two, so always correctly fill in the fix.
lat Latitude in 1E7 degrees
lon Longitude in 1E7 degrees
alt Altitude in 1E3 meters (millimeters)
eph GPS HDOP
epv GPS VDOP
v GPS ground speed (m/s)
hdg Compass heading in degrees, 0..360 degrees
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 56 of file mavlink_msg_gps_raw_int.h.
Referenced by mavlink_msg_gps_raw_int_encode(), and mavlink_test_gps_raw_int().
static uint16_t mavlink_msg_gps_raw_int_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint64_t usec, uint8_t fix_type, int32_t lat, int32_t lon, int32_t alt, float eph, float epv, float v, float hdg) inline static
Pack a gps_raw_int message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
usec Timestamp (microseconds since UNIX epoch or microseconds since system boot)
fix_type 0-1: no fix, 2: 2D fix, 3: 3D fix. Some applications will not use the value of this field unless it is at least two, so always correctly fill in the fix.
lat Latitude in 1E7 degrees
lon Longitude in 1E7 degrees
alt Altitude in 1E3 meters (millimeters)
eph GPS HDOP
epv GPS VDOP
v GPS ground speed (m/s)
hdg Compass heading in degrees, 0..360 degrees
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 108 of file mavlink_msg_gps_raw_int.h.
Referenced by mavlink_test_gps_raw_int().