APM:Libraries: libraries/GCS_MAVLink/include/mavlink/v0.9/common/mavlink_msg_manual_control.h File Reference
mavlink_msg_manual_control.h File Reference
Classes
struct __mavlink_manual_control_t
Macros
#define MAVLINK_MSG_ID_MANUAL_CONTROL 69
#define MAVLINK_MSG_ID_MANUAL_CONTROL_LEN 21
#define MAVLINK_MSG_ID_69_LEN 21
#define MAVLINK_MESSAGE_INFO_MANUAL_CONTROL
Typedefs
typedef struct
__mavlink_manual_control_t mavlink_manual_control_t
Functions
static uint16_t mavlink_msg_manual_control_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, uint8_t target, float roll, float pitch, float yaw, float thrust, uint8_t roll_manual, uint8_t pitch_manual, uint8_t yaw_manual, uint8_t thrust_manual)
Pack a manual_control message.
static uint16_t mavlink_msg_manual_control_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t *msg, uint8_t target, float roll, float pitch, float yaw, float thrust, uint8_t roll_manual, uint8_t pitch_manual, uint8_t yaw_manual, uint8_t thrust_manual)
Pack a manual_control message on a channel.
static uint16_t mavlink_msg_manual_control_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t *msg, const mavlink_manual_control_t *manual_control)
Encode a manual_control struct into a message.
static uint8_t mavlink_msg_manual_control_get_target (const mavlink_message_t *msg)
Send a manual_control message.
static float mavlink_msg_manual_control_get_roll (const mavlink_message_t *msg)
Get field roll from manual_control message.
static float mavlink_msg_manual_control_get_pitch (const mavlink_message_t *msg)
Get field pitch from manual_control message.
static float mavlink_msg_manual_control_get_yaw (const mavlink_message_t *msg)
Get field yaw from manual_control message.
static float mavlink_msg_manual_control_get_thrust (const mavlink_message_t *msg)
Get field thrust from manual_control message.
static uint8_t mavlink_msg_manual_control_get_roll_manual (const mavlink_message_t *msg)
Get field roll_manual from manual_control message.
static uint8_t mavlink_msg_manual_control_get_pitch_manual (const mavlink_message_t *msg)
Get field pitch_manual from manual_control message.
static uint8_t mavlink_msg_manual_control_get_yaw_manual (const mavlink_message_t *msg)
Get field yaw_manual from manual_control message.
static uint8_t mavlink_msg_manual_control_get_thrust_manual (const mavlink_message_t *msg)
Get field thrust_manual from manual_control message.
static void mavlink_msg_manual_control_decode (const mavlink_message_t *msg, mavlink_manual_control_t *manual_control)
Decode a manual_control message into a struct.
Macro Definition Documentation
#define MAVLINK_MESSAGE_INFO_MANUAL_CONTROL
Value:
{ \
    "MANUAL_CONTROL", \
    9, \
    {  { "target", NULL, MAVLINK_TYPE_UINT8_T, 0, 0, offsetof(mavlink_manual_control_t, target) }, \
         { "roll", NULL, MAVLINK_TYPE_FLOAT, 0, 1, offsetof(mavlink_manual_control_t, roll) }, \
         { "pitch", NULL, MAVLINK_TYPE_FLOAT, 0, 5, offsetof(mavlink_manual_control_t, pitch) }, \
         { "yaw", NULL, MAVLINK_TYPE_FLOAT, 0, 9, offsetof(mavlink_manual_control_t, yaw) }, \
         { "thrust", NULL, MAVLINK_TYPE_FLOAT, 0, 13, offsetof(mavlink_manual_control_t, thrust) }, \
         { "roll_manual", NULL, MAVLINK_TYPE_UINT8_T, 0, 17, offsetof(mavlink_manual_control_t, roll_manual) }, \
         { "pitch_manual", NULL, MAVLINK_TYPE_UINT8_T, 0, 18, offsetof(mavlink_manual_control_t, pitch_manual) }, \
         { "yaw_manual", NULL, MAVLINK_TYPE_UINT8_T, 0, 19, offsetof(mavlink_manual_control_t, yaw_manual) }, \
         { "thrust_manual", NULL, MAVLINK_TYPE_UINT8_T, 0, 20, offsetof(mavlink_manual_control_t, thrust_manual) }, \
         } \
}
Definition at line 23 of file mavlink_msg_manual_control.h.
#define MAVLINK_MSG_ID_69_LEN 21
Definition at line 19 of file mavlink_msg_manual_control.h.
#define MAVLINK_MSG_ID_MANUAL_CONTROL 69
Definition at line 3 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_pack(), and mavlink_msg_manual_control_pack_chan().
#define MAVLINK_MSG_ID_MANUAL_CONTROL_LEN 21
Definition at line 18 of file mavlink_msg_manual_control.h.
Typedef Documentation
typedef struct __mavlink_manual_control_t mavlink_manual_control_t
Function Documentation
static void mavlink_msg_manual_control_decode (const mavlink_message_t * msg, mavlink_manual_control_t * manual_control) inline static
Decode a manual_control message into a struct.
Parameters
msg The message to decode
manual_control C-struct to decode the message contents into
Definition at line 305 of file mavlink_msg_manual_control.h.
Referenced by mavlink_test_manual_control().
static uint16_t mavlink_msg_manual_control_encode (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, const mavlink_manual_control_t * manual_control) inline static
Encode a manual_control struct into a message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
manual_control C-struct to read the message contents from
Definition at line 152 of file mavlink_msg_manual_control.h.
Referenced by mavlink_test_manual_control().
static float mavlink_msg_manual_control_get_pitch (const mavlink_message_t * msg) inline static
Get field pitch from manual_control message.
Returns
pitch
Definition at line 234 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_decode().
static uint8_t mavlink_msg_manual_control_get_pitch_manual (const mavlink_message_t * msg) inline static
Get field pitch_manual from manual_control message.
Returns
pitch auto:0, manual:1
Definition at line 274 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_decode().
static float mavlink_msg_manual_control_get_roll (const mavlink_message_t * msg) inline static
Get field roll from manual_control message.
Returns
roll
Definition at line 224 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_decode().
static uint8_t mavlink_msg_manual_control_get_roll_manual (const mavlink_message_t * msg) inline static
Get field roll_manual from manual_control message.
Returns
roll control enabled auto:0, manual:1
Definition at line 264 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_decode().
static uint8_t mavlink_msg_manual_control_get_target (const mavlink_message_t * msg) inline static
Send a manual_control message.
Parameters
chan MAVLink channel to send the message
target The system to be controlled
roll roll
pitch pitch
yaw yaw
thrust thrust
roll_manual roll control enabled auto:0, manual:1
pitch_manual pitch auto:0, manual:1
yaw_manual yaw auto:0, manual:1
thrust_manual thrust auto:0, manual:1 Get field target from manual_control message
Returns
The system to be controlled
Definition at line 214 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_decode().
static float mavlink_msg_manual_control_get_thrust (const mavlink_message_t * msg) inline static
Get field thrust from manual_control message.
Returns
thrust
Definition at line 254 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_decode().
static uint8_t mavlink_msg_manual_control_get_thrust_manual (const mavlink_message_t * msg) inline static
Get field thrust_manual from manual_control message.
Returns
thrust auto:0, manual:1
Definition at line 294 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_decode().
static float mavlink_msg_manual_control_get_yaw (const mavlink_message_t * msg) inline static
Get field yaw from manual_control message.
Returns
yaw
Definition at line 244 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_decode().
static uint8_t mavlink_msg_manual_control_get_yaw_manual (const mavlink_message_t * msg) inline static
Get field yaw_manual from manual_control message.
Returns
yaw auto:0, manual:1
Definition at line 284 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_decode().
static uint16_t mavlink_msg_manual_control_pack (uint8_t system_id, uint8_t component_id, mavlink_message_t * msg, uint8_t target, float roll, float pitch, float yaw, float thrust, uint8_t roll_manual, uint8_t pitch_manual, uint8_t yaw_manual, uint8_t thrust_manual) inline static
Pack a manual_control message.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
msg The MAVLink message to compress the data into
target The system to be controlled
roll roll
pitch pitch
yaw yaw
thrust thrust
roll_manual roll control enabled auto:0, manual:1
pitch_manual pitch auto:0, manual:1
yaw_manual yaw auto:0, manual:1
thrust_manual thrust auto:0, manual:1
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 56 of file mavlink_msg_manual_control.h.
Referenced by mavlink_msg_manual_control_encode(), and mavlink_test_manual_control().
static uint16_t mavlink_msg_manual_control_pack_chan (uint8_t system_id, uint8_t component_id, uint8_t chan, mavlink_message_t * msg, uint8_t target, float roll, float pitch, float yaw, float thrust, uint8_t roll_manual, uint8_t pitch_manual, uint8_t yaw_manual, uint8_t thrust_manual) inline static
Pack a manual_control message on a channel.
Parameters
system_id ID of this system
component_id ID of this component (e.g. 200 for IMU)
chan The MAVLink channel this message was sent over
msg The MAVLink message to compress the data into
target The system to be controlled
roll roll
pitch pitch
yaw yaw
thrust thrust
roll_manual roll control enabled auto:0, manual:1
pitch_manual pitch auto:0, manual:1
yaw_manual yaw auto:0, manual:1
thrust_manual thrust auto:0, manual:1
Returns
length of the message in bytes (excluding serial stream start sign)
Definition at line 108 of file mavlink_msg_manual_control.h.
Referenced by mavlink_test_manual_control().